### ISSUE TITLE
vue2.2.6 怎么只有裁剪框 没有图片 

### ISSUE THREAD

**Issue by 617450941** [xyxiao001/vue-cropper#1]
vue2.2.6 怎么只有裁剪框 没有图片

**Comment by xyxiao001** [comment]
贴代码

**Comment by xyxiao001** [comment]
图片支持url 和  base64传入

**Comment by 617450941** [comment]
我看到img 那个标签有个display:none的属性

**Comment by 617450941** [comment]
<style scoped lang="scss">
  @import "src/sass/panel";
</style>
<template>
  <div>
    <vueCropper
      ref="cropper2"
      :img="example.img"
      :outputSize="example.size"
      :outputType="example.outputType"
      :info="example.info"
      :canScale="example.canScale"
      :autoCrop="example.autoCrop"
      :autoCropWidth="example.width"
      :autoCropHeight="example.height"
    ></vueCropper>
  </div>
</template>
<script>
  import VueCropper from 'vue-cropper';

  export default {
    components: {
      VueCropper
    },
    props: {
      img: ''
    },
    data() {
      return {
        example: {
          img: 'http://ofyaji162.bkt.clouddn.com/bg1.jpg',
          info: false,
          size: 1,
          outputType: 'jpeg',
          canScale: false,
          autoCrop: true,
          autoCropWidth: 300,
          autoCropHeight: 250,
        }
      };
    },
    methods: {
    },
    created () {
      console.log(this.img);
    }
  };
</script>

**Comment by xyxiao001** [comment]
<vueCropper
	ref="cropper2"
	:img="example2.img"
	:outputSize="example2.size"
	:outputType="example2.outputType"
	:info="example2.info"
	:canScale="example2.canScale"
	:autoCrop="example2.autoCrop"
	:autoCropWidth="example2.width"
	:autoCropHeight="example2.height"
></vueCropper>需要传入img  你传入没

**Comment by 617450941** [comment]
确定传了img url

**Comment by 617450941** [comment]
<vueCropper
      ref="cropper2"
      :img="example.img"
      :outputSize="example.size"
      :outputType="example.outputType"
      :info="example.info"
      :canScale="example.canScale"
      :autoCrop="example.autoCrop"
      :autoCropWidth="example.width"
      :autoCropHeight="example.height"
    ></vueCropper>


        example: {
          img: 'http://ofyaji162.bkt.clouddn.com/bg1.jpg',
          info: false,
          size: 1,
          outputType: 'jpeg',
          canScale: false,
          autoCrop: true,
          autoCropWidth: 300,
          autoCropHeight: 250,
        }

**Comment by xyxiao001** [comment]
页面截图看看， 还有控制台有错吗

**Comment by 617450941** [comment]
截图如下
http://wxyx.hbgeek.com/issues/1.png
http://wxyx.hbgeek.com/issues/2.png
http://wxyx.hbgeek.com/issues/3.png
http://wxyx.hbgeek.com/issues/4.png

**Comment by 617450941** [comment]
已经是按照demo复制过来 还是一样不行

**Comment by xyxiao001** [comment]
容器需要设置高度 和 宽度

**Comment by xyxiao001** [comment]
你把外层容器设置个高度

**Comment by 617450941** [comment]
可以了谢谢

**Comment by xyxiao001** [comment]
好的

**Comment by 617450941** [comment]
再问个问题 执行this.$refs.cropper.getCropDate()  浏览器报这个错误Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported. 是怎么回事

**Comment by xyxiao001** [comment]
这个是图片跨域的问题 我看看去

**Comment by 617450941** [comment]
有解决办法吗

**Comment by 617450941** [comment]
貌似给img标签增加crossOrigin="anonymous"属性就可以解决

**Comment by xyxiao001** [comment]
我等下推送个新版本上去， 你到时更新下就好， 等会我告诉你，

**Comment by 617450941** [comment]
好 谢谢 npm同步更新的吗?

**Comment by xyxiao001** [comment]
已经解决了
this.$refs.cropper.getCropDate((data) => {
  // do something
  console.log(data)  
})
你现在需要异步获取 截图的数据
需要更新到0.09版本

**Comment by 617450941** [comment]
不行 还是报Access to Image at 'http://localhost:81/Public/Uploads/Model/Album/2017-06-13/593f632d64911.jpg' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. 这个错误

**Comment by 617450941** [comment]
已经是升到0.09版本 问题依然存在

**Comment by xyxiao001** [comment]
你不能这样用本地的图片 因为图片跨域是需要后台允许， 你要使用本地图片， 请用上传的方式

**Comment by xyxiao001** [comment]
第一个例子里面有上传的例子 和写法

**Comment by xyxiao001** [comment]
点错关了

**Comment by xyxiao001** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTML/CORS_enabled_image
你必须有一个可以对图片响应正确 Access-Control-Allow-Origin 响应头的服务器。你可以使用以下片段 (来自 HTML5 Boilerplate Apache server configs) 实现正确响应头。
所以不能直接使用本地地址
