### ISSUE TITLE
安装这个依赖之后，项目会报错，移除之后就正常了，up主，注意下。

### ISSUE THREAD

**Issue by OBKoro1** [xyxiao001/vue-cropper#10]
![image](https://user-images.githubusercontent.com/24698201/29356104-bc5ce356-82a5-11e7-942d-b2260ece686f.png)

**Comment by xyxiao001** [comment]
你是说安装插件后报错吗

**Comment by OBKoro1** [comment]
![image](https://user-images.githubusercontent.com/24698201/29356425-d715bae6-82a6-11e7-9fc1-bf1af2e00a52.png)
大概是这样子，也可能是项目本身有一些东西跟插件冲突了

**Comment by xyxiao001** [comment]
你安装后 用了插件嘛 怎么使用的

**Comment by xyxiao001** [comment]
看报错 基本上全是node 本身的模块， 会不会是因为node版本过低
或者把node_module 删除了重新安装依赖看看

**Comment by OBKoro1** [comment]
是这样：本来复制了您demo栗子，后面项目就无法启动，然后把项目的所有东西都注释掉，包括引用也注释掉，启动的时候，报错如上。移除了插件之后，就正常了。

**Comment by xyxiao001** [comment]
这样啊 这个报错是指node的某些模块没找到 一般来说是安装依赖出错才会这样
但是你报错的模块是node自带的 不需要安装  
你可以试一试删掉node_module 删除了重新安装依赖看看

**Comment by OBKoro1** [comment]
![z g qwfwtqd3 4l 99nvs1](https://user-images.githubusercontent.com/24698201/29356985-94ce45a2-82a8-11e7-85d1-de5e9cb9ae2e.png)
我重新用cnpm安装了，一切正常没有报错，项目启动也是正常的。

**Comment by xyxiao001** [comment]
这是警告，你项目的警告

**Comment by xyxiao001** [comment]
没多大关系的 就是提示你的其他插件版本低了

**Comment by OBKoro1** [comment]
我也觉得应该是项目之间依赖有冲突，但是不知道为什么用cnpm安装就一切正常了。最后解决方式是：移除插件，然后重新用cnpm安装了就可以了。

**Comment by xyxiao001** [comment]
可能用npm 安装 有墙的原因 导致某些模块没安装好
