### ISSUE TITLE
上传本地图片时源码中的checkImg 方法中 img.onload 一直不生效，导致 img src(unknown)

### ISSUE THREAD

**Issue by callcter** [xyxiao001/vue-cropper#100]

**Comment by xyxiao001** [comment]
你用在线例子看看有问题吗

**Comment by callcter** [comment]
在线的没有问题，但是我用的时候是这样

**Comment by xyxiao001** [comment]
你怎么写的

**Comment by callcter** [comment]
`<template lang="pug">
.config-cover
  img(:src='cover_url', v-if='cover_url.length>0')
  img(:src='user.cover', v-else)
  Upload(action='//upload.qiniup.com/', :before-upload='handleCoverUpload')
    .config-cover-btn
      i.icon.iconfont.icon-jietu
      | 设置封面图片
  Modal(v-model='modal_show', @on-ok='crop', ok-text='保存', class-name='custom-modal', width='1180')
    i.icon.iconfont.icon-close(slot='close')
    .config-cropper-title 编辑封面
    .config-cropper-tip 调整封面尺寸和位置
    .config-cropper.cover
      VueCropper(
        ref='cropper',
        :img='crop_opt_img',
        outputType='png',
        :autoCropWidth='crop_opt_width',
        :autoCropHeight='crop_opt_height',
        :autoCrop='crop_opt_auto',
        :fixedBox='crop_opt_fixed',
        :canMoveBox='crop_opt_boxmove',
        :canScale='crop_opt_scale',
        :info='crop_opt_info')
    .config-cropper-btns
      span(@click='change_slider_num(-1)')
        i.icon.iconfont.icon-suoxiao
      Slider(v-model='slider_val', :max='30', @on-input='change_slider', show-tip='never')
      span(@click='change_slider_num(1)')
        i.icon.iconfont.icon-fangda
</template>
<script>
import { mapState } from 'vuex'
// import VueCropper from 'vue-cropper'
import VueCropper from '../common/vue-cropper.vue'
export default {
  computed: {
    ...mapState({
      user: state => state.user
    })
  },
  watch: {
    user: function(){
      this.cover_url = this.user.cover
    }
  },
  mounted(){
    this.reader.onload = () => {
      this.crop_opt_img = this.reader.result
      if(this.crop_opt_img){
        this.modal_show = true
      }
    }
  },
  data(){
    return {
      qiniu_url: 'https://o75djmyt6.qnssl.com/',
      cover_file: null,
      cover_url: '',
      modal_show: false,
      reader: new FileReader(),
      slider_val: 0,
      slider_val2: 0,
      crop_opt_img: null,
      crop_opt_width: 1020,
      crop_opt_height: 200,
      crop_opt_auto: true,
      crop_opt_fixed: true,
      crop_opt_boxmove: false,
      crop_opt_scale: false,
      crop_opt_info: false
    }
  },
  components: {
    VueCropper
  },
  methods: {
    change_slider_num(num){
      if(num<0){
        if(this.slider_val>0){
          this.slider_val --
        }
      }
      if(num>0){
        if(this.slider_val<30){
          this.slider_val ++
        }
      }
    },
    change_slider(){
      this.changeScale(this.slider_val - this.slider_val2)
      this.slider_val2 = this.slider_val
    },
    crop(){
      this.$refs.cropper.getCropBlob((data) => {
        this.cover_file = data
        axios({
          url: this.user.authHost+'/uptoken',
          method: 'get'
        }).then(response => {
          this.uploadCover(response.data.uptoken)
        }).catch(error => {
          console.log(error)
        })
        return false
      })
    },
    changeScale(num){
      num = num || 1
      this.$refs.cropper.changeScale(num)
    },
    handleCoverUpload(file){
      this.reader.readAsDataURL(file)
    },
    uploadCover(uptoken){
      let _this = this
      let form = new FormData()
      form.append('token', uptoken)
      form.append('file', this.cover_file)
      axios({
        url: this.user.qiniu_url,
        method: 'post',
        data: form
      }).then(response => {
        _this.cover_url = _this.qiniu_url+response.data.key
        axios({
          url: this.user.authHost + '/users/update',
          method: 'put',
          params: {
            format: 'json'
          },
          data: {
            user: {
              cover: _this.cover_url
            }
          },
          withCredentials: true
        }).then(res => {
          if(res.status == 200){
            _this.$Message.success('用户封面修改成功')
            this.$store.commit('SET_USER_INFO', {
              cover: _this.cover_url
            })
          }
        })
      }).catch(error => {
        console.log(error)
      })
    }
  }
}
</script>`

**Comment by callcter** [comment]
```
<template lang="pug">
.config-cover
  img(:src='cover_url', v-if='cover_url.length>0')
  img(:src='user.cover', v-else)
  Upload(action='//upload.qiniup.com/', :before-upload='handleCoverUpload')
    .config-cover-btn
      i.icon.iconfont.icon-jietu
      | 设置封面图片
  Modal(v-model='modal_show', @on-ok='crop', ok-text='保存', class-name='custom-modal', width='1180')
    i.icon.iconfont.icon-close(slot='close')
    .config-cropper-title 编辑封面
    .config-cropper-tip 调整封面尺寸和位置
    .config-cropper.cover
      VueCropper(
        ref='cropper',
        :img='crop_opt_img',
        outputType='png',
        :autoCropWidth='crop_opt_width',
        :autoCropHeight='crop_opt_height',
        :autoCrop='crop_opt_auto',
        :fixedBox='crop_opt_fixed',
        :canMoveBox='crop_opt_boxmove',
        :canScale='crop_opt_scale',
        :info='crop_opt_info')
    .config-cropper-btns
      span(@click='change_slider_num(-1)')
        i.icon.iconfont.icon-suoxiao
      Slider(v-model='slider_val', :max='30', @on-input='change_slider', show-tip='never')
      span(@click='change_slider_num(1)')
        i.icon.iconfont.icon-fangda
</template>
<script>
import { mapState } from 'vuex'
// import VueCropper from 'vue-cropper'
import VueCropper from '../common/vue-cropper.vue'
export default {
  computed: {
    ...mapState({
      user: state => state.user
    })
  },
  watch: {
    user: function(){
      this.cover_url = this.user.cover
    }
  },
  mounted(){
    this.reader.onload = () => {
      this.crop_opt_img = this.reader.result
      if(this.crop_opt_img){
        this.modal_show = true
      }
    }
  },
  data(){
    return {
      qiniu_url: 'https://o75djmyt6.qnssl.com/',
      cover_file: null,
      cover_url: '',
      modal_show: false,
      reader: new FileReader(),
      slider_val: 0,
      slider_val2: 0,
      crop_opt_img: null,
      crop_opt_width: 1020,
      crop_opt_height: 200,
      crop_opt_auto: true,
      crop_opt_fixed: true,
      crop_opt_boxmove: false,
      crop_opt_scale: false,
      crop_opt_info: false
    }
  },
  components: {
    VueCropper
  },
  methods: {
    change_slider_num(num){
      if(num<0){
        if(this.slider_val>0){
          this.slider_val --
        }
      }
      if(num>0){
        if(this.slider_val<30){
          this.slider_val ++
        }
      }
    },
    change_slider(){
      this.changeScale(this.slider_val - this.slider_val2)
      this.slider_val2 = this.slider_val
    },
    crop(){
      this.$refs.cropper.getCropBlob((data) => {
        this.cover_file = data
        axios({
          url: this.user.authHost+'/uptoken',
          method: 'get'
        }).then(response => {
          this.uploadCover(response.data.uptoken)
        }).catch(error => {
          console.log(error)
        })
        return false
      })
    },
    changeScale(num){
      num = num || 1
      this.$refs.cropper.changeScale(num)
    },
    handleCoverUpload(file){
      this.reader.readAsDataURL(file)
    },
    uploadCover(uptoken){
      let _this = this
      let form = new FormData()
      form.append('token', uptoken)
      form.append('file', this.cover_file)
      axios({
        url: this.user.qiniu_url,
        method: 'post',
        data: form
      }).then(response => {
        _this.cover_url = _this.qiniu_url+response.data.key
        axios({
          url: this.user.authHost + '/users/update',
          method: 'put',
          params: {
            format: 'json'
          },
          data: {
            user: {
              cover: _this.cover_url
            }
          },
          withCredentials: true
        }).then(res => {
          if(res.status == 200){
            _this.$Message.success('用户封面修改成功')
            this.$store.commit('SET_USER_INFO', {
              cover: _this.cover_url
            })
          }
        })
      }).catch(error => {
        console.log(error)
      })
    }
  }
}
</script>
```

**Comment by callcter** [comment]
这是全部的代码

**Comment by xyxiao001** [comment]
你看看你的img传过去没

**Comment by callcter** [comment]
```
let canvas = document.createElement("canvas");
      let img = new Image();
      let rotate = 0;
      img.onload = function(){
```
这是 checkImg 的代码，在 img.load 之前 img 已经传进来了，但是 onload 一直都没有调用

**Comment by xyxiao001** [comment]
我找上也是这样写的

**Comment by xyxiao001** [comment]
线上

**Comment by callcter** [comment]
这就是线上的代码，我这边就是不管用，之前是没有问题的，代码我觉着也没有问题 T_T

**Comment by xyxiao001** [comment]
你直接传图片地址进去是可以的嘛，只有本地上传有问题吗

**Comment by callcter** [comment]
貌似也不行，还是没有调用
```
VueCropper(
        ref='cropper',
        img='http://ofyaji162.bkt.clouddn.com/bg2.jpg',
        outputType='png',
        :autoCropWidth='crop_opt_width',
        :autoCropHeight='crop_opt_height',
        :autoCrop='crop_opt_auto',
        :fixedBox='crop_opt_fixed',
        :canMoveBox='crop_opt_boxmove',
        :canScale='crop_opt_scale',
        :info='crop_opt_info')
```

**Comment by xyxiao001** [comment]
那就是代码问题的， 你用vue看看组件里面的属性

**Comment by callcter** [comment]
我找一下问题吧，找到跟你说一声

**Comment by callcter** [comment]
找到问题了，项目里面还用到了 zrender，把 new Image()方法覆盖了，生成了一个ZImage()，所以 onload 失效，我改成了
```
img = document.createElement('img')
```
来创建 img 对象
