### ISSUE TITLE
移动端图片上传会刷新页面

### ISSUE THREAD

**Issue by SkinsTY** [xyxiao001/vue-cropper#101]
手机上传2M大小的照片，会刷新页面。安卓手机无法拍照，只能选择上传本地相册的照片。有解决的办法吗

**Comment by xyxiao001** [comment]
这个问题 目前只能通过你自己去压缩图片解决，上传是你那边做的

**Comment by yin11** [comment]
楼主，你解决了这个问题了吗？我也是遇到和你一样的问题

**Comment by xyxiao001** [comment]
你需要自己处理一下图片 压缩一下 然后传给组件

**Comment by xyxiao001** [comment]
已经在0.34版本解决移动端 会默认压缩到2000像素宽度以下

**Comment by SkinsTY** [comment]
我当时自己压缩了下
