### ISSUE TITLE
跨域怎么处理

### ISSUE THREAD

**Issue by weips001** [xyxiao001/vue-cropper#102]
我在使用的时候出现跨域了 要怎么办，大神帮帮忙啊！

**Comment by xyxiao001** [comment]
跨域需要后台配合

**Comment by weips001** [comment]
能具体说下么，我这边是用的iview的那个上传组建，现在要加一个裁剪功能，原来直接上传到服务器（二进制储存），然后后台返回一个url展示出来就行了，现在加上这个插件之后，图片显示不出来，然后就跨域了。

**Comment by xyxiao001** [comment]
服务器图片需要后端允许跨域

**Comment by 547377507** [comment]
我也遇到了跨域的问题
![image](https://user-images.githubusercontent.com/13267376/38605903-323c692c-3da7-11e8-801f-ff01c685208a.png)
