### ISSUE TITLE
PC refresh()函数使用出错

### ISSUE THREAD

**Issue by Ann-Cyq** [xyxiao001/vue-cropper#105]
首先很感谢您的贡献，由于项目需求，我使用了内置refresh，出错了，下载了example，运行使用也是出错了，请问这块是还没有开发的吗，啥时候会做更新

**Comment by xyxiao001** [comment]
什么错误，怎么写的

**Comment by Ann-Cyq** [comment]
就是图片 截框直接都没了  只剩下背景图，控制台没报错

**Comment by xyxiao001** [comment]
refresh 就是清空所有的 截图框需要自己在截取的

**Comment by Ann-Cyq** [comment]
原来是这样 我以为是刷新，我也用了clearCrop（）这个方法，可是这个方法也是会关掉截图框，还有其他内置方法可以重置图片， 又让默认截图框有效吗

**Comment by xyxiao001** [comment]
重置图片 只需要传入新的图片就行

**Comment by Ann-Cyq** [comment]
可能是项目需求有点坑  我再看一下有没有其他办法好了，最后再次感谢您！

**Comment by xyxiao001** [comment]
你需要的不是直接图片吗 还是怎么样

**Comment by xyxiao001** [comment]
切换

**Comment by Ann-Cyq** [comment]
他是需求上有一个刷新的按钮  比如说我们移动（或者放大缩小）了图片，有一个按钮可以恢复到一开始的状态， 虽然我也感觉这有点累赘

**Comment by Ann-Cyq** [comment]
我还是去说服产品吧 哈哈，感谢您，真的很棒

**Comment by xyxiao001** [comment]
这样子啊  我没加这个功能， 那有种方案可以获取原始参数 然后点击按钮， 把参数设置， 就可以恢复了

**Comment by Ann-Cyq** [comment]
好的好的  如果不同意  我就自己去试试，有方法的话，应该可以搞定，感谢！

**Comment by xyxiao001** [comment]
![13865bb9323100f9c3a51dafcaa2a399](https://user-images.githubusercontent.com/15681693/38978892-4d4bd8b6-43eb-11e8-9e32-29cfdd5df797.jpg)
