### ISSUE TITLE
只有背景，图片没有加载出来

### ISSUE THREAD

**Issue by WalkingRoy** [xyxiao001/vue-cropper#108]
问题：图片地址有传，基本都是复制 demo ，但是图片没有加载出来，只有马赛克的背景
代码：
外层已经设置一个 div ，以及固定宽高大小
`<div style="width:500px;height:500px;">
              <vue-cropper
                ref="cropper2"
                :img="example2.img"
                :outputSize="example2.size"
                :outputType="example2.outputType"
                :info="example2.info"
                :canScale="example2.canScale"
                :autoCrop="example2.autoCrop"
                :autoCropWidth="example2.autoCropWidth"
                :autoCropHeight="example2.autoCropHeight"
                :fixed="example2.fixed"
                :fixedNumber="example2.fixedNumber">
              </vue-cropper>
            </div>`
数据：
`example2: {
		img: 'http://ofyaji162.bkt.clouddn.com/bg1.jpg',
		info: true,
		size: 1,
		outputType: 'jpeg',
		canScale: false,
		autoCrop: true,
		// 只有自动截图开启 宽度高度才生效
		autoCropWidth: 300,
		autoCropHeight: 250,
		// 开启宽度和高度比例
		fixed: true,
		fixedNumber: [4, 3]
	}`
控制台错误日志：
`index.js?619d:1 Uncaught TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (<anonymous>)
    at h (index.js?619d:1)
    at o (index.js?619d:1)
    at MockXMLHttpRequest.i.onload (index.js?619d:1)
    at MockXMLHttpRequest.dispatchEvent (mock.js?ccd5:8472)
    at XMLHttpRequest.handle (mock.js?ccd5:8300)`

**Comment by xyxiao001** [comment]
是不是参数传错了 可以截图报错吗

**Comment by WalkingRoy** [comment]
(没想到传上来都乱掉了，不好意思，重新弄下)
报错信息：
![image](https://user-images.githubusercontent.com/9346810/39093137-30859c8a-464d-11e8-8323-d4939f09c2e2.png)

代码：
![image](https://user-images.githubusercontent.com/9346810/39093145-406d3cb6-464d-11e8-94dc-ab66db6c8f22.png)

![image](https://user-images.githubusercontent.com/9346810/39093155-664221ae-464d-11e8-9179-540475fa86e0.png)

**Comment by WalkingRoy** [comment]
没想到都乱了，重新处理下。。
代码：
![image](https://user-images.githubusercontent.com/9346810/39093166-9bd83d08-464d-11e8-9fe2-dfb9d80efd02.png)

![image](https://user-images.githubusercontent.com/9346810/39093172-c8a8726c-464d-11e8-8bd8-a17a4e02a1bd.png)


报错：
![image](https://user-images.githubusercontent.com/9346810/39093170-bb8d8f22-464d-11e8-8629-dd500e8537b6.png)

**Comment by WalkingRoy** [comment]
你好，是我传参数有问题是吗

**Comment by xyxiao001** [comment]
提示是参数有问题 但是代码没问题  你把插件注释掉 看看还有错吗

**Comment by WalkingRoy** [comment]
插件注释掉的话，就不会报这个错

**Comment by xyxiao001** [comment]
你可以试一试只传图片 其他参数都不传

**Comment by WalkingRoy** [comment]
去掉 img 属性就不会报错，我再看看
