### ISSUE TITLE
缩放裁切框超过200，200就无法用formData上传图片

### ISSUE THREAD

**Issue by fz20140409** [xyxiao001/vue-cropper#110]
尺寸在200以下的话裁切完转文件流可以上传  但是裁切框超过200转成文件流再传就报错

**Comment by xyxiao001** [comment]
报什么错

**Comment by fz20140409** [comment]
POST https://ks.fjmaimaimai.com/v1/pc/iconUpload 500 (Internal Server Error)
localhost/:1 Failed to load https://ks.fjmaimaimai.com/v1/pc/iconUpload: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access. The response had HTTP status code 500.

**Comment by fz20140409** [comment]
后端程序员说是文件流格式不正确    我在你的demo里也做了测试 一旦裁切框超过200，,200就无法上传 求大神指点

**Comment by xyxiao001** [comment]
这不是服务器错误吗

**Comment by xyxiao001** [comment]
而且这应该是你处理文件流的问题

**Comment by xyxiao001** [comment]
你怎么处理的

**Comment by fz20140409** [comment]
this.$refs.cropper.getCropBlob((data) => {
  // do something
  console.log(data)  
})直接把这个添加到formdata用ajax上传   200尺寸尺寸以内都正常 否则报错   用base64再转文件流也是一样情况

**Comment by xyxiao001** [comment]
那你直接new file上传呢

**Comment by fz20140409** [comment]
是正常的

**Comment by fz20140409** [comment]
不是服务端问题 一开始我也以为是服务端限制大小  结果我选择文件直接传是成功的

**Comment by xyxiao001** [comment]
那就通过这种方式上传的

**Comment by fz20140409** [comment]
但是我需要裁切啊

**Comment by xyxiao001** [comment]
裁剪后的数据 也可以new file上传啊

**Comment by fz20140409** [comment]
你是说base64转file吗 我也试过了 不可以

**Comment by xyxiao001** [comment]
formdata 如果后端限制了post提交的大小  那就会失败

**Comment by fz20140409** [comment]
但是我直接通过input选择一张好大的图上传是没问题的啊

**Comment by fz20140409** [comment]
后端是说出问题的时候文件流格式是错误的

**Comment by xyxiao001** [comment]
我这边没做别的处理 只是输出了截图的图片

**Comment by fz20140409** [comment]
![qq 20180427172551](https://user-images.githubusercontent.com/27174211/39355569-264f4ecc-4a40-11e8-9c70-67618a360821.png)

**Comment by fz20140409** [comment]
只要上面自动裁切框到201就无法上传  真不知道咋回事

**Comment by fz20140409** [comment]
我直接在你demo里传的

**Comment by xyxiao001** [comment]
可是上传和我这个插件是没关系的  我输出的处理后的图片  你那边处理上传

**Comment by fz20140409** [comment]
那个问题解决了 还想问一下 你这个好像设置了outfileType那么所有格式的图片进来最后都会被转成固定的格式啊

**Comment by xyxiao001** [comment]
我直接调用的canvas的接口输出的图片

**Comment by IEfucker** [comment]
@fz20140409 请问图片格式的问题是怎么解决的，我也在做上传，
https://github.com/xyxiao001/vue-cropper/issues/191#issuecomment-429265984
截图输出后上传服务器能正确解析数据吗，对于bmp，gif等格式，outpuType如何设定
