### ISSUE TITLE
translate3d缩放导致图片缩小后看不清楚

### ISSUE THREAD

**Issue by wswww** [xyxiao001/vue-cropper#114]
图片缩小后看不清楚,我猜测scale,translate3d属性导致,如何改成使用改变图片width,height,top,left实现滚轮缩放呢?

**Comment by xyxiao001** [comment]
手机上缩放吗

**Comment by wswww** [comment]
![ed296fa3-5531-46ba-94af-d2282655ddad](https://user-images.githubusercontent.com/27074739/39864762-461a5fac-547d-11e8-8e4a-f8cec3adbd8c.jpg)
感谢回复~  描述: 我的是PC端,我直接把您的插件当做'预览'插件使用了.外边的盒子width:400px;图片width:1700px; 
所以图片是以缩小的状态在盒子里呈现的.导致左图看不清清晰.
但是图片本身是清晰的,因为右侧放大后能清晰呈现

**Comment by xyxiao001** [comment]
如果把左边图片放大查看详细 应该是清晰的  现在是为了显示所有  所以缩放了

**Comment by wswww** [comment]
是的.放大后时可以清晰呈现的,我尝试多种缩小图片方式,都不清晰,像丢失了很多像素一样.暂时没有办法解决.  谢谢!

![9ab920ad-2dc3-41ec-a91b-d20144a25d6a](https://user-images.githubusercontent.com/27074739/39865877-f7e1f404-5480-11e8-8e15-7a00f5e563db.jpg)
