### ISSUE TITLE
设置截图宽高比无效

### ISSUE THREAD

**Issue by xlei1123** [xyxiao001/vue-cropper#12]
设置canScale: false,
					autoCrop: true,
					// 只有自动截图开启 宽度高度才生效
					autoCropWidth: 320,
					autoCropHeight: 200,
					// 开启宽度和高度比例
					fixed: true,
					fixedNumber: [1, 1]

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/29404869-cf56c58e-836e-11e7-95ff-80620cd9cc22.png)
刚刚测试这样可以

**Comment by xlei1123** [comment]
@xyxiao001  恩恩 可以了，那个demo没有写全，并且有一处错误，希望能改一下；很谢谢你

**Comment by xyxiao001** [comment]
好的 多谢指出
