### ISSUE TITLE
Nuxt / SSR compatibility

### ISSUE THREAD

**Issue by furyscript** [xyxiao001/vue-cropper#123]
Can you please update this for nuxt/ssr? The problem come when launch `import VueCropper from 'vue-cropper'`

Nuxt nothing can do if you use document/window when import. You can use that after plugin init.

I make a plugin that use `vue-cropper` and with `ssr: false` but problem persist.

**Comment by xyxiao001** [comment]
I need to know how to do it

**Comment by xyxiao001** [comment]
https://github.com/NightCatSama/vue-slider-component/issues/114

**Comment by furyscript** [comment]
Thanks, work by importing from `src` folder. You could update readme if you want, but thanks :D

**Comment by xyxiao001** [comment]
ok😷

**Comment by xyxiao001** [comment]
module.exports = {
  ...
  build: {
    vendor: [
      'vue-cropper'
    ],
    ...
    plugins: [
      { src: '~/plugins/vue-cropper', ssr: false }
    ]
  }
}

**Comment by xyxiao001** [comment]
```
module.exports = {
  ...
  build: {
    vendor: [
      'vue-slider-component'
    ],
    ...
    plugins: [
      { src: '~/plugins/vue-slider-component', ssr: false }
    ]
  }
}
```

**Comment by siberiadev** [comment]
@xyxiao001 hi
Are you sure to put plugins into the build part of nuxt.config.js
I think it should placed in the plugins part before build. Like this:
```
// /nuxt.config.js
module.exports = {
   plugins: [
      { src: '~/plugins/vue-cropper', ssr: false }
    ],
   build: {
      vendor: [
         'vue-cropperjs'
      ]
   }
}

// plugins/vue-cropper.js
import Vue from 'vue';
import VueCropper from 'vue-cropperjs';
Vue.use(VueCropper);

// in page or component
<no-ssr>
   <vue-cropper  
                    :aspectRatio="1"
                    :viewMode="0"
                    :zoomable="true"
                    style="margin-bottom: 20px;"
                    ref="cropper"
                    :src="originalImage"/>
</no-ssr>
```
BUT! It still has some problems I think. Because nuxt can't find this component, when I open my page with cropper. I get this error in console:
`Unknown custom element: <vue-cropper> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Any advices?)))

**Comment by siberiadev** [comment]
HAHA! solved!
Just change `plugins/vue-cropper.js` like this:
```
import Vue from 'vue';
import VueCropper from 'vue-cropperjs';
Vue.component('vue-cropper', VueCropper);
```

**Comment by nelsonlarocca** [comment]
vendor is not longer used !
