### ISSUE TITLE
图片如果被缓存，"cropper-box-canvas"有可能显示不出来

### ISSUE THREAD

**Issue by fancyboynet** [xyxiao001/vue-cropper#126]
实际项目中发现，传进去的图片有可能显示不出来，刷新又概率性恢复，后面把每次传进去的`img`地址都加上时间戳就好了，看源码发现`loading`是在image.onload后才设为false,图片如果被缓存好像是不会触发这个事件的，不知道这是不是一个优化的点

**Comment by xyxiao001** [comment]
好 貌似两次图片一样会出现这种情况，我去看看
