### ISSUE TITLE
请问typescript下怎么用啊

### ISSUE THREAD

**Issue by yaoyonstudio** [xyxiao001/vue-cropper#128]
请问typescript下怎么用啊

**Comment by xyxiao001** [comment]
正常引入的

**Comment by yaoyonstudio** [comment]
使用typescript，引入后，提示没有type， 我写了declare，不报找不到错了，但在使用this.$refs.cropper.getCropData 报错了，不知道getCropData 在哪里定义，typescript 不熟。大神帮帮忙。。。

**Comment by yaoyonstudio** [comment]
解决了，贴一下我的解决方案，有遇到的朋友可以参考一下。

模块定义文件（项目根目录）shims-vuecropper.d.ts

```
declare module 'vue-cropper' {
  interface VueCropper {
  }

  const VueCropper: VueCropper

  export = VueCropper
}
```

使用时加上下面一句：
```
export default class Profile extends Vue {
  public $refs!: { cropper: JSX.ElementClass }

  ...

  private crop () {
    this.$refs.cropper.getCropData((data: string) => {
        console.log('img data string:', data)
    })
  }
}
```

**Comment by txlwll** [comment]
![image](https://user-images.githubusercontent.com/18171146/51085951-1f984580-177b-11e9-8c60-57864e5e96a2.png)
@xyxiao001 最新版本在typescript下引用报错，大神帮忙看一下

**Comment by hopkinson** [comment]
请问是怎么引用 我到现在没懂

**Comment by xyxiao001** [comment]
https://github.com/xyxiao001/vue-cropper/issues/248

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/68556742-725f8e00-046e-11ea-96b6-8b85cb326711.png)
