### ISSUE TITLE
图片旋转的支持

### ISSUE THREAD

**Issue by FlyPointRed** [xyxiao001/vue-cropper#13]
对于网页上传的图片，不是所有的图片展示方向都是正的。所以有旋转图片会更好一点。
==，上传了一个竖着拍的图片，展示方向是横着。

**Comment by xyxiao001** [comment]
旋转的功能正在开发中。

**Comment by xyxiao001** [comment]
图片旋转功能已经添加 
更新到v0.19 即可使用
