### ISSUE TITLE
裁切jpg超出图片范围显示黑底

### ISSUE THREAD

**Issue by duoduodym** [xyxiao001/vue-cropper#131]
大神求助，裁切jpg超出图片范围显示黑底，我在源码里把画布填充红色但是不可以求大神指点
![image](https://user-images.githubusercontent.com/26755284/42146091-10671ffe-7df8-11e8-9241-fdf0f26d819d.png)

**Comment by xyxiao001** [comment]
jpg 就是黑色的  透明需要输出为png的
