### ISSUE TITLE
报 Uncaught TypeError: First argument to DataView constructor must be an ArrayBuffer 错误

### ISSUE THREAD

**Issue by iswu2013** [xyxiao001/vue-cropper#132]
![image](https://user-images.githubusercontent.com/3915904/42216070-19e3acd6-7ef3-11e8-9814-4ef366ae110a.png)
![image](https://user-images.githubusercontent.com/3915904/42216082-24f02762-7ef3-11e8-80d4-f627bbf6fcf6.png)

你好，这个错误困扰我很久，应该怎样修复

**Comment by xyxiao001** [comment]
你是直接传file进去组件吗

**Comment by iswu2013** [comment]
不是啊，我是直接用的你的demo，直接传的图片公网地址

**Comment by iswu2013** [comment]
![image](https://user-images.githubusercontent.com/3915904/42216305-fc3128f2-7ef3-11e8-8a1d-ec599ad5bd7a.png)
![image](https://user-images.githubusercontent.com/3915904/42216312-06aee1c0-7ef4-11e8-8cb3-c9c2aecace02.png)

以上就是引用的代码

**Comment by xyxiao001** [comment]
需要用createObjectURL转化成可以访问的链接

**Comment by xyxiao001** [comment]
直接报保证错误吗

**Comment by xyxiao001** [comment]
我看报错的位置 不是在组件代码里面

**Comment by xyxiao001** [comment]
https://github.com/xyxiao001/vue-cropper/issues/62

**Comment by iswu2013** [comment]
嗯，是不在组件里面，是你引用的exif.js代码里面报的错，这块有可能是框架中其他代码干扰了，不过我这边排查不出来。我这边有没有引用方法不当啊

**Comment by xyxiao001** [comment]
你看看我发的那个连接 检查下你的img有没有正确的传过去

**Comment by xyxiao001** [comment]
你可以看看img 正确传过去没有 props 可以用开发者工具查看

**Comment by iswu2013** [comment]
图片地址是传过去了的，但是就是在exif.js中出现了问题，貌似要转成base64传过去啊

**Comment by tangxiangmin** [comment]
应该是项目启动了mockjs或者其他类似的库导致的
