### ISSUE TITLE
图片较小时，移动截图框图片会产生重叠，重叠图片会随着截图框移动

### ISSUE THREAD

**Issue by ghlala** [xyxiao001/vue-cropper#133]
一张小图，当截图框超出图片一定范围后，再次移动图片就会发生重叠，底部图片不动，上层图片随着截图框超右移动

**Comment by xyxiao001** [comment]
是不是因为图片设置了最大 最小宽度的原因

**Comment by ghlala** [comment]
图片宽度不是固定的，就是如果图片比较小，但是截图框很大，超过图片一定宽度时在移动，上层图片和下层图片就不再同一位置，会有错位

**Comment by xyxiao001** [comment]
能否截图 或者提供图片

**Comment by xyxiao001** [comment]
已经在0.3版本中加上
