### ISSUE TITLE
发现bug， 裁剪结束，页面无法滚动，解决办法是 

### ISSUE THREAD

**Issue by GuoJiKaiHehe** [xyxiao001/vue-cropper#137]
解决办法是 
在beforeDestroy

window.removeEventListener(this.support,this.changeSize);

**Comment by xyxiao001** [comment]
这个是移动端无法滚动 还是pc

**Comment by GuoJiKaiHehe** [comment]
PC端啊 ，

**Comment by ArvinChen9539** [comment]
相同的问题,开启剪裁后  页面的滚动条无效了  不能通过鼠标滚轮滚动页面o(╥﹏╥)o  你这代码不全啊  this.support,this.changeSize这两个什么函数? @GuoJiKaiHehe

**Comment by GuoJiKaiHehe** [comment]
@ArvinChen9539  要的修改源码。   就是在源码的组件，beforeDestroy 的时候，执行 window.removeEventListener(this.support,this.changeSize);

   这个代码就行了 ， 意思就是卸载掉鼠标滚轮的监听。

**Comment by xyxiao001** [comment]
我这边的处理是开始截图  鼠标按下去监听事件  鼠标松开移除绑定  页面正常操作可以滚动 能描述下什么情况不能滚动吗

**Comment by ArvinChen9539** [comment]
我是打开了自动截图的选项
:autoCrop="true"
:outputSize="0.5"
:autoCropWidth="240"
:autoCropHeight="170"
:fixedBox="true"

**Comment by ArvinChen9539** [comment]
哦 改源码啊  我还以为在自己组件里面呢 @GuoJiKaiHehe

**Comment by xyxiao001** [comment]
我这边测试看看

**Comment by xyxiao001** [comment]
已经在0.3版本中加上 不好意思耽误了这么久

**Comment by Kento97** [comment]
https://github.com/xyxiao001/vue-cropper/issues/459
