### ISSUE TITLE
一张奇怪的图片带来的困惑！

### ISSUE THREAD

**Issue by simplefeel** [xyxiao001/vue-cropper#139]
用这张图片，就会提示：Offset is outside the bounds of the DataView，使用官方提供的demo上传就会包这个错误
图片地址：https://si.geilicdn.com/hz_img_07eb00000164d087a5a30a02685e_1500_1000.jpeg

**Comment by simplefeel** [comment]
![image](https://user-images.githubusercontent.com/9206408/43189880-478aa6ce-902a-11e8-9c35-a765eb88457a.png)
我这边就有问题

**Comment by xyxiao001** [comment]
会不会是因为原图太大base64没办法转化

**Comment by simplefeel** [comment]
原图556kb，我用列子上传个2M的都可以，是不是因为其它问题，https://github.com/43081j/id3/issues/6这是我在网上找的资料，因为对这个项目不是很熟，能否麻烦看下能否解决，不甚感激

**Comment by xyxiao001** [comment]
你修改下上传的base64转化 看看呢  直接转blob， 这个问题是上传图片报错的吧

**Comment by simplefeel** [comment]
经过反复测试，我上传图片转化成的base64编码没有问题，通过vue-cropper中img标签直接引入base64字符串，提示相同的错误（Offset is outside the bounds of the DataView），故有理由怀疑组件是否有小瑕疵，如何方便的话加下我微信zsj1256676224。

**Comment by zhiyiny** [comment]
这个问题现在修复了吗

**Comment by zhy-z** [comment]
这个问题还有吗？

**Comment by git4coder** [comment]
[npm](https://www.npmjs.com/) 那的 0.5.8 版本还有这个问题。
解决办法：
把源码拉下来后修改 【vue-cropper/src/exif-js-min.js:107】 处的 【while (offset < length) {】为【while (offset + 1 < length) {】之后把 src 目录（里边有3个文件）整个复制到你自己的项目中，用法与之前相同(需要修改原来引入 vue-cropper 的路径)
