### ISSUE TITLE
生成JPG图片，有效图片内容外 变黑色背景

### ISSUE THREAD

**Issue by malonzhao** [xyxiao001/vue-cropper#140]
![issue](https://user-images.githubusercontent.com/33288002/43381792-64671e9e-9408-11e8-8d05-0a6a53535114.png)

**Comment by xyxiao001** [comment]
需要透明 请使用png

**Comment by malonzhao** [comment]
这里并不需要 透明

**Comment by xyxiao001** [comment]
jpg 就是黑底的
