### ISSUE TITLE
图片裁剪后，变大了

### ISSUE THREAD

**Issue by cn-zx** [xyxiao001/vue-cropper#141]
3.3M的原始图，lrz压缩到209k，把压缩后的base64传给cropper裁剪，最后得到的图片1.4M大。求解
![wx20180801-104813](https://user-images.githubusercontent.com/29486720/43498211-7c35d45e-9578-11e8-8df7-03fca4a1d1b0.png)
![wx20180801-104842](https://user-images.githubusercontent.com/29486720/43498212-7d7188ea-9578-11e8-83e3-7daf9a0726b3.png)

**Comment by cn-zx** [comment]
1

**Comment by xyxiao001** [comment]
你输出的是png  png会比jpg要大

**Comment by mynameismaosheng** [comment]
不管是png还是jpg  裁剪出来的图片都比上传时候的要大很多. 原图是1.5M  压缩完是300k  上传过来裁剪之后是1.5M  裁剪比例1:1 大小跟原图一样
