### ISSUE TITLE
reader.readAsArrayBuffer(file) 不能识别

### ISSUE THREAD

**Issue by AmadeusSys** [xyxiao001/vue-cropper#144]
这是个怪异的问题，我在项目A中使用vue-cropper + plupload 没有任何问题
我将这个插件拷贝到项目B中 问题就出现了 首先是reader.readAsArrayBuffer(file) 生成的url不被vue-cropper 识别不了报如下错误
![image](https://user-images.githubusercontent.com/25811397/43903188-6ffda8e0-9c1e-11e8-8ab6-70455513f90e.png)
我试着把他修改为 reader.readAsDataURL(file)
vue-cropper 可以识别并预览了，但是！！！
 this.$refs.cropper.getCropBlob() 生成的数据plupload上传却报错 
![image](https://user-images.githubusercontent.com/25811397/43903282-b2530276-9c1e-11e8-910c-e2e5ca4cf659.png)
这些问题在项目A中却没有 两个项目使用相同的脚手架。这就很尴尬

**Comment by xyxiao001** [comment]
你看下是不是安装的版本号不同的原因 或者是说你第二个服务里面有什么事件干扰了上传

**Comment by AmadeusSys** [comment]
嗯 第二个问题是mock和plupload之间有兼容问题 第一个 问题我也怀疑是版本号问题，但是我都把版本号升级到最新，然后node_modules删除重新安装还是复现

**Comment by xyxiao001** [comment]
第一个应该是blob的问题  你blob要用window.createObjectURL转成可以访问的链接
