### ISSUE TITLE
图片比较小的时候截图内部预览的图片会偏移

### ISSUE THREAD

**Issue by hanchilin** [xyxiao001/vue-cropper#146]
cropper-view-box的定位有点问题，当图片比较小的时候，截图框内部的img，偏移会出现问题。
请修改css定位
<img width="458" alt="111" src="https://user-images.githubusercontent.com/4149648/44184561-38f08380-a142-11e8-8800-1014bc4beedb.png">

**Comment by hanchilin** [comment]
<img width="413" alt="222" src="https://user-images.githubusercontent.com/4149648/44184701-db106b80-a142-11e8-92b5-99351c2101c6.png">
目前我是这么解决的

**Comment by xyxiao001** [comment]
我这边看看去什么情况会隐藏 里面的图片定位

**Comment by hanchilin** [comment]
你的在线例子没什么问题，但是复制下来在本地运行就出现了偏移。

**Comment by xyxiao001** [comment]
我觉得应该是全局的图片设置了什么属性 影响的 可以看看你的img的样式吗

**Comment by campar** [comment]
![image](https://user-images.githubusercontent.com/23508762/44227155-361d7f00-a192-11e8-88ca-fecb8d847072.png)
![image](https://user-images.githubusercontent.com/23508762/44227255-7250df80-a192-11e8-9149-a922ac62ba62.png)

Is there any way to change the background color of "_preview image_" from **black** to **transparent** or any other color?

**Comment by yanni4night** [comment]
+1, 
![image](https://user-images.githubusercontent.com/1710436/44462436-2812a700-a647-11e8-95dd-817a7d8155bc.png) .

小图片，右边这个copy很恼人。
