### ISSUE TITLE
我在使用中出现了问题，报错First argument to DataView constructor must be an ArrayBuffer

### ISSUE THREAD

**Issue by sqlFC** [xyxiao001/vue-cropper#149]
![image](https://user-images.githubusercontent.com/29202691/44244926-fe055300-a208-11e8-97a6-08b5176ee1e6.png)
![image](https://user-images.githubusercontent.com/29202691/44244946-12e1e680-a209-11e8-9f1b-e4ac6c0593de.png)

**Comment by sqlFC** [comment]
已经解决，是mock的影响

**Comment by sparGuan** [comment]
如何不去除mock解决报错
