### ISSUE TITLE
裁剪得到的图片尺寸能否按照原图比例

### ISSUE THREAD

**Issue by FreeRide-Joe** [xyxiao001/vue-cropper#15]
例如 1000*1000 的图片，放在500*500的容器内，裁剪框为250*250，裁剪得到的图片大小也为250*250。
能否使裁剪后的大小按照比例为500*500

**Comment by xyxiao001** [comment]
这个目前还没有这个功能 ， 预计下个版本加上

**Comment by xyxiao001** [comment]
功能已经发布 更新到0.2.0就行
props 为 full 
true的时候  会按照原图比例输出截图

**Comment by FreeRide-Joe** [comment]
感谢感谢 @xyxiao001

**Comment by simplefeel** [comment]
测试发现，prop=true的时候，如果把图片大小很大，比如2M ，缩小到很小的时候，会截取不到base64。
![image](https://user-images.githubusercontent.com/9206408/43241474-18c9912a-90ce-11e8-9cbb-2d23cf71e0ea.png)
原图地址：https://pan.baidu.com/s/1e_3wz9Q7mn_g3QgtWo6EAw
