### ISSUE TITLE
没有crop的 preview属性？

### ISSUE THREAD

**Issue by xu455255849** [xyxiao001/vue-cropper#152]
是否可以提供一个边裁剪 边预览的属性，感觉还是有应用场景的

**Comment by xyxiao001** [comment]
现在有预览的

**Comment by xu455255849** [comment]
哦，readme 没看到 ，文档没写 该怎么用呢？

**Comment by xyxiao001** [comment]
我写在下面了 到时候我改一下
`
@realTime="realTime"
// Real time preview function
realTime (data) {
  this.previews = data
}
<div class="show-preview" :style="{'width': previews.w + 'px', 'height': previews.h + 'px',  'overflow': 'hidden',
    'margin': '5px'}">
  <div :style="previews.div">
    <img :src="option.img" :style="previews.img">
  </div>
</div>
`
