### ISSUE TITLE
ios低版本兼容

### ISSUE THREAD

**Issue by cn-zx** [xyxiao001/vue-cropper#155]
在iphone 5c  系统9.3.5 上 拿到base64后，传递给另一个组件，拿不到图片，提示图片跨域。信息如下：Cross-origin image load denied by Cross-Origin Resource Sharing policy.  在6s 系统12.0上正常。android暂时没发现问题

**Comment by xyxiao001** [comment]
图片跨域需要后端允许

**Comment by cn-zx** [comment]
没有涉及后端操作，在a组件中把图片用input读出来，然后提取出base64传值给b组件，b组件中用你的这个裁剪组件接收，进行裁剪操作。
![wx20180824-163304](https://user-images.githubusercontent.com/29486720/44574291-8eb8d180-a7bb-11e8-8c3c-82044440d344.png)
![wx20180824-163344](https://user-images.githubusercontent.com/29486720/44574299-94aeb280-a7bb-11e8-9424-9e7c8e68a89c.png)

**Comment by cn-zx** [comment]
5c 电脑调试就只有一个报错
![wx20180824-173438](https://user-images.githubusercontent.com/29486720/44577638-34703e80-a7c4-11e8-816f-cda16d58de53.png)
系统是9.3.2

**Comment by xyxiao001** [comment]
试一试低版本用blob
