### ISSUE TITLE
请问下nuxt的怎么配置？

### ISSUE THREAD

**Issue by hlbj105** [xyxiao001/vue-cropper#159]
现在配置了：
```
vendor: [
      'vue-cropper'
    ],
 plugins: [
    { src: '~plugins/vue-cropper', ssr: false }
  ]


 vue-cropper.js

import Vue from 'vue'
import VueCropper from 'vue-cropper'
Vue.use(VueCropper)
```
在页面该怎么使用？
```
<vue-cropper
    ref="cropper"
    :img="option.img"
    :outputSize="option.size"
    :outputType="option.outputType"
    ></vue-cropper>
```
直接使用这个会报错

**Comment by hlbj105** [comment]
@xyxiao001 当前页面刷新的话还是会报个错误：
```
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```
我的页面代码：
```
<template>
  <section id="my">
    <vueCropper
    ref="cropper"
    :img="option.img"
    :outputSize="option.size"
    :outputType="option.outputType"
    ></vueCropper>
  </section>
</template>
<script>
export default {
  layout: 'bbs',
  data() {
    return {
      option: {
        img: '127.0.0.1:3000/default.jpeg',
        size: 1,
        outputType: 'png'
      }
    }
  }
}
</script>

```

**Comment by xyxiao001** [comment]
这个问题  我去测试一下看看，

**Comment by onkiit** [comment]
hi, i'm using nuxt too, won't display the image. 
`<vue-cropper ref="cropper"
                             :img="image"
                             :info="true"
                             :fixedNumber="[1,1]"
                             :canMoveBox="true"
                             :autoCrop="true"
                             :maxImgSize="500">
</vue-cropper>
`

and the script

`export default {
    data(){
        return {
            image: 'http://somelinkforimage'
        }
    }
}`

image wont appear. just showing the size info e.g 1000 x 0. height always got zero. thanks

**Comment by xyxiao001** [comment]
@onkiit  could  you show your nuxt vue-cropper config， I want to take a look at it.

**Comment by xyxiao001** [comment]
Vue.use(vueCropper.default)

**Comment by bigHead-zhu** [comment]
那解决了吗

**Comment by siberiadev** [comment]
Working example:
// nuxt.config.js
module.exports = {
   plugins: [
      { src: '~/plugins/vue-cropper', ssr: false }
    ],
   build: {
      vendor: [
         'vue-cropperjs'
      ]
   }
}

// plugins/vue-cropper.js
import Vue from 'vue';
import VueCropper from 'vue-cropperjs';
Vue.component('vue-cropper', VueCropper);

// in page or component
<no-ssr>
   <vue-cropper  
                    :aspectRatio="1"
                    :viewMode="0"
                    :zoomable="true"
                    style="margin-bottom: 20px;"
                    ref="cropper"
                    :src="originalImage"/>
</no-ssr>

**Comment by nelsonlarocca** [comment]
> oh yeah, tysm. just solved

hi !
would you mind sharing the code you fixed ?
thanks !

**Comment by y18272609659** [comment]
> [NightCatSama / vue-slider-component＃114](https://github.com/NightCatSama/vue-slider-component/issues/114)
> 你看看这个

感谢，链接中dfeinberg5的回答解决了我的问题。
