### ISSUE TITLE
IE11 用"use strict"时出现错误

### ISSUE THREAD

**Issue by horityabiriko** [xyxiao001/vue-cropper#160]
IE11 用"use strict"模式时以下类似的代码会出现错误举报
for(n=t;

**Comment by xyxiao001** [comment]
我这边ie11 测试可以使用  你看看是不是开启了兼容模式

**Comment by horityabiriko** [comment]
没有开启兼容模式
我是头部添加了 "use strict" 运行了JavaScript的严格模式

for(n=t; 
会报错 (n 未定义)
能不能改成
for(var n=t;

**Comment by xyxiao001** [comment]
这是是babel转义出来的

**Comment by horityabiriko** [comment]
是babel转义出来的
那我自己调吧
