### ISSUE TITLE
上传图片

### ISSUE THREAD

**Issue by McsNick** [xyxiao001/vue-cropper#161]
请求上传裁剪后的图片使用blob的时候，后端返回的地址没有后缀会导致报错，当做请求了
`this.$refs.cropper.getCropBlob((data) => {
               let formData = new FormData()
               formData.append("shop", data)
               await upload(formData)

 })`

请问怎么用图片上传 ？？ 谢谢
`this.$refs.cropper.getCropDATA((data) => {
              ？？？
               await upload(formData)

 })`

**Comment by xyxiao001** [comment]
图片上传  可以base64  或者 file 或者formdata的 百度上有的

**Comment by McsNick** [comment]
嗯 找了base64转成png后上传，只是问题还没解决。不过应该不是插件的原因 我再摸索下。谢谢

**Comment by lizhong43403** [comment]
不过上传的时候，enlarge参数得传字符串类型，不然宽高会出问题。我没有传值时，默认为数字型1，裁剪200*200的图片上传到服务器上就成了400*400的了。类型是字符串类型时倒是正确的。建议可以在文档上加一个注释。因为修改代码相对比较麻烦一点 @xyxiao001
