### ISSUE TITLE
是否能設定上傳圖片的位置及大小

### ISSUE THREAD

**Issue by jijigo** [xyxiao001/vue-cropper#162]
您好，目前上傳圖片都是依照圖片真實大小

我這邊遇到的問題是
我想把裁切完的圖在放上去，但通常裁切完後圖片都很小（暫時不考慮用preview）
有試著用 `this.$refs.cropper.changeScale()` 但有點難給予數值及比例
希望可以直接調動圖片的大小，感謝

**Comment by xyxiao001** [comment]
你可以按照原始比例输出图片

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/44777184-7aeee000-abac-11e8-859a-43871d95188c.png)

**Comment by jijigo** [comment]
有設定了 但是裁完圖之後圖的大小是真實圖片的大小

<img width="725" alt="2018-08-29 4 58 05" src="https://user-images.githubusercontent.com/13200055/44777299-d751ff80-abac-11e8-8a2e-92737121eec6.png">
<img width="725" alt="2018-08-29 4 58 23" src="https://user-images.githubusercontent.com/13200055/44777300-d7ea9600-abac-11e8-992d-5685ef6bb497.png">
<img width="721" alt="2018-08-29 4 58 30" src="https://user-images.githubusercontent.com/13200055/44777301-d7ea9600-abac-11e8-9b42-19f99333a8d9.png">

**Comment by xyxiao001** [comment]
那你可以选择不要压缩图片的最大宽度 高度 我默认会压缩到2000以下  你可以设置大一点

**Comment by jijigo** [comment]
可以了！原來是我自己不小心設了300😂

**Comment by jijigo** [comment]
那另外想順便問一下
我有使用一個slider拖曳來改變圖片的大小的值
只要拖曳的值改變就呼叫 `this.$refs.cropper.changeScale(value)`
每次改變都跟上次的值比，例如增加30，value就帶入30
如果減少50就帶入-50 
但我發現當我的值變回0的時候並沒有回到原來的大小
是否有預設值呢 或是我有哪邊寫錯了
謝謝

**Comment by xyxiao001** [comment]
这个只放大 和缩小 是动态变化的  this.$refs.cropper.scale 可以获取当前的缩放
