### ISSUE TITLE
ios 上传图片出现自动旋转角度

### ISSUE THREAD

**Issue by heda20** [xyxiao001/vue-cropper#163]
ios 上传图片后出现自动旋转角度 iphone6,7,8 都有

**Comment by xyxiao001** [comment]
有截图吗

**Comment by heda20** [comment]
打印发现 exif.getTag(img, "Orientation")；为undefined, 是否是因为我压缩图片后传给组件出现的。

**Comment by xyxiao001** [comment]
有可能 你可以不压缩 传过来的
