### ISSUE TITLE
getCropBlob没用

### ISSUE THREAD

**Issue by gai-sama** [xyxiao001/vue-cropper#165]
作者这个方法返回的blob是通过HTMLCanvasElement.toBlob()接口来生成的吗？
我把这个blob赋值给img的src属性没起作用，传给后台也是报一堆错
但是我自己用canvas导出blob，赋值给img的src，并上传没有任何问题

**Comment by xyxiao001** [comment]
Blob需要转成可访问的链接才可以给img使用
