### ISSUE TITLE
图片剪裁后变得非常模糊

### ISSUE THREAD

**Issue by myDancer** [xyxiao001/vue-cropper#166]
我设置了固定剪裁框大小，然后图片剪裁后变得非常模糊

参数设置如下：
:img="option.img"
outputSize="1"
autoCropWidth=375
autoCropHeight=192
autoCrop="true"
fixedBox="true"
canMoveBox="false"

怎么设置剪裁后的图片不至于产生锯齿，清晰一点。

另外，文档参数描述的不够清晰。full，original，high，infoTrue这几个参数我反复琢磨了很多遍，还是不知道干什么用。希望能使用更通俗易懂一点的描述

然后测试了full=true之后，发现剪裁后的图片变大了7倍左右。

**Comment by xyxiao001** [comment]
full 是按照原始比例输出  high是按照高分屏去输出的

**Comment by lllomh** [comment]
搞定了吗   咋么解决的
