### ISSUE TITLE
截图框不出图片边界

### ISSUE THREAD

**Issue by cn-zx** [xyxiao001/vue-cropper#167]
能否加一个截图框限制在图片里面的功能？

截图框不能移出到图片外面

看了下centerBox 这个是不是那个功能？

我加了 centerBox 为true  但是还是能移出到图片外

**Comment by cn-zx** [comment]
我用的 0.2.9

**Comment by xyxiao001** [comment]
升级一下就可以了

**Comment by cn-zx** [comment]
OK
