### ISSUE TITLE
截取的图片为png格式的时候，背景色变黑

### ISSUE THREAD

**Issue by iceuncle** [xyxiao001/vue-cropper#168]
截取的图片为png格式的时候，原先的透明背景截取后 会变成黑色。

**Comment by xyxiao001** [comment]
你确定你输出的是png不是jpg吗

**Comment by iceuncle** [comment]
用getCropBlob获取的，输出的是blob数据

**Comment by xyxiao001** [comment]
需要传入outPutType  默认为jpeg的 你需要传入png

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/44967066-4e9edf00-af71-11e8-876a-e437c676db03.png)

**Comment by iceuncle** [comment]
哦哦，是没有传入outputType
