### ISSUE TITLE
图片跨域问题怎么解决

### ISSUE THREAD

**Issue by gouguoqing** [xyxiao001/vue-cropper#169]
我的图片地址是从oss上来的 用这个组件去访问地址的时候有跨域问题 这个怎么解决呢

**Comment by xyxiao001** [comment]
跨域问题需要后端解决

**Comment by gouguoqing** [comment]
后端刚刚解决了跨域问题 但是我每次在调试模式时就是打开F12时没有跨越问题 但是我一关闭f12调试框跨域问题就又出现了 这个是和我设置的宽高又关系吗

**Comment by xyxiao001** [comment]
跨域和图片宽高没问题的
