### ISSUE TITLE
在設置centerBox=true的情況下，旋轉後截圖框被限制在原來為旋轉前的長寬

### ISSUE THREAD

**Issue by jijigo** [xyxiao001/vue-cropper#170]
你好，又來打擾了

我的問題是
旋轉後再使用截圖
設置centerBox=true
截圖框被限制在原來為旋轉前的長寬

如圖
<img width="615" alt="2018-09-04 1 04 44" src="https://user-images.githubusercontent.com/13200055/45011158-b6255f00-b043-11e8-9d52-6b2f3374c769.png">
<img width="585" alt="2018-09-04 12 55 42" src="https://user-images.githubusercontent.com/13200055/45011159-b6255f00-b043-11e8-8769-940c4e78d6cc.png">

就算我先將centerBox改為false再進行截圖，再改回來還是不行

```
this.options.centerBox = false;
this.$refs.cropper.goAutoCrop();
this.options.centerBox = true;
```

是否能修改為限制是旋轉後的長寬呢？

感謝大神

**Comment by xyxiao001** [comment]
动态修改为false  需要执行refresh 才行

**Comment by jijigo** [comment]
有加過refresh的
但似乎最後加上這行就不行了（沒加上這行是可以的）
```
this.options.centerBox = true;
```

**Comment by xyxiao001** [comment]
nextTick的

**Comment by jijigo** [comment]
什麼意思呢

**Comment by jijigo** [comment]
了解
不過refresh之後rotate會重置
所以我必須再設定rotate
最後在設定this.options.centerBox = true;
又要refresh
這樣感覺是無窮迴圈😢

**Comment by xyxiao001** [comment]
你为啥要这样操作呢

**Comment by jijigo** [comment]
就是我們的需求是要可以旋轉後截圖
但截圖框必須4:3貼齊圖片的長寬之中的最小邊
（我們主要是參考airbnb的）

所以我必須要動態調整截圖框
大概就是醬

**Comment by xyxiao001** [comment]
我看我例子操作  动态设置centerBox 也是生效的
