### ISSUE TITLE
第一次进去的时候图片在框的左上方而没有居中

### ISSUE THREAD

**Issue by gouguoqing** [xyxiao001/vue-cropper#172]
我定义了一个宽高的盒子   但是把图片地址放进去以后图片在左上方  没有居中

**Comment by xyxiao001** [comment]
因为截图框默认是居中在容器里面的   如果设置了centerbox那么会限制不超过图片，就会出现在左上角

**Comment by gouguoqing** [comment]
并且我想去掉你源码里面的匿名跨域   应该改哪里的代码呢

**Comment by xyxiao001** [comment]
你是说这个吗  img.crossOrigin = "Anonymous"

**Comment by gouguoqing** [comment]
就是我想去掉里面的图片跨域代码

**Comment by xyxiao001** [comment]
直接改掉 img.crossOrigin = auto 就行

**Comment by gouguoqing** [comment]
图片右上角那个问题 我的意思时第一次进去的时候不会出现裁剪框  我点击裁剪的时候才会出现裁剪框 这个时候图片和裁剪框时居中的  但是我一进去我页面的时候图片在左上方  我需要手动把图片拖出来

**Comment by xyxiao001** [comment]
你的意思 图片不居中吗

**Comment by gouguoqing** [comment]
嗯 时的  我需要手动把图片拖出来

**Comment by xyxiao001** [comment]
我这边测试图片都是居中的，你修改了什么吗

**Comment by gouguoqing** [comment]
后点点击裁剪的时候图片会居中

**Comment by gouguoqing** [comment]
我没有改过  我就给包vue cropper的盒子定义了宽高

**Comment by gouguoqing** [comment]
我在看看吧

**Comment by xyxiao001** [comment]
你可以自动生成裁剪框吧

**Comment by gouguoqing** [comment]
嗯 我现在就是这个思路  一进页面先让裁剪框显示出来

**Comment by gouguoqing** [comment]
还有就是我的图片地址在浏览器打开能访问到图片   但是放在这个组件里面就一直报跨域。。。。

**Comment by xyxiao001** [comment]
Canvas会遇到跨域问题

**Comment by gouguoqing** [comment]
那这个是要后端解决吗

**Comment by xyxiao001** [comment]
是的

**Comment by gouguoqing** [comment]
我刚刚把img.crossOrigin = "Anonymous" 换成了auto  这个会有什么影响吗

**Comment by xyxiao001** [comment]
你百度下的 每个属性有不同含义

**Comment by gouguoqing** [comment]
我现在遇到一个问题  就是页面一加载进去 图片加载失败。。。

**Comment by xyxiao001** [comment]
报什么错

**Comment by gouguoqing** [comment]
跨域  但是我点下裁剪按钮图片又能出来 我实在是不知道为什么

**Comment by gouguoqing** [comment]
就是图片第一次进来报了个跨域   但是我点击裁剪按钮执行操作的时候我的图片又能显示出来 能正常裁剪

**Comment by xyxiao001** [comment]
Canvas
裁剪会遇到跨域

**Comment by gouguoqing** [comment]
现在不是裁剪遇到跨域  是第一次加载图片的时候跨域

**Comment by gouguoqing** [comment]
现在裁剪已经不跨域了  就是第一次加载的时候跨域   点击裁剪按钮的时候图片能正常显示出来并且能正常裁剪

**Comment by xyxiao001** [comment]
你是直接用组件还是自己复制出来的

**Comment by gouguoqing** [comment]
<vueCropper
                   ref="cropper"
                  :img="editorimgOption.img"
                  :outputSize="editorimgOption.size"
                  :outputType="editorimgOption.outputType"
                  :info="editorimgOption.info"
                  :full="editorimgOption.full"
                  :canMove="editorimgOption.canMove"
                  :canMoveBox="editorimgOption.canMoveBox"
                  :fixedBox="editorimgOption.fixedBox"
                  :original="editorimgOption.original"
                  :autoCrop='editorimgOption.autoCrop'
                  :canScale='editorimgOption.canScale'
                  :centerBox='editorimgOption.centerBox'
                   :autoCropWidth ='editorimgOption.autoCropWidth'
                   :autoCropHeight='editorimgOption.autoCropHeight'
                   :fixed="editorimgOption.fixed"
                   :fixedNumber="editorimgOption.fixedNumber"
              ></vueCropper>

**Comment by gouguoqing** [comment]
<vueCropper
                   ref="cropper"
                  :img="editorimgOption.img"
                  :outputSize="editorimgOption.size"
                  :outputType="editorimgOption.outputType"
                  :info="editorimgOption.info"
                  :full="editorimgOption.full"
                  :canMove="editorimgOption.canMove"
                  :canMoveBox="editorimgOption.canMoveBox"
                  :fixedBox="editorimgOption.fixedBox"
                  :original="editorimgOption.original"
                  :autoCrop='editorimgOption.autoCrop'
                  :canScale='editorimgOption.canScale'
                  :centerBox='editorimgOption.centerBox'
                   :autoCropWidth ='editorimgOption.autoCropWidth'
                   :autoCropHeight='editorimgOption.autoCropHeight'
                   :fixed="editorimgOption.fixed"
                   :fixedNumber="editorimgOption.fixedNumber"
              ></vueCropper>

**Comment by gouguoqing** [comment]
直接用<vuecropper></vuecropper>

**Comment by gouguoqing** [comment]
直接用的组件  里面配置参数

**Comment by xyxiao001** [comment]
那我img设置了跨域的  报错截图看看

**Comment by gouguoqing** [comment]
嗯嗯  等等

**Comment by xyxiao001** [comment]
会不会是你图片服务器设置的有问题

**Comment by gouguoqing** [comment]
不会  当我打开调试模式的时候这个图片就不会有跨域问题  会不会是我这个实例还没加载好  所以图片才会显示不出来呢   这个实例加载成功的方法是什么呢

**Comment by xyxiao001** [comment]
应该不是这个问题

**Comment by gouguoqing** [comment]
应该不是 我打开f12调试模式的时候每次加载都能打开这个图片

**Comment by Vicky-fan** [comment]
> 应该不是 我打开f12调试模式的时候每次加载都能打开这个图片

同样，请问怎么解决
