### ISSUE TITLE
上傳圖片能放大嗎

### ISSUE THREAD

**Issue by jijigo** [xyxiao001/vue-cropper#174]
如圖

<img width="863" alt="2018-09-06 5 24 09" src="https://user-images.githubusercontent.com/13200055/45148495-f595ac00-b1f9-11e8-89b2-6af63cedc59b.png">

如果照片本身尺寸很小，能放大嗎？

謝謝

**Comment by xyxiao001** [comment]
不可以 默认不会放大小图的

**Comment by xyxiao001** [comment]
动态修改scale就可以了

**Comment by jijigo** [comment]
好的我再試試！謝謝
