### ISSUE TITLE
png图片会有重影

### ISSUE THREAD

**Issue by gongteng0215** [xyxiao001/vue-cropper#175]

**Comment by gongteng0215** [comment]
![wx20180910-145220](https://user-images.githubusercontent.com/7477366/45281086-51697900-b509-11e8-94fe-9ca3dc8b1cd8.png)
![wx20180910-145235](https://user-images.githubusercontent.com/7477366/45281094-54fd0000-b509-11e8-9b9e-adb6a909d794.png)
<img width="262" alt="wx20180910-145251 2x" src="https://user-images.githubusercontent.com/7477366/45281099-575f5a00-b509-11e8-8fcc-e561cb5c359e.png">

**Comment by xyxiao001** [comment]
你在在线例子上看看有没有问题
http://xyxiao.cn/vue-cropper/example/

看看你的img有没有设置对齐方式  影响的

**Comment by gongteng0215** [comment]
@xyxiao001 这上面都是jpg，jpg格式的图片可以，png就不行o(╥﹏╥)o

**Comment by xyxiao001** [comment]
Png可以啊 我这边测试都可以 你把图片发出来一下

**Comment by gongteng0215** [comment]
是美工那边的问题，我去，png都能存出花样了，o(╥﹏╥)o
