### ISSUE TITLE
Can I contribute or can you create a feature?

### ISSUE THREAD

**Issue by felipemengatto** [xyxiao001/vue-cropper#176]
Hello, how are you?
I would like to contribute a new part in your code, creating an event only for when it is happening "Move Crop", how can I build with code? or can you do this for the community?

Currently I made a Fork of the project and there I implemented it.
However it would be very useful to have this default.

I'll leave here the place where I put the codes:

```js
cropMove(e) {
 ...
  newX = x - this.cropOffsertX;
  newY= y - this.cropOffsertY;
  this.cropX = newX
  this.cropY = newY
  // on here
  this.$emit('movingCrop', true);
},
```
And 
```js
leaveCrop(e) {
  // on here
  this.$emit('movingCrop', false);
  ...
}
```
can you help me?

**Comment by xyxiao001** [comment]
Do you want to trigger events when moving the crop box?

**Comment by felipemengatto** [comment]
That's right, it's very useful for me this function, because then I know exactly when the user starts moving the cut and ends it. No interference from any other situation.

**Comment by xyxiao001** [comment]
Ok I will add it as soon as possible.

**Comment by felipemengatto** [comment]
Thank you Friend, you are incredible! and the Vue-cropper too!

**Comment by xyxiao001** [comment]
I added at 0.37 version, you should update it

**Comment by xyxiao001** [comment]
methods   @cropMoving
dataType 
` {
   moving: true, // moving
   axis: {
         x1: 1, 
	 x2: 1，
	 y1: 1，
	 y2: 1 
   }
 }`

**Comment by felipemengatto** [comment]
Thanks, friend I'll update now!
As soon as the company's application goes to the air, I advise you to take a look at your component running the other side of the world :)
Thanks again! Great week.

**Comment by xyxiao001** [comment]
Very happy that you use
