### ISSUE TITLE
裁剪框不出现，display: none, 宽高都为0, 检查了好久。。。跪求

### ISSUE THREAD

**Issue by Mojie-Wang** [xyxiao001/vue-cropper#179]
![image](https://user-images.githubusercontent.com/20314455/45540782-e63ce100-b83f-11e8-9f9d-56e4d27242bd.png)
![image](https://user-images.githubusercontent.com/20314455/45540835-08cefa00-b840-11e8-9891-0aa7231f2b0b.png)
![image](https://user-images.githubusercontent.com/20314455/45541238-1769e100-b841-11e8-9aef-a8367659202f.png)
![image](https://user-images.githubusercontent.com/20314455/45541271-2f416500-b841-11e8-9e22-4ee9748b04bd.png)

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/wxwKGz
参考这个看看的

**Comment by Mojie-Wang** [comment]
谢谢，老铁

**Comment by IEfucker** [comment]
@Mojie-Wang 请问你的问题出在哪，我遇到了相同的问题

**Comment by xyxiao001** [comment]
如果是弹出框 组件需要异步渲染

**Comment by IEfucker** [comment]
异步渲染的issue看到了，用v-if，但我现在没用modal，直接放在外面了也不行，图片能出来，cropper-crop-box样式和题主一样
感觉应该是我们的错误，题主说下怎么解决的

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/wxwKGz
你对比这个链接例子看看的

**Comment by IEfucker** [comment]
@xyxiao001 谢谢，正在看着猜
