### ISSUE TITLE
base64赋值给图片img  ie能显示 chrome下报错

### ISSUE THREAD

**Issue by jhuizzzz** [xyxiao001/vue-cropper#181]
base64赋值给图片img  ie能显示 chrome下报错
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by xyxiao001** [comment]
这是因为base64中文 的原因  window.btoa(encodeURIComponent('中文')) 然后传的

**Comment by jhuizzzz** [comment]
> 这是因为base64中文 的原因 window.btoa(encodeURIComponent('中文')) 然后传的

传的base64中并没有中文啊

**Comment by xyxiao001** [comment]
我的意思是如果base64是中文转过来的会有这个问题的
