### ISSUE TITLE
图片跨域问题

### ISSUE THREAD

**Issue by ROSEMUSE** [xyxiao001/vue-cropper#183]
上传完图片后传入img参数显示跨域，该如何解决？？

**Comment by xyxiao001** [comment]
后端设置允许图片跨域的

**Comment by ROSEMUSE** [comment]
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

我看说是cavans图片跨域的问题？

**Comment by xyxiao001** [comment]
对啊  canvas图片裁剪需要服务器图片支持跨域

**Comment by ROSEMUSE** [comment]
但是图片放在静态资源服务器，如何解决那？

**Comment by xyxiao001** [comment]
你可以开启静态服务器针对于某一域名的跨域的
