### ISSUE TITLE
incorrect responsive

### ISSUE THREAD

**Issue by arbabi2010** [xyxiao001/vue-cropper#188]
Hi. i want to use this in mobile resolution but not working very well. when size is 1200* 400 . don't show in responsive mode.
what should i do

**Comment by xyxiao001** [comment]
You can turn on the full property to output based on the size of the original image

**Comment by arbabi2010** [comment]
@xyxiao001 . Actually i want to crop 1200*460 of an image . how can i set width and height of cut class to crop correct size in desktop and mobile view
