### ISSUE TITLE
不支持在Modal中使用

### ISSUE THREAD

**Issue by skanger** [xyxiao001/vue-cropper#19]
在使用iview的Modal组件中嵌入本插件，
Modal刚刚开始是隐藏的，点击按钮打开后，
初始化的数据全部失效，而且也无法切图，如下图所示
![08ff7ca8-31d5-4c0f-904a-962209c344a8](https://user-images.githubusercontent.com/18080860/29994900-fe140336-900d-11e7-8fe9-c2936b718e82.png)

**Comment by xyxiao001** [comment]
你可以使用v-if 在model渲染之后 然后渲染截图 这样就可以了

**Comment by skanger** [comment]
十分有用，感谢你的帮助
