### ISSUE TITLE
裁剪框抖动优化建议

### ISSUE THREAD

**Issue by chaoing** [xyxiao001/vue-cropper#190]
1、裁剪框放大到和容器框一样大的时候，上下左右移动裁剪框会有1px的抖动。可以内部优化处理一下这种情况的移动

**Comment by xyxiao001** [comment]
好的 你是说centerbox开启时有问题吗

**Comment by chaoing** [comment]
不开启的时候更明显，开启的时候也有点。
复现方法：test/index.html  中将裁剪框长宽拖成最大。 再移动裁剪框的时候，会上下抖动，有时还会超出容器1px。
预期：裁剪框最大的时候，移动裁剪框，裁剪框固定不动

**Comment by xyxiao001** [comment]
好的 这个问题我去看一下

**Comment by xyxiao001** [comment]
0.41版本已解决
