### ISSUE TITLE
outputType

### ISSUE THREAD

**Issue by IEfucker** [xyxiao001/vue-cropper#191]
设定outputType失效，发现这行代码，
https://github.com/xyxiao001/vue-cropper/blob/master/src/vue-cropper.vue#L1567

`callback(new Blob([arr], { type: that.type || "image/png" }));`

这里的type是不是写错了

**Comment by xyxiao001** [comment]
没有啊  你设置什么没成功

**Comment by IEfucker** [comment]
哦看文档不仔细
我看这个问题最后的回复，截图输出是不是也要考虑下原图片是什么格式
https://github.com/xyxiao001/vue-cropper/issues/110#issuecomment-384928986

我看有效值有`jpeg || png || webp`
请问原图片bmp，gif怎么设定

**Comment by xyxiao001** [comment]
canvas只支持这三种输出

**Comment by xyxiao001** [comment]
应该是可以的
