### ISSUE TITLE
IE9+不兼容

### ISSUE THREAD

**Issue by web-Marker** [xyxiao001/vue-cropper#192]
您好，IE9以上好像不支持，目前IE11的用户好像不多，有什么办法可以让IE9+也支持吗，谢谢

**Comment by xyxiao001** [comment]
Ie9我抽时间去看一看

**Comment by xyxiao001** [comment]
ie9 建议使用js的cropper  我在ie9不支持

**Comment by web-Marker** [comment]
> ie9 建议使用js的cropper 我在ie9不支持

请问IE11支持吗？

**Comment by xyxiao001** [comment]
可以
