### ISSUE TITLE
截取框上下拖动问题

### ISSUE THREAD

**Issue by ibubbo** [xyxiao001/vue-cropper#193]
![image](https://user-images.githubusercontent.com/32586819/46912770-5b234800-cfb1-11e8-925a-14b5ff2a11bf.png)
不能完全拖到最底部，并且顶部超出了一点 ↓：
![image](https://user-images.githubusercontent.com/32586819/46912773-87d75f80-cfb1-11e8-9786-a47cc031e447.png)
左右没有问题（在你们给的demo中截的图）。

**Comment by xyxiao001** [comment]
好的 我去看看

**Comment by xyxiao001** [comment]
@ibubbo 提供下图片 我测试下吧

**Comment by xyxiao001** [comment]
0.41版本已解决
