### ISSUE TITLE
如果父节点或其他原因使得span.cropper-view-box的css样式是text-align;center;或right 会出现异常

### ISSUE THREAD

**Issue by SCWR** [xyxiao001/vue-cropper#194]
1. 如果父节点或其他原因使得span.cropper-view-box的css样式是text-align:center;或right 会出现异常
![image](https://user-images.githubusercontent.com/8925282/46924569-c1af7100-d058-11e8-8e20-e08a9056fc6e.png)

所以应该给span.cropper-view-box 强制赋值text:left

![snipaste_2018-10-15_09-02-45](https://user-images.githubusercontent.com/8925282/46924658-7a75b000-d059-11e8-84da-70014702c6ea.jpg)
就正常了
![image](https://user-images.githubusercontent.com/8925282/46924666-87929f00-d059-11e8-91a2-613c0f82e697.png)

2.如果元素一开始是隐藏的因为有些需求是点开才出现弹窗,但是那时会出异常
这是因为获取不到高宽.

会出现这种情况

![image](https://user-images.githubusercontent.com/8925282/46924746-1bfd0180-d05a-11e8-9f72-806b3b5b1282.png)

拉不开 因为宽高被获取为0,0

现在解决方案是
this.$refs.cropper.checkedImg()
this.$refs.cropper.reload()

希望推出一个api能够重新启动

**Comment by xyxiao001** [comment]
0.41已经加上对齐的问题，如果是弹框，你需要等弹框出来之后去渲染

**Comment by SCWR** [comment]
在vue文件中应该如何做到弹框出来之后去渲染

**Comment by xyxiao001** [comment]
v if

**Comment by SCWR** [comment]
好的 我试试  谢谢你的回答
