### ISSUE TITLE
Manually set cropAxis, imgAxis, scale

### ISSUE THREAD

**Issue by batmanhit** [xyxiao001/vue-cropper#198]
Is it possible to set the cropAxis & imgAxis manually when the image has loaded?

**Comment by batmanhit** [comment]
So what I want to achieve is that we crop the image and when we try to edit the cropped image, we need to replicate the cropping dialog.

**Comment by xyxiao001** [comment]
Cannot set cropAxis and   ImgAxis

**Comment by batmanhit** [comment]
So we cannot replicate the previous state?

**Comment by xyxiao001** [comment]
you can modify the values in the components to achieve them.

**Comment by xyxiao001** [comment]
img：  this.$refs.cropper.x  this.$refs.cropper.y
crop：  this.$refs.cropper.cropX  this.$refs.cropper.cropY

**Comment by batmanhit** [comment]
This is awesome.
And the scale will be calculated automatically?

**Comment by xyxiao001** [comment]
yeah  this.$refs.cropper.scale

**Comment by batmanhit** [comment]
when do I need to set those values?
Once the image loaded, all of the values get initialized.

**Comment by xyxiao001** [comment]
imgLoad  methods

**Comment by batmanhit** [comment]
Do I need to call checkoutImgAxis() after that?

**Comment by batmanhit** [comment]
It seems like working without checkoutImgAxis().
Thanks for all your help.
