### ISSUE TITLE
除了服务器端解决资源跨域 还有没其他办法解决

### ISSUE THREAD

**Issue by 617450941** [xyxiao001/vue-cropper#2]
除了服务器端解决资源跨域 还有没其他办法解决

**Comment by xyxiao001** [comment]
没办法了 必须要后端允许 你上传不可以吗

**Comment by xyxiao001** [comment]
img: '../asset/favicon.ico', 我这样传入本地图片也是正常的

**Comment by 617450941** [comment]
我裁剪的这个图片是已经上传好了的图片  不是上传前裁剪 最后还是让服务端返回base64编码的图片过来 绕过了这个跨域问题 才解决了

**Comment by xyxiao001** [comment]
你可以服务端设置允许的 蛮简单的设置， 不过你这种也行

**Comment by 617450941** [comment]
服务端环境 条件不允许跨域 只能这样处理了

**Comment by xyxiao001** [comment]
好吧，到时我在研究 研究 有没有办法
