### ISSUE TITLE
希望添加背景色支持

### ISSUE THREAD

**Issue by skanger** [xyxiao001/vue-cropper#20]
在我使用透明png图片的时候， 默认切割出来的是黑色背景色，
应该很多人都存在需要透明背景色的需求吧，如下图所示
![cropper-touming](https://user-images.githubusercontent.com/18080860/30021931-aad3de78-919b-11e7-90db-d705106c2098.png)
![gougou-butouming](https://user-images.githubusercontent.com/18080860/30021937-aef621aa-919b-11e7-94c6-8ed70528386c.png)

**Comment by xyxiao001** [comment]
你配置下outputType 属性设置为png  就可以了
