### ISSUE TITLE
有时候option.img赋值base64数据后，没有执行imgLoad事件（PC端）

### ISSUE THREAD

**Issue by zhangsuyun1230** [xyxiao001/vue-cropper#200]
第一次赋值，有打印出success，
第二次赋值，没有打印imgLoad事件的回调结果

**Comment by xyxiao001** [comment]
如果图片数据没有发生更改 不会触发多次

**Comment by zhangsuyun1230** [comment]
但是有时候会出现这种情况，option.img已经赋值
![image](https://user-images.githubusercontent.com/40994217/47342042-3c216600-d6d5-11e8-9280-cd8c368f3ac0.png)

**Comment by xyxiao001** [comment]
怎么操作出现的  我这边例子并没偶遇出现这样的情况

**Comment by zhangsuyun1230** [comment]
第一次选中一张图片，把url赋值给img，点击下一步，可以显示出来，
点击上一步，把previews清空，再次选中一张图片，把url赋值给img，点击下一步，有时候会不显示，偶现的

**Comment by xyxiao001** [comment]
这个需要你手动清空input file
