### ISSUE TITLE
图片加载不成功  老是跨域， 但服务端设置了跨域，烦请看看

### ISSUE THREAD

**Issue by GrowingMonkey** [xyxiao001/vue-cropper#205]
`<template>
  <div class="image-croppy-container">
    <div class="header">
      <h1>选择封面</h1>
    </div>
    <div class="center">
      <div class="left" @mouseup="moveMouse()">
        <div class="croppy-title">封面展示区域</div>
        <vueCropper
          class="croppy-box"
          ref="cropper2"
          :img="example2.img"
          :outputSize="example2.size"
          :outputType="example2.outputType"
          :info="example2.info"
          :canScale="example2.canScale"
          :autoCrop="example2.autoCrop"
          :autoCropWidth="example2.autoCropWidth"
          :autoCropHeight="example2.autoCropHeight"
          :fixed="example2.fixed"
          :fixedNumber="example2.fixedNumber"
          @realTime="realTime"
        ></vueCropper>
      </div>
      <div class="right">
        <div class="yulan-item1" style="position: relative">
          <img :src="modelSrc?modelSrc:cover" alt="" class="-img" style="width: 210px;height: 118px"
               crossOrigin="Anonymous">
          <div class="info-box">
            <h1>图文封面（16：9）</h1>
            <span>客户端首页显示此封面</span>
          </div>
        </div>
        <div class="yulan-item2">
          <img :src="modelSrc?modelSrc:cover" alt="" class="-img" crossOrigin="Anonymous">
          <div class="info-box">
            <h1>图文封面（1 ：1）</h1>
            <span>分享微信，QQ等第三方平台，用户看到此封面</span>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <span class="cancle" @click.stop.prevent="showImgUp">取消</span>
      <span class="sure" @click.stop.prevent="sureFilish">确定</span>
    </div>
  </div>
</template>

<script>
  import VueCropper from 'vue-cropper'

  export default {
    props: ['cover'],
    name: 'imageCropper',
    data() {
      return {
        mobileCover:'',
        coverName: '',
        crap: false,
        previews: {},
        modelSrc: '',
        lists: [
          {
            img: 'https://fengyuanchen.github.io/cropper/images/picture.jpg'
          },
          {
            img: 'http://ofyaji162.bkt.clouddn.com/touxiang.jpg'
          }
        ],
        downImg: '#',
        example2: {
          img: window.sessionStorage.getItem('articleCover'),
          info: true,
          size: 1,
          outputType: 'jpeg',
          canScale: false,
          autoCrop: true,
          canMoveBox: true,
          // 只有自动截图开启 宽度高度才生效
          autoCropWidth: 266,
          autoCropHeight: 133,
          // 开启宽度和高度比例
          fixed: true,
          fixedNumber: [16, 9]
        }
      }
    },
    beforeMount(){
      console.log(this.cover);
      this.example2.img=window.sessionStorage.getItem('articleCover');
    },
    mounted() {
      // this.example2.img = this.cover;
      this.coverName = new Date().getTime();
      // this.finish('base64');
    },
    components: {
      VueCropper
    },
    methods: {
      showImgUp() {
        this.$store.commit({type: 'SHOW_DIALOG', dialogType: 4})
      },
      moveMouse() {
        console.log(1111111);
        this.finish('base64')
      },
      realTime(data) {
        this.previews = data;
      },
      canvasEg() {
        var that = this;
        var image = new Image();
        var canvas = document.createElement('canvas');
        var ctx = canvas.getContext("2d");
        var $img = document.querySelector('.-img');
        image.crossOrigin = "anonymous";
        image.onload = function () {
          var width = this.width;
          var height = this.height;
          var dataUrl;
          ctx.drawImage(image, that.previews.w / 2, that.previews.h / 2, width, height, 0, 0, width, height);
          dataUrl = canvas.toDataURL("image/png");
          $img.src = dataUrl;
        }
        console.log(that.cover);
        image.src = this.example2.img;
      },
      finish(type) {
        // 输出
        // var test = window.open('about:blank')
        // test.document.body.innerHTML = '图片生成中..'
        if (type === 'blob') {
          this.$refs.cropper2.getCropBlob((data) => {
            var img = window.URL.createObjectURL(data)
            this.model = true;
            this.modelSrc = img;
          })
        } else {
          this.$refs.cropper2.getCropData((data) => {
            this.model = true;
            console.log(data);
            this.modelSrc = data;
          })
        }
      },
      sureFilish() {

        let file =this.dataURLtoFile(this.modelSrc,this.cover);
        console.log(file);
        let filename = this.coverName;
        let param = new FormData();  // 创建form对象
        param.append('pictures', file, filename);  // 通过append向form对象添加数据
        param.append('uid', this.$store.state.userInfo.uid);
        // 添加form表单中其他数据
        console.log('上传图片');
        this.$store.dispatch({
          type:'upload_img',
          params:param,
          isCover:true,
        }).then((res) => {
          console.log(res);
          if(parseInt(res.data.code)!==0){
            this.$message({
              showClose: true,
              message: res.data.msg,
              type: 'error'
            });
          }
          this.$store.commit('HIDDEN_DIALOG', {
            dialogType: 4
          })
        })
      },
      dataURLtoFile(dataurl, filename) {//将base64转换为文件
        var arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1],
          bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);
        while (n--) {
          u8arr[n] = bstr.charCodeAt(n);
        }
        return new File([u8arr], filename, {type: mime});
      }
      // down (type) {
      //   // event.preventDefault()
      //   var aLink = document.createElement('a')
      //   aLink.download = 'demo'
      //   // 输出
      //   if (type === 'blob') {
      //     this.$refs.cropper.getCropBlob((data) => {
      //       this.downImg = data
      //       aLink.href = data
      //       aLink.click()
      //     })
      //   } else {
      //     this.$refs.cropper.getCropData((data) => {
      //       this.downImg = data
      //       aLink.href = data
      //       aLink.click()
      //     })
      //   }
      // },
    }
  }
</script>

<style lang="less" scoped>
  .image-croppy-container {
    width: 808px;
    height: 638px;
    border-radius: 10px;
    background: #ffffff;
    .header {
      padding: 30px;
      border-bottom: 1px solid #f7f7f7;
      box-sizing: border-box;
      h1 {
        font-size: 20px;
        color: #2c2a25;
      }
    }
    .center {
      display: flex;
      .left {
        max-width: 387px;
        padding: 43px 60px 0 60px;
        box-sizing: border-box;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        .croppy-title {
          font-size: 16px;
          color: #8f8f8f;
          margin-bottom: 30px;
        }
        .croppy-box {
          width: 266px;
          height: 212px;
        }
      }
      .right {
        .yulan-item1 {
          margin-bottom: 18px;
          display: flex;
          height: 168px;
          overflow: hidden;
          align-items: center;
          justify-content: center;
          img {
            width: 210px;
            height: 168px;
          }
          .info-box {
            width: 210px;
            height: 168px;
            padding-left: 20px;
            padding-top: 38px;
            box-sizing: border-box;
            h1 {
              font-size: 18px;
              color: #2c2a25;
              margin-bottom: 20px;
            }
            span {
              font-size: 14px;
              color: #8f8f8f;
            }
          }
        }
        .yulan-item2 {
          display: flex;
          height: 210px;
          overflow: hidden;
          align-items: center;
          justify-content: center;
          img {
            width: 210px;
            height: 210px;
          }
          .info-box {
            width: 210px;
            height: 210px;
            padding-left: 20px;
            padding-top: 8px;
            box-sizing: border-box;
            h1 {
              font-size: 18px;
              color: #2c2a25;
              margin-bottom: 20px;
            }
            span {
              font-size: 14px;
              color: #8f8f8f;
            }
          }
        }
      }
    }
    .footer {
      margin-top: 60px;
      display: flex;
      justify-content: center;
      span {
        border-radius: 10px;
        display: inline-block;
        width: 118px;
        height: 44px;
        line-height: 44px;
        text-align: center;
        cursor: pointer;
      }
      .cancle {
        margin-right: 50px;
        background: #eeeeee;
        font-size: 22px;
        color: #8f8e8e;
      }
      .sure {
        background: #fef450;
        font-size: 22px;
        color: #2c2a25;
      }
      .cancle:hover {
        opacity: 0.6;
      }
      .sure:hover {
        opacity: 0.6;
      }
    }
  }
</style>
`

**Comment by xyxiao001** [comment]
设置了应该就可以了  没设置成功吗

**Comment by GrowingMonkey** [comment]
@xyxiao001 设置了  但是会报图片跨域的错误，使用项目demo的图片地址  不存在跨域 但使用自己数据库的项目地址，就会报跨域，然后我再服务端设置后发现  在导入的vueCropper组件的父组件里的mounted里测试  如果是
![image](https://user-images.githubusercontent.com/24692542/47553873-abe45a80-d93a-11e8-85fb-2f9f82558067.png)zhe这样写就会报跨域错误，如果是
![image](https://user-images.githubusercontent.com/24692542/47553912-c585a200-d93a-11e8-91e9-28eef8c43b39.png)
就不会报错了

**Comment by xyxiao001** [comment]
canvas 才会有跨域问题 img标签不存在跨域问题

**Comment by GrowingMonkey** [comment]
不是canvas 而是使用的img标签回显的   而且这个跨域是偶尔引起的   
![image](https://user-images.githubusercontent.com/24692542/47555313-0f23bc00-d93e-11e8-96de-df77497beb37.png)
移动选框4次就好了
![image](https://user-images.githubusercontent.com/24692542/47555407-5a3dcf00-d93e-11e8-96f2-dea944e1870b.png) 截图成功

**Comment by xyxiao001** [comment]
这么奇怪吗   img按理是不存在跨域  只有canvas绘制才会触发

**Comment by GrowingMonkey** [comment]
如果我将传给vueCropper的图片地址直接写死  而不是其他组件传过来的变量的话  就是好的
![image](https://user-images.githubusercontent.com/24692542/47555752-329b3680-d93f-11e8-9c99-8686edaa6b4c.png)
@xyxiao001   我现在也只有怀疑是生命周期或者数据响应的问题

**Comment by GrowingMonkey** [comment]
this.$refs.cropper2.getCropData((data) => {
            this.model = true;
            console.log(data);
            this.modelSrc = data
          })
排查了这个方法报跨域，加载的组件的时候报2次跨域，移动选框截图也就是这个方法，注释点 无论我怎么移动选框 他都不爆跨域了
@xyxiao001

**Comment by xyxiao001** [comment]
这个是调用canvas截图的

**Comment by GrowingMonkey** [comment]
还是跨域  使用最新版本的，传给vue-croppy组件的img 不是响应的  不能根据我的img地址变化而变化
![image](https://user-images.githubusercontent.com/24692542/47635675-d16aa180-db90-11e8-8ff7-abdf15ad4f2a.png)
![image](https://user-images.githubusercontent.com/24692542/47635688-e1828100-db90-11e8-8afe-504e83cc0656.png)
![image](https://user-images.githubusercontent.com/24692542/47635695-e6473500-db90-11e8-8c58-bb7638cf59c9.png)
![image](https://user-images.githubusercontent.com/24692542/47635719-ffe87c80-db90-11e8-999d-8adfbc357a87.png)
@xyxiao001

**Comment by xyxiao001** [comment]
加qq群857471950

**Comment by 1029800858** [comment]
> 还是跨域 使用最新版本的，传给vue-croppy组件的img 不是响应的 不能根据我的img地址变化而变化 ![image](https://user-images.githubusercontent.com/24692542/47635675-d16aa180-db90-11e8-8ff7-abdf15ad4f2a.png) ![image](https://user-images.githubusercontent.com/24692542/47635688-e1828100-db90-11e8-8afe-504e83cc0656.png) ![image](https://user-images.githubusercontent.com/24692542/47635695-e6473500-db90-11e8-8c58-bb7638cf59c9.png) ![image](https://user-images.githubusercontent.com/24692542/47635719-ffe87c80-db90-11e8-999d-8adfbc357a87.png) @xyxiao001

请问解决了嘛？如何解决的能提供一下解决方案嘛

**Comment by xyxiao001** [comment]
报错提示很明显，跨域问题

**Comment by 1029800858** [comment]
> 报错提示很明显，跨域问题

我知道，我也遇到楼主一样的问题了。服务器也配置了。我就问下他最后是怎么处理的
