### ISSUE TITLE
希望支持按裁剪框的尺寸倍率输出图片的尺寸

### ISSUE THREAD

**Issue by Ghostdar** [xyxiao001/vue-cropper#206]
有些需要很大尺寸的图片场景，如果只支持输出裁剪框尺寸的图片，就不友好了

**Comment by xyxiao001** [comment]
可以的 加个版本加上的

**Comment by Ghostdar** [comment]
最新版本有加上吗？我看文档里好像没有控制的参数

**Comment by xyxiao001** [comment]
下个版本加上

**Comment by xyxiao001** [comment]
你可以开启full  按照原始比例输出

**Comment by xyxiao001** [comment]
@Ghostdar 升级最新版  0.45 可以采用倍率输出 props enlarge

**Comment by Ghostdar** [comment]
@xyxiao001 哈哈感谢感谢，我刚自己撸完补丁，你就更新了，这速度可以
