### ISSUE TITLE
从0.2.9升级到0.4.5选择图片后将要渲染，提示组件渲染不出来

### ISSUE THREAD

**Issue by Molly0920** [xyxiao001/vue-cropper#207]
选择图片后将要渲染，控制台提示Failed to mount component: template or render function not defined.
参数什么的都对了，我是从0.2.9升级到0.4.5
![_20181105135601](https://user-images.githubusercontent.com/26627730/47980445-a937f100-e102-11e8-9973-062558ebe3bb.png)
![_20181105135731](https://user-images.githubusercontent.com/26627730/47980480-cc62a080-e102-11e8-81d1-bbbe5226cfc1.png)

**Comment by xyxiao001** [comment]
import { VueCropper } from 'vue-cropper'

**Comment by Molly0920** [comment]
> import { VueCropper } from 'vue-cropper'

这个有的
![_20181105140155](https://user-images.githubusercontent.com/26627730/47980603-6591b700-e103-11e8-82ca-2b5b9127fea9.png)

**Comment by Molly0920** [comment]
之前用的0.2.9截图功能挺正常的，就是低版本的mac会有点反应慢，就选择升级了一下，升级了之后就提示无法渲染了，检查了引用传参都没有问题

**Comment by xyxiao001** [comment]
升级之后报什么错

**Comment by Molly0920** [comment]
就是选择完图片后要在弹窗口渲染，控制台就提示Failed to mount component: template or render function not defined.

**Comment by Molly0920** [comment]
我刚刚试了一下还原会0.2.9渲染组件就正常，可以正常剪切图片

**Comment by xyxiao001** [comment]
好的 我这边看看  是nuxt吗

**Comment by Molly0920** [comment]
是的，nuxt2.0

**Comment by xyxiao001** [comment]
https://zh.nuxtjs.org/faq/window-document-undefined/

**Comment by xyxiao001** [comment]
加一下这个看看

**Comment by Molly0920** [comment]
用process.BROWSER_BUILD会提示组件未注册，我用的process.browser

**Comment by xyxiao001** [comment]
设置 plugins ssr false 呢   https://zh.nuxtjs.org/guide/plugins/#%E4%BD%BF%E7%94%A8-vue-%E6%8F%92%E4%BB%B6

**Comment by Molly0920** [comment]
是不是你们的vue-loader版本问题，因为nuxt2.0依赖的已经到15.+了

**Comment by xyxiao001** [comment]
这样嘛  那只能我这边到时候去测试下

**Comment by 2ue** [comment]
升级之后(0.4.5)遇到同样问题，
+ webpack@4.25.1
+ vue@2.5.17
+ vue-cli@2.9.6
各种方法试了不起作用。
请问有什么好的解决方法么？

**Comment by xyxiao001** [comment]
你也是nuxt框架吗，还是报错

**Comment by 2ue** [comment]
> 你也是nuxt框架吗，还是报错

没有用nuxt，就是使用了一个饿了么UI组件库

**Comment by maniaslol** [comment]
我也有載不到套件的問題是使用Vue cli3,在main.js使用
import VueCropper from 'vue-cropper' 

Vue.use(VueCropper)

載入失敗

**Comment by 2ue** [comment]
> @2ue 参考下文档的最新引入方式

解决了，谢谢

**Comment by Molly0920** [comment]
问题没解决就close?

**Comment by xyxiao001** [comment]
解决了 nuxt使用方式更新在文档了

**Comment by 86driver** [comment]
> 决了 nuxt使用方式更新在文档

老哥 现在在Nuxt中怎引用，  我试过readme的方法，不行，   issue中的方法也不行， nuxt版本 2.0.0

**Comment by xyxiao001** [comment]
文档有个qq群，加一下的，看看你的错误
