### ISSUE TITLE
如何不使用npm 安装 ，直接下载到本地使用这个插件呢

### ISSUE THREAD

**Issue by zxzhgk** [xyxiao001/vue-cropper#21]
现在我下载到本地使用这个插件，报错

**Comment by xyxiao001** [comment]
引入dist目录的index.js, 或者src 里面的vue文件直接当作普通组件

**Comment by zxzhgk** [comment]
哇，大神这么快就回复了，我现在就是这么用的，可是一直报  
Error in beforeCreate hook: "TypeError: Cannot read property 'call' of undefined"

found in

---> <VueCropper> at Z:\svn\hd\public\basesrc\template\cropper\vue-cropper.vue
       <Root>

这个错误

**Comment by zxzhgk** [comment]
我是把src里面的vue当做普通组件用，然后就报上面这个错误

**Comment by xyxiao001** [comment]
截图看看错误

**Comment by xyxiao001** [comment]
你怎么使用的  组件使用 可以直接参考example里面的例子

**Comment by zxzhgk** [comment]
![Uploading QQ图片20170912172014.png…]()

**Comment by xyxiao001** [comment]
加我qq 463618622 吧

**Comment by zxzhgk** [comment]
好的

**Comment by pengliheng** [comment]
![image](https://user-images.githubusercontent.com/14355994/38711215-f55781ee-3ef6-11e8-8cd1-05ab6078404f.png)

**Comment by pengliheng** [comment]
一个神奇的错误。当我重新编译一次就不会再报错，，
也就是说第一次编译，webpack一定报错，
而第二次编译就不报错了

**Comment by casyalex** [comment]
遇到同一个错误。。。改动一下热更替就没错了
