### ISSUE TITLE
每次切换分支后 提示 无法找到vue-cropper模块，需要重新安装后才可以。

### ISSUE THREAD

**Issue by qinghua5453** [xyxiao001/vue-cropper#211]
每次切换分支后 提示 无法找到vue-cropper模块，需要重新安装后才可以。

This dependency was not found:

* vue-cropper in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/upload/cropper-1.0.vue

To install it, you can run: npm install --save vue-cropper

事实上，我是安装了的。
先是执行 npm install --save vue-cropper 切换回这个分支后提示如上。
然后卸载
再次执行npm install --save-dev vue-cropper 再切换回这个分支后提示如上。

git 我用的是git-up

**Comment by xyxiao001** [comment]
你的node_modules 添加到.gitignore里面

**Comment by qinghua5453** [comment]
node_modules/
/dist/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
/test/unit/coverage/
/test/e2e/reports/
selenium-debug.log
package-lock.json

# Editor directories and files
.idea
.vscode
*.suo
*.ntvs*
*.njsproj
*.sln
我添加了点

**Comment by xyxiao001** [comment]
那这种切换分支需要安装依赖的这种问题我还没遇到过， 你看看是不是node_module里面有吗

**Comment by qinghua5453** [comment]
node_module 这个里面装了以后也没有，但执行npm run dev 是可以成功的。切换一次分支，再切回来，再次执行npm run dev 就找不到这个模块了。

**Comment by ellenging** [comment]
我也遇到这个问题了， 安装了 qs ， run dev 也能运行， 就是分支一切换 就找不到了，又需要重新安装。
