### ISSUE TITLE
截取网络上的图片而不是本地图片报错如何解决

### ISSUE THREAD

**Issue by lilu1814** [xyxiao001/vue-cropper#212]

**Comment by xyxiao001** [comment]
跨域问题需要后端配合

**Comment by lilu1814** [comment]
<img width="1615" alt="cropper 2x" src="https://user-images.githubusercontent.com/16162077/48340424-8e86ee80-e6a5-11e8-9dfb-2039c5cc0cbf.png">

后台做的代理，已经有response.setHeader("Access-Control-Allow-Origin", "*"); 在地址栏里可以显示图片，在插件里就报上面的错误，什么原因呢

**Comment by xyxiao001** [comment]
canvas会遇到跨域的问题

**Comment by xyxiao001** [comment]
地址栏不存在跨域
