### ISSUE TITLE
旋转之后切换图片后，旋转信息没有被重置

### ISSUE THREAD

**Issue by 2ue** [xyxiao001/vue-cropper#213]
最新版的vue-cropper，旋转之后再切换图片，旋转的角度没有被重置，请问可以处理一下么？

**Comment by xyxiao001** [comment]
这个应该是我这边的bug， 我会处理， 你可以在每次上传时设置this.$refs.cropper.rotate = 0来处理

**Comment by 2ue** [comment]
> 这个应该是我这边的bug， 我会处理， 你可以在每次上传时设置this.$refs.cropper.rotate = 0来处理

好的，谢谢

**Comment by xyxiao001** [comment]
已在0.46版本更新
