### ISSUE TITLE
被截图的尺寸变成这样是什么原因？

### ISSUE THREAD

**Issue by XiaYuYing** [xyxiao001/vue-cropper#215]
代码环境：vue2.0
vue-cropper: 最新版
![http://cdn.cctv69.top/test/materialResource/24dca4a592314a16b87990027d86793d.jpg](http://cdn.cctv69.top/test/materialResource/24dca4a592314a16b87990027d86793d.jpg)
截图的背景特别小，然后截图框里的内容是截图框的尺寸
应用场景是：截图嵌在一个dialog里，没有用v-if去渲染vue-cropper
上传多次之后会偶现这样的情况
试过在弹窗关闭前调用this.$refs.cropper.refresh()
但是好像没有用
求大神解答

**Comment by xyxiao001** [comment]
看不到图片

**Comment by xyxiao001** [comment]
这个你看看css里面有没有现在图片的最大宽度和高度什么的属性
