### ISSUE TITLE
按照原图比例输出有问题

### ISSUE THREAD

**Issue by 364124337** [xyxiao001/vue-cropper#222]
上传一张  这么大的图片上去

![_20181126101308](https://user-images.githubusercontent.com/24290491/48989175-08b67900-f164-11e8-8008-de1338f7323b.png)
显示为：
![image](https://user-images.githubusercontent.com/24290491/48989110-ba08df00-f163-11e8-8f60-3072b8ea7ed8.png)
代码：
![image](https://user-images.githubusercontent.com/24290491/48989199-2a176500-f164-11e8-9c97-68c0a917c92a.png)
直接裁剪结果为：
![image](https://user-images.githubusercontent.com/24290491/48989241-5b903080-f164-11e8-8b3a-0ce653c08544.png)
请问下这里面哪里出了问题？？

**Comment by xyxiao001** [comment]
这个是等比例原图大小输出的  没毛病的

**Comment by xyxiao001** [comment]
最大只会根据你的原图大小去输出 不会变大了
![image](https://user-images.githubusercontent.com/15681693/48989648-297fce00-f166-11e8-8f85-a13423119ee5.png)
这个可以强制放大

**Comment by 364124337** [comment]
![_20181126101308](https://user-images.githubusercontent.com/24290491/48989676-50d69b00-f166-11e8-85ea-cd36174e5c24.png)
怎么做才能最大输出？现在我输出不了最大的（现在最大只能输出width :900px）
