### ISSUE TITLE
能分别限制图片最大宽度和高度吗？

### ISSUE THREAD

**Issue by 364124337** [xyxiao001/vue-cropper#223]

**Comment by 364124337** [comment]
maxImgSize：[900,500]这样的可以吗？

**Comment by xyxiao001** [comment]
不能  因为那个最大宽度其实只是为了移动端的浏览器不崩溃的

**Comment by xyxiao001** [comment]
![f2c08fe565987f86538f05c758d0b421](https://user-images.githubusercontent.com/15681693/49000036-5dbdb380-f193-11e8-95c4-241c92af4381.jpg)
不能  因为那个最大宽度其实只是为了移动端的浏览器不崩溃的

**Comment by 364124337** [comment]
我上传了一张
![image](https://user-images.githubusercontent.com/24290491/49000225-da509200-f193-11e8-8a89-b2eb902887d3.png)
限制为900   为啥显示为：
![image](https://user-images.githubusercontent.com/24290491/49000258-f5230680-f193-11e8-8ce5-c1d505f4d9fa.png)

**Comment by 364124337** [comment]
是bug吗？

**Comment by xyxiao001** [comment]
什么意思 这有什么关联吗

**Comment by 364124337** [comment]
不应该显示为：750*416.6666667吗？

**Comment by 364124337** [comment]
比例是9:5

**Comment by xyxiao001** [comment]
我会去掉小数点的展示 。 而且这个图片默认是会有进行缩放在容器展示的。

**Comment by xyxiao001** [comment]
压缩的只是图片的最大大小， 不是显示的

**Comment by 364124337** [comment]
上传图片的宽750高1208都是够的    限制为900   750这条边为啥就不能全部显示出来裁切？

**Comment by xyxiao001** [comment]
外层容器也会影响图片的展示的

**Comment by 364124337** [comment]
我把外层
![image](https://user-images.githubusercontent.com/24290491/49000751-8f377e80-f195-11e8-9e73-228bea08df3b.png)
放大了好像也不行

**Comment by xyxiao001** [comment]
你可以修改截图框大小的

**Comment by 364124337** [comment]
但是截图框大小超出图片会截取到外部的像素不是吗？我只想裁切图片

**Comment by xyxiao001** [comment]
可以限制截图框不超过图片的

**Comment by 364124337** [comment]
这个能改下吗？我看别人的裁切都是不受外边容器影响的，只要没超过限制的宽高大小都是原样裁切的

**Comment by 364124337** [comment]
558*310  这个加起来差不多 900            我限制为1200   显示为745*414    加起来差不多1200    这真没问题吗？

**Comment by xyxiao001** [comment]
不是很懂。描述详细一点，比如想实现什么，遇到的问题

**Comment by 364124337** [comment]
![_20181126101308](https://user-images.githubusercontent.com/24290491/49002229-fd7e4000-f199-11e8-9c4f-e7862d5402a4.png)

我现在上传一张这样的图片，代码限制maxImgSize:900 ，比例为【9：5】 ，上传的这张图片大小是在限制的大小范围内的，为啥不能完整的显示？只显示为：
![image](https://user-images.githubusercontent.com/24290491/49002212-f22b1480-f199-11e8-954e-cb1189a47a9c.png)

**Comment by 364124337** [comment]
不应该会显示750×多少吗？

**Comment by xyxiao001** [comment]
Maximgsize这个属性只是会压缩图片，和这个限制没有关系的

**Comment by 364124337** [comment]
那为啥描述是：
![image](https://user-images.githubusercontent.com/24290491/49002400-7bdae200-f19a-11e8-8163-ee8571b14b47.png)
有解决的办法吗？来限制裁剪的大小

**Comment by xyxiao001** [comment]
可以固定裁剪框的大小

**Comment by 364124337** [comment]
只能把外层容器加大？固定裁剪框的大小？那按原图比例裁切不是没用？

**Comment by xyxiao001** [comment]
原图比例裁剪的意思是输出的大小是按照原图比例输出的

**Comment by 364124337** [comment]
好的，我知道了

**Comment by 364124337** [comment]
感谢
