### ISSUE TITLE
图片无法缩放到最小，四边有间隙

### ISSUE THREAD

**Issue by zhongzhifa** [xyxiao001/vue-cropper#228]
如下图：
![image](https://user-images.githubusercontent.com/25548250/49413948-9588b480-f7ac-11e8-986e-e19a037dac09.png)

        :centerBox="true"`
        :fixedNumber="[100, 100]"
        :autoCrop="true"
        :fixed="true"
        :fixedBox="true"
        :autoCropWidth="100"
        :autoCropHeight="100"

原图：560px*560px
![timg](https://user-images.githubusercontent.com/25548250/49414023-df719a80-f7ac-11e8-8c86-47ff64cb784b.jpg)

**Comment by xyxiao001** [comment]
因为比例问题  只要有一边 缩小后小于截图框 就不能缩小

**Comment by endday** [comment]
问题解决了吗，我也遇到类似的问题，任意一个边都大于截图框，但是就是缩小不了

**Comment by zhongzhifa** [comment]
后面我自己对cropper.js进行了封装，就没有这个问题

**Comment by cookie-y** [comment]
你好 请问是怎么解决的呀
