### ISSUE TITLE
在竖图比例下，自动生成选框超出范围

### ISSUE THREAD

**Issue by zhongzhifa** [xyxiao001/vue-cropper#229]
效果如下：
![image](https://user-images.githubusercontent.com/25548250/49414153-51e27a80-f7ad-11e8-8db9-e9d4457f34e0.png)

参数如下：
 ```
:centerBox="true"
:fixedNumber="[600, 10240]"
:autoCrop="true"
:fixed="true"
:fixedBox="true"
:autoCropWidth="600"
:autoCropHeight="10240"
```
无意为难，罪过罪过；客户发现的。他要上传长微博图

**Comment by zhongzhifa** [comment]
原图：
![timg](https://user-images.githubusercontent.com/25548250/49414288-d634fd80-f7ad-11e8-9b8c-4cdc4d97458e.jpg)

**Comment by xyxiao001** [comment]
这个是我这边的判断的问题，  我没考虑到高度不够的情况， 现在默认是我不会去拉伸图片

**Comment by xyxiao001** [comment]
长微博图截图   用这种貌似不是特别合适 没办法完全显示

**Comment by zhongzhifa** [comment]
相信你可以改进的。棒棒的。

**Comment by xyxiao001** [comment]
0.47 可以修改渲染方式
