### ISSUE TITLE
一开始是隐藏的，然后点击弹窗显示图片，但是显示出来不能使用

### ISSUE THREAD

**Issue by youlm** [xyxiao001/vue-cropper#23]
如题

**Comment by xyxiao001** [comment]
用v-if 试一试 放在外层容器

**Comment by youlm** [comment]
我是把vueCropper放在modal里面。。v-if是具体放哪个地方？

**Comment by xyxiao001** [comment]
就是modal里面 的 vueCropper 
<div v-if="">
<vueCropper
  ref="cropper"
  :img="option.img"
  :outputSize="option.size"
  :outputType="option.outputType"
></vueCropper>
</div>

**Comment by xyxiao001** [comment]
`
<div v-if="show">
<vueCropper
  ref="cropper"
  :img="option.img"
  :outputSize="option.size"
  :outputType="option.outputType"
></vueCropper>
</div>
`

**Comment by xyxiao001** [comment]
记得vue-cropper  外层div需要设置宽度 高度

**Comment by youlm** [comment]
设置了高度跟宽度都没用。。有没有具体的demo？

**Comment by xyxiao001** [comment]
https://github.com/xyxiao001/vue-cropper/issues/19

**Comment by xyxiao001** [comment]
你需要的是在modal出现之后 然后v-if去渲染插件
