### ISSUE TITLE
有些图片能加载出来，有些加载不出来

### ISSUE THREAD

**Issue by xcmy** [xyxiao001/vue-cropper#230]
https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1543842889932&di=4a267f66ef7b23c8e3de5bf33130679f&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimgad%2Fpic%2Fitem%2F3812b31bb051f8199a4bd39ed0b44aed2f73e7fc.jpg
                    http://bpic.588ku.com/element_origin_min_pic/16/11/21/70aef95da98fb0e5147d87627b189935.jpg

上面两一个可以一个不行，为什么呢

**Comment by xyxiao001** [comment]
图片涉及到跨域

**Comment by xcmy** [comment]
我知道，有什么好的解决办法吗？改库的不太好吧

**Comment by xyxiao001** [comment]
跨域需要后端配合的

**Comment by xcmy** [comment]
后台是自己的当然好处理，如果图片是从一些免费资源的网站拿的，我就没辙了

**Comment by xyxiao001** [comment]
是的 那就没办法了
