### ISSUE TITLE
默认打开或者切换图片不能实时预览，需要手动改变裁剪框。给的demo也是这样的问题

### ISSUE THREAD

**Issue by yixiyimeng** [xyxiao001/vue-cropper#231]

**Comment by xyxiao001** [comment]
切换图片可以啊  我在线例子不就是吗

**Comment by yixiyimeng** [comment]
你再测试一下，
![image](https://user-images.githubusercontent.com/31124160/49843758-33a6fb00-fdfb-11e8-9c51-797ea76703b0.png)
切换图片以后，预览没有出现。我看到你的源码中
// 优化不要多次触发
      if (this.isCanShow) {
        this.isCanShow = false;
        setTimeout(() => {
          this.isCanShow = true;
        }, 16);
      } else {
        //return false;
      } 
我把return false 注释调。就可以了。但是会触发多次

**Comment by strugglexiang** [comment]
遇见了同样问题，有方便的解决方案吗

**Comment by xyxiao001** [comment]
0.47版本已经修改
