### ISSUE TITLE
VUE APP选择图片，点击勾去选定时，有时候app会崩溃

### ISSUE THREAD

**Issue by hanfeng1982** [xyxiao001/vue-cropper#233]
电脑，手机浏览器都没有问题。但是VUE APP从手机相册选择图片时，点击勾确定图片时，10次中有2，3次，app会崩溃。请问是啥问题呀？现在手机app时安卓端的，苹果端的，暂时没有手机和开发者账户，ios 的app还没有测试。

**Comment by xyxiao001** [comment]
是渲染时候崩溃吗

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/50291274-0fa58280-04a9-11e9-9343-75146f07d1ec.png)
可以把这个属性改小一点

**Comment by hanfeng1982** [comment]
是的哈，选择后去预览页面的时候哈。谢谢，我试下
