### ISSUE TITLE
能否多次截图，以及后台保存之后，再次编辑的时候怎么把原先保存的选择框显示出来

### ISSUE THREAD

**Issue by wang777777** [xyxiao001/vue-cropper#235]
1.能否多次截图
2.后台保存之后，再次编辑的时候怎么把原先保存的选择框显示出来

有人知道吗？谢谢

**Comment by xcmy** [comment]
startcrop()  然后 save ,然后stopcrop()，
重复以上操作

**Comment by xyxiao001** [comment]
开启autoCrop的
