### ISSUE TITLE
mode: '100% auto'情况下高度大于容器的图片不会完全缩放

### ISSUE THREAD

**Issue by lixinlu** [xyxiao001/vue-cropper#236]
例如：容器尺寸 300*300 ，如果上传 386*1296的图片，图片会放大填充容器，不能缩放显示全图；如果mode改为默认值，上传2048*1536的图，图会放大，不能显示全图

**Comment by xyxiao001** [comment]
还是一下 cover看看

**Comment by xyxiao001** [comment]
已经在0.48版本修改cover显示
