### ISSUE TITLE
在设置centerBox=true的情况下旋转图片时的bug

### ISSUE THREAD

**Issue by pehalo** [xyxiao001/vue-cropper#237]
开始是这样的
![image](https://user-images.githubusercontent.com/15843581/50330267-838d6c80-0535-11e9-9e72-8f298924d3b7.png)
然后我旋转了90度后
![image](https://user-images.githubusercontent.com/15843581/50330301-a881df80-0535-11e9-98d3-971137bc278c.png)
截图框只有右边发生了重置，而左边就被移动出去了，正常来说截图框在图片变小的时候应该重置到图片的边界，因为我设置了centerBox=true。
还是说我使用的方式有问题？

**Comment by xyxiao001** [comment]
这个是因为我这边没有自动做缩小截图框

**Comment by xyxiao001** [comment]
开启autoCrop这个  目前可以旋转自动缩小截图框

**Comment by pehalo** [comment]
额，我试了，在截图框宽度小于旋转后图片的宽度的时候是会自动居中的。 但截图框大于了图片的时候应该也触发了居中了，但是这个宽度容不下就超出了。并没有自动缩小截图框。
我设置了img，outputSize=0.8，outputType=png，centerBox=true，autoCrop=true，mode=cover，fixedBox=false，fixed=true，canScale=true，fixedNumber=[2, 1]其他全是默认的值

**Comment by xyxiao001** [comment]
好的，后续版本我会修复

**Comment by xyxiao001** [comment]
已经在0.48版本修复
