### ISSUE TITLE
如何获取原图尺寸？

### ISSUE THREAD

**Issue by xcmy** [xyxiao001/vue-cropper#238]
有没有开放获取原图宽高的接口？既然已经加载了一次图片，应该可以获取到吧。如果我们再去加载一次重新获取宽高感觉有点不合适。

**Comment by xyxiao001** [comment]
可以  this$refs.cropper.trueWidth  this$refs.cropper.trueHeight

**Comment by xcmy** [comment]
ok ,,thanks
