### ISSUE TITLE
在chrome浏览器下，偶现页面滚动条失效情况，概率比较大

### ISSUE THREAD

**Issue by vicol007** [xyxiao001/vue-cropper#241]
在做一个模板和图片合成的效果，需要截图。但是偶现出现了页面的滚动条失效的情况，无法滚动。
是否有解决方案或者可以规避的方案？
谢谢~~

**Comment by xyxiao001** [comment]
可以提供在线例子吗，我这边没遇到过

**Comment by vicol007** [comment]
现在就在想一个解决方案使得出现的概率降到最低，后续还请您多关注下这个问题哈
这个vue-cropper还是很不错的，后续会有很大的上升空间~

**Comment by xyxiao001** [comment]
可能是因为绑定了 window滚动条事件解绑失败了

**Comment by vicol007** [comment]
这个问题，通过手动盖一个透明遮罩层规避减少出现的概率，目前还没有发现有问题。

**Comment by Pineapple-Black** [comment]
我也出现了这个问题  几乎 只要点了确定 滚动条就失效了，请问怎么解决

**Comment by vicol007** [comment]
> 我也出现了这个问题 几乎 只要点了确定 滚动条就失效了，请问怎么解决
我这个是发现了失效的起点，发现在图片没有加载进来时点击了截图匡就会有问题，我就给截图款加了一个div遮罩层，在图片加载成功后撤下就行了
