### ISSUE TITLE
裁剪的像素大约大于1000 x 420的时候，剩余像素会变透明

### ISSUE THREAD

**Issue by sachi-meow** [xyxiao001/vue-cropper#242]
环境：
vue:  2.5.2
vue-simple-uploader:  0.4.6
vue-cropper:  0.4.7
window系统

参数：
imgOption: {
                    img: '', 
                    size: 1, 
                    full: false, 
                    outputType: 'png', 
                    canMove: true, 
                    fixedBox: true, 
                    original: true, 
                    canMoveBox: true, 
                    autoCrop: true, 
                    autoCropWidth: 1160,
                    autoCropHeight: 420,
                    centerBox: false,
                   high: true 
}

当裁剪图片大小为1160 x 420的时候，上传服务器，返回来的图片是1160 x 420的规格，但是在图片在最下面出现透明色。

裁剪的图片在浏览器可以可以正确显示：
![demo 5](https://user-images.githubusercontent.com/22806915/50537605-e10c6380-0b9c-11e9-9327-a45196561502.png)

上传服务器的图片：
![20181229154337463](https://user-images.githubusercontent.com/22806915/50537514-8292b580-0b9b-11e9-9936-ef33743cc554.jpg)

可以看到两张图片同样的规格，不过少了很多像素
if (type === 'blob') {
	 this.$refs.cropper.getCropBlob((data) => {
          this.$refs.uploader.uploader.fileList[0].file = data
      this.$refs.uploader.uploader.files[0].file = data
this.$refs.uploader.uploader.fileList[0].size = data.size
    this.$refs.uploader.uploader.files[0].size = data.size;
       this.previewImgURL = window.URL.createObjectURL(data);
}

**Comment by bh-chen** [comment]
第一张图片传错了

![demo 5](https://user-images.githubusercontent.com/22806915/50537593-adc9d480-0b9c-11e9-9276-b8ee9c7c6c6a.png)

**Comment by xyxiao001** [comment]
是不是截图框刚好超过了图片

**Comment by sachi-meow** [comment]
这个问题当时已经解决了，是因为file里面原图片的size小于裁剪之后的size，当时是重置这个大小为最新的，具体是哪些属性就不去看了。有这个问题的朋友可以自己看看
