### ISSUE TITLE
图片加载显示问题

### ISSUE THREAD

**Issue by xcmy** [xyxiao001/vue-cropper#243]
一张宽大于高的原图，当设置cropper的宽高比大于原图宽高比的时候显示如下：

<img width="528" alt="wx20190103-174019 2x" src="https://user-images.githubusercontent.com/8855353/50631447-3d95c700-0f7f-11e9-95bb-1ca9aaa1288c.png">

当设置cropper的宽高比小于原图宽高比的时候显示如下：
<img width="287" alt="wx20190103-174121 2x" src="https://user-images.githubusercontent.com/8855353/50631497-75047380-0f7f-11e9-8afc-f327e9655bd7.png">

如何设置让图片显示在cropper框内，并按比例显示

**Comment by xyxiao001** [comment]
可以看看mode这个属性

**Comment by xcmy** [comment]
你这个mode属性中contain属性适合宽高比大于1，cover适合宽高比小于1，100px适合固定宽高的，100% auto和前面的contain重复的，也就是不能自动根据图片的比例去渲染是吧？（就是有没有让图片自动填充在框内，撑满宽或者高，而比例不失调的属性啊）

**Comment by xyxiao001** [comment]
Cover就是撑满的

**Comment by xcmy** [comment]
这是设置为cover下的一张图，显示是有问题的。cover做的是横向充满吧。

cropper  style  width:50%;height:100%;
<img width="286" alt="wx20190103-184017 2x" src="https://user-images.githubusercontent.com/8855353/50633660-17742500-0f87-11e9-8ccd-456764495994.png">

cropper  style  width:100%;height:50%;
<img width="563" alt="wx20190103-183927 2x" src="https://user-images.githubusercontent.com/8855353/50633665-193de880-0f87-11e9-90ab-4e74ef231f0c.png">

目标效果是这样的，
<img width="886" alt="wx20190103-184508 2x" src="https://user-images.githubusercontent.com/8855353/50633931-f8c25e00-0f87-11e9-952b-b33b87c0b972.png">

**Comment by xyxiao001** [comment]
更新最新版本试一下，最新的cover应该可以了
