### ISSUE TITLE
没有使用npm时，实时预览没起作用

### ISSUE THREAD

**Issue by JohnGene** [xyxiao001/vue-cropper#245]
https://codepen.io/xyxiao001/pen/wxwKGz  这个例子中实时预览功能@real-time好像没起作用，同样的按照文档加入@img-load类似的带有@的函数都没有作用，楼主有解决方案没？

**Comment by xyxiao001** [comment]
不用短横线呢

**Comment by JohnGene** [comment]
不用也试过了，都没有效果，本想用拖动和加载完成两个组合起来代替realtime的但是也同样没有效果

**Comment by xyxiao001** [comment]
我看看

**Comment by xyxiao001** [comment]
已经在0.49版本更新解决  短横线方式触发事件
