### ISSUE TITLE
请问最新版本在typescript下引用VueCropper报错，能帮忙看一下吗

### ISSUE THREAD

**Issue by txlwll** [xyxiao001/vue-cropper#248]
![image](https://user-images.githubusercontent.com/18171146/51168986-b4b74d80-18e5-11e9-9128-9284fb940e7f.png)

**Comment by xyxiao001** [comment]
我这边还没兼容ts  你可以加个d.ts 先去兼容

**Comment by txlwll** [comment]
![image](https://user-images.githubusercontent.com/18171146/51191725-fa910780-191f-11e9-8eb4-70764b2f2fd3.png)
是加这样的一个文件吗，我也加了还是报那个错

**Comment by xyyVee** [comment]
改成 `declare module 'vue-cropper'`
