### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by shx1545** [xyxiao001/vue-cropper#25]
![image](https://user-images.githubusercontent.com/29303050/30694235-b804bb9a-9f05-11e7-9c0b-c4d08713819b.png)

**Comment by xyxiao001** [comment]
什么bug

**Comment by xyxiao001** [comment]
这个是怎么出现的 改变浏览器大小 需要刷新的

**Comment by shx1545** [comment]
刷新后还是这样

**Comment by shx1545** [comment]
我现在移动端项目需要用这个来裁剪头像

**Comment by shx1545** [comment]
代码我直接拷贝你写的示例，另外外层没有任何布局，全局样式我注释了，还是会这样子

**Comment by xyxiao001** [comment]
你直接访问呢 我的例子https://xyxiao001.github.io/vue-cropper/example/

**Comment by shx1545** [comment]
找到原因了，img不能设置max-width

**Comment by shx1545** [comment]
另外想问下，如何禁锢 截图框   宽100%，高度等与宽度，并且禁止拖拽，因为我要裁剪头像嘛

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/30695268-2ae3b6d0-9f0a-11e7-8c3b-6317581041ab.png)

**Comment by shx1545** [comment]
我知道能固定截图框大小，但是还是能 拖动截图框，并且在截图框里 无法手势 放大或者缩小 遮罩的图片。

**Comment by xyxiao001** [comment]
是的  截图框里面无法手势 缩放

**Comment by xyxiao001** [comment]
https://github.com/dai-siki/vue-image-crop-upload
这个比较适合头像上传

**Comment by shx1545** [comment]
这个我看过，手机端体验不行，还不如你这个

**Comment by xyxiao001** [comment]
不过截图框可以移动也不影响截图的

**Comment by shx1545** [comment]
是的，我准备用你这个算了

**Comment by xyxiao001** [comment]
不过因为截图框也有拖动 所以我做的时候就把截图框里面的手势 给禁用掉了， 考虑不周全，
如果你想放大 缩小 也可以 通过按钮事件去触发
 this.$refs.cropper.changeScale() 修改图片大小 正数为变大 负数变小

**Comment by shx1545** [comment]
好的，谢啦
