### ISSUE TITLE
nuxt下使用要怎么配置呢？

### ISSUE THREAD

**Issue by bigHead-zhu** [xyxiao001/vue-cropper#253]
nuxt环境下有成功使用了vue-cropper的大佬吗，可以看一下配置嘛，我照着文档做，还是不行

**Comment by aaronksaunders** [comment]
where does this code go?

**Comment by xyxiao001** [comment]
module.exports = {
  ...
  build: {
    vendor: [
      'vue-cropper
    ...
    plugins: [
      { src: '~/plugins/vue-cropper', ssr: false }
    ]
  }
}

**Comment by zacharytyhacz** [comment]
I've done this and other solutions. NuxtJS getting this error:
` nuxt ^2.8.1 `


![image](https://user-images.githubusercontent.com/38140593/59609146-dd39b280-90e4-11e9-8e20-04ff37830535.png)

The english answers and readme is not fully understandable and I do not understand chinese to see what other issues are open that may be similar to mine.

 Also upon compilation, NuxtJS throws this warning: 
```
WARN  vendor has been deprecated due to webpack4 optimization
```

Is there going to be an updated version? Also, a new solution to this?
