### ISSUE TITLE
实时预览不可用

### ISSUE THREAD

**Issue by webxmsj** [xyxiao001/vue-cropper#254]
![image](https://user-images.githubusercontent.com/40289489/51517498-e6846300-1e55-11e9-82b0-616b8c7bb272.png)
![c4631cacc48108acd4e75e0c49fd536](https://user-images.githubusercontent.com/40289489/51517513-f0a66180-1e55-11e9-8611-a6467f145923.png)

**Comment by xyxiao001** [comment]
@realTime="realTime"

realTime(data) {
  this.previews = data;
},


<div class="show-preview" :style="{'width': previews.w + 'px', 'height': previews.h + 'px',  'overflow': 'hidden',
    'margin': '5px'}">
  <div :style="previews.div">
    <img :src="option.img" :style="previews.img">
  </div>
</div>

**Comment by xyxiao001** [comment]
`@realTime="realTime"
// Real time preview function
realTime(data) {
  var previews = data;
  var h = 0.5;
  var w = 0.2;

  this.previewStyle1 = {
    width: previews.w + "px",
    height: previews.h + "px",
    overflow: "hidden",
    margin: "0",
    zoom: h
  };

  this.previewStyle2 = {
    width: previews.w + "px",
    height: previews.h + "px",
    overflow: "hidden",
    margin: "0",
    zoom: w
  };
  this.previews = data;
},


<div class="show-preview" :style="{'width': previews.w + 'px', 'height': previews.h + 'px',  'overflow': 'hidden',
    'margin': '5px'}">
  <div :style="previews.div">
    <img :src="option.img" :style="previews.img">
  </div>
</div>`

**Comment by xyxiao001** [comment]
@realTime="realTime"
realTime(data) {
  this.previews = data;
},

**Comment by xyxiao001** [comment]
节点看文档的

**Comment by webxmsj** [comment]
已经加过了，不行

**Comment by webxmsj** [comment]
> 已经加过了，不行

![image](https://user-images.githubusercontent.com/40289489/51523411-92ce4580-1e66-11e9-8979-e2e07d4fb833.png)

@realTime感觉这里返回的宽度不对， 
![image](https://user-images.githubusercontent.com/40289489/51523463-aa0d3300-1e66-11e9-8cc0-3848c50299ee.png)

裁剪框这里显示的是200,realTime这里返回的宽度是1024
![image](https://user-images.githubusercontent.com/40289489/51523513-c7420180-1e66-11e9-862c-9762e6411141.png)

**Comment by xyxiao001** [comment]
这个是对的 你看看是不是你其他样式影响了

**Comment by webxmsj** [comment]
> 这个是对的 你看看是不是你其他样式影响了

看源代码 宽度不是裁切框的宽度吗？ 裁切框的宽度是200啊， 为什么是1024
