### ISSUE TITLE
上传大图片(20M) 的时候 报错 net::ERR_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by zechen706** [xyxiao001/vue-cropper#255]
上传大图片(20M) 的时候 报错 net::ERR_INSUFFICIENT_RESOURCES

**Comment by xyxiao001** [comment]
可以提供大图我去测试嘛

**Comment by xyxiao001** [comment]
好的 不过我猜测应该是内存的限制， 毕竟是绘制到canvas里面，有可能图片太大了

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/51523677-2bfd5c00-1e67-11e9-90a6-63f04fb8be22.png)
我这边是可以的 你的是什么环境不行

**Comment by xyxiao001** [comment]
那有可能是因为图片太大的原因吧 我到时去测一下 我mac是正常的
