### ISSUE TITLE
同一个页面不能同时使用多个

### ISSUE THREAD

**Issue by gitHub-ljrong** [xyxiao001/vue-cropper#256]

**Comment by xyxiao001** [comment]
能啊 ref不要设置一样的就可以

**Comment by vlonsir** [comment]
说一下我的情况吧，共有需要的同学参考。
问题描述：同一个页面不能同时使用多个。我是在一个vue组件页面create.vue中引入了一个组件uploadImg.vue组件(作为选择图片弹窗来使用)，再在uploadImg.vue中引入了cropperVue组件，由于页面中需要上传一个封面图片和一个播放器logo图片，所以，我引入了uploadImg.vue组件两次，分别命名为uploadImg1和uploadImg2用来在同一个页面的两个地方上传图片，此时uploadImg.vue组件中的cropperVue组件有没有被实例化为2个组件我不知道。但是问题就是我为uploadImg1上传图片后，进入图片裁剪弹窗界面，此时不满意上传的图片，在不关闭裁剪弹窗的情况下，我重新选择图片，此时选择的图片竟然进入到了uploadImg2组件中。经过反复测试，我发现这样不行，于是我在一个页面引入2个cropperVue组件，同时引入两个uploadImg.vue组件，在uploadImg1中选择完图片，到cropperVue1裁剪，但是在裁剪弹窗中重新选择图片，图片数据仍然被加载到了uploadImg2组件中，不知道cropperVue的赋值逻辑是怎样的。

重点来了=============

我于是在每次打开弹窗uploadImg的时候，注入一个缓存变量，用来区分打开的是uploadImg1还是uploadImg2，在裁剪弹窗中重新选择完图片载入数据时，我通过缓存变量判断下是uploadImg1还是uploadImg2，这样就给生生掰过来了。

@vlonsir  不明白的同学可以私信我

**Comment by bxychy** [comment]
我也遇到了同样的问题 第二个选择图片 重新赋值到第一个组件中 并且宽高都为基础的100x80

**Comment by xyxiao001** [comment]
> 

修改不一样的 ref
