### ISSUE TITLE
老哥，还是跨域问题~~~

### ISSUE THREAD

**Issue by HuayangZhao** [xyxiao001/vue-cropper#257]
我在Issues中搜了很多跨域问题也没解决，我的图片地址是可以随意访问的，后台也设置了，但还是报跨域，想问老哥这可能是什么原因？
```
<vueCropper
     ref="cropper" 
     img="http://192.168.0.129:9999/group1/M00/00/03/wKgAgVxKvAOAOG5ZAABPERhkO9k001.jpg"
>
</vueCropper>
```
```
Access to Image at 'http://192.168.0.129:9999/group1/M00/00/03/wKgAgVxKvAOAOG5ZAABPERhkO9k001.jpg'from origin
 'http://localhost:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin'header is
 present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.
```

**Comment by HuayangZhao** [comment]
不是https?

**Comment by xyxiao001** [comment]
后台没设置好吧

**Comment by HuayangZhao** [comment]
感谢老哥百忙之中还能回复我，好人一生平安！图片地址在别的电脑上也可以访问，这应该算是跨域了吧？
我刚刚用你在线示例中的地址没问题，用自己的就不行，然后我怀疑是http和https的原因，然而百度Logo（https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/img/logo/bd_logo1_31bdc765.png）
的地址也不行。。。这个LOGO图片我能在我电脑访问，应该不存在跨域，然鹅还是报跨域

**Comment by xyxiao001** [comment]
不是  跨域是canvas跨域  访问不算跨域的

**Comment by weidadedawei** [comment]
![image](https://user-images.githubusercontent.com/25583243/73844896-724c1000-485c-11ea-9fd1-b5efe334a06d.png)
我是腾讯云cos图片，在腾讯云上设置跨域

**Comment by Fallen-Skies** [comment]
这怎么说到一半不说了

**Comment by Fallen-Skies** [comment]
这怎么说到一半不说了，我遇到的也是这样的问题，各位大哥怎么解决的啊

**Comment by HailongJson** [comment]
哎.我这边也是跨域的问题,直接在页面上是可以渲染出来的,但是在cropper中就报跨域.后端都没问题,感觉问题还是出在插件上.

**Comment by xyxiao001** [comment]
插件这边已经设置允许跨域了

**Comment by xyxiao001** [comment]
img 是没有跨域问题，canvas 才有

**Comment by HailongJson** [comment]
[](url)

> img 是没有跨域问题，canvas 才有

好吧 我在看看

**Comment by Fallen-Skies** [comment]
能不能让这个组件哪怕报跨域问题的错，也把图片给显示出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AHai"<notifications@github.com&gt;; 
发送时间: 2021年2月23日(星期二) 下午4:25
收件人: "xyxiao001/vue-cropper"<vue-cropper@noreply.github.com&gt;; 
抄送: "从家华"<1515470519@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [xyxiao001/vue-cropper] 老哥，还是跨域问题~~~ (#257)





 

  
img 是没有跨域问题，canvas 才有
  
好吧 我在看看
