### ISSUE TITLE
怎么固定裁图框的尺寸，我的需求要裁剪出一个正方形，所以想拉伸裁图框的时候实际上是一个正方形放大缩小

### ISSUE THREAD

**Issue by NICEJB** [xyxiao001/vue-cropper#262]

**Comment by xyxiao001** [comment]
设置比例的 文档
![image](https://user-images.githubusercontent.com/15681693/53555841-b1b6aa80-3b7d-11e9-986d-67e78277e80e.png)

**Comment by NICEJB** [comment]
谢谢
