### ISSUE TITLE
Preview image wrong display

### ISSUE THREAD

**Issue by bocanhcam** [xyxiao001/vue-cropper#270]
I just used exactly the example code but the display preview image is wrong.

<img width="1154" alt="Screen Shot 2019-03-12 at 15 33 32" src="https://user-images.githubusercontent.com/35592955/54185748-5ae59500-44dc-11e9-9388-b77ea2678560.png">
<img width="1202" alt="Screen Shot 2019-03-12 at 15 33 17" src="https://user-images.githubusercontent.com/35592955/54185749-5ae59500-44dc-11e9-8210-562743a1d792.png">
<img width="1181" alt="Screen Shot 2019-03-12 at 15 32 37" src="https://user-images.githubusercontent.com/35592955/54185750-5ae59500-44dc-11e9-8e7a-9a98ae13e838.png">

**Comment by xyxiao001** [comment]
Maybe it's your effect on the width, height, or attributes of the image.

**Comment by bocanhcam** [comment]
I used exactly the example code https://codepen.io/xyxiao001/pen/wxwKGz?editors=0010.

I changed nothing except the real-time to realTime. I think the style of previews.div is right but the style of previews.img is wrong for me.

It has warned in the codepen if I change real-time to realTime so I can't make a demo for you to see.

**Comment by xyxiao001** [comment]
Currently using CDN can't preview images in real time. This is a bug. I'll go back and fix it later, because HTML can't trigger the hump method.

**Comment by bocanhcam** [comment]
I found out that I have the wrong display image because I have the default style.
`img {
    max-width: 100%;
}`
Thank you for your support, I will close this issue now.
