### ISSUE TITLE
How to set width height output of image

### ISSUE THREAD

**Issue by bocanhcam** [xyxiao001/vue-cropper#271]
Can I set the width height output of image somewhere or make it equal to autoCropWidth, autoCropHeight?

**Comment by xyxiao001** [comment]
high:false

**Comment by bocanhcam** [comment]
Thanks @xyxiao001, but It does not work if I zoom in or zoom out the image

**Comment by xyxiao001** [comment]
enlarge  ,output ratio multiplier based on screenshots

**Comment by bocanhcam** [comment]
Sorry but I still don't know how to do that.

I try to set enlarge when cropping but it not work.

Can you give me an idea or an example code, please?

Thank you.

**Comment by xyxiao001** [comment]
Enlarge is a property that enlarges the image when calling getCropData to get the screenshot. You can describe what you want to do.

**Comment by bocanhcam** [comment]
I set options like this.

```
autoCropWidth: 450,
autoCropHeight: 450,
fixedBox: true,
```
I want every images crop have the same width height 450*450.

**Comment by xyxiao001** [comment]
you should set  high: false,  The image output is the same size as the screenshot box by default.
If your picture is too small, you can set mode: cover

**Comment by bocanhcam** [comment]
Yes. By default it right but if I zoom in or zoom out the image. It gonna have a different width height.

**Comment by xyxiao001** [comment]
Can you take a look at your options screenshots?

**Comment by bocanhcam** [comment]
This is my options.

```
img: '',
mode: 'cover',
size: 1,
infoTrue: true,
full: true,
outputType: 'jpeg',
canMove: true,
fixedBox: true,
original: true,
canMoveBox: true,
autoCrop: true,
autoCropWidth: 450,
autoCropHeight: 450,
centerBox: false,
high: false,
enLarge: 1
```

**Comment by xyxiao001** [comment]
full: false  This property will install the screenshot box and the original image scale output.

**Comment by bocanhcam** [comment]
Oh sorry. I should know that earlier.

Thank you very much for your time.
