### ISSUE TITLE
npm install后使用无效果

### ISSUE THREAD

**Issue by OUZHANBO** [xyxiao001/vue-cropper#272]
我在vue组件中important并且注册为组件但是使用无效果，按着control也没有链接到依赖包

**Comment by xyxiao001** [comment]
有报错吗  你怎么使用的

**Comment by OUZHANBO** [comment]
谢谢你的回复，我现在在坐地铁，等下回去给你截图

**Comment by OUZHANBO** [comment]
![image](https://user-images.githubusercontent.com/26184112/54272427-a53f4280-45be-11e9-9558-4e9bcf5b219f.png)这是我的代码
![image](https://user-images.githubusercontent.com/26184112/54272959-b9d00a80-45bf-11e9-8c16-46284a6c9679.png)
![image](https://user-images.githubusercontent.com/26184112/54272982-c9e7ea00-45bf-11e9-9022-7a0b00a46ff4.png)
界面什么都没有

**Comment by xyxiao001** [comment]
设置外层容器宽度高度

**Comment by OUZHANBO** [comment]
谢谢，问题已经解决
