### ISSUE TITLE
移动端设置截图框宽高。横图和竖图裁剪框大小不一样

### ISSUE THREAD

**Issue by Likeag6xx** [xyxiao001/vue-cropper#274]
移动端设置截图框宽高。横图和竖图裁剪框大小不一样。请问这个是需要怎么解决，设置了裁剪框符于图片内部，所以有些图片高度或者宽度没达到设定的值，所以就会促使截图框在设定宽高值的情况下更据图片原始宽高比发生变化，求解决办法

**Comment by xyxiao001** [comment]
这样变是因为图片比例的问题。 可以选择设置mode: cover 来实现图片铺满容器，这样截图框自然就可以正常显示了

**Comment by Likeag6xx** [comment]
完美解决，万分感谢

**Comment by Likeag6xx** [comment]
完美解决，万分感谢

**Comment by xyxiao001** [comment]
😁
