### ISSUE TITLE
您好 显示substr 为null 然后有时候拿不到选择的图片怎么处理

### ISSUE THREAD

**Issue by Dashsoap** [xyxiao001/vue-cropper#278]
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'substr' of null"

found in

---> <VueCropper> at src/vue-cropper.vue
       <SuiModalContent>
         <SuiModal>
           <Modal> at src/components/Modal.vue
             <ImageCropper> at src/components/ImageCropper.vue
               <ProfileEdit> at src/views/ProfileEdit.vue
                 <App> at src/App.vue
                   <Root>

**Comment by xyxiao001** [comment]
你怎么传图片进去的

**Comment by Dashsoap** [comment]
> 进去

通过一个input file 拿到file以后通过e.target.file 传到：img里面去的

**Comment by Dashsoap** [comment]
已解决 是未读取图片的情况下 渲染了组件
