### ISSUE TITLE
这种注册方式不对吗？

### ISSUE THREAD

**Issue by YoungZhang08** [xyxiao001/vue-cropper#280]
<template lang="pug">
  .upload-container
    input(type="file", accept=".jpg, .png, .jpeg", @change="uploadImg($event, 1)")
    VueCropper(ref="cropper",
              :img="option.img",
              :outputSize="option.size",
              :info="true",
              :full="option.full",
              :canMove="option.canMove",
              :canMoveBox="option.canMoveBox",
              :fixedBox="option.fixedBox",
              :original="option.original",
              :autoCrop="option.autoCrop",
              :autoCropWidth="option.autoCropWidth",
              :autoCropHeight="option.autoCropHeight",
              :centerBox="option.centerBox",
              :high="option.high",
              :infoTrue="option.infoTrue",
              :maxImgSize="option.maxImageSize",
              @realTime="realTime",
              @imgLoad="imgLoad",
              @cropMoving="cropMoving",
              :enlarge="option.enlarge",
              :mode="option.mode")
    .upload-submit(@click="gotoUpload()") 上传照片
</template>
<script>
import Vue from 'vue'
if (process.browser) {
  const VueCropper = require('vue-cropper')
  Vue.use(VueCropper)
}
export default {
  data () {
    return {
      model: false,
      modelSrc: "",
      crap: false,
      previews: {},
      // 裁剪组件的基础配置option
      option: {
        img: '', // 裁剪图片的地址
        info: true, // 裁剪框的大小信息
        outputSize: 0.8, // 裁剪生成图片的质量
        outputType: 'png', // 裁剪生成图片的格式
        canScale: false, // 图片是否允许滚轮缩放
        autoCrop: true, // 是否默认生成截图框
        // autoCropWidth: 300, // 默认生成截图框宽度
        // autoCropHeight: 200, // 默认生成截图框高度
        fixedBox: true, // 固定截图框大小 不允许改变
        fixed: true, // 是否开启截图框宽高固定比例
        fixedNumber: [1, 1], // 截图框的宽高比例
        full: true, // 是否输出原图比例的截图
        canMoveBox: false, // 截图框能否拖动
        original: false, // 上传图片按照原始比例渲染
        centerBox: false, // 截图框是否被限制在图片里面
        infoTrue: true, // true 为展示真实输出图片宽高 false 展示看到的截图框宽高
        high: false,
        cropData: {},
				enlarge: 1,
        mode: 'contain',
        maxImgSize: 2000
      },
    }
  },
  components: {
    VueCropper
  },

![image](https://user-images.githubusercontent.com/20597992/55136687-13ad0480-516a-11e9-882e-6f70e5152b16.png)

**Comment by YoungZhang08** [comment]
`<template lang="pug">
  .upload-container
    input(type="file", accept=".jpg, .png, .jpeg", @change="uploadImg($event, 1)")
    VueCropper(ref="cropper",
              :img="option.img",
              :outputSize="option.size",
              :info="true",
              :full="option.full",
              :canMove="option.canMove",
              :canMoveBox="option.canMoveBox",
              :fixedBox="option.fixedBox",
              :original="option.original",
              :autoCrop="option.autoCrop",
              :autoCropWidth="option.autoCropWidth",
              :autoCropHeight="option.autoCropHeight",
              :centerBox="option.centerBox",
              :high="option.high",
              :infoTrue="option.infoTrue",
              :maxImgSize="option.maxImageSize",
              @realTime="realTime",
              @imgLoad="imgLoad",
              @cropMoving="cropMoving",
              :enlarge="option.enlarge",
              :mode="option.mode")
    .upload-submit(@click="gotoUpload()") 上传照片
</template>
<script>
import Vue from 'vue'
if (process.browser) {
  const VueCropper = require('vue-cropper')
  Vue.use(VueCropper)
}
export default {
  data () {
    return {
      model: false,
      modelSrc: "",
      crap: false,
      previews: {},
      // 裁剪组件的基础配置option
      option: {
        img: '', // 裁剪图片的地址
        info: true, // 裁剪框的大小信息
        outputSize: 0.8, // 裁剪生成图片的质量
        outputType: 'png', // 裁剪生成图片的格式
        canScale: false, // 图片是否允许滚轮缩放
        autoCrop: true, // 是否默认生成截图框
        // autoCropWidth: 300, // 默认生成截图框宽度
        // autoCropHeight: 200, // 默认生成截图框高度
        fixedBox: true, // 固定截图框大小 不允许改变
        fixed: true, // 是否开启截图框宽高固定比例
        fixedNumber: [1, 1], // 截图框的宽高比例
        full: true, // 是否输出原图比例的截图
        canMoveBox: false, // 截图框能否拖动
        original: false, // 上传图片按照原始比例渲染
        centerBox: false, // 截图框是否被限制在图片里面
        infoTrue: true, // true 为展示真实输出图片宽高 false 展示看到的截图框宽高
        high: false,
        cropData: {},
				enlarge: 1,
        mode: 'contain',
        maxImgSize: 2000
      },
    }
  },
  components: {
    VueCropper
  },`

**Comment by xyxiao001** [comment]
文档上面有写的
