### ISSUE TITLE
请问作者getCropChecked方法里面的ctx.drawImage的dx跟dy是怎么算出来的？

### ISSUE THREAD

**Issue by ll527563266** [xyxiao001/vue-cropper#282]
我想实现旋转0-360度的功能，把交互弄成了按传入的有效数字来旋转角度，但是获取转换成base64 的图片信息，调用的是getCropChecked方法，里面设定是按90度旋转，想请教作者ctx.drawImage()的第二个参数和第三个参数是怎么算出来的？

**Comment by xyxiao001** [comment]
因为canvas绘图本质上是旋转canvas然后进行图片绘制，相当于，图片本身坐标不变，canvas反向旋转之后去计算，这个你要画图才知道怎么算。
