### ISSUE TITLE
图片旋转 bug

### ISSUE THREAD

**Issue by yong16** [xyxiao001/vue-cropper#283]
![WechatIMG227](https://user-images.githubusercontent.com/16696647/55279007-5deedb00-534e-11e9-8830-45bf290f0cff.jpeg)
**bug**:  部分竖图展示时被转为横图了。
**需求**：因为需求只是用来展示，真正的裁切是后台来做，只发给后台坐标值和原线上图片地址做为记录。一是为了兼容性，二是后台只保存原图，等需要时才会输出裁切图。因为都是线上图片，前台不能自定义旋转。
**导致后果**：因为线上图片是竖形图，前台如果被旋转的话，对应的坐标值都会错误，后台裁剪出来的图片也就都是错的。
请问有什么解决方法吗？

**Comment by yong16** [comment]
现在发现的是上面的图片会有这种问题，其它竖图暂未发现，还请帮忙看下，谢谢。

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/55284900-6bd64780-53b2-11e9-8b0a-12ce593f5465.png)
我测试是 正常的啊  直接用的你上面图片的链接

**Comment by yong16** [comment]
![image](https://user-images.githubusercontent.com/16696647/55285183-13567880-53b9-11e9-99cd-65ee1acc9424.png)
这是显示的横图。我看了下，内网测试环境的图片地址单独打开是横图，img 引入后显示的是正常竖图。裁切图转 blob 前可能拿到的 url 地址就是横图？上面的链接单独打开就是竖图，可能跟这个有关吧。。你试下源文件会不会有问题

**Comment by xyxiao001** [comment]
你在我的http://xyxiao.cn/vue-cropper/example/ 这个例子上面测试呢

**Comment by yong16** [comment]
好的，我试下。。

**Comment by qieman** [comment]
我也遇到这个问题，ios上传图片竖图会转成横图，有解决办法吗
