### ISSUE TITLE
请问我如何在不下载的情况下，拿到截图后的图片URL

### ISSUE THREAD

**Issue by song-le-yi** [xyxiao001/vue-cropper#285]

**Comment by xyxiao001** [comment]
// 获取截图的base64 数据
this.$refs.cropper.getCropData((data) => {
  // do something
  console.log(data)  
})

// 获取截图的blob数据
this.$refs.cropper.getCropBlob((data) => {
  // do something
  console.log(data)  
})

**Comment by song-le-yi** [comment]
多谢大佬
