### ISSUE TITLE
Not able to get binary data of uploaded image after cropping

### ISSUE THREAD

**Issue by rpankaj** [xyxiao001/vue-cropper#287]
After cropping the image, How to get the binary data which can be sent as payload to an API?

My API expects payload in below format:
`------WebKitFormBoundary5yEu8RpiERgwzMno
Content-Disposition: form-data; name="file"; filename="file.png"
Content-Type: image/png

PNG


IHDRnnÆ[&ûdIDATx^í	xTÕÇÿï½ÉFB	²I,²Â*E UjígµV¥(µU«m¡J,DAqA¢¢(6F$,a$!°$d#ëmfú;¾a¶Ì{o7dÞý>?¿ÜåÜó{÷ÞsÏ9ï
·dö2Sî[DpW £îþ?cPIÂgÎ%#«n9Òû°¤8F<©[Ü)VIËº
8àuárð°°
.........................
ó0È{CjÅYúd½ÒdÙ&8sÆXì_¢¿wj9¯J
hÀ"ÔÖü¢½&u¥X/)IÃ:x7L²µ\ÖsS­ÐÀ©¨\5»ÖÀ©©]ûÖÀ©¨\5»ÖÀ©©]ûÖÀ©¨\5»þ?Ð?Ïy¦(YIEND®B`
------WebKitFormBoundary5yEu8RpiERgwzMno--

**Or**
Is there any feature that accepts API url and call that with binary data?

**Comment by xyxiao001** [comment]
you can use this.$refs.cropper.getCropBlob  get blob 
then  blob to binary 
https://stackoverflow.com/questions/27208407/convert-blob-to-binary-string-synchronously
