### ISSUE TITLE
你好，img地址支持使用微信sdk中chooseImage返回的localId吗？

### ISSUE THREAD

**Issue by hellowillian21** [xyxiao001/vue-cropper#288]
你好，img地址支持使用微信sdk中chooseImage返回的localId吗？

**Comment by xyxiao001** [comment]
img标签 能显示的  就能用的

**Comment by hellowillian21** [comment]
> img标签 能显示的 就能用的

我遇到一个问题就是可以使用<img :src="localId"/>可以显示图片，<vueCropper :img="使用本地图片"></vueCropper >可以显示裁剪图片，但是<vueCropper :img="localId"></vueCropper >无法显示裁剪图片。

**Comment by hellowillian21** [comment]
> img标签 能显示的 就能用的

我遇到一个问题就是可以使用`<img :src="localId"/> `可以显示图片，`<vueCropper :img="使用assets的本地图片></vueCropper>`可以显示裁剪图片，但是`<vueCropper :img="localId"></vueCropper>`无法显示裁剪图片。

**Comment by xyxiao001** [comment]
有报错吗

**Comment by hellowillian21** [comment]
> 有报错吗

没有报错

**Comment by xyxiao001** [comment]
localid 是一个url地址吗 还是什么

**Comment by hellowillian21** [comment]
> localid 是一个url地址吗 还是什么
localid 的格式是 weixin://resoureceid/xxxxxxxxxxxx
