### ISSUE TITLE
使用vue-cropper遇到两个问题，图片变形和安卓机图片不显示

### ISSUE THREAD

**Issue by whomeet** [xyxiao001/vue-cropper#290]
realOptions:{
        autoCrop:true,
        img:'',
        outputType:'png',
        info:false,
        fixed:true,
        outputSize: 1,
        autoCropWidth:'100%',
        fixedNumber:[1,1],
        canMoveBox:false,
        centerBox:true,
        fixedBox:true
      }
（1）第一个问题安卓手机上图片不显示：
基本配置是这样，传入的img是base64格式图片，定位到原因是base64转blob是出了问题，执行atob失败，错误码Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
（2）第二个问题，图片会变形，出现概率很高，不分机型，基本竖长型的图片都会被拉伸

**Comment by xyxiao001** [comment]
组件版本多少

**Comment by whomeet** [comment]
0.4.9

**Comment by whomeet** [comment]
![image]

**Comment by whomeet** [comment]
![image](https://user-images.githubusercontent.com/19629668/56415328-f7f7d280-62bf-11e9-8538-a5435ba5a68d.png)

**Comment by whomeet** [comment]
你的组件内部base64转blob有点问题，我现在在组件外部先将base64转blob，然后再转成url链接，安卓手机图片可以显示了

**Comment by xyxiao001** [comment]
好的，这个问题，我去看看

**Comment by whomeet** [comment]
但是图片变形问题还没解决，能帮忙看看吗，变形太严重

**Comment by whomeet** [comment]
知道了，图片变形不是组件问题，是选择图片的API出了问题
