### ISSUE TITLE
在chrome73版本，使用滚轮缩放图片时，chrome会出现Unable to preventDefault inside passive event listener due to target being treated as passive.告警

### ISSUE THREAD

**Issue by WangYu1992** [xyxiao001/vue-cropper#291]
在chrome73版本，使用滚轮放大缩小图片时，chrome会出现Unable to preventDefault inside passive event listener due to target being treated as passive.告警，并且缩放很不流畅

**Comment by xyxiao001** [comment]
你用版本多少

**Comment by WangYu1992** [comment]
> 你用版本多少

"vue-cropper": "^0.4.8"，而且在笔记本的话，使用触摸板会把整个页面放大，是在chrome71版本以上

**Comment by xyxiao001** [comment]
不在截图区，触摸板本身就可以放大整个页面

**Comment by xyxiao001** [comment]
更新0.49

**Comment by WangYu1992** [comment]
> 更新0.49

好了，谢谢大佬！
