### ISSUE TITLE
请问如何在不限制outputType时，缩小裁切后图片大小

### ISSUE THREAD

**Issue by Ling-l** [xyxiao001/vue-cropper#296]
您好，现在有个疑问
被裁切的原图大小为126kb，裁切后图片为700多kb.
如果把outputType改成jpeg，同时outputSize改成0.1，裁切出的图片会比原图小，但是底色变成黑色了；
如果把outputType 改成png，底色是透明的，可是大小又很大了。

请问有没有办法可以同时保留透明背景色 和 缩小裁切后大小？

**Comment by xyxiao001** [comment]
png会比较大， 建议裁剪后使用第三方库压缩下
