### ISSUE TITLE
`canMove` property doesn't work

### ISSUE THREAD

**Issue by mk-tool** [xyxiao001/vue-cropper#298]
`canMove` property doesn't work in my environment.
`canMoveBox` property works well.

How should I do to use `canMove` property?
I read this [example](https://github.com/xyxiao001/vue-cropper/blob/master/example/src/App.vue). But I couldn't find my error.

I use VueCropper like below.

```
<vueCropper
  ref="cropper"
  :img="option.img"
  :outputSize="option.size"
  :outputType="option.outputType"
  autoCrop
  :canMoveBox="true"
  :canMove="true"
  :enlarge="2"
  style="height:500px;background:rgba(0, 0, 0, 0.5);"
></vueCropper>
```

`outputType` property is jpg.

I tried with `v0.4.7` and `v0.4.9`.

**Comment by mk-tool** [comment]
I solved this problem.
I used `vue-cropper` at the latter of my program.
But after move this program to top, this program works well.
Some program was affected with `vue-cropper`.

**Comment by mk-tool** [comment]
If I use two `vue-cropper` component which has the same  `ref` value, I could use `canMove` property.
But cause of two same `ref` value, this solution couldn't solve this problem.

**Comment by xyxiao001** [comment]
If you use two components, you need two different refs，Otherwise, there is no way to distinguish

**Comment by mk-tool** [comment]
@xyxiao001 
Thank you for your reply.
I'm understanding your pointing. But if I use different two refs, I can't use `canMove` property.
If I set two same refs, the first component could use `canMove` property and the second component couldn't use  `canMove` property. 

Are there any tips to use `canMove` property.

**Comment by mk-tool** [comment]
@xyxiao001 
If I use `vue-cropper` in `v-dialog` of `Vuetify`, this problem occurs.
I quit using `v-dialog`.

**Comment by mk-tool** [comment]
If I hide vue-cropper component with `v-if` or `z-index:-1`, the same problem occurred.
But `v-show` works well in  [online example](https://codepen.io/xyxiao001/pen/wxwKGz).
So this problem occurs only in my environment.
