### ISSUE TITLE
最新的版本组件不显示

### ISSUE THREAD

**Issue by 569202812** [xyxiao001/vue-cropper#299]
![image](https://user-images.githubusercontent.com/34082148/57861998-35517080-782a-11e9-9c63-560774fc422d.png)
我看dist文件有注释的地方

**Comment by jovercao** [comment]
+1

**Comment by xyxiao001** [comment]
怎么使用的

**Comment by jovercao** [comment]
直接按复制example目录的范例的app.vue及code.vue使用，
我试过0.4.8也不行，
而后使用0.4.0后变回正常
能正常编译，运行后浏览器console提示：
无法找到template与render函数。

**Comment by xyxiao001** [comment]
4.8的使用请看文档的引入方式

**Comment by 569202812** [comment]
我的是引用问题 import { vueCropper } from "vue-cropper"

**Comment by jovercao** [comment]
```es6
import VueCropper from "vue-cropper";
// import { VueCropper } from '../test'

import codes from "./code";

export default {
  components: {
    VueCropper,
    codes
  },
  // ...
}
```

**Comment by 569202812** [comment]
> ```js
> 进口 VueCropper  从 “ VUE-栽跟头” ;
> //从'../test'导入{VueCropper}
> 
>  从“ ./code ”导入代码  ; 
> 
> export  default {
>   组件： {
>     VueCropper，
>     代码
>   }，
>   // ... 
> }
> ```

import { VueCropper } from 'vue-cropper'

**Comment by jovercao** [comment]
是在 0.4.3 之后规修改了组件引入方式，0.4.3及之后的版本使用 `import { VueCropper } from 'vue-cropper'`方式引入组件即可。
