### ISSUE TITLE
可以增加更多的参数吗？

### ISSUE THREAD

**Issue by bcw104** [xyxiao001/vue-cropper#3]
[https://github.com/fengyuanchen/cropperjs#options](url)
## 这里面的参数，可否提供一个方法一次性设置进去？

**Comment by xyxiao001** [comment]
我没有用到这个cropperjs,   你可以通过props 把参数传进去

**Comment by bcw104** [comment]
我以为是基于cropperjs实现的，能否提供一个参数，让截图框固定宽高比例？

**Comment by xyxiao001** [comment]
我明白了 ， 你希望截图框宽高比固定对吧， 那我去加上这个功能吧， 待会推个新版本上去。

**Comment by xyxiao001** [comment]
fixed	是否开启截图框比例限制
fixedNumber	比例限制 w:h  默认 [1 : 1]
安装最新的0.1版本就行
