### ISSUE TITLE
看了issue没有看到类似的，裁剪的时候能不能让裁剪框跟我图片的宽度或者高度一样

### ISSUE THREAD

**Issue by PasserbyFluid** [xyxiao001/vue-cropper#303]
比如图片很长 那就让裁剪框跟图片高度一样，如果很高，那就让裁剪框跟宽度一样。类似于微信裁剪头像那样的效果。

**Comment by PasserbyFluid** [comment]
顺便请问一下，移动端是不是不太友好，我在一个模态框里面使用，加载图片的时候会卡顿，而且设定内容大小之后会明显看到中间停顿一下才变成设定的大小

**Comment by xyxiao001** [comment]
设定内容大小是指什么 手动改变宽度吗

**Comment by PasserbyFluid** [comment]
![微信图片_20190613102702](https://user-images.githubusercontent.com/20455673/59399777-dd297200-8dc7-11e9-9331-6c563cfc9b15.jpg)
![微信图片_20190613104051](https://user-images.githubusercontent.com/20455673/59399779-ddc20880-8dc7-11e9-9672-3794fc6ac5a3.jpg)
这样的，打开之后的弹框大小应该是大的，但是会在小的这个位置卡一下，调试没定位到问题，所以想问一下是组件里面限定大小了吗，源码也没看到

**Comment by xyxiao001** [comment]
没有限制大小 你可以在外层外层包裹个div设置宽度高度
