### ISSUE TITLE
@realTime doesnot work.

### ISSUE THREAD

**Issue by chawlautsav** [xyxiao001/vue-cropper#304]
@realTime doesnot work.
I see it in your example but try installing using npm in a vue cli project.
I have seen the same issue reported but its been dismissed.
Kindly look into it before dismissing this one.

**Comment by xyxiao001** [comment]
use npm  template @realTime="realTime"
html ->   @real-time="realTime"

**Comment by chawlautsav** [comment]
`<template>
	<div>  
        <input
            type="file"
            name="image"
            accept="image/*"
            style="display : none;"
            @change="setImage"
            ref='fileInput'
        />
            
        <div v-if="imgSrc===''" @click="$refs.fileInput.click()" style="width: 350px; height:350px; border: 1px solid gray; display: inline-block;">
            Click to upload
        </div>

        <div v-else style="width: 350px; height:350px; border: 1px solid gray; display: inline-block;"	>
            
            <vue-cropper
                ref="cropper"
                :view-mode="0"
                :guides="false"
                :highlight="true"
                drag-mode="crop"
                :auto-crop-area="0.7"
                :min-container-width="150"
                :min-container-height="150"
                :background="false"
                :rotatable="true"
                :src="imgSrc"
                :aspectRatio="1/1"
                :initialAspectRatio="1/1"
                alt="User Image"
                :img-style="{ width: '350px', height: '350px' }"
                >
            </vue-cropper>
        </div>
		
		
       	<img
            :src="cropImg"
            style="width: 300px; height : 300px; border: 1px solid gray; border-radius : 50% "
            alt="User Image"
        />
        
        <div @click="rotate"> Rotate </div>
			
        <button @click="cropImage" v-if="imgSrc != ''" style="margin-right: 40px;">
            Crop
        </button>
    </div>
</template>
<script>

import axios from 'axios';
import VueCropper from 'vue-cropperjs';
import 'cropperjs/dist/cropper.css';
export default {
	name: 'Test',
	components: {
		VueCropper
	},
	
	data() {
		return {
			imgSrc: "",
			cropImg: "",
		};
	},
	methods: {
		realTime(e)
		{
			console.log("new crop");
		},
		setImage(e) {
			const file = e.target.files[0];

			if (!file.type.includes("image/")) {
				alert("Please select an image file");			//error msg here
				return;
			}

			if (typeof FileReader === "function") {
		
				const reader = new FileReader();
				reader.onload = event => {
					this.imgSrc = event.target.result;
					this.$refs.cropper.replace(event.target.result);
				};

				reader.readAsDataURL(file);
			}
			else {
				alert("Sorry, FileReader API not supported");		//error msg here
			}
		},
		
		cropImage() {

			this.cropImg = this.$refs.cropper.getCroppedCanvas().toDataURL();

			let formData = { image :  this.cropImg }
			axios.post('http://localhost:3000/upload', formData)
				.then( res => console.log( res) )
				.catch(  err => console.log( err, err));

		},
		rotate() {
			this.$refs.cropper.rotate(90);
		}
	}
}
</script>
`

**Comment by chawlautsav** [comment]
https://textuploader.com/1dx0s!

I have tried many things but not able to generate any event.
Kindly look in this and tell me whats my mistake.
Thanks in advance.

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/  you can see that

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/59345972-e3760a80-8d43-11e9-89ae-38b8059379ca.png)
realTime

**Comment by chawlautsav** [comment]
Yes, I have been referring to this from 8 hours.
This I totally get it and have experimented.
I have tried
@realTime="realTime"  
@realtime="realTime"
@real-Time="realTime"
@real-time="realTime"

None seems to work.

**Comment by xyxiao001** [comment]
@realTime=""

**Comment by chawlautsav** [comment]
Yes, github is changing case, I got your point. lower camel case. That I have already tried.

**Comment by xyxiao001** [comment]
😁

**Comment by chawlautsav** [comment]
Is there any other way to specify a event handler for any movement of the cropping frame.
Just an open thought. Maybe through $refs directive??

**Comment by xyxiao001** [comment]
There is currently no way to move the position of the screenshot box.
