### ISSUE TITLE
截图后的图片和截图框一样的长宽

### ISSUE THREAD

**Issue by wangdongdong9264** [xyxiao001/vue-cropper#306]
`<vue-cropper
            ref="cropper"
            :img="option.img"
            :output-size="option.size"
            :output-type="option.outputType"
            :fixed="option.fixed"
            :auto-crop="option.autoCrop"
            :auto-crop-width="option.autoCropWidth"
            :auto-crop-height="option.autoCropHeight"
            :fixed-box="option.fixedBox"
          />
option: {
        img: '',
        size: 1,
        outputType: 'png',
        fixed: false,
        fixedNumber: [16, 9],
        autoCrop: true,
        autoCropWidth: 320,
        autoCropHeight: 200,
        fixedBox: true,
        centerBox: true
      },`

**Comment by xyxiao001** [comment]
描述清楚一点

**Comment by wangdongdong9264** [comment]
例如 我的截图框是320*200 但是我滚轮缩放后 产生的截图可能大于或小于320*200  但是我想要的是320*200(也就是截图框的宽高)

**Comment by xyxiao001** [comment]
这个目前因为图片比例存在问题还有我代码处理的问题， 可能没办法准确缩放，

**Comment by wangdongdong9264** [comment]
不是这个意思 
现在产生的截图是依据原图尺寸(例如 原图是1200*800 截图框是320*200 缩放后 对应原图的尺寸是640*400) 
产生的截图是640*400 但我需要的是320*200(也就是截图框看到的部分)
这个可以吗

**Comment by wangdongdong9264** [comment]
可以关闭这个问题了
