### ISSUE TITLE
这个插件支持旋转图片吗

### ISSUE THREAD

**Issue by bing2313** [xyxiao001/vue-cropper#308]

**Comment by xyxiao001** [comment]
![Uploading image.png…]()

**Comment by xyxiao001** [comment]
this.$refs.cropper.rotateRight() 向右边旋转90度
this.$refs.cropper.rotateLeft() 向左边旋转90度

**Comment by xyxiao001** [comment]
this.$refs.cropper.rotateRight() 向右边旋转90度
this.$refs.cropper.rotateLeft() 向左边旋转90度
