### ISSUE TITLE
图片URL为空时显示上一次URL的图片

### ISSUE THREAD

**Issue by linglonghui** [xyxiao001/vue-cropper#310]
图片能够正常加载进来，但是如果：img属性的为空时，显示的是上一个显示的图片,请教一下这个是什么原因？该图片URL是兄弟组件传递过来的，然后在组件上监听这个URL(val)，如果URL有值，就赋值:
watch: {
        preImgURL(val) {
          console.log(val)
          this.$nextTick(() => {
            // this.option.img = val
            if(val){
              // this.isImgURL = true
              this.option.img = val
            }else{
              // this.isImgURL =false
              this.option.img = ''
            }
          })
        }
      },

**Comment by xyxiao001** [comment]
因为默认组件必须显示图片 所以设置为空没有效果

**Comment by linglonghui** [comment]
现在真实的情况是：在进入这个界面时，如果前面传入的URL为空，那么它是不显示图片的；直到URL传入了具体的值，组件上才显示图片，后续URL为空的话会显示上一次的图片。如果组件默认必须显示图片，那么第一次URL为空时它却没有显示图片？   有没有什么方法让它不显示图片吗？或者说这个组件能否考虑一下去掉这个必须显示图片的设定

**Comment by xyxiao001** [comment]
可以   后续看看加上   可以不传的功能

**Comment by ameibj** [comment]
我也这个需求，一般情况这样的，点击本地图片上传，然后选择截图框截图，再次上传到后端服务器！我的需求是，点击按钮在一个视图上，或者图片上，弹出遮照和剪裁框，剪裁完后把得到的图片存数组或上传后台，但我的视图或图片是要切换的，等于不停动态给组件option.img赋值，会导致点击选择新图不对应的问题

**Comment by ameibj** [comment]
还有截图后，在方法里拿到剪裁图数据push到数组，页面有循环这个数组显示截图记录的，感觉不能即时更新试图，大致情况剪裁框选完保存push后，数据没进来，再次重复流程会看到上次的截图数据。

**Comment by xyxiao001** [comment]
0.5版本已解决
