### ISSUE TITLE
vue-cropper下的img就有跨域问题

### ISSUE THREAD

**Issue by jasmine-song** [xyxiao001/vue-cropper#312]
![image](https://user-images.githubusercontent.com/44150070/61206471-3bc67080-a725-11e9-9e09-2520f86fbb03.png)
DOM里 单独写img src图片可以显示
vue-cropper下的图片就有跨域问题

**Comment by xyxiao001** [comment]
因为截图需要 canvas 处理 就会跨域

**Comment by jasmine-song** [comment]
请问 在两个img标签中加上 anonymous 属性可以么
有具体的解决方式么

**Comment by xyxiao001** [comment]
不可以 需要服务端设置

**Comment by jasmine-song** [comment]
第三方服务器暂时找不到维护更改的话
![image](https://user-images.githubusercontent.com/44150070/61264215-46811400-a7be-11e9-9911-76a605dc8dce.png)
src 改为base64是不可以显示
请问这里是怎么转为blob的

**Comment by jasmine-song** [comment]
第三方服务器找不到人修改了...
后台返回base64的话 请问大神 插件源码需要改的多吗 看迷糊了

**Comment by xyxiao001** [comment]
base64 那就没有跨域问题了
