### ISSUE TITLE
请问设置fixed为true 之后，设置autoCropWidth就无效了吗

### ISSUE THREAD

**Issue by coolHt** [xyxiao001/vue-cropper#314]
试了一下，fixedNumber设置比例有效，但是设置autoCropWidth则无效，有时候截图框会过大，所以想设置一下width,作者可以通过设置的width 和 fixedNumber 自动设置height吗？

**Comment by xyxiao001** [comment]
有效啊

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/61344400-b1485300-a883-11e9-9817-878e4df5c160.png)

**Comment by coolHt** [comment]
![image](https://user-images.githubusercontent.com/23614026/61344494-08e6be80-a884-11e9-870e-7115fd9bd93c.png)


![image](https://user-images.githubusercontent.com/23614026/61344512-156b1700-a884-11e9-9b5c-fb98c56001ad.png)

**Comment by coolHt** [comment]
您看一下，我这儿有设置，但是没有生效。

**Comment by xyxiao001** [comment]
带上 px

**Comment by xyxiao001** [comment]
25px

**Comment by xyxiao001** [comment]
我刚刚看了下代码 你还需要传入截图框自动生成的高度 ，不然会默认进入初始化大小

**Comment by xyxiao001** [comment]
是数字

**Comment by coolHt** [comment]
我设置了自动生成的宽高之后，设置了fixed为true 之后，宽高就无效了吶。

**Comment by coolHt** [comment]
解决了。谢谢！

**Comment by HuRuilin** [comment]
请问最终是怎么解决的呢？我也遇到了autoCropWidth设置后，不生效的问题
