### ISSUE TITLE
截图框显示问题？

### ISSUE THREAD

**Issue by ameibj** [xyxiao001/vue-cropper#318]
引入组件，用v-show根据变量显示vueCropper组件，在动态传入option.img发现初始化没有图，只有默认的格子背景图，再次点击后，会显示上一次图，但是剪裁框变成100x100了，不是初始化传入的尺寸了！后来我只能给css用visiable定义显示隐藏解决了问题。另外，我是方法里动态赋值本地img和显示隐藏此插件的，手机码字，忘记截图了，抱歉

**Comment by xyxiao001** [comment]
使用v-show 第一次需要等组件加载出来之后 然后赋值img

**Comment by ameibj** [comment]
能讲下，如何判断vue-cropper组件是否加载完毕？

**Comment by xyxiao001** [comment]
v-show的 nextTick

**Comment by ameibj** [comment]
感谢你作者大佬的回答，我用了定时器和this.$nexttick也没实现。另外弱弱问下，在线demo怎么看到设置参数的demo代码，我目前是源码例子里找的，

**Comment by xyxiao001** [comment]
我的意思是show之后然后赋值img

**Comment by ameibj** [comment]
还有一个问题就是，拿到截图后的img数据后，我把img存数组list里，视图循环显示，也遇到数据push不进去list，再次截图会看到上次的视图数据

**Comment by xyxiao001** [comment]
因为v-show 不会销毁组件 所以显示的是上一次的

**Comment by ameibj** [comment]
我变量true，是show之后，然后定时器，和next赋值img的

**Comment by ameibj** [comment]
576164240希望能加您的群探讨？

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/61960583-55569a80-aff8-11e9-9c60-2fe522f6a19c.png)
