### ISSUE TITLE
为什么显示vueCropper is not defined

### ISSUE THREAD

**Issue by chenxiong666** [xyxiao001/vue-cropper#32]
我先install然后import了，结果报这个错

**Comment by xyxiao001** [comment]
你怎么引入的

**Comment by chenxiong666** [comment]
在组件中import VueCropper from 'vue-cropper'
components: {
			vueCropper
		}

**Comment by xyxiao001** [comment]
你在mounted 里面打印vueCropper 试一试

**Comment by xyxiao001** [comment]
代码截图看看

**Comment by chenxiong666** [comment]
![image](https://user-images.githubusercontent.com/31265809/32358243-82cd26d8-c07f-11e7-92be-aec9a53bca0f.png)

**Comment by chenxiong666** [comment]
![image](https://user-images.githubusercontent.com/31265809/32358286-c5f992b6-c07f-11e7-8fdb-91fea278ecd6.png)

**Comment by xyxiao001** [comment]
可能是没安装成功吧 重新安装试一试呢

**Comment by xyxiao001** [comment]
看看node_module 里面有吗

**Comment by chenxiong666** [comment]
![image](https://user-images.githubusercontent.com/31265809/32358313-efec8682-c07f-11e7-8d0c-e35442753ccd.png)
有啊

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/32358429-07346750-c081-11e7-8646-2b3e5bde2cf4.png)

**Comment by xyxiao001** [comment]
刚刚新建项目测试的

**Comment by chenxiong666** [comment]
我新建了一个项目还是报错，components: {vueCropper},这段代码注释掉 mounted才有输出

**Comment by xyxiao001** [comment]
加我qq463618622 我帮你看看
