### ISSUE TITLE
实时预览，第一次使用旋转功能后返回的裁切框宽高数据有问题

### ISSUE THREAD

**Issue by 364124337** [xyxiao001/vue-cropper#320]
我在@realTime里面使用定时器延迟几毫秒后才能正确的获取到第一次旋转后裁切框的宽高，但是data.img.transform返回的位置计算是有问题的

**Comment by 364124337** [comment]
就第一次旋转有问题，后面都OK

**Comment by 364124337** [comment]
前提条件是：centerBox: true, // 截图框是否被限制在图片里面，我使用你的列子试了也是一样的

**Comment by 364124337** [comment]
我发现只要旋转，裁切框的宽高被改变就会出现这个问题，不是第一次的问题

**Comment by 364124337** [comment]
原因应该是：没判断裁切框宽高是否改变，旋转直接计算了showPreview

**Comment by xyxiao001** [comment]
改变之后showPreview会重新出发的

**Comment by 364124337** [comment]
是的，但实际是没触发到，
不知道是不是：
// 优化不要多次触发
      if (this.isCanShow) {
        this.isCanShow = false;
        setTimeout(() => {
          this.isCanShow = true;
        }, 16);
      } else {
        return false;
      }
这段代码导致的

**Comment by 364124337** [comment]
我在旋转后，弄个定时器（超过16ms）触发showPreview 就是正确的结果，你看看是否需要优化下

**Comment by xyxiao001** [comment]
好 我看看这个问题
