### ISSUE TITLE
iphone 6 Plus 调用拍照会崩！！！！！

### ISSUE THREAD

**Issue by Caaaaa** [xyxiao001/vue-cropper#321]
iphone 6 Plus 调用拍照会崩！！！！！
拍照-确定，然后就崩了

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/62204905-c9aa8880-b3c0-11e9-81d7-608e9a6a0b36.png)
这个 属性设置小一点的
