### ISSUE TITLE
是否有destroy功能和reset功能？

### ISSUE THREAD

**Issue by yrj-essential** [xyxiao001/vue-cropper#322]
是否有取消裁剪功能？
是否有重置裁剪，即重置图片大小位置、裁剪框大小位置？

**Comment by xyxiao001** [comment]
文档有对应方法的

**Comment by yrj-essential** [comment]
> 文档有对应方法的

感谢您的及时回复！
查看文档后，destroy可由以下代码实现
`this.option.canScale = false
                this.option.canMove= false
                this.$refs.cropper.clearCrop()`
reset可由以下代码实现
`this.$refs.cropper.refresh();`
但每次调用refres()，会出现图片抖动情况。

**Comment by xyxiao001** [comment]
refresh 是因为会重新渲染图片

**Comment by yrj-essential** [comment]
> refresh 是因为会重新渲染图片

是否考虑添加不重新渲染的refresh()，
或者暴露取消裁/添加剪框的方法

**Comment by xyxiao001** [comment]
清除截图框是 this.$refs.cropper.clearCrop()

autoCrop 修改为 true 可以生成截图框

**Comment by yrj-essential** [comment]
> 清除截图框是 this.$refs.cropper.clearCrop()
> 
> autoCrop 修改为 true 可以生成截图框

谢谢！搞定了！

**Comment by young-3303** [comment]
refresh页面会抖动一下体验有点不好呀
