### ISSUE TITLE
outputType；可以在canvan绘制之前先把背景画成白色（加多个配置项？）

### ISSUE THREAD

**Issue by 364124337** [xyxiao001/vue-cropper#330]
// 在canvas绘制前填充白色背景
        context.fillStyle = "#fff";

**Comment by xyxiao001** [comment]
这个目前建议自己去处理， 后续我看看加上颜色的配置

**Comment by 364124337** [comment]
处理回来后的图片吗

**Comment by xyxiao001** [comment]
是的， 或者你截图框不要截到图片外面也可以呀

**Comment by 364124337** [comment]
好的，感谢，图片就是上传Png格式的，是在图片里面了，无奈

**Comment by WangMargin** [comment]
> // 在canvas绘制前填充白色背景
> context.fillStyle = "#fff";

您好， 您是在裁切图片的时候出现的 透明背景 然后上传jpg的时候透明背景变成了黑色，这个问题么？
