### ISSUE TITLE
截图框最大宽高不为原始图的最大宽高

### ISSUE THREAD

**Issue by attacking** [xyxiao001/vue-cropper#345]
传递一个1000*1000的图片给vue-cropper，调整其截图框大小使其尽可能大，但最大只有720px，不能达到原图大小。请问这个是如何设置使得截图框最大尺寸可以和图片大小一致呢

**Comment by attacking** [comment]
在这里即可复现：[地址](http://github.xyxiao.cn/vue-cropper/example/)。选择一张大图进行裁剪，截图框宽度达不到图片宽度

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/66990922-ae1a6880-f0f9-11e9-886d-0191fe8f28d2.png)
这不是可以的

**Comment by xyxiao001** [comment]
截图框大小会被容器的大小给限制住， 如果开启了 centerbox 会被限制在图片里面

**Comment by xyxiao001** [comment]
这样也可以呀， 只要你容器 和图片都比截图框大就可以的。
你可以在这个网站上测试的
https://codepen.io/xyxiao001/pen/wxwKGz

**Comment by attacking** [comment]
容器要比截图框大这个可能不合理。在页面中容器的宽度是受限制的，不能依据图片的真实宽高来设置。我再探索一下。多谢你，咖啡奉上。



在 2019-10-17 16:29:31，"goodboy" <notifications@github.com> 写道：


这样也可以呀， 只要你容器 和图片都比截图框大就可以的。
你可以在这个网站上测试的
https://codepen.io/xyxiao001/pen/wxwKGz
