### ISSUE TITLE
how to instance multiple crop image ?

### ISSUE THREAD

**Issue by spham** [xyxiao001/vue-cropper#347]
i would like to have many instance. in a foreach.

**Comment by xyxiao001** [comment]
You can use the v-for loop to use the component, but refs needs to bind more than one to get the screenshot.

**Comment by spham** [comment]
have you an example ?

**Comment by xyxiao001** [comment]
Do you want multiple crop frames to crop the image, or a crop frame to crop multiple images?

**Comment by spham** [comment]
i would like on click change each image 
https://jsfiddle.net/spham92/u5gsx9he/

**Comment by xyxiao001** [comment]
Emm, I think you can write a modal, then click on the image to display the cropper component, the incoming click image

**Comment by spham** [comment]
yes, but i dont get how to make a loop in ref

**Comment by xyxiao001** [comment]
No need to loop ref, a component is enough, just need to pass in the clicked image.

**Comment by spham** [comment]
how ?

**Comment by xyxiao001** [comment]
Just like the file upload of my example, but your click on the incoming image display component

**Comment by xyxiao001** [comment]
You only need to modify props img  when you click on the image.

**Comment by spham** [comment]
like this ? 
https://codepen.io/spham/pen/eYYgxGr

**Comment by xyxiao001** [comment]
yeah, You can do a  dialog to display the component and then pass in the img address of the click.
