### ISSUE TITLE
ios拍照之后无法显示在剪辑图片容器中？

### ISSUE THREAD

**Issue by Mrlilili** [xyxiao001/vue-cropper#35]
1.拍完照之后，报错canvas.toBlob is not a function
https://github.com/pfnet/PaintsChainer/issues/51
尝试了下vue-cropper依赖exif-js降级到2.2.0版本也不会报错，但是还是会出现下面的问题

2.用这个方法解决后，没有报错，但是还是无法在剪辑局域正常显示所拍照片

测试机型：iPhone5s(IOS 8.1)、iPhone 7 plus(IOS10.3.3)

**Comment by xyxiao001** [comment]
你用在线的例子测试会有问题吗

**Comment by Mrlilili** [comment]
在线例子也是有问题的

**Comment by xyxiao001** [comment]
我刚刚用iphone7  ios11测试没问题

**Comment by Mrlilili** [comment]
刚刚验证了下是iPhone5s IOS8.1出现了这种情况

**Comment by russellmars** [comment]
我也有这个问题，等着更新，0.2.6好像还是有这个问题，上面老哥说的这两个机型的ios，直接选择照片是没问题的，拍照的就有问题

**Comment by xyxiao001** [comment]
好的 我去研究看看
