### ISSUE TITLE
图片渲染出现跨域

### ISSUE THREAD

**Issue by cangyu1993** [xyxiao001/vue-cropper#353]
### ### **渲染图片出现跨域怎么处理？有没有遇到过的？**

![image](https://user-images.githubusercontent.com/42930030/68181402-1b6f3a00-ffd2-11e9-932a-c69f32279cf9.png)

**Comment by xyxiao001** [comment]
服务器设置的

**Comment by cangyu1993** [comment]
后台的服务器已经设置了跨域了

**Comment by xyxiao001** [comment]
图片是存在后端的嘛

**Comment by cangyu1993** [comment]
是的，图片在服务器上

**Comment by xyxiao001** [comment]
那应该是没问题的，应该是没设置好

**Comment by xyxiao001** [comment]
这个前端没办法处理跨域

**Comment by cangyu1993** [comment]
好吧，谢谢解答，看看后端能不能处理吧
