### ISSUE TITLE
在图片为空值时，占位图出现

### ISSUE THREAD

**Issue by yrj-essential** [xyxiao001/vue-cropper#355]
当一个cropper加载过图片后，进行新增操作时，若上次的图片尺寸小于画布会出现img标签的占位图。
尝试过refres 和 clearCrop组合操作，无法解决。
是否能考虑添加destroy功能，或对图片为空值时进行处理。
![image](https://user-images.githubusercontent.com/24262359/68742061-32dda100-062a-11ea-8a84-737adca85c0a.png)

**Comment by xyxiao001** [comment]
目前占不支持清空图片 后续会添加的

**Comment by yrj-essential** [comment]
好的，期待新版本
