### ISSUE TITLE
为什么这个插件放到element-ui Dialog 对话框当中，实时预览会出问题？

### ISSUE THREAD

**Issue by renleiabc** [xyxiao001/vue-cropper#357]
![image](https://user-images.githubusercontent.com/24283195/68912876-68060280-0794-11ea-9833-3f2ee25e0b8c.png)
![image](https://user-images.githubusercontent.com/24283195/68912897-76ecb500-0794-11ea-9f60-50d9c0f23a7c.png)

**Comment by xyxiao001** [comment]
你看看是不是 img 的样式影响了组件
