### ISSUE TITLE
请问作者能否暴漏上传图片的真实大小

### ISSUE THREAD

**Issue by 18210092010** [xyxiao001/vue-cropper#358]
对接云上传的时候，需要拿到图片的真实大小，这样才能保证本地裁切和云裁切一致，实现所见即所得

**Comment by xyxiao001** [comment]
上次的真实大小  你是指啥 是裁剪获取的图片大小吗

**Comment by 18210092010** [comment]
上传的图片的真实大小，就是你代码里的turewidth,tureheight



发自我的小米手机在 goodboy <notifications@github.com>，2019年11月15日 下午5:43写道：上次的真实大小  你是指啥 是裁剪获取的图片大小吗



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/xyxiao001/vue-cropper/issues/358?email_source=notifications\u0026email_token=AEYLHJPKNNI6ELEBDRBE6ADQTZVMJA5CNFSM4JNVGDHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEE4OHA#issuecomment-554288924",

"url": "https://github.com/xyxiao001/vue-cropper/issues/358?email_source=notifications\u0026email_token=AEYLHJPKNNI6ELEBDRBE6ADQTZVMJA5CNFSM4JNVGDHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEE4OHA#issuecomment-554288924",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
