### ISSUE TITLE
容器内显示不对啊

### ISSUE THREAD

**Issue by ubbcou** [xyxiao001/vue-cropper#36]
为什么我用的会是这个样子呢？？

![image](https://user-images.githubusercontent.com/25863414/32955073-dac8252e-cbef-11e7-8f0e-2e7b3386226e.png)
```
.avatar-box {
            position: relative;
            height: 500px;
        }
<div class="avatar-box">
                    <VueCropper ref="cropper"
                    :img="option.img"
                    :autoCrop="true"
                    :outputType="option.outputType"></VueCropper>
                </div>
```

**Comment by xyxiao001** [comment]
在线例子也会出这个问题吗

**Comment by ubbcou** [comment]
@xyxiao001 是的，在线上也是出现了

**Comment by xyxiao001** [comment]
方便把图片发我一下吗 我看看

**Comment by ubbcou** [comment]
图片？所有图片都这样显示欸 =。 你看下在线例子?  [嘀嘀嘀](https://nb.goduc.cc/#/userinfo/)

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/32976897-adef1248-cc5c-11e7-9d94-d44ce66007bc.png)
没问题啊

**Comment by ubbcou** [comment]
对啊，我也看了你的例子。甚至例子源码都复制过来了试试，也一样显示异常..我不知道哪出了问题。。你点我那个在线例子看看？

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/32976913-3362b812-cc5d-11e7-93db-9fa0a88e4a78.png)
 这个最大宽度影响了截图框的图片

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/32976924-6366e47a-cc5d-11e7-892f-d55b58570854.png)

**Comment by ubbcou** [comment]
噢，这样啊。好吧，麻烦了TAT..
