### ISSUE TITLE
关于图片裁剪固定尺寸的问题

### ISSUE THREAD

**Issue by G-dc** [xyxiao001/vue-cropper#360]
请问作者，当前该工具是否支持如下所描述的功能：
假设设置的裁剪框为300*200，之后不论上传的图片如何缩放，通过裁剪框裁剪出来的部分大小总是300*200（不考虑原图缩小到小于300*200）

**Comment by xyxiao001** [comment]
目前就是这样的，默认输出的图片大小就是裁剪框大小

**Comment by G-dc** [comment]
目前我的测试结果是这样的， 比如我裁剪框固定的尺寸是700*450，然而不管有没有缩放，裁剪出来的图片尺寸和裁剪框设置的固定尺寸值是不一致的。
我想请问一下出现这种情况是参数设置的原因吗？

**Comment by xyxiao001** [comment]
看看你的参数

**Comment by G-dc** [comment]
![Snipaste_2019-11-21_08-53-39](https://user-images.githubusercontent.com/22066144/69290918-6a58d880-0c3c-11ea-9ed2-d6df67673d3b.png)

**Comment by xyxiao001** [comment]
Full是根据原图比例去修改裁剪框，设置为fat

**Comment by G-dc** [comment]
尝试过了，full设置为false之后还是存在上述问题

**Comment by xyxiao001** [comment]
没问题呀，你可以看看例子的

**Comment by G-dc** [comment]
那我再看看demo，谢谢~
