### ISSUE TITLE
mode切换没有重载

### ISSUE THREAD

**Issue by 498755303** [xyxiao001/vue-cropper#361]
下面有代码  引入之后  过程中更改了mode，并且调用了组件reload方法,并不能reload,另外 截图框 采用宽高比的情况下 只设置宽或高即可 
<template>
  <div class="cropper-dialog">
    <el-dialog title="图片裁切"
               :visible.sync="visible"
               top="2vh"
               width="60%"
               :show-close="true"
               @open="_openHandle">
      <div :class="'cropper-content-wrap '+ wrapClass">
        <vueCropper ref="cropper"
                    :img="imgUrl"
                    :outputSize="options.outputSize"
                    :outputType="options.outputType"
                    :info="options.info"
                    :canScale="options.canScale"
                    :autoCrop="options.autoCrop"
                    :autoCropWidth="options.autoCropWidth"
                    :autoCropHeight="options.autoCropHeight"
                    :fixed="options.fixed"
                    :fixedNumber="options.fixedNumber"
                    :full="options.full"
                    :fixedBox="options.fixedBox"
                    :canMove="options.canMove"
                    :canMoveBox="options.canMoveBox"
                    :original="options.original"
                    :centerBox="options.centerBox"
                    :high="options.high"
                    :infoTrue="options.infoTrue"
                    :maxImgSize="options.maxImgSize"
                    :mode="mode"
                    :enlarge="options.enlarge"
                    @imgLoad="_imgLoad"
                    @realTime="_realTime"
                    @imgMoving="_imgMoving"
                    @cropMoving="_cropMoving"></vueCropper>

      </div>
      <span slot="footer"
            class="dialog-footer">
        <el-button @click="_handleCancel">取 消</el-button>
        <el-button type="primary"
                   @click="_handleSure">确 定</el-button>
      </span>
    </el-dialog>
  </div>
</template>
<script>
import { VueCropper } from 'vue-cropper';
export default {
  props: {
    wrapClass: {
      type: String
    }
  },
  data() {
    return {
      visible: false,
      imgUrl: "",
      options: {},
      mode: "contain"
    };
  },
  methods: {
    openDialog(o) {
      this.imgUrl = o.imgUrl;
      this.options = o.options      
      this.mode = "auto 100%";
      this.visible = true;
    },
    _openHandle() {
      this.mode = "100% auto";
      this.$nextTick(() => {
        this.$refs.cropper.checkedImg()
        this.$refs.cropper.reload()
      })
    },
    _imgLoad(e) {
      // console.log(e, arguments);
    },
    _realTime(e) {
      // console.log(e, arguments);
    },
    // 图片移动回调
    _imgMoving(data) {
      this.$emit("_imgMoving", data);
    },
    // 截图移动回调
    _cropMoving(data) {
      this.$emit("_cropMoving", data);
    },
    // 取消处理
    _handleCancel() { return false; },
    // 确定处理
    _handleSure() {
      this.$refs.cropper.getCropData((data) => {
        // do something
        console.log(data);
      });

      // 获取截图的blob数据
      this.$refs.cropper.getCropBlob((data) => {
        // do something
        console.log(data);
      });
      return false;
    }
  },
  components: {
    VueCropper
  }
};
</script>
<style lang="less" scoped>
@baseClass: cropper-content-wrap;
</style>

**Comment by xyxiao001** [comment]
在线例子， 切换 mode， 确实会自动重载
http://github.xyxiao.cn/vue-cropper/example/

**Comment by 498755303** [comment]
我看过示例代码   但是我这边这个代码 写的一样 的确是切换之后没有变化 
![image](https://user-images.githubusercontent.com/28357943/69700617-d00a0080-1125-11ea-9013-e704803938f0.png)

**Comment by 498755303** [comment]
刚才通过在源码里面打印看了下  监听到了mode的变化  ，只不过没按变化显示
![image](https://user-images.githubusercontent.com/28357943/69700976-d187f880-1126-11ea-92d9-8f326ef82ca9.png)

**Comment by 498755303** [comment]
看了代码 找到原因了
original  设置为true了  打扰了  可以在文档上加一下这个说明

**Comment by xyxiao001** [comment]
好的多谢提醒
