### ISSUE TITLE
Deleting images doesn't clear input 

### ISSUE THREAD

**Issue by sytheveenje** [xyxiao001/vue-cropper#363]
Hi,

I'm sorry if this question is already asked before, most issues are in Chinese and I can't read that..

When I upload an image and then delete the image (from my cropper), than apparently the input is still filled with the image. When I upload the same image again, my browser does nothing. I can't find a way to clear the input.

Does someone has the same issue? Is there a solution?

**Comment by chenhu2077** [comment]
1、是input的重复上传问题 

<input type="file" id="uploads" style="position:absolute; clip:rect(0 0 0 0);" accept="image/png, image/jpeg, image/gif, image/jpg" @change="uploadImg($event,1)">
...

uploadImg(e){
  ...
  e.target.value = '';
}

2、清除图片
他有非空判断，随便传一个string就行了
this.$set(this.option,'img',"-1")

**Comment by sytheveenje** [comment]
Thanks for your answer.  I tried this, but it doesn't work.

```
uploadImg(e) {
    e.target.value = '';
},

remove() {
    this.$refs.cropper.clearCrop();
}
```

**Comment by chenhu2077** [comment]
uploadImg 看不出来有什么问题。remove() {     this.$set(this.option,'img',"-1") }remove 这样写你试试I hope it helps.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sythe Veenje"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 下午4:35
收件人:&nbsp;"xyxiao001/vue-cropper"<vue-cropper@noreply.github.com&gt;;
抄送:&nbsp;"小虎"<1158590650@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xyxiao001/vue-cropper] Deleting images doesn't clear input  (#363)




Thanks for your answer.  I tried this, but it doesn't work.
 uploadImg(e) {     e.target.value = ''; }, remove() {     this.$refs.cropper.clearCrop(); }

**Comment by xyxiao001** [comment]
You can set props img = '', a space to clear the screenshot box

**Comment by xyxiao001** [comment]
After the input is uploaded, clear the input box，
