### ISSUE TITLE
关于 URL.createObjectURL 可能导致的内存泄露的问题

### ISSUE THREAD

**Issue by wxlzmt** [xyxiao001/vue-cropper#367]
关于 URL.createObjectURL 可能导致的内存泄露的问题

### 缘由

> 使用 `URL.createObjectURL` 创建的对象示例: `"blob:http://192.168.8.81:1888/762a0cb0-a17b-4cf7-86ba-edfaa93491b3"` ,可作为URL直接在浏览器访问, 创建之后一直保持在内存中,直到`body`重载或者页面关闭后销毁, 或者调用`URL.revokeObjectURL()`手动清理

> 另外(chrome下): `typeof URL.createObjectURL(file) ==='string'` , 多次调用 `URL.revokeObjectURL()`不报错.

### 建议1 (针对组件源码) --不建议

在`refresh()`内,执行`this.imgs = "";`之前,添加代码`URL.revokeObjectURL(this.imgs);`,对内存进行清理释放.    

详细如下:    
```
refresh() {
   // console.log('refresh')
   let img = this.img;
   
   if(this.imgs){
       URL.revokeObjectURL(blob);
   }
   this.imgs = "";
   
   //后续略
}
```

**警告:** 该方式会导致调用`refresh()`之后,先前调用`getCropBlob()`获取到的`blob`失效.

`imgs`是`checkOrientationImage`诞生的产物,它是由`URL.createObjectURL`产生的.
```
watch: {
    // 如果图片改变， 重新布局
    img() {
      // 当传入图片时, 读取图片信息同时展示
      this.checkedImg();
    },
}
//imgs: "blob:http://192.168.8.81:1888/1b2bf5b4-903d-4658-b853-1e690d3859a9"
```

```
canvas.toBlob(
    blob => {
      let data = URL.createObjectURL(blob);
      this.imgs = data;
    },
    "image/" + this.outputType,
    1
    );
```

### 建议2 (针对组件使用者,不改变源码的情况下控制内存泄露)  !优!

使用 `getCropBlob` 的开发人员在回调方法中,处理完自身业务之后,及时清理回调方法中的入参`blob`, 
从源码`/src/vue-cropper.vue`可以看到每次调用`getCropBlob`都将执行`URL.createObjectURL(blob);`创建`ObjectURL`.

```
<vueCropper ref="cropper" 其它属性略 />

export default {
    methods:{
        cleanMemory() {//createObjectURL 产生的内容只有在 document unload 才会被自动清理, 所以需要手动清理内存
            try {
              if (this.$refs.cropper) {
                if (this.$refs.cropper.img && this.$refs.cropper.img.startsWith("blob:")) {
                  URL.revokeObjectURL(this.$refs.cropper.img);
                }
                if (this.$refs.cropper.imgs && this.$refs.cropper.imgs.startsWith("blob:")) {
                  URL.revokeObjectURL(this.$refs.cropper.imgs);
                }
              }
            } catch (e) {
              console.error(e);
            }
        }
    },
    created() {
      this.$once("hook:beforeDestroy", () => {
        this.cleanMemory();
      });
    }
}
```
考虑到每次调用 `this.$refs.cropper.getCropBlob` 都会覆盖 `this.imgs`, 所以需要获取到裁剪内容之后及时自行清理
```
this.$refs.cropper.getCropBlob((blob) => {

//TODO 业务处理

//最后清理内存
URL.revokeObjectURL(blob);
});
```

---

在 vue单页面 应用中, 用户可能很久都不会关闭标签页或者刷新网页, 所以控制内存泄露很重要.

**Comment by xyxiao001** [comment]
好的，多谢指出， 目前重构的过程中，已经考虑到了这个问题，后续会更新上去的。

**Comment by wxlzmt** [comment]
我仔细想了想在组件内自动 `revokeObjectURL` 不太合适, 有可能组件调用者获取到的`blob`还在使用中.

**建议**    
在组件内部创建一个数组, 每次`createObjectURL`的时候都`push`一下实例进入数组,  对外提供清理内存的方法, 组件调用者在自己觉得适当的时候调用, 清理数组中的所有`blob`, 如果调用者对此并不在意,则可以不用管内存的事情.

**Comment by xyxiao001** [comment]
可以看看next分支，目前的做法是，切换图片时，清除上一个createObjectURL

**Comment by xyxiao001** [comment]
小版本  0.5版本已经修复

**Comment by yoghurtxu** [comment]
m

**Comment by Rabbitzzc** [comment]
建议统一所有的 Blob URL，在合适的时机统一清除 revoke
