### ISSUE TITLE
图片跨域问题，使用了在线例子测试还是存在跨域

### ISSUE THREAD

**Issue by SuperRun** [xyxiao001/vue-cropper#368]

**Comment by SuperRun** [comment]
服务器已经配置了跨域

**Comment by xyxiao001** [comment]
没配置好吧

**Comment by SuperRun** [comment]
![微信图片_20191218102323](https://user-images.githubusercontent.com/28804901/71050595-98203700-2180-11ea-9e2e-d1d32f4a8144.png)
这是访问服务图片的请求，响应带了Access-Control-Allow-Origin

**Comment by SuperRun** [comment]
![微信图片_20191218102323](https://user-images.githubusercontent.com/28804901/71050661-c00f9a80-2180-11ea-89c1-e4163519fb75.png)

**Comment by xyxiao001** [comment]
因为只有 canvas 才会出现图片的跨域， 建议自己测试下

**Comment by SuperRun** [comment]
![20191218102323](https://user-images.githubusercontent.com/28804901/71050695-d87fb500-2180-11ea-9b1f-5641d108c84a.png)
