### ISSUE TITLE
xyxiao001您好，我这边截图以后为什么图片变大了很多呢，从1M变到了9.4M？

### ISSUE THREAD

**Issue by sunhao0313** [xyxiao001/vue-cropper#369]
xyxiao001您好，我这边截图以后为什么图片变大了很多呢，从1M变到了9.4M？
` <vue-cropper
                    :auto-crop="true"
                    :can-move="false"
                    :canScale="false"
                    :centerBox="true"
                    :enlarge="1"
                    :fixed="true"
                    :fixed-number="fixedNumber"
                    :img="cropperImageSrcOrBase64"
                    :info="true"
                    :info-true="true"
                    :output-size="1"
                    :style="'width: '+cropperWidth+'px;height:'+cropperHeight+'px'"
                    @imgLoad="imgLoad"
                    mode="contain"
                    output-type="jpeg"
                    ref="cropper"
            ></vue-cropper>`

**Comment by xyxiao001** [comment]
是不是对图片进行放大了，这样图片会变大的

**Comment by sunhao0313** [comment]
是的，我动态的修改了enlarge，具体代码我整理好发在下面，谢谢回复

发件人: goodboy [mailto:notifications@github.com]
发送时间: 2019年12月18日 16:30
收件人: xyxiao001/vue-cropper
抄送: 孙浩; Author
主题: Re: [xyxiao001/vue-cropper] xyxiao001您好，我这边截图以后为什么图片变大了很多呢，从1M变到了9.4M？ (#369)


是不是对图片进行放大了，这样图片会变大的

**Comment by xyxiao001** [comment]
是的

**Comment by xyxiao001** [comment]
如果觉得太大了 ， 可以采用第三方进行压缩下
