### ISSUE TITLE
裁剪后可生成不同size的图片吗？像这个图片中的这样

### ISSUE THREAD

**Issue by startblingbling** [xyxiao001/vue-cropper#374]
<img width="580" alt="WeChat56c6c5904bc1d61ede3ff55b86dea7be" src="https://img.sucaihuo.com/jquery/0/29/big.jpg">

**Comment by xyxiao001** [comment]
你展示的时候， 通过文档描述的方式去显示不同尺寸，
最后输出时，你可以生成一张大图 然后通过 canvas 去转成你需要的不同尺寸的图片
