### ISSUE TITLE
设置autoCropHeight不生效

### ISSUE THREAD

**Issue by 86driver** [xyxiao001/vue-cropper#375]
<vue-cropper
              ref="cropper"
              :info="false"
              :img="cutterImg"
              :output-size="option.size"
              :output-type="option.outputType"
              :full="option.full"
              :fixed="fixed"
              :can-move="option.canMove"
              :can-move-box="option.canMoveBox"
              :fixed-box="option.fixedBox"
              :original="option.original"
              :auto-crop="option.autoCrop"
              :auto-crop-width="option.autoCropWidth"
              :auto-crop-height="option.autoCropHeight"
              :center-box="option.centerBox"
              :fixed-number="fixedNumber"
              :high="option.high"
              @real-time="realTime"
              mode="cover"
            ></vue-cropper>

  data() {
    return {
      cutterImg: '',
      fixed: true,
      fixedNumber: [160, 160],
      option: {
        size: 1,
        full: false,
        outputType: 'png',
        canMove: true,
        fixedBox: true,
        original: true,
        canMoveBox: false,
        autoCrop: true,
        centerBox: true,
        high: true,
        autoCropWidth: 160,
        autoCropHeight: 160,
      },
    }
  },

 初始化之后展示的截图框大小为75*75

**Comment by 86driver** [comment]
已解决

**Comment by xyxiao001** [comment]
fixedNumber 会有冲突
