### ISSUE TITLE
About imgAxis() and cropAxis() calculations

### ISSUE THREAD

**Issue by Abdulsametileri** [xyxiao001/vue-cropper#386]
Hello, First of all thank you for this great component! 

Now, I have a problem.  I have some documents. Users crop the part of image whenever they want.  For example I want to crop this area as shown below.

![g1](https://user-images.githubusercontent.com/19360039/74340760-973e0700-4db7-11ea-8cba-5a8bfcfae315.png)

I have to draw this newly cropped area on the **another page** using html canvas. I get x1, y1, cropH, cropW of the cropped area **according to image container** and I draw a red rectangle **on the original image**.

![g2](https://user-images.githubusercontent.com/19360039/74341079-2d722d00-4db8-11ea-856a-2a39a7a680cc.png)

Look carefully, some deviation is here. I dont know why behave like that. 

This is my calculation for the cropped area

```
const imgAxis = this.$refs.cropper.getImgAxis()
const cropAxis = this.$refs.cropper.getCropAxis()

x1: cropAxis.x1 - imgAxis.x1,
y1: cropAxis.y1 - imgAxis.y1,
cropW: this.$refs.cropper.cropW,
cropH: this.$refs.cropper.cropH,
scale: this.$refs.cropper.scale
And I post this data.
```
![cal](https://user-images.githubusercontent.com/19360039/74351129-c0ff2a00-4dc7-11ea-9c3a-18b42f8f685b.jpg)

--------

```
I draw original image with the scaled value. 
const c = this.$refs.myCanvas;
let ctx = c.getContext("2d");
const image = document.getElementById('img');
const val = ss.val() (scale comes from my postted data above.)
ctx.scale(val.scale, val.scale)
ctx.drawImage(image, 0,0)

```

----------

```
I draw a red rectangle as follow
const c = this.$refs.dikdortgenCanvas;
let ctx = c.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = "red";
val = comes from service.  (Same values my posted data, I sure)
const canvas = {
        x: val.x1,
        y: val.y1,
        framew: val.cropW,
        frameh: val.cropH
}
ctx.rect(canvas.x, canvas.y, canvas.framew, canvas.frameh);
ctx.stroke();
```
![res](https://user-images.githubusercontent.com/19360039/74351202-dd9b6200-4dc7-11ea-919f-51409b166dcd.jpg)

This is my template
```
 <div>
        <canvas ref="myCanvas" id="myCanvas" width="2000" height="1257" style="position: absolute; border:1px solid #d3d3d3;">
        </canvas>

        <canvas ref="dikdortgenCanvas" style="position: absolute; z-index:99;" width="2000" height="1257">

        </canvas>

        <img style="display: none;" id="img" ref="img"  :src="img" alt="">
    </div>
```

Why is behavior like that? Why is deviation happened? What is my mistake? @xyxiao001

**Comment by xyxiao001** [comment]
Do you want to draw the  box on the canvas again？

**Comment by Abdulsametileri** [comment]
Yes. Absolutely

**Comment by xyxiao001** [comment]
Wait for me to write an example test

**Comment by xyxiao001** [comment]
https://jsbin.com/cukogapafi/edit?js,console,output

you can see that

**Comment by xyxiao001** [comment]
` drawCanvas () {
          // get img size
          let img = new Image();
          img.onload = () => {
            const scale = this.$refs.cropper.scale.toFixed(5)
//             console.log(scale)
            const imgAxis = {
              x: this.$refs.cropper.getImgAxis().x1,
              y: this.$refs.cropper.getImgAxis().y1
            }
            const width = this.$refs.cropper.trueWidth
            const height = this.$refs.cropper.trueHeight
            const canvas = this.$refs.canvas
            const ctx = canvas.getContext('2d')
            canvas.width = 200
            canvas.height = 200
            // draw img
            ctx.drawImage(img, imgAxis.x, imgAxis.y, width * scale, height * scale);
            // draw  box
            const cropAxis = {
              x: this.$refs.cropper.getCropAxis().x1,
              y: this.$refs.cropper.getCropAxis().y1
            }
            ctx.beginPath()
            ctx.strokeStyle = 'red'
            ctx.rect(cropAxis.x, cropAxis.y, this.$refs.cropper.cropW, this.$refs.cropper.cropH)
            ctx.stroke()
//             console.log(cropAxis)
          }
          img.src = this.option.img
          
        },`

**Comment by xyxiao001** [comment]
`
 drawCanvas () {
          // get img size
          let img = new Image();
          img.onload = () => {
            const scale = this.$refs.cropper.scale.toFixed(5)
//             console.log(scale)
            const imgAxis = {
              x: this.$refs.cropper.getImgAxis().x1,
              y: this.$refs.cropper.getImgAxis().y1
            }
            const width = this.$refs.cropper.trueWidth
            const height = this.$refs.cropper.trueHeight
            const canvas = this.$refs.canvas
            const ctx = canvas.getContext('2d')
            canvas.width = 200
            canvas.height = 200
            // draw img
            ctx.drawImage(img, imgAxis.x, imgAxis.y, width * scale, height * scale);
            // draw  box
            const cropAxis = {
              x: this.$refs.cropper.getCropAxis().x1,
              y: this.$refs.cropper.getCropAxis().y1
            }
            ctx.beginPath()
            ctx.strokeStyle = 'red'
            ctx.rect(cropAxis.x, cropAxis.y, this.$refs.cropper.cropW, this.$refs.cropper.cropH)
            ctx.stroke()
//             console.log(cropAxis)
          }
          img.src = this.option.img
          
        },
`

**Comment by Abdulsametileri** [comment]
This is what I am looking for. Thanks you for your help. I am grateful to you.

**Comment by wantao666** [comment]
作者 @xyxiao001 我也遇到了类似的问题，我通过
```
let width = this.$refs.cropper.trueWidth * this.$refs.cropper.scale;
let height = this.$refs.cropper.trueHeight * this.$refs.cropper.scale;
```
拿到显示的图片的宽高。
通过
```
let cropAxis = this.$refs.cropper.getCropAxis();
let imgAxis = this.$refs.cropper.getImgAxis();
let cropWidth = this.$refs.cropper.cropW;
let cropHeight = this.$refs.cropper.cropH;
let position = [
        parseInt(cropAxis.x1 - imgAxis.x1, 10),
        parseInt(cropAxis.y1 - imgAxis.y1, 10),
        parseInt(cropWidth, 10),
        parseInt(cropHeight, 10)
      ];
```
拿到了截图框的位置和宽高。
然后将这些数据交给后端裁剪。但是发现总是向右下角偏移了，不知道为什么。
这个很急很重要。need help soon!!!

**Comment by xyxiao001** [comment]
https://jsbin.com/cukogapafi/edit?js,console,output

你可以看看这个例子
