### ISSUE TITLE
横向图片旋转为纵向之后，图片不会自动缩放以符合 contain 渲染模式，导致在 canScale 为 false 时不能裁取图片上下被隐藏的区域

### ISSUE THREAD

**Issue by Riant** [xyxiao001/vue-cropper#389]
如题。

建议在旋转操作之后，按照 渲染模式配置 重新对图片进行缩放计算、渲染。

谢谢。

**Comment by xyxiao001** [comment]
mode仅对首次渲染生效，后续操作不进行处理

**Comment by xyxiao001** [comment]
mode仅对首次渲染生效，后续操作不进行处理

**Comment by Riant** [comment]
旋转之后，宽高信息也没有对调，导致外部尝试手动计算并调用 changeScale 来进行缩放也做不到。

那岂不是意味着这个问题无解了？
