### ISSUE TITLE
cors error not fix yet

### ISSUE THREAD

**Issue by phoenix-Force** [xyxiao001/vue-cropper#391]
i cannot give the url which is in the s3 bucket..its showing cors error

**Comment by xyxiao001** [comment]
cros requires backend or server configuration to support

**Comment by phoenix-Force** [comment]
i have tried this too but some of those picture are still showing cors error and some of them are not .. but one thing to notice that all of those picture are showing in the canvas..

**Comment by xyxiao001** [comment]
cros need  backend support

**Comment by busing** [comment]
我碰到一样的问题了，确实有这个现象，aws的s3 已经配置跨域，其他的image显示都没有问题，但是打开vue-cropper 的时候会报跨域错误
