### ISSUE TITLE
使用过程中图片变小情况发生

### ISSUE THREAD

**Issue by eliayng** [xyxiao001/vue-cropper#394]
![image](https://user-images.githubusercontent.com/7861398/75597706-f4cd9580-5ad1-11ea-87d2-6076915f0124.png)
以下是默认传入参数：
option: {
          previews:{},
          img: '', // 裁剪图片的地址
          info: true, // 裁剪框的大小信息
          outputSize: 1, // 裁剪生成图片的质量
          outputType: 'png', // 裁剪生成图片的格式
          canScale: true, // 图片是否允许滚轮缩放
          autoCrop: true, // 是否默认生成截图框
          autoCropWidth: 200, // 默认生成截图框宽度
          autoCropHeight: 200, // 默认生成截图框高度
          fixedBox: true, // 固定截图框大小
          full: true, // 是否输出原图比例的截图
          enlarge: 2,
          canMoveBox: true, // 截图框能否拖动
          original: false, // 上传图片按照原始比例渲染
          centerBox: false, // 截图框是否被限制在图片里面
          infoTrue: false // true 为展示真实输出图片宽高 false 展示看到的截图框宽高
        },

`<div v-if="clipboard" class="modal fade clipboards" :id="'avatar-modal'+id" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" action="crop.php" enctype="multipart/form-data" method="post">
            <div class="modal-header">
              <button class="close" data-dismiss="modal" type="button">&times;</button>
              <h4 class="modal-title" id="avatar-modal-label">
                图片裁剪<i style="font-size: 14px;margin-left: 5px;font-weight: 300;" >限制图片大小为{{option.autoCropWidth}}px*{{option.autoCropHeight}}px</i>
              </h4>
            </div>
            <div class="modal-body">
              <div class="vue-cropper-box">
                <div class="vue-cropper-content row">
                  <div class="col-sm-12 col-md-7" >
                    <vueCropper
                        ref="cropper"
                        :img="option.img"
                        :outputSize="option.size"
                        :outputType="option.outputType"
                        :info="true"
                        :full="option.full"
                        :canMove="option.canMove"
                        :canMoveBox="option.canMoveBox"
                        :fixedBox="option.fixedBox"
                        :original="option.original"
                        :autoCrop="option.autoCrop"
                        :autoCropWidth="option.autoCropWidth"
                        :autoCropHeight="option.autoCropHeight"
                        :centerBox="option.centerBox"
                        :high="option.high"
                        :infoTrue="option.infoTrue"
                        @realTime="realTime"
                        @imgLoad="imgLoad"
                        :enlarge="option.enlarge"
                    />
                  </div>
                  <div class="col-sm-12 col-md-5" >
1
                  </div>
                </div>
                <div class="operate-wrap">
                  <div class="lf">
                    <zxwBtn :name="'左旋转'" :type="'anticlockwise'" @click="turnLeft" ></zxwBtn>
                    <zxwBtn :name="'右旋转'" :type="'rightrotation'" @click="turnRight" ></zxwBtn>
                    <zxwBtn :name="'放大'" :type="'magnify'" @click="changeScale(1)" ></zxwBtn>
                    <zxwBtn :name="'缩小'" :type="'shrink'" @click="changeScale(-1)" ></zxwBtn>
                    <zxwBtn :name="'上传'" :type="'confirm'" @click="onCubeImg" ></zxwBtn>
                  </div>
                  <div class="rt">
                    <zxwBtn :name="'取消截图'" :type="'cancelCrop'" @click="cancleCropper" ></zxwBtn>
                  </div>
                </div>
              </div>
            </div>
            
          </form>
        </div>
      </div>
    </div>`

**Comment by eliayng** [comment]
<div v-if="clipboard" class="modal fade clipboards" :id="'avatar-modal'+id" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" action="crop.php" enctype="multipart/form-data" method="post">
            <div class="modal-header">
              <button class="close" data-dismiss="modal" type="button">&times;</button>
              <h4 class="modal-title" id="avatar-modal-label">
                图片裁剪<i style="font-size: 14px;margin-left: 5px;font-weight: 300;" >限制图片大小为{{option.autoCropWidth}}px*{{option.autoCropHeight}}px</i>
              </h4>
            </div>
            <div class="modal-body">
              <div class="vue-cropper-box">
                <div class="vue-cropper-content row">
                  <div class="col-sm-12 col-md-7" >
                    <vueCropper
                        ref="cropper"
                        :img="option.img"
                        :outputSize="option.size"
                        :outputType="option.outputType"
                        :info="true"
                        :full="option.full"
                        :canMove="option.canMove"
                        :canMoveBox="option.canMoveBox"
                        :fixedBox="option.fixedBox"
                        :original="option.original"
                        :autoCrop="option.autoCrop"
                        :autoCropWidth="option.autoCropWidth"
                        :autoCropHeight="option.autoCropHeight"
                        :centerBox="option.centerBox"
                        :high="option.high"
                        :infoTrue="option.infoTrue"
                        @realTime="realTime"
                        @imgLoad="imgLoad"
                        :enlarge="option.enlarge"
                    />
                  </div>
                  <div class="col-sm-12 col-md-5" >
1
                  </div>
                </div>
                <div class="operate-wrap">
                  <div class="lf">
                    <zxwBtn :name="'左旋转'" :type="'anticlockwise'" @click="turnLeft" ></zxwBtn>
                    <zxwBtn :name="'右旋转'" :type="'rightrotation'" @click="turnRight" ></zxwBtn>
                    <zxwBtn :name="'放大'" :type="'magnify'" @click="changeScale(1)" ></zxwBtn>
                    <zxwBtn :name="'缩小'" :type="'shrink'" @click="changeScale(-1)" ></zxwBtn>
                    <zxwBtn :name="'上传'" :type="'confirm'" @click="onCubeImg" ></zxwBtn>
                  </div>
                  <div class="rt">
                    <zxwBtn :name="'取消截图'" :type="'cancelCrop'" @click="cancleCropper" ></zxwBtn>
                  </div>
                </div>
              </div>
            </div>
            
          </form>
        </div>
      </div>
    </div>

**Comment by eliayng** [comment]
<div v-if="clipboard" class="modal fade clipboards" :id="'avatar-modal'+id" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <form class="avatar-form" action="crop.php" enctype="multipart/form-data" method="post">
            <div class="modal-header">
              <button class="close" data-dismiss="modal" type="button">&times;</button>
              <h4 class="modal-title" id="avatar-modal-label">
                图片裁剪<i style="font-size: 14px;margin-left: 5px;font-weight: 300;" >限制图片大小为{{option.autoCropWidth}}px*{{option.autoCropHeight}}px</i>
              </h4>
            </div>
            <div class="modal-body">
              <div class="vue-cropper-box">
                <div class="vue-cropper-content row">
                  <div class="col-sm-12 col-md-7" >
                    <vueCropper
                        ref="cropper"
                        :img="option.img"
                        :outputSize="option.size"
                        :outputType="option.outputType"
                        :info="true"
                        :full="option.full"
                        :canMove="option.canMove"
                        :canMoveBox="option.canMoveBox"
                        :fixedBox="option.fixedBox"
                        :original="option.original"
                        :autoCrop="option.autoCrop"
                        :autoCropWidth="option.autoCropWidth"
                        :autoCropHeight="option.autoCropHeight"
                        :centerBox="option.centerBox"
                        :high="option.high"
                        :infoTrue="option.infoTrue"
                        @realTime="realTime"
                        @imgLoad="imgLoad"
                        :enlarge="option.enlarge"
                    />
                  </div>
                  <div class="col-sm-12 col-md-5" >
1
                  </div>
                </div>
                <div class="operate-wrap">
                  <div class="lf">
                    <zxwBtn :name="'左旋转'" :type="'anticlockwise'" @click="turnLeft" ></zxwBtn>
                    <zxwBtn :name="'右旋转'" :type="'rightrotation'" @click="turnRight" ></zxwBtn>
                    <zxwBtn :name="'放大'" :type="'magnify'" @click="changeScale(1)" ></zxwBtn>
                    <zxwBtn :name="'缩小'" :type="'shrink'" @click="changeScale(-1)" ></zxwBtn>
                    <zxwBtn :name="'上传'" :type="'confirm'" @click="onCubeImg" ></zxwBtn>
                  </div>
                  <div class="rt">
                    <zxwBtn :name="'取消截图'" :type="'cancelCrop'" @click="cancleCropper" ></zxwBtn>
                  </div>
                </div>
              </div>
            </div>
            
          </form>
        </div>
      </div>
    </div>

**Comment by eliayng** [comment]
已解决，延迟下等弹框出来后再设置图片信息，或手动调用下this.$refs.cropper.checkedImg();  不过还是希望能改进下。  作者很棒

**Comment by xyxiao001** [comment]
好的， 后续容器渲染大小会进行优化
