### ISSUE TITLE
谷歌浏览器更新到8.0新版本，在可裁剪区域使用鼠标滚轮进行放大缩小图片会报错下谷歌到8.0版本，在可裁剪区域用鼠标滚轮对图片进行放大或者缩小谷歌就会报错

### ISSUE THREAD

**Issue by liugen6688** [xyxiao001/vue-cropper#397]
我vue-cropper的版本是0.32
没有更新谷歌前没有这个问题，但是更新了下谷歌到8.0版本，在可裁剪区域用鼠标滚轮对图片进行放大或者缩小谷歌就会报错。
这个是谷歌报错的信息
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
changeSize @ index.js?619d:1

查了下是谷歌5.6版本以上就会有的问题。网上给出的两种解决方案
1、注册处理函数时，用如下方式，明确声明为不是被动的
window.addEventListener(‘touchmove’, func, { passive: false })
2、应用 CSS 属性 touch-action: none; 这样任何触摸事件都不会产生默认行为，但是 touch 事件照样触发。

试了都没有解决报错的问题

**Comment by xyxiao001** [comment]
你的版本是多少，更新下使用版本

**Comment by liugen6688** [comment]
> 你的版本是多少，更新下使用版本

感谢我的版本是0.32、很早的版本了。升级到5.0这个报错的问题解决了
