### ISSUE TITLE
您好，这个插件支持移动端么？另外getCropData()返回的是裁剪的信息，还是裁剪后的base64编码？

### ISSUE THREAD

**Issue by RoseEnd** [xyxiao001/vue-cropper#4]

**Comment by xyxiao001** [comment]
裁剪后的base64 编码 ，  移动端图片的缩放不支持手势。

**Comment by xyxiao001** [comment]
this.$refs.cropper.getCropDate((data) => {
  // do something
  console.log(data)  
})
get output img blob

this.$refs.cropper.getCropBlob((data) => {
  // do something
  console.log(data)  
})

一个是base64，  一个是blob文件

**Comment by xyxiao001** [comment]
这个版本的单词打错了 等下会修复成data

**Comment by RoseEnd** [comment]
好的

**Comment by RoseEnd** [comment]
这个不是自动上传吧，我想手动上传

**Comment by xyxiao001** [comment]
没有自动上传啊 我只是把截图数据返回给你了， 你可以手动上传

**Comment by RoseEnd** [comment]
好的，perfect

**Comment by RoseEnd** [comment]
另外适配移动端么

**Comment by xyxiao001** [comment]
移动端截图是可以得， 但是没有手势缩放背景图。 因为pc是滚轮缩放的。

**Comment by RoseEnd** [comment]
好的，我看看，找了好久的移动端图片裁剪的组件，之前用的vue-crop-image-upload移动端打包成android APP 之后没用，希望你这个能好吧
