### ISSUE TITLE
为什么不开放一个初始化的方法呢？？

### ISSUE THREAD

**Issue by aioros2016** [xyxiao001/vue-cropper#40]
很多时候希望图片加载完毕后，初始化组件。没有这个方法，很多事情都做不了了

**Comment by xyxiao001** [comment]
图片替换后 ，参数都会重置的

**Comment by aioros2016** [comment]
设置裁剪框默认宽高后，希望图片加载完毕后，重新初始化裁剪框宽高，这个要怎么做？我改了autoCropWidth也没有效果

**Comment by xyxiao001** [comment]
你是想手动修改裁剪框的宽度和高度吗

**Comment by aioros2016** [comment]
是啊，我也修改过this.$refs.cropper.cropW，但是因为默认裁剪框宽高的原因，位置渲染就不居中了。

**Comment by xyxiao001** [comment]
手动修改后肯定就不居中了， autoCropWidth 只有第一次渲染 才会生效

**Comment by aioros2016** [comment]
所以我才会希望能够开放一个初始化的方法，方便后续修改之后再渲染一遍

**Comment by xyxiao001** [comment]
好的， 下个版本我会加上的， 不过你直接设置autoCropWidth先用吧

**Comment by aioros2016** [comment]
好的，期待你的下个版本！

**Comment by aioros2016** [comment]
另外我看到你的实例中有rotateLeft效果，请问这个方法在API中没有出现，在哪里能够找到？还是自己用代码实现？

**Comment by xyxiao001** [comment]
this.$cropper.rotateRight() 向右边旋转90度

**Comment by xyxiao001** [comment]
this.$cropper.rotateRight() 向右边旋转90度
this.$cropper.rotateLeft() 向左边旋转90度

**Comment by aioros2016** [comment]
ok，谢谢！

**Comment by xyxiao001** [comment]
已在0.27版本加上 refresh
