### ISSUE TITLE
多页签裁剪问题

### ISSUE THREAD

**Issue by lghisfc** [xyxiao001/vue-cropper#400]
多页签裁剪时加载非当前页签图片尺寸不对，怎么处理？还有你们的QQ群怎么加不了呢？
![image](https://user-images.githubusercontent.com/18201422/76720610-3fa90780-6778-11ea-9e5c-c6f24c9d5052.png)

**Comment by xyxiao001** [comment]
不太理解你的问题， 群用手机加
