### ISSUE TITLE
如何重置或者销毁cropper

### ISSUE THREAD

**Issue by mcq-rgba** [xyxiao001/vue-cropper#408]
使用elementUI的dialog去加载vue-cropper组件，第一次打开dialog，截图展示都没有问题；关掉对话框，另选一条数据，此时打开dialog，组件里的图片大小就自动缩小了，当我把图片放大到需要的大小后，截图功能就出bug了，附上图片
![1](https://user-images.githubusercontent.com/63093457/78336154-7a58cf80-75c1-11ea-8bea-1708dc2c801a.png)，麻烦大佬给看下

**Comment by xyxiao001** [comment]
可以在弹框出来后，再去渲染组件

**Comment by mcq-rgba** [comment]
多谢大佬，已经处理好了
