### ISSUE TITLE
能否让大尺寸的图片按照原始尺寸初始化？

### ISSUE THREAD

**Issue by kenthigh** [xyxiao001/vue-cropper#41]
能否让大尺寸的图片按照原始尺寸初始？或者是50%放大倍数初始化。。

这里有个需求是，用户用手机对着桌子上的文件拍照，然后通过这个上传。部分用户不会去缩放，直接传上来了。原本手机拍出来一个1920X1080的图 变长了一个极小的图。所有的文字都看不清。所以 如果这个插件能实现，当用户选择了图片之后，展示给用户的是一张放大了的，用户就会自己去选择需要截图的位置。

**Comment by xyxiao001** [comment]
目前还没有这个方法， 我会在稍后的版本加上属性配置， 来实现这个方法

**Comment by xyxiao001** [comment]
已在0.27版本加上
