### ISSUE TITLE
Cropping an image with fixed ratio

### ISSUE THREAD

**Issue by netzfluencer** [xyxiao001/vue-cropper#410]
When using the cropper with setting up a fixed cropping ratio, some of the corners are only stretchable on the x-axis - this is a strange behaviour for user of the cropper. 

When disabling the the fixed property the cropping from the corners is working as intended?

Will this get fixed? Thank you!

**Comment by xyxiao001** [comment]
Because a fixed ratio can only change one value, then another value changes with the ratio. I will consider how to optimize

**Comment by netzfluencer** [comment]
thank you
