### ISSUE TITLE
一个页面上存在两个vueCropper标签时，赋值问题

### ISSUE THREAD

**Issue by 15301170766** [xyxiao001/vue-cropper#411]
我在移动端使用该插件（vue项目）
1.当我在一个页面上引用两次含有vueCropper的组件时，我对其中任何一个this.option.img赋值，它总是将数据渲染到最后一个vueCropper中去
2.我尝试对其使用不同的name以及ref,都没能成功

**Comment by xyxiao001** [comment]
贴一下代码看看

**Comment by 15301170766** [comment]
<div class="top_item">
            <SharePhotoTem></SharePhotoTem>
            <div
              class="top_item_title pop_color2"
              :class="{'selected':firstTitle!=='轻点选择','border_none':firstTitle!=='轻点选择'}"
              @click="chooseTitle(1)"
            >{{firstTitle}}</div>
          </div>
          <div class="top_item">
            <SharePhotoTem></SharePhotoTem>
            <div
              class="top_item_title pop_color2"
              :class="{'selected2':secondTitle!=='轻点选择','border_none':secondTitle!=='轻点选择'}"
              @click="chooseTitle(2)"
            >{{secondTitle}}</div>
          </div>
        </div>

**Comment by 15301170766** [comment]
<div class="top_group">
          <div class="top_item">
            <SharePhotoTem></SharePhotoTem>
            <div
              class="top_item_title pop_color2"
              :class="{'selected':firstTitle!=='轻点选择','border_none':firstTitle!=='轻点选择'}"
              @click="chooseTitle(1)"
            >{{firstTitle}}</div>
          </div>
          <div class="top_item">
            <SharePhotoTem></SharePhotoTem>
            <div
              class="top_item_title pop_color2"
              :class="{'selected2':secondTitle!=='轻点选择','border_none':secondTitle!=='轻点选择'}"
              @click="chooseTitle(2)"
            >{{secondTitle}}</div>
          </div>
        </div>

**Comment by 15301170766** [comment]
``` html
<div class="top_item">
            <SharePhotoTem></SharePhotoTem>
            <div
              class="top_item_title pop_color2"
              :class="{'selected':firstTitle!=='轻点选择','border_none':firstTitle!=='轻点选择'}"
              @click="chooseTitle(1)"
            >{{firstTitle}}</div>
          </div>
          <div class="top_item">
            <SharePhotoTem></SharePhotoTem>
            <div
              class="top_item_title pop_color2"
              :class="{'selected2':secondTitle!=='轻点选择','border_none':secondTitle!=='轻点选择'}"
              @click="chooseTitle(2)"
            >{{secondTitle}}</div>
          </div>
        </div>
```

**Comment by 15301170766** [comment]
```html
子组件
<vueCropper ref="cropper" :img="option.img"></vueCropper>
```

**Comment by xyxiao001** [comment]
你这个img是怎么传进去的

**Comment by xyxiao001** [comment]
那你这个要在上层就要做一下img的区分吧，加个key

**Comment by 15301170766** [comment]
我做了如下调整，还是未能成功
```html
父组件
<div class="top_group">
          <div class="top_item" ref="left_parent">
            <SharePhotoTem :keyId="'left'" key="left" ref="left"></SharePhotoTem>
          </div>
          <div class="top_item" ref="right_parent">
            <SharePhotoTem :keyId="'right'" key="right" ref="right"></SharePhotoTem>
          </div>
        </div>

子组件
    <vueCropper :key="keyId" :ref="'cropper'+keyId" :img="option.img"></vueCropper>
```

**Comment by xyxiao001** [comment]
加qq群吧，md上面有
