### ISSUE TITLE
`img` property: Is **Blob/File** really supported?

### ISSUE THREAD

**Issue by hoanvh** [xyxiao001/vue-cropper#412]
My code as below:
```
<VueCropper v-if="originalChangedAvatar" ref="avatarCropper" :img="originalChangedAvatar"></VueCropper>
<FileUploader v-else accept="image/*" @input="originalChangedAvatar = $event"></FileUploader>
```
**FileUploader** is a kind of wrapper for [Boostrap Form File](https://bootstrap-vue.js.org/docs/components/form-file/).
Above code is not work due to this check https://github.com/xyxiao001/vue-cropper/blob/master/src/vue-cropper.vue#L536
My question is: can I pass a **Blob**/**File** to `img` property? Or just **String** only?

**Comment by xyxiao001** [comment]
use  window.URL.createObjectURL Transform  blob

**Comment by hoanvh** [comment]
I see. So it means that we cannot pass a **Blob**/**File** as a parameter directly, but need to transform to a **String** URL instead.
Thanks for your instant feedback 🙇‍♂️
