### ISSUE TITLE
RangeError: offset is outside the bounds of the Dataview 

### ISSUE THREAD

**Issue by linglonghui** [xyxiao001/vue-cropper#419]
部分图片会报错：RangeError: offset is outside the bounds of the Dataview at DataView.getUint8 (<anonymous>)
![test](https://user-images.githubusercontent.com/46190593/81383548-c825a200-9142-11ea-8104-17c500d40635.jpg)

**Comment by git4coder** [comment]
解决办法：
把代码拉下来后修改 【vue-cropper/src/exif-js-min.js:107】 处的 【while (offset < length) {】为【while (offset + 1 < length) {】之后把 src 目录（里边有3个文件）整个复制到你自己的项目中，用法与之前相同(需要修改原型引入 vue-cropper 的路径)

**Comment by cplcurry3035** [comment]
> 

那这样子是不是不能使用npm方式了啊，用的类似jq的包的link形式？

**Comment by xyxiao001** [comment]
你们是用啥图片，可以提供下吗，我测试下报错

**Comment by xyxiao001** [comment]
https://github.com/xyxiao001/vue-cropper/issues/748

**Comment by cplcurry3035** [comment]
、

> 你们是用啥图片，可以提供下吗，我测试下报错



> 你们是用啥图片，可以提供下吗，我测试下报错

[](url)
