### ISSUE TITLE
有模式选择让图片完整显示出来吗

### ISSUE THREAD

**Issue by cuteCloud** [xyxiao001/vue-cropper#421]
因为图片宽度很长 没办法让用户一进来看到全图 现在需要不断滑动鼠标滚轮缩小图片 有办法使图片完整显示吗，并且使裁剪框宽高自动等于图片宽高，因为大部分用户是会原图裁剪

**Comment by xyxiao001** [comment]
mode: cover

**Comment by xyxiao001** [comment]
mode: cover
