### ISSUE TITLE
vue-cropper图片裁剪问题

### ISSUE THREAD

**Issue by wantao666** [xyxiao001/vue-cropper#423]
https://ask.csdn.net/questions/1071899

**Comment by xyxiao001** [comment]
没看懂描述， 可以加qq群的

**Comment by wantao666** [comment]
> 没看懂描述， 可以加qq群的

我想鼠标进入VueCropper(enter方法)，开始裁剪，点击裁剪按钮拿到裁剪后的图片。
但是我点击裁剪按钮后拿到的图片并没有裁剪过，是原图。
同时我发现如果是在鼠标离开VueCropper(leave方法)中拿到裁剪后的图片确实是被裁剪过的。
不知道为什么会这样

**Comment by xyxiao001** [comment]
因为裁剪有耗时，点击按钮可能还没裁剪完成吧
