### ISSUE TITLE
iphone手持设备拍摄带有orientation为6的照片（正着拍摄），cropper内部代码会再次操作orientation导致多余旋转

### ISSUE THREAD

**Issue by TomatoDroid** [xyxiao001/vue-cropper#427]
可以使用此照片在首页例子中稳定复现
https://situstatic.oss-cn-beijing.aliyuncs.com/miniprogram/miniDetection/WechatIMG2412.jpeg

**Comment by xyxiao001** [comment]
收到  新版 ios 确实会出问题，这个我去看看，预计周末修复

**Comment by xyxiao001** [comment]
0.53版本已修复

**Comment by linxner** [comment]
iPhone xs不会旋转但现在6跟6s会旋转了
