### ISSUE TITLE
为什么我的图片传不上去呢

### ISSUE THREAD

**Issue by yyccQQu** [xyxiao001/vue-cropper#43]
![image](https://user-images.githubusercontent.com/32674176/33510334-2791755c-d746-11e7-9ac4-176fa3a5d195.png)

**Comment by xyxiao001** [comment]
你怎么传的

**Comment by xyxiao001** [comment]
可以参考例子里面去做

**Comment by yyccQQu** [comment]
![image](https://user-images.githubusercontent.com/32674176/33510359-73624150-d746-11e7-97e3-9a0df7d3ec51.png)
我把你这里d的例子都粘贴下去 但是就上上面那种情况啊

**Comment by xyxiao001** [comment]
你看看你的prop img传过去没

**Comment by yyccQQu** [comment]
![image](https://user-images.githubusercontent.com/32674176/33510423-c6dcb3ec-d746-11e7-886e-eea25ce466e2.png)
这里的吗？

**Comment by yyccQQu** [comment]
![image](https://user-images.githubusercontent.com/32674176/33510433-e66062c2-d746-11e7-83ca-e1df190e0cfb.png)
这里就只能显示这一张

**Comment by xyxiao001** [comment]
是一张 按钮都是我写的测试方法，你要修改图片吗，需要自己写方法，传新的图片进去

**Comment by yyccQQu** [comment]
？？？？

**Comment by yyccQQu** [comment]
我要把本地图片传上去，然后裁剪

**Comment by yyccQQu** [comment]
最好还能多传几张图片上去，预览

**Comment by xyxiao001** [comment]
可以啊 我例子里面有提供本地上传的例子，

**Comment by yyccQQu** [comment]
![Uploading G]~EBYK0ANGL3E$~V(1X9$J.png…]()


就是这个UPload 我这儿要不得啊

**Comment by yyccQQu** [comment]
就是那个upload的列子，我这儿就是要不得啊

**Comment by xyxiao001** [comment]
组件接受一个img url 就可以了，你上传后你把img传过去就行

**Comment by yyccQQu** [comment]
:url="option.img.url" ？？

**Comment by xyxiao001** [comment]
prop img

**Comment by xyxiao001** [comment]
img	裁剪图片的地址	空	url 地址 || base64 || blob

**Comment by xyxiao001** [comment]
看文档的

**Comment by yyccQQu** [comment]
![image](https://user-images.githubusercontent.com/32674176/33510626-29c4b598-d749-11e7-8efe-e74e9d42b054.png)
？？

**Comment by yyccQQu** [comment]
![image](https://user-images.githubusercontent.com/32674176/33510630-4da4d0ba-d749-11e7-9933-c112f9ed6daf.png)
![image](https://user-images.githubusercontent.com/32674176/33510633-5a22a63c-d749-11e7-8bc0-720ccf8be0ac.png)

**Comment by xyxiao001** [comment]
我是说组件接收img  就可以了，你可以自己写上传方法，我也可以参考我的
