### ISSUE TITLE
拖拽引起的报错Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by ningploy** [xyxiao001/vue-cropper#430]
大佬处理下吧 全是error看得难受
另外 0.5.3 的log输出关掉吧
第一次提问题 如有不当 请多包涵

**Comment by xyxiao001** [comment]
0.54 移除了 log。你说的这个preventDefault inside passive 报错怎么复现

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/
我看例子是没有这个错误
