### ISSUE TITLE
赋值 img 后，图片变得很小，也无法交互， 请问这个是啥原因？

### ISSUE THREAD

**Issue by ChenRiliang** [xyxiao001/vue-cropper#434]
![image](https://user-images.githubusercontent.com/30994257/84000653-a153c900-a997-11ea-91dc-47113a7f6447.png)

**Comment by xyxiao001** [comment]
如果弹框，需要等弹框渲染完成后，再去渲染组件，不然组件宽高初始化会失败

**Comment by ChenRiliang** [comment]
> 如果弹框，需要等弹框渲染完成后，再去渲染组件，不然组件宽高初始化会失败

原来， 感谢， 可以了
