### ISSUE TITLE
第一次成功使用后点击第二次裁剪无法使用

### ISSUE THREAD

**Issue by lyJava** [xyxiao001/vue-cropper#440]
在element dialog中使用的时候出现。具体就跟这个上面说的情形一样
https://blog.csdn.net/qq_39234840/article/details/92806946。

**Comment by xyxiao001** [comment]
动态渲染插件，等弹框出来后再去加载插件 这是因为插件宽高获取失败了

**Comment by lyJava** [comment]
我每次上传成功都调用了this.$refs.cropper.clearCrop();但是这个貌似不生效。每次都是需要刷新当前tab页或者刷新整个页面，再次点击图片，裁剪功能才正常。具体表现在这个网址：
https://gitee.com/y_project/RuoYi-Vue/issues/I1L81Z
具体的代码在这：
https://gitee.com/y_project/RuoYi-Vue/blob/master/ruoyi-ui/src/views/system/user/profile/userAvatar.vue

**Comment by xyxiao001** [comment]
动态渲染插件，等弹框出来后再去加载插件 这是因为插件宽高获取失败

**Comment by xyxiao001** [comment]
绑定弹框出来之后事件  v-if vue-cropper
![image](https://user-images.githubusercontent.com/15681693/85218329-e6caba00-b3cb-11ea-94ed-9021daaf3f74.png)

**Comment by lyJava** [comment]
哈，非常感谢，问题已经解决了。感谢大佬百忙之中给我回复。
