### ISSUE TITLE
Safair和google浏览器正着拍的图片预览的时候逆时针旋转了90度（安卓和IOS都有），但是在微信浏览器正常

### ISSUE THREAD

**Issue by xiaoqizhu** [xyxiao001/vue-cropper#443]

**Comment by xiaoqizhu** [comment]
之前都是OK的，，最近突然出现这个问题

**Comment by xyxiao001** [comment]
因为chrome新版本 和 ios13.以上修复了图片本身旋转的 bug，所以和组件有冲突了，这个我会尽快解决

**Comment by xiaoqizhu** [comment]
> 因为chrome新版本和ios13。以上修复了图片本身旋转的bug，所以和组件有冲突了，这个我会尽快解决

好的，麻烦了，修复了扣我一下
