### ISSUE TITLE
无法显示格子背景，只能显示图片。

### ISSUE THREAD

**Issue by narutooturan** [xyxiao001/vue-cropper#444]
无法显示格子背景，只能显示图片。
在elementui dialog和普通组件中都试过，偶尔会出现一次格子背景，刷新后又消失了。
试过动态组件还是失败。

**Comment by xyxiao001** [comment]
格子背景是css 你看看是不是被覆盖了

**Comment by narutooturan** [comment]
> 格子背景是css 你看看是不是被覆盖了

不是的 我看 cropper-crop-box div 上的 style width height 都是 0 px
而且有些时候是会出现的 刷新就没了 感觉是宽高始终没获取成功

**Comment by narutooturan** [comment]
而且getCropBlob方法获取到的data是null

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/wxwKGz
参考例子

**Comment by narutooturan** [comment]
@xyxiao001 就是参考例子做的 
main.js 中 import vuecropper 然后 vue.use(cropper)
然后在vue文件中使用vue-cropper 外面包裹一层 div 设置固定大小

格子背景偶尔出现一次 会出现两张图片 整个功能都无法使用
放到弹窗里动态组件直接不显示了

想问下要么能否在某个位置我手动重新加载下组件？

**Comment by xyxiao001** [comment]
你可以等弹框出来 然后再去加载组件

**Comment by narutooturan** [comment]
@xyxiao001 我用了 <component /> 在弹框@opened事件中设置了 :is="" 的值 是这样做的吧？

**Comment by xyxiao001** [comment]
你也可以上手动重新加载  this.$refs.cropper.refresh()

**Comment by narutooturan** [comment]
@xyxiao001 还是不行
我在 el-dialog opened事件里 加入了 settimeout ，5秒后refresh，再设置图片，功能还是有问题的，跟以前一样。

**Comment by xyxiao001** [comment]
不放弹框也不能用吗

**Comment by xyxiao001** [comment]
你说的不能用 是什意思  功能不完全， 还是截图框没出来

**Comment by narutooturan** [comment]
@xyxiao001 
截图框完全没出来 无法获取宽高 都是0*0
不放弹框也不行

**Comment by xyxiao001** [comment]
可以提供复现bug例子吗

**Comment by narutooturan** [comment]
@xyxiao001 在内网没法提供 我换个版本再看看吧
