### ISSUE TITLE
【移动端】高亮图与后面真实图位置出现偏差

### ISSUE THREAD

**Issue by GoodLuck333** [xyxiao001/vue-cropper#45]
上传图片较小时不能放满容器，出现高亮图向右偏差。能否解决或将图片铺满全屏，谢谢！

**Comment by xyxiao001** [comment]
目前小图是显示原图 不会拉伸 ， 偏差问题能截图看看嘛 还有机型

**Comment by GoodLuck333** [comment]
在电脑上测的偏差，手机上的照片会自动将小图宽设置成屏幕宽。较小机率出现这类问题吧。能设置成拉伸效果么，以高度在可选区最大值，宽按高宽比算。能设置图片禁止滑动么？

**Comment by xyxiao001** [comment]
目前还没有这个功能   会在后续加上属性配置的

**Comment by GoodLuck333** [comment]
![img01](https://user-images.githubusercontent.com/26056426/33818340-42646048-de7f-11e7-9a18-b0f0eeb9186b.png)

滑选区域 > 小图宽

![img0](https://user-images.githubusercontent.com/26056426/33818324-1c4bf51a-de7f-11e7-8d1b-1df6dd55f155.png)

滑选区域 <= 小图宽

**Comment by xyxiao001** [comment]
我的在线例子会出现这个问题嘛

**Comment by GoodLuck333** [comment]
在线例子上是没问题的

**Comment by xyxiao001** [comment]
那应该是样式冲突了 影响了截图的样式

**Comment by GoodLuck333** [comment]
好吧，我再看看
