### ISSUE TITLE
截图框的宽高和真实输出图片的宽高不一致怎么办

### ISSUE THREAD

**Issue by fh332393900** [xyxiao001/vue-cropper#451]

**Comment by xyxiao001** [comment]
elarge 和  high full 都会改变输出图片的大小
可以设置infoTrue 来控制截图框宽高显示为实际输出大小

**Comment by fh332393900** [comment]
> elarge 和 high full 都会改变输出图片的大小
> 可以设置infoTrue 来控制截图框宽高显示为实际输出大小

嗯已经解决了，把high等于false就可以了
