### ISSUE TITLE
大佬，ios系统小于13.5的有没有维护呢

### ISSUE THREAD

**Issue by Pollylpl** [xyxiao001/vue-cropper#455]
现在有这么一种情况，就是用了最新版本的插件之后大部分苹果手机拍照正常展示了，但是系统版本低于13.5的依旧是照片旋转90度，有没有遇到这种情况啊

**Comment by xyxiao001** [comment]
这个13.5 以下 ios 旋转的问题  下个版本会修复

**Comment by Pollylpl** [comment]
下个版本大约啥时候

**Comment by xyxiao001** [comment]
0.55 版本已经发布 更新下
