### ISSUE TITLE
如果容器不够大，裁剪的对象可不可以是原图而不是缩放后的图片

### ISSUE THREAD

**Issue by wangshantao** [xyxiao001/vue-cropper#456]
比如我要裁剪一个1000 * 1000的图得到一个750 * 650的图片，我外部的容器只有500 * 400，这样自动生成的裁剪框大概只有400多 * 300多，裁剪出来的图片也就是裁剪框的大小，我使用了enlarge放大到750 * 650，但是enlarge只能放大图片，原来的清晰度已经丢失。
就是我希望的是裁剪的图片裁剪的图片按比例缩放，裁剪框也按比例缩放，裁剪是以原图作为操作，而不是缩放后的图片。

**Comment by xyxiao001** [comment]
Full

**Comment by xyxiao001** [comment]
Full属性可以根据原图比例输出图片

**Comment by wangshantao** [comment]
> Full属性可以根据原图比例输出图片

好的，这个参数基本可以解决我的问题了。我之前也用过这个参数，使用的是一张790 * 14975 的图片，使用的fixedNumber为[6,5]，截图后生成的图片大小为105 * 88 图片就明显失真了，不知道是不是长宽差太多导致比例算错了。在这个场景下能不能生成790 * 658（6:5的比例）的裁剪图片。

**Comment by xyxiao001** [comment]
maxImgSize 设置的大一点，不然会压缩的

**Comment by wangshantao** [comment]
maxImgSize 原先是2000，我改成了999999，还是会压缩

**Comment by xyxiao001** [comment]
更新下 0.55 版本试下

**Comment by wangshantao** [comment]
还是一样，这是那张图片
![O1CN01V1xlL71IOugOAH051_!!2616970884](https://user-images.githubusercontent.com/14883268/87616315-5cb20f00-c747-11ea-90b0-f489ad5fe76f.jpg)

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/87621964-9f2e1880-c754-11ea-860d-17eb5070a660.png)

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/ 
在线例子测试没问题

**Comment by wangshantao** [comment]
同事传prop写的是maxImgSize，其他的都是对的 就这个写错了，没注意看，很抱歉。

**Comment by wangshantao** [comment]
刚刚问了下他，他说是从https://codepen.io/xyxiao001/pen/wxwKGz复制的，看了下这里果然写错了。

**Comment by xyxiao001** [comment]
好 我去修改下
