### ISSUE TITLE
裁减图片完成之后偶现滚轮失效的 bug

### ISSUE THREAD

**Issue by GenesisLQ** [xyxiao001/vue-cropper#459]
选择图片裁减完成之后，偶尔会出现使用鼠标不能滚动页面的问题，初步排查应该是某个操作调用了 `preventDefault` 方法，但是组件销毁的时候没有移除，所以会导致这个问题，但是不太好复现，就没查出来是哪个地方出了问题，希望作者能看一下这个问题。

**Comment by xyxiao001** [comment]
如果你想去销毁组件前， 可以先调下 this.$refs.cropper.cancelScale()

**Comment by GenesisLQ** [comment]
谢谢，已经找到原因了，就是因为没有移除滚轮事件导致的一直阻止滚轮的默认事件

**Comment by xyxiao001** [comment]
![E9CB32CA641C91304E96AF3D061B192C](https://user-images.githubusercontent.com/15681693/87757133-b6e0cc00-c83c-11ea-8d84-1bc262474b1d.gif)

**Comment by Kento97** [comment]
> 
谢谢，虽然我看源码也基本看出来了（doge）
![](https://user-images.githubusercontent.com/15681693/87757133-b6e0cc00-c83c-11ea-8d84-1bc262474b1d.gif)

**Comment by SereinSillage** [comment]
请问是怎么解决的呢
