### ISSUE TITLE
截图框 无法高亮  没有加任何的css 

### ISSUE THREAD

**Issue by yuantu** [xyxiao001/vue-cropper#46]
![image](https://user-images.githubusercontent.com/12454813/33813183-3f9aa60a-de5d-11e7-9ea0-89d07a54b3d3.png)

**Comment by xyxiao001** [comment]
鼠标移到截图框 看看样式

**Comment by yuantu** [comment]
![image](https://user-images.githubusercontent.com/12454813/33813235-829c38a6-de5d-11e7-9c43-8040fa01173f.png)

**Comment by yuantu** [comment]
![image](https://user-images.githubusercontent.com/12454813/33813252-9c9e043c-de5d-11e7-90b4-4e960bd5a6fd.png)

**Comment by yuantu** [comment]
想问下 截图框 高亮 是什么原理    图片覆盖上去吗

**Comment by xyxiao001** [comment]
你添加一条css看看
.cropper-crop-box {
  z-index: 100
}

**Comment by yuantu** [comment]
![image](https://user-images.githubusercontent.com/12454813/33813329-e78091c2-de5d-11e7-9997-4485356b8e22.png)

**Comment by xyxiao001** [comment]
其实就是一个遮罩层 然后高亮的图片在遮罩上面  原图在下面

**Comment by yuantu** [comment]
老铁 不管用  愁死我了

**Comment by xyxiao001** [comment]
有没有在线的例子 我看看

**Comment by xyxiao001** [comment]
你看我在线的例子 是正常的嘛

**Comment by yuantu** [comment]
我发现了  是img 标签 添加 了全局的 max-width   删掉就好了   感谢老铁
![image](https://user-images.githubusercontent.com/12454813/33813760-d8be2cd2-de60-11e7-84f5-a477d6570cc1.png)

**Comment by xyxiao001** [comment]
可以的
