### ISSUE TITLE
为什么上传一些大的图片预览区域的图片会被自动倒过来了

### ISSUE THREAD

**Issue by chenjiaobin** [xyxiao001/vue-cropper#468]
![image](https://user-images.githubusercontent.com/24197503/88992835-ec92b400-d316-11ea-9ac2-9be174fd770e.png)

**Comment by chenjiaobin** [comment]
裁剪区域的图片却是正常的，一开始以为是图片链接格式问题，裁剪区域是blog，预览区域是base64，后面把base64转成blog也还是一样会被旋转，查了下说是图片的Exif本身带了Orientation参数导致旋转了，但如果是这样的话为什么裁剪区域的图片就显示正常呢，而预览的却是被自动旋转了。并且window系统的电脑有些是正常的，有些是不正常的，用一台mac看了下也是正常的，请问有大佬遇到过吗？或者知道什么原因？或者知道怎么解决吗？

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/wxwKGz

例子的预览会有问题吗， 或者出问题的浏览器版本是多少

**Comment by chenjiaobin** [comment]
会
浏览器的版本“5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"

**Comment by xyxiao001** [comment]
用的插件版本是最新的吗 0.55

**Comment by xyxiao001** [comment]
因为 chrome 84 版本修复了图片ore 会旋转的问题， 所以插件也做了兼容，高版本不处理图片了

**Comment by chenjiaobin** [comment]
用的0.5.4

**Comment by chenjiaobin** [comment]
看错了，用的就是0.5.5

**Comment by xyxiao001** [comment]
预览和渲染的就是一张图    怎么出现一个正常 一个不正常😂😂

**Comment by chenjiaobin** [comment]
升级了下浏览器版本就没问题了，我去看下你源代码吧

**Comment by xyxiao001** [comment]
😂  代码是判断 chrome 版本的 我回去用 80 版本测试看看

**Comment by chenjiaobin** [comment]
我有一张图的Orientation=3，被旋转了180度，另外一张Orientation=6，被旋转了90度。那些没被旋转的，正常显示的是因为它本身的图片的exif信息就是{}空的
