### ISSUE TITLE
可否提供属性，让截图框为圆形。

### ISSUE THREAD

**Issue by Liuhuifeng** [xyxiao001/vue-cropper#47]

**Comment by xyxiao001** [comment]
![65hmy5 _ e5 1 54 g](https://user-images.githubusercontent.com/15681693/33820365-ff9d35b8-de89-11e7-8d75-8647251de4ea.jpg)
你是要做圆形头像吗

**Comment by Liuhuifeng** [comment]
嗯 需要圆形的图片

**Comment by xyxiao001** [comment]
可以添加border-radious 让截图框看起来像圆形 但是实际截图出来不是圆的， 显示的时候添加border-raious就行
