### ISSUE TITLE
图片画质问题

### ISSUE THREAD

**Issue by xikeqian** [xyxiao001/vue-cropper#471]
在maxImageSize参数设置成比图片宽高中最大的一个还大时，图片宽高比截图框宽高要大，图片会超过截图容器的范围，但是把maxImageSize设置成截图容器宽高中的最大值时，图片会完整显示在截图容器内，但是图片会经过canvas压缩画质，没有原图那样清晰了，有什么参数可以设置图片在截图容器内完整展示，但是不压缩画质吗？
autoCrop:true
autoCropHeight:374
autoCropWidth:232
maxImageSize: 6340
fixedNumber: [12.3, 19.79]
img_height:1512 //图片真实高度
img:"https://img-large.xxpie.com/MTU5NjA5MzY0MjY1M18yMjRBNjgxOS4f1db0fe-137b-40a3-8613-aa869fa7662b?imageView2/2/w/2560/q/100%7Cimageslim&attname=224A6819-12-1.jpg&e=1596520123&token=C8FPxG2IPHtDmtLKn5YCeZdF7OAlefKwHu-rPykj:fUkP0dVQBAL9A_LDJscQqDz_t9Y="
img_width:2560 //图片真实宽度
cropper_width: 634 //截图框宽度
cropper_height: 628 //截图框高度

**Comment by xyxiao001** [comment]
设置  full  或者 maxImgSize 设置大一点

**Comment by Shawn-zs** [comment]
移动端不能拖动  放大缩小都不行  是啥原因呢？IOS手机

**Comment by bq49** [comment]
确实是，即便设置了full，画质还是稍有出入。这个都还是可以接受，但是容量变大就太不能接受了。1536*864 的图片 144k，裁切后800*450 容量却达到 515k。。。。

**Comment by xikeqian** [comment]
现在是兼容处理了一下，我自己用一个canvas把原图绘制在画布上，canvas尺寸跟原图一致，在根据vue-cropper组件提供的截取的图片位置坐标，把截去的图片从第一个canvas绘制到一个新的canvas，在通过canvas进行输出，这样图片的画质得到了保存，因为我的canvas绘制都是按原图尺寸来的，没有经过尺寸缩小
