### ISSUE TITLE
png格式裁剪上传后图片占用空间变大

### ISSUE THREAD

**Issue by lhd-1727865856** [xyxiao001/vue-cropper#482]
因为我上传裁剪的是有透明背景的图片所以不能使用jpeg ,这个时候发现png裁剪完以jpeg的形式上传后文件整整大了一倍
Because What I uploaded and cropped was a picture with transparent background, I could not use JPEG. At this time, I found that the file size was doubled after PNG was cropped and uploaded as JPEG

**Comment by xyxiao001** [comment]
可以压缩下
