### ISSUE TITLE
how to change scoped css?

### ISSUE THREAD

**Issue by newbie78** [xyxiao001/vue-cropper#487]
![image](https://user-images.githubusercontent.com/28735/99011652-a5df6780-255d-11eb-98af-1f4f366495f8.png)
i'm have artefacts with 
```
.cropper-view-box {
outline: 1px solid #39f;
}
```
how i'm change with to 2px?

big thanks for component!
спасибо! )

**Comment by xyxiao001** [comment]
div  id = cropper

#cropper  .cropper-view-box {
  outline: 2px solid #39f;
}
