### ISSUE TITLE
如果截图框拖动过快，导致预览框展示的内容不对

### ISSUE THREAD

**Issue by 2507483326** [xyxiao001/vue-cropper#488]
![image](https://user-images.githubusercontent.com/10804157/99019846-405c9c80-2598-11eb-821c-35281bb51915.png)
如图所示，如果截图框拖动的速度太快，预览框展示的内容不对

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/   我在例子上面没有复现，请问是怎么拖动的

**Comment by 2507483326** [comment]
如下这个视频所示
https://user-images.githubusercontent.com/10804157/103438108-54ed1500-4c6a-11eb-948e-0cbaf415a3e1.mp4
