### ISSUE TITLE
uniapp 项目编译出错 ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by toshcn** [xyxiao001/vue-cropper#490]
Hbuilder x 2.9.7.20201105 window 10 64
运行-》运行到手机或模拟器-》真机usb 调式 （华为Mate 30）
22:20:08.149 正在热刷新，如刷新失败，请点击控制台工具栏上的【重启应用图标】
22:20:09.037 ReferenceError: Blob is not defined

**Comment by xyxiao001** [comment]
https://uniapp.dcloud.io/matter?id=%E5%8C%BA%E5%88%AB%E4%BA%8E%E4%BC%A0%E7%BB%9F-web-%E5%BC%80%E5%8F%91%E7%9A%84%E6%B3%A8%E6%84%8F

**Comment by xyxiao001** [comment]
非H5端不是浏览器环境不支持 Dom、Bom 接口，没有 Blob 也没有 document 。
这在uni-app文档开篇的介绍中有说明

**Comment by githubkl** [comment]
> 非H5端不是浏览器环境不支持 Dom、Bom 接口，没有 Blob 也没有 document 。 这在uni-app文档开篇的介绍中有说明

意思是本插件没做uniapp移动端兼容吗
