### ISSUE TITLE
你好,敬爱的开源作者 是否有开发vue3版本的计划呢？

### ISSUE THREAD

**Issue by catpigdog** [xyxiao001/vue-cropper#492]

**Comment by yuqingc** [comment]
我来帮你 at @xyxiao001

**Comment by yuqingc** [comment]
有的，看这个分支 https://github.com/xyxiao001/vue-cropper/tree/next-vue3

**Comment by xyxiao001** [comment]
正在开发了😂

**Comment by wujingc** [comment]
我拉了这个分支，没有看到裁剪功能，是还没写完吗？@yuqingc

**Comment by stanleyxu2005** [comment]
最近我也在尝试做项目升级，发现vue3在插件加载方式上有完全不一样的做法，vue3本身的实现也有了很大差异。感觉核心代码要脱离vue来编写，最后再绑定到vue2或者vue3的wrapper上。不知道开发者的vue2+3的支持之路准备怎么走？

**Comment by xyxiao001** [comment]
@stanleyxu2005  vue3 这块我基本是重新开发的，准备两个版本分别支持的

**Comment by pacey-li** [comment]
你好，想问下vue3版本大概什么时候发布？

**Comment by xyxiao001** [comment]
你们项目这么快就用上vue3.0了嘛😷😷

**Comment by pacey-li** [comment]
哈哈，刚好有个新项目，做的功能跟以前的一个项目差不多，所以看了一下依赖的vue插件，就到这里问了下，做下预研

如果没有vue3版本，我就先用vue2了，但是会密切关注这个项目的版本更新（大佬辛苦了，新年快乐哈）

**Comment by xyxiao001** [comment]
厉害，新年快乐🙂🙂🙂🙂

**Comment by xyxiao001** [comment]
Vue3开发中

**Comment by Roommate** [comment]
> Vue3版本开发中

哈喽，vue3版本开发的如何啦，我已经期待了好久了，或者需要什么帮助吗？

**Comment by xyxiao001** [comment]
😂😂之前一段时间都在搞其他项目，那我抓紧点时间了

**Comment by Roommate** [comment]
> 😂😂之前一段时间都在搞其他项目，那我抓紧点时间了

好的，万分感谢

**Comment by aardw** [comment]
苦啊

**Comment by aardpro** [comment]
等不及了，我搞了一个简洁版本的，有需要的老铁去看看 。
https://github.com/aardpro/vue3-image-slim

**Comment by xyxiao001** [comment]
已经支持 vue3 使用
安装 vue-cropper@next
