### ISSUE TITLE
您好，拖动截图框时会报错

### ISSUE THREAD

**Issue by pengchi-wb** [xyxiao001/vue-cropper#494]
截图功能可以正常使用，但是拖动截图框或者图片，或者改变截图框大小时，都会报index.js?7e79:1 Unable to preventDefault inside passive event listener invocation

**Comment by pengchi-wb** [comment]
> 截图功能可以正常使用，但是拖动截图框或者图片，或者改变截图框大小时，都会报index.js?7e79:1 Unable to preventDefault inside passive event listener invocation

**Comment by pengchi-wb** [comment]
谷歌浏览器报红色错误，
火狐浏览器是黄色警告，警告内容为：忽略一个注册为“passive”的监听器的事件类型为“mosemove”的“preventDefault（）”调用

**Comment by xyxiao001** [comment]
插件使用版本为多少

**Comment by pengchi-wb** [comment]
> 插件使用版本为多少

就是最新的，0.5.5

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/
我看在线例子没有这样的问题  我的 chrome 为 86

**Comment by pengchi-wb** [comment]
> http://github.xyxiao.cn/vue-cropper/example/
> 我看在线例子没有这样的问题 我的 chrome 为 86

我的是87，报错显示为cropper的js错误

**Comment by xyxiao001** [comment]
截图看看

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/101567385-ab6c8800-3a0b-11eb-8032-da48fe83ddce.png)
我刚刚更新了 检查也没有报错， 你可以把node_modules里面的 vue-cropper删掉重新安装看看

**Comment by pengchi-wb** [comment]
> ![image](https://user-images.githubusercontent.com/15681693/101567385-ab6c8800-3a0b-11eb-8032-da48fe83ddce.png)
> 我刚刚更新了 检查也没有报错， 你可以把node_modules里面的 vue-cropper删掉重新安装看看

还是一样的，只要移动就会报错

**Comment by xyxiao001** [comment]
😂这么奇怪  新版应该没问题啊 ，例子在你那边有问题嘛

**Comment by pengchi-wb** [comment]
> 😂这么奇怪 新版应该没问题啊 ，例子在你那边有问题嘛

例子我没有试过，晚一点我试一下，麻烦您了

**Comment by pengchi-wb** [comment]
> 😂这么奇怪 新版应该没问题啊 ，例子在你我这个是和element UI一起用的，会不会这方面的影响

**Comment by pengchi-wb** [comment]
> 😂这么奇怪新版应该没问题啊，例子在你那边有问题嘛

我这个是和element UI一起用的，会不会这方面的影响

**Comment by pengchi-wb** [comment]
https://www.cnblogs.com/ecmasea/p/9040820.html
这个网址里解释了为什么会出现这种情况

**Comment by pengchi-wb** [comment]
https://www.cnblogs.com/ecmasea/p/9040820.html
这个网址里解释了为什么会出现这种情况，

**Comment by xyxiao001** [comment]
插件里面已经针对这个做过了兼容😷 单独使用是没问题的

**Comment by pengchi-wb** [comment]
![image](https://user-images.githubusercontent.com/70841381/101752511-9592bc00-3b0c-11eb-8050-8402445da3a9.png)
我不会是下了个假的cropper吧😭

**Comment by pengchi-wb** [comment]
您觉得我这边可能是什么地方促使出的错，实在改不掉，😭😭😭

**Comment by pengchi-wb** [comment]
您好，很抱歉，我又来打扰了，我看您js中用了  t.preventDefault()来阻止默认事件，会不会是这方面的问题😭😭😭
如果有时间，麻烦您看一下这个
https://www.cnblogs.com/macliu/p/11763318.html
![image](https://user-images.githubusercontent.com/70841381/101867507-44d79d80-3bb6-11eb-85f1-fef31b6d51f0.png)

**Comment by pengchi-wb** [comment]
![image](https://user-images.githubusercontent.com/70841381/101867578-73557880-3bb6-11eb-8e07-c5f409b0deef.png)

**Comment by xyxiao001** [comment]
这个插件已经做过处理了 你可以看例子的使用也是没问题的

**Comment by pengchi-wb** [comment]
好的，打扰您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "goodboy"<notifications@github.com&gt;; 
发送时间: 2020年12月11日(星期五) 中午1:42
收件人: "xyxiao001/vue-cropper"<vue-cropper@noreply.github.com&gt;; 
抄送: "候鸟一言"<1524486813@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xyxiao001/vue-cropper] 您好，拖动截图框时会报错 (#494)





 
这个插件已经做过处理了 你可以看例子的使用也是没问题的

**Comment by xyxiao001** [comment]
你试一下，单独用一个页面 使用组件看看

**Comment by xyxiao001** [comment]
排除其他的影响看看  有可能是组件之间有冲突

**Comment by pengchi-wb** [comment]
单独使用页面也会报错，然后我把element UI中的上传框取消之后，拖动还是会报错，我尝试一下新创建一个vue项目试试

**Comment by xyxiao001** [comment]
这么奇怪   https://codepen.io/xyxiao001/pen/wxwKGz

**Comment by pengchi-wb** [comment]
效果都可以实现，就是有这个报错，现在用的台式，我的笔记本上也报错😭

**Comment by pengchi-wb** [comment]
太难了😭

**Comment by DaxtonChen** [comment]
@xyxiao001 我在拖动截图框时也会报错，但不太一样

![圖片已上傳至：2020-12-18 17-56](https://user-images.githubusercontent.com/32349878/102601205-d026d500-415a-11eb-9c32-7dfb847738ed.png)

https://user-images.githubusercontent.com/32349878/102601249-de74f100-415a-11eb-8f1d-0d870197a72f.mp4

**Comment by xyxiao001** [comment]
@DaxtonChen  0.56版本已经修复了

**Comment by DaxtonChen** [comment]
@xyxiao001 谢谢。
还想请教，我只点击一下或是拖曳一下子之后，它就粘着我的滑鼠指标不放，是为什么呢？如影片....

**Comment by PeyFon** [comment]
![微信图片_20210419095836](https://user-images.githubusercontent.com/60815493/115171704-35350c00-a0f6-11eb-86bf-44b41a7ca755.png)
![微信图片_20210419100024](https://user-images.githubusercontent.com/60815493/115171705-36663900-a0f6-11eb-82be-8c26133c1755.png)
您好，这个问题仍旧存在。

**Comment by lincenying** [comment]
检查下, 是否引入了`default-passive-events`依赖
