### ISSUE TITLE
修改成圆形截图框

### ISSUE THREAD

**Issue by Dangerous828** [xyxiao001/vue-cropper#498]
你好作者，请问圆形截图框要如何修改
我在网上查到这篇文章，但是vue手脚架引入的依赖里面找不到对应的事件
https://www.cnblogs.com/beizhi666/p/10935518.html
可以麻烦您看一下嘛

**Comment by xyxiao001** [comment]
这个不是 cropper.js  修改圆形截图框，可以用 css 样式去控制
