### ISSUE TITLE
maxImgSize限制图片最大宽度和高度没有效果

### ISSUE THREAD

**Issue by zxy295547387** [xyxiao001/vue-cropper#499]
设置了maxImgSize为5000，裁剪的时候最大宽度和高度依然是2000

**Comment by xyxiao001** [comment]
这个你怎么传递进去的

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/  可以看看例子

**Comment by zxy295547387** [comment]
option: {
  img: '', // 裁剪图片的地址
  info: true, // 裁剪框的大小信息
  outputSize: 1, // 裁剪生成图片的质量
  outputType: 'png', // 裁剪生成图片的格式 
  canScale: true, // 图片是否允许滚轮缩放
  autoCrop: true, // 是否默认生成截图框
  // autoCropWidth: 300, // 默认生成截图框宽度
  // autoCropHeight: 200, // 默认生成截图框高度
  fixedBox: false, // 固定截图框大小 不允许改变
  fixed: true, // 是否开启截图框宽高固定比例
  fixedNumber: [4, 3], // 截图框的宽高比例
  full: true, // 是否输出原图比例的截图
  canMoveBox: true, // 截图框能否拖动
  // maxImgSize: 300, // 限制图片最大宽度和高度。默认2000。。
  // original: true, // 上传图片按照原始比例渲染。
  centerBox: false, // 截图框是否被限制在图片里面
  infoTrue: true, // true 为展示真实输出图片宽高 false 展示看到的截图框宽高
},

你可以看下我这边的配置，我设置了maxImgSize没有效果。   版本："vue-cropper": "^0.5.5"

**Comment by xyxiao001** [comment]
maxImgSize 有传进去嘛，或者直接

<vue-cropper maxImgSize="300"></vue-cropper>

**Comment by xyxiao001** [comment]
`<vue-cropper  maxImgSize="300"></vue-cropper>`

**Comment by zxy295547387** [comment]
<vue-cropper maxImgSize="300"></vue-cropper>   方式可以，  而通过配置maxImgSize: 300就不行。  感谢大佬

**Comment by xyxiao001** [comment]
这样  不行的模式我去研究看看
