### ISSUE TITLE
 上传服务端

### ISSUE THREAD

**Issue by bDreams** [xyxiao001/vue-cropper#5]
如何将裁剪的数据传递给服务端，getCropData这个方法返回的只是一个base64编码，getCropBlob这个方法返回的是blob，这个blob数据是裁剪后的图片的流吗？

**Comment by xyxiao001** [comment]
是的 blob可以塞到form表单控件里面提交

**Comment by SAOSO** [comment]
@xyxiao001 获取的是blob:http://localhost:8081/e1aa5ee9-6ca8-461f-9b1d-8837878090a4
这种，如何把它转成Blob上传到服务端

**Comment by xyxiao001** [comment]
把blob数据通过表单提交 或者 ajax 提交过去
http://blog.csdn.net/moonpure/article/details/50462043
详情可以参考这篇文章

**Comment by SAOSO** [comment]
@xyxiao001 如何把blob:http://localhost:8081/e1aa5ee9-6ca8-461f-9b1d-8837878090a4

转成一个Blob上传呢？

**Comment by xyxiao001** [comment]
你直接调用this.$refs.getCropBlob((data) => {console.log(data)})
这样就得到了blob对象 然后塞到formdata里面就可以提交了
或者 this.$refs.getCropData 是base64的 直接提交

**Comment by xyxiao001** [comment]
刚刚在0.17版本修复了 blob 数据返回错误的情况， 更新下 ， 然后调用this.$refs.getCropBlob((data)
就可以得到正确的blob对象
