### ISSUE TITLE
截出来的图很模糊这个有什么设置项吗，研究半天没搞明白

### ISSUE THREAD

**Issue by boosver** [xyxiao001/vue-cropper#500]
截出来的图很模糊这个有什么设置项吗，研究半天没搞明白

**Comment by xyxiao001** [comment]
full  或者 enlarge

**Comment by boosver** [comment]
> 全或放大

都试了还是模糊哎

**Comment by xyxiao001** [comment]
那或者你本身图片不够清晰

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/ 看下例子

**Comment by boosver** [comment]
> http://github.xyxiao.cn/vue-cropper/example/ 看下例子

我在研究一下谢谢大佬
