### ISSUE TITLE
拖拽裁剪框，如果一不小心拖拽到外面。页面就会报错，似乎是元素没有找到

### ISSUE THREAD

**Issue by CasualMing** [xyxiao001/vue-cropper#502]
![image](https://user-images.githubusercontent.com/40878104/102837379-a1e51600-4436-11eb-9517-35ff7023318c.png)

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/  
例子可以复现嘛

**Comment by CasualMing** [comment]
> http://github.xyxiao.cn/vue-cropper/example/
> 示例可以复现嘛
![Uploading image.png…]()

**Comment by CasualMing** [comment]
> http://github.xyxiao.cn/vue-cropper/example/
> 例子可以复现嘛

![image](https://user-images.githubusercontent.com/40878104/102837929-ecb35d80-4437-11eb-87c0-8bde7113b652.png)

**Comment by xyxiao001** [comment]
怎么操作复现，我直接拖出去没有报错，拖动事件是绑定在window上的

**Comment by xyxiao001** [comment]
这个问题我加个 判断修复下

**Comment by xyxiao001** [comment]
0.56版本已经修复了
