### ISSUE TITLE
滑鼠点击后放开，截图框粘着我的滑鼠指标不放，是为什么呢？

### ISSUE THREAD

**Issue by DaxtonChen** [xyxiao001/vue-cropper#504]
我只点击一下或是拖曳一下子之后，它就粘着我的滑鼠指标不放，是为什么呢？如影片....

https://user-images.githubusercontent.com/32349878/102955475-f230a680-4510-11eb-8f34-fc28d5ba771d.mp4

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/

**Comment by xyxiao001** [comment]
我在例子上没有复现，你有复现地址嘛，或者提供你浏览器版本看看

**Comment by DaxtonChen** [comment]
稍等我部属一个网址
先附上浏览器版本

![圖片已上傳至：2020-12-23 11-28](https://user-images.githubusercontent.com/32349878/102956064-615aca80-4512-11eb-90a3-b6a7266f6191.png)

**Comment by DaxtonChen** [comment]
@xyxiao001 有找到是什么问题了
Vue file里面vue-cropper和vue-table-2同时存在时就会有上述问题
大老有什么看法吗？

**Comment by xyxiao001** [comment]
难道是绑定事件冲突了

**Comment by DaxtonChen** [comment]
@xyxiao001 目前我找不到问题在哪里@@

测试专案git：https://gitlab.songtai.com.tw/daxton/test01
有问题的测试连结：http://test.songtailurker.com/#/merchants/merchants
没问题的测试连结：http://test.songtailurker.com/#/merchants/merchants1

**Comment by xyxiao001** [comment]
有可能是 vue-table-2 监听了鼠标事件导致的，可以把 截图和表格分开放在不同的 div 里面呢

**Comment by DaxtonChen** [comment]
@xyxiao001  还是一样呢
没遇过这种问题，太难了 :sob:

**Comment by DaxtonChen** [comment]
@xyxiao001  大佬有这问题的解决方案吗？ 谢谢

**Comment by xyxiao001** [comment]
木有 看不出是什么冲突了😂
