### ISSUE TITLE
如何按照固定比例去缩放裁剪框？

### ISSUE THREAD

**Issue by BrokenGatsby** [xyxiao001/vue-cropper#509]
在缩放裁剪框的时候，如何按照固定的宽高比例去自由缩放裁剪框，现在在拖动角去缩放裁剪框时，会使得宽高并不按照等比去缩放。

**Comment by xyxiao001** [comment]
设置下 fiexd  和 fixedNumber

**Comment by BrokenGatsby** [comment]
> 设置下 fiexd 和 fixedNumber

已经设置了，fixed默认是开启的，fixedNumber也设置的 [1:1]，但是在拖动裁剪框的角进行缩放的时候，宽高没有等比的缩放。

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/wxwKGz

**Comment by BrokenGatsby** [comment]
> https://codepen.io/xyxiao001/pen/wxwKGz

非常抱歉。
是我这边配置的问题，我一度认为option的配置，是一整个option去赋值，而不是单项单项去赋值，给你带来一些困扰非常抱歉。

**Comment by xyxiao001** [comment]
😂😂😂😂
