### ISSUE TITLE
请问预览区域能否当截图框放大或者缩小时对应的将图片缩小或者放大？

### ISSUE THREAD

**Issue by HaLoJJ** [xyxiao001/vue-cropper#512]
现在有个需求就是使用截图工具给我的系统的用户修改头像，我的系统的头像容器大小是120px*120px的，当用户上传头像时，放大（缩小）截图框时，我预览区域的图片会跟着缩小（放大），让截图的内容一直保持在120px*120px的容器里，这个要怎么实现呢？

**Comment by xyxiao001** [comment]
你可以看看文档，可以通过zoom实现固定大小

**Comment by xyxiao001** [comment]
`
  固定为100宽度
  this.previewStyle3 = {
    width: previews.w + "px",
    height: previews.h + "px",
    overflow: "hidden",
    margin: "0",
    zoom: 100 / preview.w
  };`
