### ISSUE TITLE
裁剪框区域显示错误问题

### ISSUE THREAD

**Issue by xmskying** [xyxiao001/vue-cropper#513]
很奇怪的问题，当图片尺寸比较小的时候，就会出现裁剪框区域内图像显示错误。都会发生在左侧，头疼两天！望回复~
场景再现：
![1](https://user-images.githubusercontent.com/20277030/106081357-bada9880-6153-11eb-90be-102c643c7260.gif)
截图：
![微信截图_20210128102820](https://user-images.githubusercontent.com/20277030/106081337-adbda980-6153-11eb-93c3-565113e08810.png)

**Comment by xyxiao001** [comment]
看看是不是你的 css 属性影响了截图框里面图片的布局

**Comment by xyxiao001** [comment]
比如 min-width  flex都可能会影响

**Comment by xmskying** [comment]
经排查，确实是img全局设置了max-width: 100%导致的样式覆盖问题。已解决，谢谢！
