### ISSUE TITLE
请问一下移动端裁剪框直上直下拖动卡顿，但是向左划一下再上下移动就正常如何解决

### ISSUE THREAD

**Issue by LaughAndEnjoy178** [xyxiao001/vue-cropper#515]
请问一下移动端裁剪框直上直下拖动卡顿，但是向左划一下再上下移动就正常如何解决

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/ 
测试例子 移动端截图框拖动是正常的
