### ISSUE TITLE
拖动裁剪框会报错

### ISSUE THREAD

**Issue by fengruoxian** [xyxiao001/vue-cropper#517]
在单独的 vue+element demo中测试发现并没有报错，但是使用 vue-element-admin这个模板的时候拖拽会报Unable to preventDefault inside passive event listener invocation。如下图，就是不知道和哪个插件冲突了，删除了部分组件还是没有找到问题
![error-info](https://user-images.githubusercontent.com/13239694/107139375-a23d6000-6955-11eb-99c2-932cbb123bf0.png)

**Comment by vodka0629** [comment]
没错，我也遇到了这个问题，似乎是 chrome 升级后才有的问题
``
chrome 版本 88.0.4324.104（正式版本） （64 位）
``

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/  我在最新插件版本和 chrome88上面测试没问题，可以升级下插件版本

**Comment by ANTHAK** [comment]
![image](https://user-images.githubusercontent.com/25068848/123030449-6e02a180-d415-11eb-8549-1b1eae95eae8.png)
依旧会有拖动报错问题
![image](https://user-images.githubusercontent.com/25068848/123030521-84106200-d415-11eb-9f29-a6d2809d03f5.png)

**Comment by ANTHAK** [comment]
![image](https://user-images.githubusercontent.com/25068848/123030580-99858c00-d415-11eb-8630-c5556e4b206e.png)

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/123030700-c89bfd80-d415-11eb-930a-419b870c665b.png)
我刚刚看的在线例子。没问题呀
http://github.xyxiao.cn/vue-cropper/example/

**Comment by ANTHAK** [comment]
先前造成这个报错的原因是什么呢，我按这个思路排查一下

**Comment by xyxiao001** [comment]
可以看看你代码里面是否有绑定的事件相互影响，或者vue-cropper单独放在一个页面看看

**Comment by ANTHAK** [comment]
好的  谢谢
