### ISSUE TITLE
阿里云图片跨域，OSS配置了允许跨域还是不可以

### ISSUE THREAD

**Issue by fqybzhangji** [xyxiao001/vue-cropper#518]
![image](https://user-images.githubusercontent.com/12755324/108304168-62db0300-71e2-11eb-859e-6f623ef339c4.png)
![image](https://user-images.githubusercontent.com/12755324/108304196-6e2e2e80-71e2-11eb-87dc-4d35156ed14a.png)

**Comment by xyxiao001** [comment]
这个应该是你oss的跨域请求头没有配置好

**Comment by fqybzhangji** [comment]
配置了没有用最终解决方案是后台解决的

最终解决方案
将后台图片转成 data url base64传到前段就可以直接使用了
之前走了不少弯路

Java 参考代码

```
//获取图片文件
File file = .......;
//转成base64
byte[] fileContent = FileUtils.readFileToByteArray(file);
String encodedString = Base64.getEncoder().encodeToString(fileContent);
//构造data url
StringBuilder sb = new StringBuilder();
sb.append("data:");
sb.append("image/*");
sb.append(";base64,");
sb.append(encodedString);
```
最终把这个string 返回给前段就可以直接使用了
