### ISSUE TITLE
传入base64给img,img会自动在前面加上http://localhost

### ISSUE THREAD

**Issue by fqybzhangji** [xyxiao001/vue-cropper#519]
![image](https://user-images.githubusercontent.com/12755324/108315021-ca4e7e00-71f5-11eb-8b19-a126620a4d4e.png)

**Comment by xyxiao001** [comment]
base64插件会自动处理为blob的流访问

**Comment by fqybzhangji** [comment]
> base64插件会自动处理为blob的流访问

我npm安装和配置js-base64?

**Comment by fqybzhangji** [comment]
> base64插件会自动处理为blob的流访问

![image](https://user-images.githubusercontent.com/12755324/108321177-c4a96600-71fe-11eb-8e2b-df2ee1c1f71f.png)
![image](https://user-images.githubusercontent.com/12755324/108321201-cbd07400-71fe-11eb-9ae9-979a57ca1333.png)
![image](https://user-images.githubusercontent.com/12755324/108321218-d0952800-71fe-11eb-9b05-7c0d270f46dd.png)

blob格式的，还是不可以

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/ 我测试在线例子是可以的。你那边是有报错吗

**Comment by fqybzhangji** [comment]
> http://github.xyxiao.cn/vue-cropper/example/ 我测试在线例子是可以的。你那边是有报错吗

我传入的是blob，你的例子里面没有这种方式，但是你说支持这种方式的

![image](https://user-images.githubusercontent.com/12755324/108579390-9c864800-7361-11eb-9def-abc54e91fbb4.png)
![image](https://user-images.githubusercontent.com/12755324/108579401-a60fb000-7361-11eb-99cf-2d5ab053beef.png)
![image](https://user-images.githubusercontent.com/12755324/108579464-e53e0100-7361-11eb-8629-3ad3b0b215d1.png)

**Comment by xyxiao001** [comment]
blob 需要使用URL.createObjectURL生成访问地址

**Comment by fqybzhangji** [comment]
> blob

![image](https://user-images.githubusercontent.com/12755324/108584802-1678fa00-737f-11eb-9a80-25121416a4f9.png)
![image](https://user-images.githubusercontent.com/12755324/108584844-6fe12900-737f-11eb-9711-3beba9d6fbbc.png)
![image](https://user-images.githubusercontent.com/12755324/108584828-57710e80-737f-11eb-9994-c72b747b9964.png)

**Comment by xyxiao001** [comment]
有报错嘛

**Comment by fqybzhangji** [comment]
> 有报错嘛

啥报错都没有，就是很迷，不知该如何下手了

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/wxwKGz
在线例子看看

**Comment by fqybzhangji** [comment]
> https://codepen.io/xyxiao001/pen/wxwKGz
> 在线例子看看
`
      let _this=this;
        this.blobToDataURI(res, function (data) {
          _this.options.img = data;
        });

    /**
     *
     * blob二进制 to base64
     **/
    blobToDataURI(blob, callback) {
      var reader = new FileReader();
      reader.onload = function (e) {
        callback(e.target.result);
      };
      reader.readAsDataURL(blob);
    },`

虽然这样子写法报错
![image](https://user-images.githubusercontent.com/12755324/108671330-37765200-751b-11eb-95a6-0acb635f590a.png)

但是功能却莫名其妙的实现了

**Comment by fqybzhangji** [comment]
> > https://codepen.io/xyxiao001/pen/wxwKGz
> > 在线例子看看
> > `
> > let _this=this;
> > this.blobToDataURI(res, function (data) {
> > _this.options.img = data;
> > });
> 
> ```
> /**
>  *
>  * blob二进制 to base64
>  **/
> blobToDataURI(blob, callback) {
>   var reader = new FileReader();
>   reader.onload = function (e) {
>     callback(e.target.result);
>   };
>   reader.readAsDataURL(blob);
> },`
> ```
> 
> 虽然这样子写法报错
> ![image](https://user-images.githubusercontent.com/12755324/108671330-37765200-751b-11eb-95a6-0acb635f590a.png)
> 
> 但是功能却莫名其妙的实现了

**Comment by fqybzhangji** [comment]
@xyxiao001 

最终解决方案
将后台图片转成 data url base64传到前段就可以直接使用了
之前走了不少弯路

相关参考代码

```
        //获取图片文件
        File file = .......;
        byte[] fileContent = FileUtils.readFileToByteArray(file);
        String encodedString = Base64.getEncoder().encodeToString(fileContent);
        StringBuilder sb = new StringBuilder();
        sb.append("data:");
        sb.append("image/*");
        sb.append(";base64,");
        sb.append(encodedString);
```
最终把这个string 返回给前段就可以直接使用了
