### ISSUE TITLE
关于IE11使用时选择要裁切的图片无显示的疑问

### ISSUE THREAD

**Issue by FFFirer** [xyxiao001/vue-cropper#522]
在IE11中使用时，选择图片后裁切框里没有出现要裁切的图片
![image](https://user-images.githubusercontent.com/22254170/109502195-a3385c00-7ad3-11eb-878b-af96f2448447.png)

翻看源码，调试后发现如下代码
![image](https://user-images.githubusercontent.com/22254170/109502368-d844ae80-7ad3-11eb-920c-a1f90d47721d.png)

对于IE浏览器使用XMLHttpRequest去获取图片的blob数据
但是我测试过发现对于传入的props:img为一个base64字符串时，这样使用会报出'Access is denied'的错误
这是获取上传图片base64的代码
![image](https://user-images.githubusercontent.com/22254170/109502971-a8e27180-7ad4-11eb-9a7a-7cf918bc489c.png)

这是我写的测试用例模拟调试时的截图
![image](https://user-images.githubusercontent.com/22254170/109503143-da5b3d00-7ad4-11eb-9f9f-e124729c7fd0.png)

当我把针对IE的代码删掉，使用和其他浏览器一样的设置img的url时，在IE11上运行没有问题
这是修改后的代码
![image](https://user-images.githubusercontent.com/22254170/109503432-358d2f80-7ad5-11eb-8e18-bb60eed49ea0.png)

最后，我想知道的是对于这段针对IE特别处理的代码的作用是什么，主要是解决什么场景下的问题，不太明白，想请教一下。

**Comment by FFFirer** [comment]
在issue #413 中，我也看到这个示例 http://github.xyxiao.cn/vue-cropper/example/
但我在IE11中打开时，Upload无法正常上传图片，提示格式不对，在Edge等其他浏览器上都可以正常显示。
![image](https://user-images.githubusercontent.com/22254170/109504784-e5af6800-7ad6-11eb-8e01-f228b2b66a47.png)
![image](https://user-images.githubusercontent.com/22254170/109504743-d7f9e280-7ad6-11eb-98e5-aabcfbc1274e.png)

**Comment by xyxiao001** [comment]
明天早上我去看一看🤔

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/109586435-2d1e0e80-7b40-11eb-9acc-a1e6065dfdc1.png)
我测试 ie11 是可以渲染的和截图的，你说的这个图片类型判断应该是我这边 upload 判断逻辑在 ie 下面有点问题

**Comment by FFFirer** [comment]
渲染和截图没有问题，是的，但是我看你这个原图片的地址是一个http的链接，是一个网络资源。
但我在使用时，加载的是本地的图片，是一个base64字符串。
基于以上的信息，我判断，在针对IE的那段代码下，如果传入的是一个url那是可以正常读取的，但对于base64字符串是有问题的。

**Comment by xyxiao001** [comment]
之前做那个ie 兼容是因为 base64 在 ie 下面直接用会出问题，可以考虑 ie下面上传的图片转化为 blob 的链接进行处理

**Comment by FFFirer** [comment]
是准备兼容哪些版本的IE呢，那段在IE下转换为blob的代码现在我在IE11下会报错，所以我索性在IE 11下是直接使用base64了，暂时是没发现问题的。

**Comment by xyxiao001** [comment]
目前应该暂时只兼容到 ie11 和 ie10

**Comment by Programmer-girl** [comment]
vue-cropper@0.5.6版本
![image](https://user-images.githubusercontent.com/24430661/119928209-b7460980-bfad-11eb-88c6-58ecb5d6f64c.png)
xhr.open("GET", this.img, true);是报错的，提示拒绝访问，如果关闭if (this.isIE) 判断，直接将img.src赋值是没问题的，和上面同学应该是一个问题，@xyxiao001 麻烦您再看下这个问题
