### ISSUE TITLE
异步传入图片的URL

### ISSUE THREAD

**Issue by ThreeStonesLee** [xyxiao001/vue-cropper#524]
异步传入图片的URL，然后赋值给img，为什么显示在裁剪框中很小，并且截图框只能在很小的范围内移动
![Uploading 问题.jpg…]()

**Comment by xyxiao001** [comment]
如果是弹框，那么需要设置下，弹框渲染完成再去渲染截图组件，不然坐标判断可能不准

**Comment by ThreeStonesLee** [comment]
好的，多谢大佬

**Comment by ThreeStonesLee** [comment]
> 如果是弹框，那么需要设置下，弹框渲染完成再去渲染截图组件，不然坐标判断可能不准

好的，多谢大佬
