### ISSUE TITLE
如何获取截图框相对图片点坐标，需要获取截图框左上和右下的点坐标

### ISSUE THREAD

**Issue by 13160671810** [xyxiao001/vue-cropper#529]
http://shopline-ocr.oss-cn-shenzhen.aliyuncs.com/Images/1616495188757267411616495010_.pic.jpg

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/112144735-8abfeb00-8c14-11eb-99f5-eb0c419e605d.png)
提供了图片和截图框相对容器的坐标

**Comment by 13160671810** [comment]
感谢博主大大 已解决坐标问题~ 想问下为啥第二次打开第二张图片的时候， 图片会以画布左上角为原点 而且变得很小 这个有办法解决吗

**Comment by xyxiao001** [comment]
如果是 dialog 弹框，需要等弹框出来后去渲染组件

**Comment by 13160671810** [comment]
为什么第一次dialog弹框的第一张图是正常大小的 有没有像option那种初始化图片属性可以控制

**Comment by 13160671810** [comment]
已解决~ 新增v-if 搞掂 感谢博主大大答疑
