### ISSUE TITLE
在van-popup组件中使用时，图片拖动起来会很费劲，在vux的popup中则无问题

### ISSUE THREAD

**Issue by yangbo990713** [xyxiao001/vue-cropper#530]
在van-popup组件中使用时，图片拖动起来会很费劲，在vux的popup中则无问题

**Comment by xyxiao001** [comment]
van popup可能存在组件渲染获取宽度的问题，可以等 popup 渲染完成之后，再去渲染 cropper 截图组件

**Comment by xyxiao001** [comment]
van popup可能存在组件渲染获取宽度的问题，可以等 popup 渲染完成之后，再去渲染 cropper 截图组件

**Comment by yangbo990713** [comment]
vant 的版本 2.6.0
vux 的版本 2.9.4

**Comment by xyxiao001** [comment]
有复现 demo 嘛。比如https://codesandbox.io/ 的例子
