### ISSUE TITLE
在ios端，如果图片太大，比如用相机拍的照片，会导致浏览器崩溃，其他端或者小图不会

### ISSUE THREAD

**Issue by 649273833** [xyxiao001/vue-cropper#532]
在ios端，如果图片太大，比如用相机拍的照片，会导致浏览器崩溃，其他端或者小图不会

**Comment by 649273833** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, minimum-scale=1, user-scalable=0" />
发现是这条meta信息导致的，目前使用option.maxImgSize: 1000,控制了最大尺寸，才不会页面崩溃，具体原因不清楚了

**Comment by xyxiao001** [comment]
ios图片 2000 就会崩溃。所以提供了maxImgSize来进行控制

**Comment by 649273833** [comment]
设置完了maxImgSize后，再把meta改为这个更好，  <meta name="viewport" content="width=375, initial-scale=1, maximum-scale=1.0, minimum-scale=1, user-scalable=0" />，视口的宽度直接给他设置375，如果我不设置这个也会崩溃，设置了就好了

**Comment by 649273833** [comment]
设置完了maxImgSize后，再把meta改为这个更好，  <meta name="viewport" content="width=375, initial-scale=1, maximum-scale=1.0, minimum-scale=1, user-scalable=0" />，视口的宽度直接给他设置375，如果我不设置这个也会崩溃，设置了就好了
