### ISSUE TITLE
能否转成png图片保存到本地，然后传给后台

### ISSUE THREAD

**Issue by warmilk** [xyxiao001/vue-cropper#54]
后台给的是百度webUploader的接口，不能传base64字符串 QAQ

**Comment by xyxiao001** [comment]
那blob呢 通过表单提交过去

**Comment by warmilk** [comment]
@xyxiao001 这是我们后台给的接口字段
![image](https://user-images.githubusercontent.com/14016918/34368737-2b2ee01e-eaf1-11e7-8cee-87e1b0a8b326.png)

**Comment by warmilk** [comment]
表单？formdata格式的吗

**Comment by xyxiao001** [comment]
是的

**Comment by warmilk** [comment]
猴，thanks a lot ~

**Comment by warmilk** [comment]
![image](https://user-images.githubusercontent.com/14016918/34369757-a890026a-eaf9-11e7-8e1c-78610fc9f949.png)

大神能再问多个问题么，为啥我图片本地裁剪处理完之后，通过

```js
this.$refs.cropper.getCropBlob((data) => {
	console.log(data)
})

```
log出来的blob都是这些啊。。

![image](https://user-images.githubusercontent.com/14016918/34369656-93c57078-eaf8-11e7-9b98-d686c31e4c28.png)

是我写的获取blob写入axios的formData请求有误吗

**Comment by xyxiao001** [comment]
你是用  formdata.append添加的嘛

**Comment by warmilk** [comment]
接口是这样写的
![image](https://user-images.githubusercontent.com/14016918/34369922-061b8494-eafb-11e7-9a63-d74712234a5d.png)

组件页面内是这样传参调接口的：
![image](https://user-images.githubusercontent.com/14016918/34369954-3382d55e-eafb-11e7-87c9-37ac9b722d23.png)

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/34370022-b67d66ea-eafb-11e7-83ff-8249316394b0.png)
把这个放回调里面呢

**Comment by warmilk** [comment]
乌龙了orz，万分感谢大神！

**Comment by warmilk** [comment]
后续剧情：

吾等愚民踩了个formData的坑，导致发了一早上的请求，都无法把用户本地裁剪完的图片的blob数据post到服务器上，借楼主一地，希望给路过的盆友一点前车之鉴

 formData.append( ) 平时是写两个参数的
```js

formData.append("CustomField", "This is some extra data");

```
但当你传的的是 **blob** 类型的数据时，第三个参数，也就是 **文件名**，一定要记得写哦亲......

```js

formDataappend("myfile", myBlob, "filename.txt");

```
[使用FormData对象上传文件](https://developer.mozilla.org/zh-CN/docs/Web/API/FormData/Using_FormData_Objects)

**Comment by xyxiao001** [comment]
可以的

**Comment by zhangvj** [comment]
> 后续剧情：
> 
> 吾等愚民踩了个formData的坑，导致发了一早上的请求，都无法把用户本地裁剪完的图片的blob数据post到服务器上，借楼主一地，希望给路过的盆友一点前车之鉴
> 
> formData.append( ) 平时是写两个参数的
> 
> ```js
> formData.append("CustomField", "This is some extra data");
> ```
> 
> 但当你传的的是 **blob** 类型的数据时，第三个参数，也就是 **文件名**，一定要记得写哦亲......
> 
> ```js
> formData.append("myfile", myBlob, "filename.txt");
> ```
> 
> [使用FormData对象上传文件](https://developer.mozilla.org/zh-CN/docs/Web/API/FormData/Using_FormData_Objects)

详细补充一下，如果不加文件名，上传后返回的文件链接很可能也不带拓展名，今天也踩坑了
