### ISSUE TITLE
关于 IE11剪裁窗口初始化时，拒绝访问

### ISSUE THREAD

**Issue by Programmer-girl** [xyxiao001/vue-cropper#545]
vue-cropper@0.5.6版本
![image](https://user-images.githubusercontent.com/24430661/119928461-363b4200-bfae-11eb-83a1-823cd28c2849.png)

经排查，在xhr.open("GET", this.img, true);是报错的，提示拒绝访问，如果关闭if (this.isIE)   判断，直接将img.src赋值是没问题的，和上面同学应该是一个问题， 麻烦您再看下这个问题

**Comment by xyxiao001** [comment]
好的，我去看一下，顺便问下你的图片地址是传入的url还是base64

**Comment by Programmer-girl** [comment]
base64格式的，辛苦看下

**Comment by xyxiao001** [comment]
好，周末我去测试下
