### ISSUE TITLE
关于img传blob时报错问题

### ISSUE THREAD

**Issue by homear** [xyxiao001/vue-cropper#546]
prop img 在传入blob对象时 报错 ，substr属于string原型对象的方法

查看了下在vue-cropper/src/vue-cropper.vue文件，在576行使用了如下方法：

// 判断如果不是base64图片 再添加crossOrigin属性，否则会导致iOS低版本(10.2)无法显示图片
      if (this.img.substr(0, 4) !== "data") {
        img.crossOrigin = "";
      }

不知是否以上原因导致

**Comment by xyxiao001** [comment]
blob 需要转成 url 链接 window.createObjcectURL
