### ISSUE TITLE
3000 * 3000的照片裁剪后尺寸小很多 怎么解决 

### ISSUE THREAD

**Issue by 617450941** [xyxiao001/vue-cropper#547]
3000 * 3000的照片裁剪后尺寸小很多 怎么解决     比如截图框只有500 * 500 那出来的就是这样的尺寸  这样的话缩小的太多了

**Comment by xyxiao001** [comment]
full 设置为 true

**Comment by 617450941** [comment]
> full 设置为 true

还有一个问题 怎么输出指定的图片尺寸

**Comment by xyxiao001** [comment]
不能指定尺寸，可以通过 enlarge 输出对应截图框的倍数。
