### ISSUE TITLE
图片显示模糊

### ISSUE THREAD

**Issue by xskdjs1995** [xyxiao001/vue-cropper#550]
手机直接拍照上传 设置 :max-img-size 375 手机屏幕宽度  图片特别模糊 请问有什么相关配置么
![image](https://user-images.githubusercontent.com/35458749/122713602-87caaa00-d298-11eb-9b87-9930f45f97b2.png)

**Comment by xyxiao001** [comment]
设置宽度大一点的，然后设置 mode:contain 来控制渲染

**Comment by xskdjs1995** [comment]
> mode:contain

![image](https://user-images.githubusercontent.com/35458749/122717985-ef83f380-d29e-11eb-918d-a0e5038c2b48.png)
mode:'contain' 宽度设置为2000
宽度就变2000px 特别大 怎么办大佬

**Comment by xyxiao001** [comment]
设置下， mode: 375px auto

**Comment by xskdjs1995** [comment]
mode: '375px auto'   这样吗 设置后没啥变化

**Comment by xyxiao001** [comment]
你传进去了吗 mode 属性

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/122719627-09bed100-d2a1-11eb-8a87-7d55b59fdf73.png)
contain 在线例子也是居中渲染的

**Comment by xskdjs1995** [comment]
![image](https://user-images.githubusercontent.com/35458749/122719735-34108e80-d2a1-11eb-8102-1d748a74c4a3.png)

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/  看看在线例子的

**Comment by xskdjs1995** [comment]
好的 十分感谢帮助 我再看看
