### ISSUE TITLE
会升级vue3吗

### ISSUE THREAD

**Issue by PeyFon** [xyxiao001/vue-cropper#556]
大佬， 会升级到vue3吗？会的话 大概啥时候？谢谢

**Comment by xyxiao001** [comment]
😂😂😂工作一直太忙，会抓紧时间升级的，sorry

**Comment by PeyFon** [comment]
> 😂😂😂工作一直太忙，会抓紧时间升级的，sorry

能升就好， 大佬辛苦了

**Comment by xyxiao001** [comment]
已经支持 vue3 使用
安装 vue-cropper@next
