### ISSUE TITLE
自动生成裁剪框时比例不对

### ISSUE THREAD

**Issue by 2574021892** [xyxiao001/vue-cropper#559]
` <vueCropper
            ref="cropper"
            :img="img"
            auto-crop
            full
            fixed-box
            can-move
            :can-move-box="false"
            :fixed="false"
            :enlarge="1"
            info-true
            :auto-crop-width="cropperWidth"
            :auto-crop-height="cropperHeight"
          ></vueCropper>`

这是我的配置 cropperWIdth=700 cropperHeight=240。当我用这个配置上传一个小的图片时可以正确的生成裁剪框。当我上传一个大的图片是裁剪框就不对了
![image](https://user-images.githubusercontent.com/45650311/126291697-a0030f70-19f5-4576-af12-d22c9529cec3.png)
![image](https://user-images.githubusercontent.com/45650311/126291708-ee01a160-f2f6-4f75-874c-eeec201c9a59.png)

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/wxwKGz  可以看看在线例子
