### ISSUE TITLE
固定截图框后，如果图片小于容器宽度，出现两张图片不重叠

### ISSUE THREAD

**Issue by iamzuijiasunyou** [xyxiao001/vue-cropper#56]
![image](https://user-images.githubusercontent.com/15125049/34411870-a0c42cac-ec14-11e7-833c-0daf79a2362b.png)
<div class="photo-wrap">
         <vue-cropper ref="cropper"
 :img="vueCropper.sourceImgUrl"
 :canScale="cropperOption.canScale"
 :fixedNumber="cropperOption.fixedNumber"
 :fixedBox="cropperOption.fixedBox" 
:fixed="cropperOption.fixed" 
:autoCrop="cropperOption.autoCrop" 
:autoCropWidth="cropperOption.autoCropWidth" 
:autoCropHeight="cropperOption.autoCropHeight"
 :leaveCropCallback="leaveCropCallback">
</vue-cropper>
 </div>
配置：
cropperOption: {
                canScale: false,
                fixedNumber: [16, 9],
                fixedBox: true,
                autoCrop: true,
                fixed:true,
                autoCropWidth: 360,
                autoCropHeight: 202
            }

用的版本是0.26版本 请问这个是什么原因造成的呢

**Comment by iamzuijiasunyou** [comment]
这里是html代码：
`                                <div class="photo-wrap">
                                    <vue-cropper ref="cropper" 
                                    :img="vueCropper.sourceImgUrl" 
                                    :canScale="cropperOption.canScale" 
                                    :fixedNumber="cropperOption.fixedNumber" 
                                    :fixedBox="cropperOption.fixedBox" 
                                    :fixed="cropperOption.fixed" 
                                    :autoCrop="cropperOption.autoCrop" 
                                    :autoCropWidth="cropperOption.autoCropWidth" 
                                    :autoCropHeight="cropperOption.autoCropHeight" 
                                    :leaveCropCallback="leaveCropCallback">
                                    </vue-cropper>
                                </div>`

**Comment by xyxiao001** [comment]
建议升级到最新版本 或者查看下图片是否设置了最大最小宽度的限制

**Comment by iamzuijiasunyou** [comment]
那我再试试。。我是因为修改了源码所以不好升级版本（在0.26版本加了截图框固定和拖动截图框结束的回调）  建议新增一个拖动结束事件的回调。。

**Comment by xyxiao001** [comment]
好的👌🏻 建议已收到，你可以看看是不是你的css影响了

**Comment by iamzuijiasunyou** [comment]
说下这里的问题  父容器设置了text-align:center导致了图片居中后再加transform 所以出现了两张图片不重叠。
