### ISSUE TITLE
能否提供属性，修改截图框的位置

### ISSUE THREAD

**Issue by maoyaocsf** [xyxiao001/vue-cropper#57]

**Comment by xyxiao001** [comment]
你是说通过方法 去手动更改截图框位置吗

**Comment by maoyaocsf** [comment]
是的。现在我用的截图框固定，但我想修改它的位置

**Comment by xyxiao001** [comment]
目前还没有直接修改的方法  可以通过修改this.$refs.cropper.cropX 和  cropY来改变位置
我会在后面的版本加上的

**Comment by maoyaocsf** [comment]
好的，谢谢

**Comment by maoyaocsf** [comment]
transform: translate3d(24px, 87.5px, 0px);，这里面的值怎么修改，用了this.$refs.cropper.cropX 修改没有用

**Comment by xyxiao001** [comment]
这是根据坐标计算的截图位置
