### ISSUE TITLE
图片微裁剪以后  格式大小

### ISSUE THREAD

**Issue by kyhuangmouren** [xyxiao001/vue-cropper#576]
![image](https://user-images.githubusercontent.com/52807841/132274688-28af0a61-4ec3-4811-81da-c995d9fef1ec.png)
原图大小380k  
![image](https://user-images.githubusercontent.com/52807841/132274803-f04630cc-5739-4576-bd6e-9a0303fc2c1c.png)
裁剪完以后 变2M多
不知道什么原因造成的

**Comment by xyxiao001** [comment]
你是把图片放大裁剪了吗，这样会导致裁剪图片变大

**Comment by kyhuangmouren** [comment]
缩小的裁剪  别的都很正常就这张图片出现的了问题

**Comment by xyxiao001** [comment]
图片可以提供下吗，我去测试看看

**Comment by kyhuangmouren** [comment]
![企业(1)](https://user-images.githubusercontent.com/52807841/132277606-bc68e2d4-fe2d-4688-8c90-82b089f539b0.jpg)

**Comment by kyhuangmouren** [comment]
裁剪的多了 反而没事  但如果只是裁剪一点点就会造成这个问题

**Comment by xyxiao001** [comment]
https://xyxiao001.github.io/vue-cropper/example/
我在在线例子上面测试，裁剪后只有 75k，没有看出问题，你是不是设置输出多倍图了

**Comment by xyxiao001** [comment]
![demo](https://user-images.githubusercontent.com/15681693/132278162-4e3ff8fd-e4f2-44fb-9161-1c6d0df293b2.png)

**Comment by kyhuangmouren** [comment]
好的  我再去看看代码

**Comment by kyhuangmouren** [comment]
当  full  设置为true 的时候  造成了这个现象 我想问什么？？？

**Comment by xyxiao001** [comment]
full 是会输出原始比例图片，会放大
