### ISSUE TITLE
是否支持 reset 操作呢

### ISSUE THREAD

**Issue by adward321** [xyxiao001/vue-cropper#577]
这里想在裁剪图片后 将图片重置回原来的大小和位置 还有去除裁剪框，不知道目前有这样的api 吗

**Comment by xyxiao001** [comment]
支持的 this.$refs.cropper.reload()

**Comment by adward321** [comment]
这个方法没在文档中体现，应该以后更新的吧，只是建议一下，楼主不要多想哈

**Comment by xyxiao001** [comment]
好的😂😂😂，这些方法我到时更新到文档下
