### ISSUE TITLE
作者可以添加一个设置截图图片尺寸的方法吗（getCroppedCanvas）

### ISSUE THREAD

**Issue by Xrj-Ajie** [xyxiao001/vue-cropper#581]
这个需求应该很多伙伴都遇到过，就是截图后图片大小保持不变

**Comment by xyxiao001** [comment]
截图图片尺寸，默认是和截图框一样大
full 可以让截图相对于图片等比例输入原始大小
enlarge 可以动态修改输出大小，设置 0- max 的比例
后续可以考虑看看怎么添加强制设置截图大小的方法。
目前可以配合 enlarge 输出指定大小图片

**Comment by Xrj-Ajie** [comment]
好的 谢谢&nbsp; 我这边尝试一下&nbsp;


许仁杰 Jaime


M: 18721863642

T:021-59890032







 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月15日(星期三) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xyxiao001/vue-cropper] 作者可以添加一个设置截图图片尺寸的方法吗（getCroppedCanvas） (#581)





 
截图图片尺寸，默认是和截图框一样大
 full 可以让截图相对于图片等比例输入原始大小
 enlarge 可以动态修改输出大小，设置 0- max 的比例
 后续可以考虑看看怎么添加强制设置截图大小的方法。
 目前可以配合 enlarge 输出指定大小图片
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xrj-Ajie** [comment]
&nbsp;你好 我动态设置&nbsp; enlarge&nbsp; 然后使用 getCropBlob截得图片大小还是不行




 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xyxiao001/vue-cropper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xyxiao001/vue-cropper] 作者可以添加一个设置截图图片尺寸的方法吗（getCroppedCanvas） (#581)





 
截图图片尺寸，默认是和截图框一样大
 full 可以让截图相对于图片等比例输入原始大小
 enlarge 可以动态修改输出大小，设置 0- max 的比例
 后续可以考虑看看怎么添加强制设置截图大小的方法。
 目前可以配合 enlarge 输出指定大小图片
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xyxiao001** [comment]
enlarge 是会等比放大当前截图框图片的大小，比如设置 2 就会输出截图框 大小2 倍

**Comment by Xrj-Ajie** [comment]
我直接设置的三倍 然后保存截图 发现还是和之前一样大 是我姿势不对吗------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月15日(星期三) 晚上6:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xyxiao001/vue-cropper] 作者可以添加一个设置截图图片尺寸的方法吗（getCroppedCanvas） (#581)

**Comment by xyxiao001** [comment]
你是设置 full 了吗，full 优先级会高一点

**Comment by xyxiao001** [comment]
http://github.xyxiao.cn/vue-cropper/example/  例子上面直接改 enlarge 可以看看

**Comment by Xrj-Ajie** [comment]
设置了full为true------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月15日(星期三) 晚上7:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xyxiao001/vue-cropper] 作者可以添加一个设置截图图片尺寸的方法吗（getCroppedCanvas） (#581)

**Comment by Xrj-Ajie** [comment]
这两个属性是冲突的吗 我等下回家试试哈 谢谢回复------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月15日(星期三) 晚上7:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xyxiao001/vue-cropper] 作者可以添加一个设置截图图片尺寸的方法吗（getCroppedCanvas） (#581)

**Comment by xyxiao001** [comment]
是的
