### ISSUE TITLE
裁剪后模糊怎么办?

### ISSUE THREAD

**Issue by lllomh** [xyxiao001/vue-cropper#582]
裁剪后模糊怎么办? 有办法吗?

**Comment by xyxiao001** [comment]
full 设置为 true 可以按照原比例输出截图

**Comment by lllomh** [comment]
也还裁剪后也是模糊了很多啊...

**Comment by lllomh** [comment]
裁剪后图片质量降低了  不清晰了 模糊

**Comment by lllomh** [comment]
拍的带文字的图片 粗剪后看的最明显  裁剪后的图片跟原图对比 模糊了很多

**Comment by xyxiao001** [comment]
默认图片渲染会压缩到 2000 以下，可以把 maxImgSize设置大一点
