### ISSUE TITLE
mode设置px在超过图片本身宽度时无效

### ISSUE THREAD

**Issue by magicianShiro** [xyxiao001/vue-cropper#586]
环境
移动端 chrome浏览器调试

配置如下
```javascript
<vue-cropper
  ref="cropperRef"
  auto-crop
  :info="false"
  :can-move-box="false"
  :center-box="true"
  auto-crop-width="350"
  auto-crop-height="310"
  fixed-box
  mode="350px auto"
  :img="state.img"
 />
```
此时我上传一张 宽高分别为 302px ,  600px 的图片

预计效果:
图片会将宽度拉至350px, 高度auto

实际效果:
截图框会将宽度缩放到302px 而不是图片宽度拉伸至350px, 但如果mode使用百分比则能生效

我这边的需求其实是针对 截图框 实现cover的效果 而不是整个容器..._
现在的做法是获取图片的宽高判断是横图还是竖图, 从而设置mode来实现, 结果现在mode设置px会失效 
请问有更好的方式实现吗? 给大佬递茶  :beers::beers:

**Comment by xyxiao001** [comment]
目前没有办法去针对截图框铺满图片，计算逻辑都是外层容器的，不过你可以获取到截图框的大小，然后再去设置图片的大小

**Comment by magicianShiro** [comment]
> 目前没有办法去针对截图框铺满图片，计算逻辑都是外层容器的，不过你可以获取到截图框的大小，然后再去设置图片的大小

设置图片的大小是通过 mode 属性吗?  如果是mode的话, 当设置的值超过了图片自身的话, mode设置的px就失效了
