### ISSUE TITLE
输出图片时能否指定图片尺寸？例如我截图框是350x200 我想截出来的图片大小是700x400 这个要怎么实现呢？

### ISSUE THREAD

**Issue by iamzuijiasunyou** [xyxiao001/vue-cropper#59]

**Comment by xyxiao001** [comment]
目前只有输出截图框大小  或者按照图片原始比例输出

**Comment by iamzuijiasunyou** [comment]
好的 我自己想想办法

**Comment by hoythan** [comment]
如果可以拿到截图位置（top，left，height，width）的话，倒是可以根据位置和比例计算出实际图片裁切大小，然后在服务端进行裁切。
@xyxiao001 在生成时可否返回这些数据？

**Comment by xyxiao001** [comment]
可以 我会在下个版本返回加上接口返回这些数据

**Comment by xyxiao001** [comment]
0.34 已经返回数据  并且加上了高分屏的兼容
