### ISSUE TITLE
上傳圖片初始是否能縮放使其限制在截圖框中

### ISSUE THREAD

**Issue by harveylee0307** [xyxiao001/vue-cropper#595]
您好 
請問上傳圖片是否能初始時
是否能以截圖框作為基準，縮放填滿於截圖框中

[情境]
1.圖片大於截圖框尺寸-(縮小填滿截圖框)
(如同conterBox:true時，圖片縮放到最小的限制狀態)
![image](https://user-images.githubusercontent.com/16809915/140611087-24ea8598-440c-42fd-8895-3a9ddae3fa0b.png)

2.圖片小截圖框尺寸-(放大填滿截圖框)
![image](https://user-images.githubusercontent.com/16809915/140841990-493a114c-29f2-4c2d-bd8d-262b3f4f3364.png)

**Comment by xyxiao001** [comment]
可以的。设置centerbox

**Comment by harveylee0307** [comment]
@xyxiao001 您好 
我的意思是 上傳的圖片渲染會以cropper-box為基準縮放
所以如果上傳圖片比截圖框大，還是會超出截圖框範圍
![image](https://user-images.githubusercontent.com/16809915/144552111-58a731fe-3c3a-48ff-abe3-a38d9bee2af1.png)

想詢問能不能以截圖框為基準，上傳圖片被限制在截圖框內

[期望狀態]上傳圖片初始渲染時，被限制在截圖框內
![image](https://user-images.githubusercontent.com/16809915/144552466-73eede5b-f2aa-4dba-bde4-b2991d33ca6e.png)

**Comment by xyxiao001** [comment]
不支持这样的操作

**Comment by imaxing** [comment]
有没有api可以调用类似鼠标缩放的功能 手动缩放到最小比例
