### ISSUE TITLE
vue3.0+ts 使用vue-cropper 1.0.2 版本报错

### ISSUE THREAD

**Issue by okaxuan** [xyxiao001/vue-cropper#598]
全局引入：
import VueCropper from 'vue-cropper'; 
import 'vue-cropper/dist/index.css'
app.use(VueCropper)
  <div class="cut">
        <vueCropper
          ref="cropper"
          :img="option1.img"
          :outputSize="option1.size"
          :outputType="option1.outputType"
        ></vueCropper>
      </div>
option1 在setup()已定义

runtime-core.esm-bundler.js?5c40:38 
        
       [Vue warn]: Unhandled error during execution of render function 
  at <VueCropper ref="cropper" img="https://avatars2.githubusercontent.com/u/15681693?s=460&v=4" outputSize=1  ... > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> 

vue-cropper.es.js?04b0:1 Uncaught (in promise) TypeError: Object(...) is not a function
    at Proxy.g.render (vue-cropper.es.js?04b0:1)

**Comment by xyxiao001** [comment]
https://github.com/xyxiao001/cropper-test/blob/master/src/App.vue
看看例子

**Comment by xyxiao001** [comment]
vue3 不是 use 了吧，是 vue.component

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/yLooYKg

**Comment by okaxuan** [comment]
@xyxiao001 Thanks!
