### ISSUE TITLE
苹果7p，6p手机，对于拍照的图片裁切，导致页面重新加载

### ISSUE THREAD

**Issue by zaiYe** [xyxiao001/vue-cropper#6]
6s没有这个问题，7p和6p上面问题比较明显。demo上也有这个问题，微信浏览器里拍照上传进行裁剪，会导致页面重新加载。safari里会提示页面出现错误，重新载入。

**Comment by xyxiao001** [comment]
微信里面上传图片可以用jsdk  
http://blog.csdn.net/fengqingtao2008/article/details/51469705
然后通过props 传入图片的url 或者base64
我写在例子里面的是比较简单的图片上传方法
