### ISSUE TITLE
固定截图框后，截图框可以移出容器内1px，文档demo也会有这个问题

### ISSUE THREAD

**Issue by iamzuijiasunyou** [xyxiao001/vue-cropper#60]
![image](https://user-images.githubusercontent.com/15125049/34637108-7d0efc48-f2e9-11e7-9063-c64021328371.png)

**Comment by iamzuijiasunyou** [comment]
不对 自信看了下 官方文档没问题。。我看看是不是样式导致的

**Comment by xyxiao001** [comment]
![hk 0z4mlcd n8qbo jdm5se](https://user-images.githubusercontent.com/15681693/34637135-0926a17c-f2ea-11e7-937a-0a9b174a00f6.jpg)

**Comment by iamzuijiasunyou** [comment]
找到问题了。。原来默认截图框用的outline 所以四边都留了1px给边框  但是我的项目用的background来显示边框。。导致两边会有1px空隙。。

**Comment by xyxiao001** [comment]
是的

**Comment by iamzuijiasunyou** [comment]
其实为什么当初不直接用border呢？是出于什么原因用的outline

**Comment by iamzuijiasunyou** [comment]
border的话  tramslate也不需要留1px空间了

**Comment by xyxiao001** [comment]
因为边框要拉伸操作

**Comment by iamzuijiasunyou** [comment]
OK了 通过调整样式达到了需求。 谢谢解答

**Comment by iamzuijiasunyou** [comment]
还是希望以后的版本能提供更多的回调事件  changeSize,changeCropEnd,leaveCrop（拖动截图框，滚轮放大图片，改变截图框大小）  这样子用户每次操作完都可以看到截图后的图片 
![image](https://user-images.githubusercontent.com/15125049/34637510-6328c5b6-f2f3-11e7-8262-779c04a03d38.png)

**Comment by xyxiao001** [comment]
好的 后续版本会增加的
