### ISSUE TITLE
使用CDN引入，enlarge无法生效

### ISSUE THREAD

**Issue by songtina** [xyxiao001/vue-cropper#600]
使用在线例子添加enlarge:2, root-data-option中数值正确，但是VueCropper-props中enlarge始终为1。

通过this.$children[0].$props.enlarge = 2可以更改，但是不符合Vue代码规范。

麻烦看下是否有Bug，还是需要其他设置。

**Comment by xyxiao001** [comment]
vue2 还是 vue3 的版本

**Comment by songtina** [comment]
两个版本都测试过，应该是一样的，通过直接更改生效的是在Vue2上尝试的。

**Comment by xyxiao001** [comment]
测试是生效的
![image](https://user-images.githubusercontent.com/15681693/145023209-e6708e2f-f8b9-4880-a6e7-9b5591bfaeab.png)

**Comment by songtina** [comment]
这个参数是添加在html的吗，我是添加在js的option里，不生效

**Comment by songtina** [comment]
哦哦，没注意到Html里面没有绑定这个参数，现在可以了，谢谢
