### ISSUE TITLE
example里面app.vue里面的代码都是乱的，上传一个小图标截图显示两个

### ISSUE THREAD

**Issue by cwx2018** [xyxiao001/vue-cropper#61]

**Comment by cwx2018** [comment]
![1](https://user-images.githubusercontent.com/30886374/34713160-4dd3c67e-f560-11e7-80b3-8bdd379a560a.png)

**Comment by xyxiao001** [comment]
在线例子有问题嘛  运行环境

**Comment by cwx2018** [comment]
新建vue项目，把你的例子app.vue拿来用，前面152行代码的内容重复了2遍？

**Comment by xyxiao001** [comment]
app.vue是我用来写在线例子的

**Comment by cwx2018** [comment]
你的演示例子上传小图片，裁剪的时候正常，我本地运行的时候就有问题，拖动裁剪框的时候就会出现两个小图片，这个是怎么回事

**Comment by xyxiao001** [comment]
你看下是不是你的css影响了 比如图片的最大 最小宽度  flex布局啥的

**Comment by cwx2018** [comment]
谢谢博主，郁闷了一下午，原来我的app.vue有一个默认布局，删掉就好了，再请教一个问题，做项目的时候这个图片要怎么保存到后台呢，是要保存url到数据库吗

**Comment by xyxiao001** [comment]
可以传base64 或者blob 都可以的

**Comment by cwx2018** [comment]
此issue可能是个长期贴......下班

**Comment by 91martincheung** [comment]
能否说下怎么使用，小白不会用，谢谢

**Comment by xyxiao001** [comment]
安装之后 引入就可以用了   可以看看例子 有代码

**Comment by cwx2018** [comment]
this.$refs.cropper.getCropBlob((data) => {
  // do something
  console.log(data)  
})
请问一下，上传图片，是把data作为变量直接存到数据库吗

**Comment by xyxiao001** [comment]
这个方法是blob文件流 可以传给后台

**Comment by cwx2018** [comment]
就是二进制流对吧，直接存到数据库某个字段（longblob）中可以吧？

**Comment by xyxiao001** [comment]
是的
