### ISSUE TITLE
同时使用两个cropper，切换时第二个cropper的图片不能占满容器

### ISSUE THREAD

**Issue by sv-98-maxin** [xyxiao001/vue-cropper#614]

**Comment by xyxiao001** [comment]
这和几个 cropper 没关系，每个组件是独立的，mode:cover可以控制

**Comment by sv-98-maxin** [comment]
但是裁剪框的位置依然只能在哪一个小区域内移动

**Comment by xyxiao001** [comment]
是弹框嘛，如果是弹框动态生成需要在弹框之后渲染截图组件

**Comment by sv-98-maxin** [comment]
就是想要同时裁剪两个尺寸😂

**Comment by xyxiao001** [comment]
两个 cropper 属性单独设置就行，不会互相影响的

**Comment by sv-98-maxin** [comment]
![image](https://user-images.githubusercontent.com/58161021/154636316-138fd901-1d18-4cdc-ac07-14a75a3a4bf7.png)

**Comment by xyxiao001** [comment]
那这个也不需要两个 cropper， 一个就够了，动态修改参数就行

**Comment by sv-98-maxin** [comment]
动态修改参数就不能做到同时裁剪预览了吧
![image](https://user-images.githubusercontent.com/58161021/154636648-bf0164c6-5c72-4a5a-8c0e-0347d9ed69a7.png)

**Comment by xyxiao001** [comment]
不能，不过你用 v-show 控制应该可以同时预览

**Comment by sv-98-maxin** [comment]
对，能同时预览，就是我切换到2:1想要自己裁的时候，裁剪框就会这样。

**Comment by xyxiao001** [comment]
v-show 是隐藏节点，应该是不会这样的，看看是不是有其他操作错误的

**Comment by xyxiao001** [comment]
同时使用，不会影响的，可以排查看看是什么操作，影响到了

**Comment by deverWidi** [comment]
同样的问题，请问你解决了吗

**Comment by sv-98-maxin** [comment]
> 



> 同样的问题，请问你解决了吗

解决了，你是什么情况下遇到这种情况呢

**Comment by deverWidi** [comment]
> > 
> 
> > 同样的问题，请问你解决了吗
> 
> 解决了，你是什么情况下遇到这种情况呢

        感谢回复，抱歉现在才看到，我这边也是用v-show来切换cropper的时候，发现切换后第二个cropper图片变小了。后面发现出现这个的原因是，我在上传成功后就直接给两个cropper的option.img属性赋值，然后切换到第二个cropper的时候图就变小了。目前我的解决办法是在点击比例切换当前显示的cropper之后，再给第二个cropper的option.img赋值，这样就不会变小。
        但是目前还有两个可以优化的问题，不知道你是否遇到过，能否分享一下解决方案，谢谢。
        1. 如何在打开弹窗的时候给预览区域一个默认的宽高；
        2. 上传完图片后如何给两个预览区域同时赋值；

![image](https://user-images.githubusercontent.com/94038854/176147096-ef4c694d-3d42-41d1-a226-cefc0fa95b2f.png)
