### ISSUE TITLE
宽大于高的图片缩放到和截取框差不多大小时，旋转后截取框会缩小

### ISSUE THREAD

**Issue by syczuan** [xyxiao001/vue-cropper#615]
已经固定了截取框宽高，并且不允许改变，宽大于高的图片缩放到和截取框差不多大小时，旋转后截取框会缩小，然后再继续缩放到截取框大小，旋转后截取框又会继续缩小，可以固定截取框始终是自定义尺寸不允许改变吗，在这种情况旋转时自动把旋转后的图片宽度放大到截取框的宽度

**Comment by xyxiao001** [comment]
可以取消 centerbox 的限制，因为这个和旋转其实是有冲突的
