### ISSUE TITLE
img实际上并不支持Blob

### ISSUE THREAD

**Issue by KawaiiZapic** [xyxiao001/vue-cropper#616]
当向img选项传入Blob时, 将直接报错: `this.img.substr is not a function`
查看代码发现, 代码并未实现Blob对象的支持, 仅在prop的属性声明中声称支持Blob.
https://github.com/xyxiao001/vue-cropper/blob/master/src/vue-cropper.vue#L529

**Comment by xyxiao001** [comment]
window.createObjurl 转一下就可以了

**Comment by xyxiao001** [comment]
文档我没有写清楚

**Comment by CrazyBoyM** [comment]
+1
