### ISSUE TITLE
vue3  createApp 用法报错，vue2 是好的

### ISSUE THREAD

**Issue by xu455255849** [xyxiao001/vue-cropper#618]
// main.vue
<img width="570" alt="image" src="https://user-images.githubusercontent.com/15166243/154926021-125cc104-d77b-4a71-835f-7ee7b8fffdb7.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/15166243/154926030-4f62382e-c79f-4d6b-add1-bca4cdd5f827.png">

// crop.ts

import { createApp } from 'vue';
import Crop from './main.vue';
import { IFileType } from './typings/interface';

class CropService `{`
  private static instance: any;

  init({ file, toBlob, fixedNumber, tips }: IFileType) {
    return new Promise((resolve) => {
      // 创建一个挂载容器
      const parentNode = document.createElement('div');
      const mountNode = document.createElement('div');
      parentNode.appendChild(mountNode);

      CropService.instance = createApp(Crop, {
        file,
        tips,
        toBlob: toBlob || false,
        fixedNumber: fixedNumber || [16, 9],
        onConfirm: (data: any) => {
          resolve(data);
          this.destroy(parentNode);
        },
        onCancel: () => {
          this.destroy(parentNode);
        },
      });

      // 挂载组件
      document.body.appendChild(parentNode);
      CropService.instance.mount(mountNode);
    });
  }

  destroy(parentNode: Node) {
    CropService.instance.unmount();
    document.body.removeChild(parentNode);
  }
}

export default new CropService();

//package.json

"dependencies": {
    "vue-cropper": "^1.0.2"
  }

``

**Comment by xyxiao001** [comment]
可以看看文档，有 vue3 的例子

**Comment by xu455255849** [comment]
> 可以看看文档，有 vue3 的例子

![image](https://user-images.githubusercontent.com/15166243/154926944-6489b63c-7e18-4ac3-845c-580188bbb266.png)

文档 我看了，我写法有点不一样，封装了一下  上面这个是报错 ，感觉是底层的问题

**Comment by xu455255849** [comment]
![image](https://user-images.githubusercontent.com/15166243/154927134-55e9df06-3f4d-4729-9215-56910d9a02b1.png)

**Comment by xu455255849** [comment]
vue 和vite 版本降级到和vue-cropper 一样，顺利解决问题， 适配下最新的vue3 版本？
<img width="955" alt="image" src="https://user-images.githubusercontent.com/15166243/154953344-e775aac3-7d57-480c-8e21-a6b83b17c3ee.png">

<img width="885" alt="image" src="https://user-images.githubusercontent.com/15166243/154953357-5e2915bc-1de8-47d5-b775-94fa556ba03f.png">

**Comment by JoyceZouZou** [comment]
请问什么时候能发布新包解决这个问题呀？

**Comment by xyxiao001** [comment]
不好意思，我今天发布解决下

**Comment by xyxiao001** [comment]
1.03版本发布了，测试最新版本 vue 和 vite 是可以的

**Comment by ziyingjie** [comment]
> 请问什么时候能发布新包解决这个问题呀？

可以否分享下antd 的cropper 封装demo 思路

**Comment by xyxiao001** [comment]
> > 请问什么时候能发布新包解决这个问题呀？
> 
> 可以否分享下antd 的cropper 封装demo 思路

已经发布了，你更新看看

**Comment by 2209407652** [comment]
> > > 请问什么时候能发布新包解决这个问题呀？
> > 
> > 
> > 可以否分享下antd 的cropper 封装demo 思路
> 
> 已经发布了，你更新看看
![image](https://user-images.githubusercontent.com/84689886/180346853-1dc71eb0-e834-4bf2-91c9-ca4eeea64b84.png)
![image](https://user-images.githubusercontent.com/84689886/180346898-f0390e79-b953-440c-af43-9fe88bc99201.png)
![image](https://user-images.githubusercontent.com/84689886/180346918-8e6890ad-79cc-4d45-842c-a0b40d0ab586.png)
![image](https://user-images.githubusercontent.com/84689886/180346989-406ebf42-109a-4c87-878e-99a612fbc375.png)
还是会出现上述的问题，我需要降低一下vue和vite版本嘛
