### ISSUE TITLE
直接在vue-cli里用，为什么会出现img src（unkonwn）的情况，还有Uncaught TypeError: First argument to DataView constructor must be an ArrayBuffer报错情况

### ISSUE THREAD

**Issue by ArrayZheng** [xyxiao001/vue-cropper#62]
![image](https://user-images.githubusercontent.com/21194346/34806626-0b83c232-f6bf-11e7-88ac-84bfaea146e0.png)

**Comment by xyxiao001** [comment]
你怎么传的src

**Comment by ArrayZheng** [comment]
example3: {
          img: 'https://o90cnn3g2.qnssl.com/0C3ABE8D05322EAC3120DDB11F9D1F72.png',
          autoCrop: true,
          autoCropWidth: 200,
          autoCropHeight: 200,
          fixedBox: true
        }
直接copy app.vue里的内容哇，然后渲染出来的页面就是没有图片，而且img里的src是unkonwn

**Comment by xyxiao001** [comment]
你引入组件的代码

**Comment by xyxiao001** [comment]
<vue-cropper> 这个

**Comment by ArrayZheng** [comment]
`npm install vue-cropper`
import vueCropper from 'vue-cropper'
然后调用组件
```
<div class="test">
          <vueCropper
            ref="cropper3"
            :img="example3.img"
            :autoCrop="example3.autoCrop"
            :autoCropWidth="example3.autoCropWidth"
            :autoCropHeight="example3.autoCropHeight"
            :fixedBox="example3.fixedBox"
          ></vueCropper>
        </div>
```
`别的就没有了```

**Comment by xyxiao001** [comment]
你看看你的img 传过去没有， 应该是img没传到组件

**Comment by ArrayZheng** [comment]
对啊 ，就是没传到组件里去，只要data里的img有内容就报错
**First argument to DataView constructor must be an ArrayBuffer**

**Comment by ArrayZheng** [comment]
![image](https://user-images.githubusercontent.com/21194346/34807086-b36b4f22-f6c1-11e7-8ee4-e5a468f0c429.png)

**Comment by xyxiao001** [comment]
截图代码看看

**Comment by ArrayZheng** [comment]
![image](https://user-images.githubusercontent.com/21194346/34807282-d937a1dc-f6c2-11e7-802d-ca474319e4d9.png)
这是引进的包

![image](https://user-images.githubusercontent.com/21194346/34807245-98bbdf7e-f6c2-11e7-9eff-dcdaeb587c80.png)
这是template里的

![image](https://user-images.githubusercontent.com/21194346/34807273-cc356bb8-f6c2-11e7-9ad8-25af63e41ddc.png)
这是js部分的

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/34807315-07b88b5c-f6c3-11e7-9323-af8eb52ad59b.png)

这个值有吗 example2.img

**Comment by ArrayZheng** [comment]
![image](https://user-images.githubusercontent.com/21194346/34807438-c3509846-f6c3-11e7-803e-c6eb498e8b45.png)
有啊 
http://ofyaji162.bkt.clouddn.com/bg1.jpg
这原封不动copy您的哇

**Comment by xyxiao001** [comment]
那你直接在 写
```
:img="https://o90cnn3g2.qnssl.com/0C3ABE8D05322EAC3120DDB11F9D1F72.png"
```
看看

**Comment by xyxiao001** [comment]
还不行加我qq 463618622的

**Comment by ArrayZheng** [comment]
这个肯定不行啊 ，:img是vue实例绑定的属性，里面必须是data返回的属性值，那样的话直接报错。去掉：也不行哈

**Comment by fidding** [comment]
@ArrayZheng 请问这个错误问题解决了么？

**Comment by wypsanity** [comment]
我也出现这种情况！楼主

**Comment by xyxiao001** [comment]
是不是因为prop img没传过去

**Comment by fidding** [comment]
@xyxiao001 谢谢，初步确认是因为prop img传递的类型不正确。

**Comment by cmtj199337** [comment]
我也遇到这个问题，但是我init的新项目就没有这个问题

**Comment by xyxiao001** [comment]
可能是mock服务的问题

**Comment by cmtj199337** [comment]
有好的解决办法吗

**Comment by xyxiao001** [comment]
目前还不知道为什么mock会引发这个问题  你直接传url也会报错吗

**Comment by cmtj199337** [comment]
ok，确实是mock的问题，解决啦。谢谢

**Comment by cmtj199337** [comment]
直接传也报错，prop也传过去了。而且不管怎样，src都是unknow

**Comment by xyxiao001** [comment]
mock为啥呢 我这边自己去装个mock看看

**Comment by sparGuan** [comment]
这个bug好严重啊

**Comment by sparGuan** [comment]
我现在是不能去除mock
