### ISSUE TITLE
'vueCropperGlobal' is a type and must be imported using a type-only import

### ISSUE THREAD

**Issue by pengfan2013** [xyxiao001/vue-cropper#621]
error TS1444: 'vueCropperGlobal' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

**Comment by xyxiao001** [comment]
https://github.com/xyxiao001/cropper-test/tree/master/src  看看例子

**Comment by xyxiao001** [comment]
ok 1.04版本解决了这个问题，改为 type引入
