### ISSUE TITLE
为啥报Home.vue?bff2:42 Uncaught ReferenceError: vueCropper is not defined？？

### ISSUE THREAD

**Issue by 91martincheung** [xyxiao001/vue-cropper#63]
![image](https://user-images.githubusercontent.com/29765895/34811790-90b4fe26-f6dd-11e7-97c7-5920003b61a8.png)
安装npm install vue-cropper
使用 import VueCropper from vue-cropper

都是按步骤来的，删了重装还是这样

**Comment by xyxiao001** [comment]
没引入成功吧  你在mounted里面打印vueCropper看看

**Comment by xyxiao001** [comment]
![v8d9b um_ zl22zjv8c vtl](https://user-images.githubusercontent.com/15681693/34812074-01339fda-f6df-11e7-9b51-65e2be0970df.png)
 上下大小写一致

**Comment by 91martincheung** [comment]
嗯嗯，这个是咋回事呢？
![image](https://user-images.githubusercontent.com/29765895/34812132-4d59017a-f6df-11e7-8c4c-cbd047bb22d7.png)

**Comment by xyxiao001** [comment]
这个是你ref没声明吧 通过组件实例去调用方法

**Comment by xyxiao001** [comment]
打印看看this.$refs.cropper是不是组件的

**Comment by 91martincheung** [comment]
不行打印不出来。。。。

**Comment by xyxiao001** [comment]
那说明你this指向出了问题 或者ref名字不是这个

**Comment by 91martincheung** [comment]
😭请问如何更改呢

**Comment by xyxiao001** [comment]
![ak1smlhx 3_gl_l2t42b4 r](https://user-images.githubusercontent.com/15681693/34813825-5edfc4cc-f6e6-11e7-9fc4-f2656fdfd7da.jpg)
不知道你怎么写的 可能是函数里面this指向变了

**Comment by 91martincheung** [comment]
![2018-01-1111](https://user-images.githubusercontent.com/29765895/34813971-04100e98-f6e7-11e7-85f2-18f7a8153161.png)😖

**Comment by xyxiao001** [comment]
![image](https://user-images.githubusercontent.com/15681693/34814035-3ea95a1e-f6e7-11e7-8b90-26eaf3aa6a34.png)
上面是cropper2 下面是cropper

**Comment by 91martincheung** [comment]
![image](https://user-images.githubusercontent.com/29765895/34814200-be783850-f6e7-11e7-8ce0-62dac899c9a0.png)
改了还是报同样的错。。。。

**Comment by xyxiao001** [comment]
？ 这些button不需要啊   组件实例上写ref="cropper"  因为你下面调用写的是cropper

**Comment by 91martincheung** [comment]
![image](https://user-images.githubusercontent.com/29765895/34814875-39c85c4a-f6ea-11e7-9ec7-217ef337eec5.png)
preview(base64)没反应是啥情况？

**Comment by xyxiao001** [comment]
你看看回调函数执行没有 打印下的

**Comment by 91martincheung** [comment]
![image](https://user-images.githubusercontent.com/29765895/34815042-e12c8ca4-f6ea-11e7-8120-71a8fe488338.png)

**Comment by xyxiao001** [comment]
我的意思是在回调函数里面打印 看看执行回调函数没有

**Comment by 91martincheung** [comment]
![image](https://user-images.githubusercontent.com/29765895/34815147-3e2330ca-f6eb-11e7-9fed-64412ab74559.png)
执行了else里的

**Comment by xyxiao001** [comment]
这就是回调回来的base64的

**Comment by 91martincheung** [comment]
再问个问题，怎么看到截取后的图片？

**Comment by xyxiao001** [comment]
把数据放在img src上面就行

**Comment by 91martincheung** [comment]
感谢！！么么哒

**Comment by 91martincheung** [comment]
我想问问就是手机上测试，当裁剪框跟页面的宽度一样的时候，框里的图片是不是不能移动和放大缩小？

**Comment by xyxiao001** [comment]
有属性 固定截图框就可以

**Comment by xyxiao001** [comment]
现在还没有这个方法

**Comment by 91martincheung** [comment]
希望大神哥哥能加这新功能~🙇
