### ISSUE TITLE
当裁剪图片小于裁剪框时，在导出 jpg 格式的时候，透明区域的填充颜色是否可以支持自定义，现在默认是黑的

### ISSUE THREAD

**Issue by Eurkidu** [xyxiao001/vue-cropper#634]
## 使用场景
裁剪框固定1:1，裁剪图片，因为需要可以展示全图，所以当长方形图片进行裁剪时，会缩放图片，左右留白

## 复现步骤
裁剪框调整至如下
![image](https://user-images.githubusercontent.com/13271070/169809060-778abf47-4dd8-41ea-9bae-45bcb4f205bb.png)

导出格式选择 `jpeg`, 使用 `getCropData` 或者 `getCropBlob` 获得图片

## 现有问题 
查看预览时可以发现获得的图片透明部分填充的颜色是黑色
![image](https://user-images.githubusercontent.com/13271070/169809455-9f73e1cc-1ae7-4a62-a050-f7b0ca9be4be.png)

## 希望效果
是否可以增加一个自定义参数，设定默认的填充颜色

应该可以在这里实现，给 canvas 设定一个默认背景色
https://github.com/xyxiao001/vue-cropper/blob/713cd62cee57fa9e40548e8301c27918b7e6f53e/src/vue-cropper.vue#L1345-L1349

**Comment by xyxiao001** [comment]
可以的，我看看暴露一个参数出去

**Comment by yuzjoey** [comment]
可以将导出格式设置为png,这样可以保留图片的透明部分。

**Comment by Mr-Lee0318** [comment]
> 可以的，我看看暴露一个参数出去
大佬解决了吗 这个问题  我现在使用背景透明的图片 出来结果是黑色

**Comment by xyxiao001** [comment]
> > 可以的，我看看暴露一个参数出去
> > 大佬解决了吗 这个问题  我现在使用背景透明的图片 出来结果是黑色

设置输出png就行了
