### ISSUE TITLE
有没有办法控制宽高比例在一定范围内

### ISSUE THREAD

**Issue by miaowwwww** [xyxiao001/vue-cropper#635]
如题。
一个奇怪的需求。
宽高比例最小16:9， 最大1:1.。。。。
例如：width=320， height= [180~320]之前

**Comment by miaowwwww** [comment]
我尝试了在realTime中进行wh的判断，然后设置 cropH。但是效果不大如意。
<img width="438" alt="image" src="https://user-images.githubusercontent.com/17811091/170933705-2489e524-7820-4e33-81ff-e7c42716e0db.png">

**Comment by xuedongwang** [comment]
@miaowwwww 
```js
// 是否开启固定宽高比
    fixed: {
      type: Boolean,
      default: false
    },
    // 宽高比 w/h
    fixedNumber: {
      type: Array,
      default: () => {
        return [1, 1];
      }
    },
```
看源码有这两个属性，也许你有用。
