### ISSUE TITLE
0.5.8 跨域最大的BUG

### ISSUE THREAD

**Issue by dehyang** [xyxiao001/vue-cropper#641]
![image](https://user-images.githubusercontent.com/83799221/176069121-e66313df-5e55-42c8-b7b8-0c902b533b58.png)

配置了一天腾讯云，还把腾讯骂了。。结果是这个BUG！！！

**Comment by dehyang** [comment]
`if (this.img.substr(0,4) !== "data") {
     img.crossOrigin = "Anonymous";
}`

修改成

**Comment by yi00nine** [comment]
If crossOrigin is an empty string (""), the anonymous mode is selected.
设置空字符串不是会默认选中anonymous模式嘛

**Comment by dehyang** [comment]
> If crossOrigin is an empty string (""), the anonymous mode is selected. 设置空字符串不是会默认选中anonymous模式嘛

我的无知，也是被坑了，刚好改了配置，也清了缓存就可以。最后发现是缓存问题！！

例如先用 img标签加载图片，然后再用这个链接去截图，就会提示跨域！ 有些图片默认返回头部没有加 Access-Control-Allow-Origin 。。点名腾讯云  cos！配置了一天了！

**Comment by dehyang** [comment]
关闭
