### ISSUE TITLE
vite@2.9.10，vue@3.2.37，Property "$createElement" was accessed during render but is not defined on instance.

### ISSUE THREAD

**Issue by iamdanta** [xyxiao001/vue-cropper#643]
![image](https://user-images.githubusercontent.com/37389328/177236966-5b0b62cb-0512-4cc9-9ff0-dfd89c959f89.png)
看来vuevite高一点的版本也不太行。。
1.0.3反馈

**Comment by xyxiao001** [comment]
我测试发现 3.2.37 是可以的
