### ISSUE TITLE
ie11 图片为base64如何解决哇，大佬能不能看看哇求

### ISSUE THREAD

**Issue by wuzhouchao** [xyxiao001/vue-cropper#649]
![1658477163369](https://user-images.githubusercontent.com/62629899/180393623-1d7994a3-2e7e-42b7-8465-ba50afb192e8.png)
这里能不能增加个判断，判断下this.img是url还是base64 或者进行trycatch

**Comment by xyxiao001** [comment]
你可以在外面判断下 ie，转化为 blob 传入试一试
