### ISSUE TITLE
能不能写更多的内置方法？ 比如：我想获取图片相对于截图框平移了多少？

### ISSUE THREAD

**Issue by JackFrancisLiu** [xyxiao001/vue-cropper#65]
https://developer.qiniu.com/dora/manual/1270/the-advanced-treatment-of-images-imagemogr2
这是七牛云的服务器端截取需要的参数，您这个插件里并没有这么多参数，能不能返回更多的参数信息和写更多的内置方法。

**Comment by xyxiao001** [comment]
后续开发， 会增加这些接口参数的返回

**Comment by xyxiao001** [comment]
目前可以直接通过 
this.$refs.cropper.x
this.$refs.cropper.y
this.$refs.cropper.scale
来获取图片偏移  和缩放

**Comment by JackFrancisLiu** [comment]
可是我看您文档上没写？那我试试，谢谢您

**Comment by JackFrancisLiu** [comment]
![image](https://user-images.githubusercontent.com/25114528/34924421-2d9ce778-f9de-11e7-8c9c-537b416f6024.png)
比如：translate3d里面的x方向的平移您返回的感觉不对啊

**Comment by xyxiao001** [comment]
不对 我忘记了这是相对于外层框的位置   截图框的计算也是相对于外层框的

**Comment by xyxiao001** [comment]
后续我会加上图片相对于截图框的位置

**Comment by JackFrancisLiu** [comment]
this.$refs.cropper.x那这个方法是获取图片相对于外层框的位置，现在有没有截图框相对于外层框的位置，如果有做个减法我就能获取了

**Comment by xyxiao001** [comment]
如果图片不旋转就可以
cropX
cropY

**Comment by xyxiao001** [comment]
旋转之后涉及到的计算就比较复杂了

**Comment by JackFrancisLiu** [comment]
好的，我先设计不让用户旋转这边也行。谢谢您

**Comment by JackFrancisLiu** [comment]
this.$refs.cropper.cropX;并不能获取截图框距离外层框的距离，不过没关系。这插件很棒了

**Comment by xyxiao001** [comment]
插件开发不够完善 后续会重构的

**Comment by JackFrancisLiu** [comment]
好的，加油！

**Comment by xyxiao001** [comment]
已经在0.3版本加上 获取坐标的函数
