### ISSUE TITLE
为什么我的裁剪框和实际输出图片的尺寸不一致

### ISSUE THREAD

**Issue by HillStupidBear** [xyxiao001/vue-cropper#652]
组件是封装后通过dialog弹出调用的，
但是使用中，infoTrue设成true和false尺寸是不一致的，
截图框的尺寸通过autoCropWidth和autoCropHeight约束了
但是实际输出的图片尺寸会受到外层dialog的影响，
dialog较大时，输出图片尺寸会被放大，
dialog较小时尺寸会缩小
比如我autoCropWidth和autoCropHeight设置了1248*702，
但是在dialog较大的情况下，裁剪输出的结果可能是1560*878
并且enlarge参数设置了不生效
`<vue-cropper ref="cropper" :img="option.img" :outputSize="option.outputSize" :outputType="option.outputType"
          :info="option.info" :canScale="option.canScale" :autoCrop="option.autoCrop"
          :autoCropWidth="option.autoCropWidth" :autoCropHeight="option.autoCropHeight" :fixed="option.fixed"
          :fixedNumber="option.fixedNumber" :full="option.full" :fixedBox="option.fixedBox" :canMove="option.canMove"
          :canMoveBox="option.canMoveBox" :original="option.original" :centerBox="option.centerBox"
          :height="option.height" :infoTrue="option.infoTrue" :maxImgSize="option.maxImgSize" :enlarge="option.enlarge"
          :mode="option.mode" @imgLoad="imgLoad">
        </vue-cropper>`

`props: {
    image: {
      required: true
    },
    autoCropWidth: {
      type: Number,
      default: 480,
    },
    autoCropHeight: {
      type: Number,
      default: 360,
    },
fixedNumber: {
      type: Array,
      default: () => {
        return [4, 3]
      },
    },
  },`

`return {
      option: {
        img: this.image,
        outputSize: 1,
        outputType: 'jpeg',
        info: true,
        canScale: true,
        autoCrop: true,
        autoCropWidth: this.autoCropWidth,
        autoCropHeight: this.autoCropHeight,
        fixed: true,
        fixedNumber: this.fixedNumber,
        fixedBox: true,
        canMove: true,
        canMoveBox: true,
        centerBox: false,
        full: true,
        original: true,
        height: true,
        infoTrue: true,
        maxImgSize: 2000,
        enlarge: 1,
        mode: '100%'
      }
    };`

**Comment by xyxiao001** [comment]
可以压缩下， 或者通过 enlarge 控制

**Comment by HillStupidBear** [comment]
> 

谢谢，我把enlarge改成2然后把截图框缩小到1/2解决问题了。
enlarge设置成1好像并不会按照1倍比例输出。
我在在线的demo试了一下发现enlarge设置成1，160*90的裁剪框输出后依旧会变成200*113
但是enlarge设成非1的数值就能正确缩放

**Comment by dzl157044** [comment]
谢谢大佬我也遇到了,苹果电脑不适配,但是windows是可以的

**Comment by linnngz** [comment]
我设置full：false生效了。
