### ISSUE TITLE
vue版本 3.0.0 使用后报错 ！

### ISSUE THREAD

**Issue by 13622831458** [xyxiao001/vue-cropper#653]
vue版本 3.0.0 使用后报错 ！

**Comment by xyxiao001** [comment]
3.0版本需要安装 next 版本，可以看看文档

**Comment by 13622831458** [comment]
> 
已经安装了next 版本啦，vue3.0.0版本按照文档引入报错

**Comment by 13622831458** [comment]
> 3.0版本需要安装 next 版本，可以看看文档



> 3.0版本需要安装 next 版本，可以看看文档

**Comment by 13622831458** [comment]
> 3.0版本需要安装 next 版本，可以看看文档

已经安装了next版本啦，vue3.0.0版本按照文档引入报错

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/yLooYKg  看看例子
