### ISSUE TITLE
如何重置最初始的状态，默认生成裁剪框之后拖动放大后，想要重置回原始状态，如何处理

### ISSUE THREAD

**Issue by zhongyi07** [xyxiao001/vue-cropper#654]
手动重置裁剪框的大小，如果靠近边界，会超出画布
<img width="483" alt="iShot2022-08-10 15 46 59" src="https://user-images.githubusercontent.com/87864512/183846151-9af1f996-a7d2-402c-8a85-18d927672397.png">
如果强行改变裁剪框的transform，会连同画布一起拖动了

<img width="449" alt="iShot2022-08-10 15 49 27" src="https://user-images.githubusercontent.com/87864512/183846227-a84ae4c3-202c-479c-81df-a44547655250.png">

**Comment by zhongyi07** [comment]
![infoflow 2022-08-12 10-15-02](https://user-images.githubusercontent.com/87864512/184272573-1d92c34d-a1a9-484b-99c5-c30007ad630a.png)
这个回调就可以了。。。。。。。。。。。。

**Comment by xyxiao001** [comment]
是的 或者调用 refresh

**Comment by zhongyi07** [comment]
调用完goAutoCrop初始坐标有问题，我自己从新计算初始坐标了
