### ISSUE TITLE
大佬能不能把操作台的background-img给暴露出来啊  

### ISSUE THREAD

**Issue by WHmuse** [xyxiao001/vue-cropper#659]
大佬能不能把操作台的background-img给暴露出来可以diy啊  我想换个底图  现在这种马赛克的有点不是很想用

**Comment by xyxiao001** [comment]
可以通过 css 替换

**Comment by WHmuse** [comment]
大佬我可以把写代码运用到我们公司的项目中么



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月08日 12:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [xyxiao001/vue-cropper] 大佬能不能把操作台的background-img给暴露出来啊   (Issue #659) |

可以通过 css 替换
