### ISSUE TITLE
vite3下无法使用

### ISSUE THREAD

**Issue by remiliyaScarlet** [xyxiao001/vue-cropper#666]
![image](https://user-images.githubusercontent.com/38554772/203475544-bb2e73d8-d4cd-4d66-85f0-0609d93d618c.png)
版本用的是最新的1.0.5，但是我看依赖包里用的还是vite2的

![image](https://user-images.githubusercontent.com/38554772/203475474-f74e64b6-fda2-416c-8caa-38e70b21c083.png)

**Comment by xyxiao001** [comment]
我看看，这个是例子，应该不影响编译后的代码吧

**Comment by jim1010** [comment]
请问这个问题解决了吗？我也需要同样的问题

**Comment by xyxiao001** [comment]
周末会更新发布一个版本，到时内部编译会升级为 vite3.x, 到时我发布后可以试一试看看
