### ISSUE TITLE
Min-width, min-height

### ISSUE THREAD

**Issue by carlcoks** [xyxiao001/vue-cropper#67]
It will be great if you added min-width and min-height. Please, sir, can you add it?

**Comment by xyxiao001** [comment]
What do you say is cut box  or a image

**Comment by carlcoks** [comment]
class -> .cropper-crop-box
i think, cut box?! =)

**Comment by xyxiao001** [comment]
yeah i will add it

**Comment by carlcoks** [comment]
you're the best)

**Comment by lishichao1002** [comment]
什么时候能看到这个特性呢？

**Comment by xyxiao001** [comment]
新版本在next分支开发的，图片最小，最大，截图框最小，最大，都可以加上的。

**Comment by lishichao1002** [comment]
什么时候发版到npm包里面呢？

**Comment by xyxiao001** [comment]
😂大概要年后，正在开发中，还要测试
