### ISSUE TITLE
v3.0中使用，预览变形严重

### ISSUE THREAD

**Issue by baimingxuan** [xyxiao001/vue-cropper#674]
![微信截图_20221208172503](https://user-images.githubusercontent.com/26238723/206409370-40d1b867-1ba1-4633-b03f-e27746c88280.png)
v3.0中使用，预览变形严重，分辨率过高的图片无法再预览区出现

**Comment by xyxiao001** [comment]
看看是不是项目中的 css 属性影响了

**Comment by wuchaoxin** [comment]
我也遇到了同样的问题，发现作者说的没错，是其他样式影响了预览区域的图片。F12 查看图片的样式，一个个取消掉公有 img 样式（比如 max-width），即可解决。
