### ISSUE TITLE
blob格式跨域问题

### ISSUE THREAD

**Issue by susuJiang** [xyxiao001/vue-cropper#683]
![vue-cropper](https://user-images.githubusercontent.com/20085925/211518941-87e28c81-e7bc-4838-9bcb-0d9e1268ea82.jpg)
用vue-cropper在本地开发项目时，预览和截取图片一切都正常，但上传到生产环境时，一直提示如上问题，【Refused to load the image 'blob:https://.../ccfef582-96d1-4654-b83d-e118027a2969' because it violates the following Content Security Policy directive: "img-src 'self' data:".】去搜索关于Content Security Policy 的解决办法，大部分说shi CSP的问题，加上<meta http-equiv="Content-Security-Policy" content="default-src *;img-src 'self' data: base64; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"/> 就可以了，我在项目里面加了，怎么改都无效，没办法只能修改vue-cropper源码，把源码初始化相关的blob格式图片转换成base64格式的图片那部分代码重写，然后用patch-package插件打补丁上传到git环境，重新发布，图片就能正常显示了。希望同样遇到这个问题的可以参考一下。

**Comment by xyxiao001** [comment]
This is the fix for either image and base64.

Need to add img-src 'self' blob: data:; As follow:

<meta http-equiv="Content-Security-Policy" 
    content="
      worker-src blob:; 
      child-src blob: gap:;
      img-src 'self' blob: data:;
      default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:">

**Comment by inoryxun** [comment]
> `<meta http-equiv="Content-Security-Policy" content=" worker-src blob:; child-src blob: gap:; img-src 'self' blob: data:; default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:">`

vue3 添加了这个，也不行
