### ISSUE TITLE
怎么让图片默认铺满容器

### ISSUE THREAD

**Issue by genwohuijia** [xyxiao001/vue-cropper#686]
![微信截图_20230201100318](https://user-images.githubusercontent.com/35017877/215927124-498aceb3-8f54-488e-b2db-dd925e858fbb.png)
mode属性只能针对大图  那类似这种小图如何”默认！“铺满容器？

**Comment by xyxiao001** [comment]
mode: cover 小图也可以铺满

**Comment by genwohuijia** [comment]
> mode: cover 小图也可以铺满

谢谢了，刚开始改mode属性没生效，大图是刚好铺满以为只针对大图，但是刚看源码发现小图也是铺满的，回来一看组件上边没绑定mode属性，一直改的是data中的mode，被自己蠢到了o.0
还有个问题，看源码发现图片缩放是用scale控制的，但是直接修改$refs.cropper.scale，图片没进行放大缩小啊

**Comment by xyxiao001** [comment]
直接修改，应该是生效的啊，或者你通过 $refs.cropper.changeScale  传入正负数来控制缩放

**Comment by genwohuijia** [comment]
> 直接修改，应该是生效的啊，或者你通过 $refs.cropper.changeScale 传入正负数来控制缩放

嗯嗯  我是在watch中监听上传图片后img.onload中改变 $refs.cropper.scale的，应该是设置之后，源码里边的checkedImg方法又把scale重置成1了
