### ISSUE TITLE
Wtf your docs and your code comments in chinese ...

### ISSUE THREAD

**Issue by stouch** [xyxiao001/vue-cropper#689]
Seriously guys, it's more and more frequent in chinese projects... Why do you write your docs and code comments in chinese... Stop doing this, use english please... You are slowing opensource love...

**Comment by xyxiao001** [comment]
First of all, thank you for your attention. Because I am Chinese, the comments and documents are written in my native language, but the corresponding English documents are also added to the top of my document. I will complete the corresponding English comments in the comments in the subsequent code.

**Comment by clordho** [comment]
Maybe you should use 'English doc please' instead of 'wtf'.
And then you will find [REAMDME_english](https://github.com/xyxiao001/vue-cropper/blob/master/english.md) if you can read English.

**Comment by stouch** [comment]
I was not able to understand some comments in code , everything in chinese. Nobody on earth do this for international project.. (even in France we have big issues with speaking english but we ensure that our opensource projects can be improved worldwide...) I see this behaviour in many of chinese repo on github... So, yes : wtf.

**Comment by johnmap** [comment]
If that bothers you, instead of being rude about it you could consider making a pull request with improved English documentation 🤷‍♂️

**Comment by stouch** [comment]
Sorry I am not going to change a common chinese developers behaviour . I just switched to another project because I cannot contribute to this one
