### ISSUE TITLE
设置了fixed:false 和 centerBox:true 时图片未限制在图片内部

### ISSUE THREAD

**Issue by liyangyangi** [xyxiao001/vue-cropper#695]
![image](https://user-images.githubusercontent.com/22519600/223612701-395570e7-ba19-452a-b601-0400dd10d133.png)
![image](https://user-images.githubusercontent.com/22519600/223612729-5bb639d6-396d-4be1-95d3-ee53be0d6f98.png)

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/wxwKGz  看看例子 我刚刚测试没复现，你可以用 vue devtools看看组件参数嘛
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/15681693/223615995-78956747-5277-42a7-8202-7ed7f26a00d7.png">

**Comment by liyangyangi** [comment]
![image](https://user-images.githubusercontent.com/22519600/223618729-b66dc2df-72dc-4416-bd8e-96d4352ec939.png)

**Comment by liyangyangi** [comment]
奇怪，我在例子也没复现

**Comment by xyxiao001** [comment]
https://codepen.io/xyxiao001/pen/yLooYKg  我看 vue3 版本也不存在问题

**Comment by xyxiao001** [comment]
你用来哪个版本，有可能是版本过低导致的

**Comment by liyangyangi** [comment]
vue2  0.5.8 版本

**Comment by xyxiao001** [comment]
那应该不会啊 是最新的版本，看看是不是在 load 之后，改动了截图框大小的，如果手动操作可能会出问题。如果不能解决，你可以设置截图框小一点，小于外层容器大小就行

**Comment by liyangyangi** [comment]
嗯嗯 小于容器是没问题的 ，但是截图尺寸不是死的，我再新建个简单的项目试试
