### ISSUE TITLE
IE兼容问题

### ISSUE THREAD

**Issue by paddingH** [xyxiao001/vue-cropper#699]
Error in mounted hook: "Error: 拒绝访问。  
found in
---> <VueCropper> at [src/vue-cropper.vue[](url)](url)

![image](https://user-images.githubusercontent.com/15725390/224528953-1e4b7e2e-abca-48f6-8564-0b7d0a9f4e76.png)

**Comment by xyxiao001** [comment]
ie 的话把图片处理为blob url 或者用在线url方式传入

**Comment by paddingH** [comment]
感谢，解决了 大佬666
