### ISSUE TITLE
怎么设置viewMode参数？

### ISSUE THREAD

**Issue by wscart** [xyxiao001/vue-cropper#7]
在手机上图片比例没有铺满，看了cropper文档里面有viewMode，但是在你开发的vue-cropper上好像缺少了这个支持，那么怎么设置viewMode?

**Comment by wscart** [comment]
对的，在底层上图片比例要铺满

**Comment by xyxiao001** [comment]
目前没这功能 我后续加上去。 我会加上手机端手机缩放的

**Comment by wscart** [comment]
这样谢谢了

**Comment by wscart** [comment]
在node_modules里面可以修改代码吗

**Comment by xyxiao001** [comment]
可以修改的 修改后打包就是你修改的

**Comment by wscart** [comment]
恩，是/src这个路径没错吗

**Comment by wscart** [comment]
如果是正确的话 为什么没生效？

**Comment by xyxiao001** [comment]
你想生效什么功能

**Comment by wscart** [comment]
我写console.log，然后在浏览器上没有收到console信息。
这好像是说 路径不对吗 还是要重新打包？

**Comment by xyxiao001** [comment]
重启服务呢 应该是修改后就会生效

**Comment by wscart** [comment]
重启服务是指npm run dev还是？

**Comment by xyxiao001** [comment]
npm run dev

**Comment by wscart** [comment]
没生效的  - -！
<img width="495" alt="wx20170802-152448 2x" src="https://user-images.githubusercontent.com/3970076/28862229-dfe5e526-7796-11e7-9b4a-ccf91f99dd0d.png">

**Comment by xyxiao001** [comment]
这个是当移动图片才会触发的

**Comment by wscart** [comment]
没错  但我有动几次移动，没有触发
我想说，是不是路径有问题？  是src 还是example/src? 或者dist？

**Comment by xyxiao001** [comment]
你直接改源码没用 在里面重新打包 因为引入的是dist的  
我觉得你要改 直接把vue-cropper 复制出去当做你的组件 这样更方便

**Comment by xyxiao001** [comment]
复制 src 里面的vue-cropper 就行

**Comment by wscart** [comment]
说的是哈哈  谢谢

**Comment by Mrlilili** [comment]
是在哪里改的viewMode？
