### ISSUE TITLE
当两次同时上传同一张图片时，截图框的显示比例及位置跟上次最后调整的一样，不是新设置的fixedNumber值

### ISSUE THREAD

**Issue by tomorrowface** [xyxiao001/vue-cropper#70]
我要实现的是上传一组图，大小不一样。
第一步：上传图片a，截图框比例设为3：5，成功裁剪
第二步：上传图片b，截图框比例设为14：9，成功裁剪

但下面的情况会出问题：
第一步：上传图片a，截图框比例设为3：5，成功裁剪
第二步：上传图片a，截图框比例设为14：9，显示的截图框比例还是3：5，这时手动调整截图框，截图框的比例会立马变成正确的14：9

当两次同时上传同一张图片时，截图框的显示比例跟上次一样，不是设置的fixedNumber值

**Comment by xyxiao001** [comment]
重新设置fixedNumber 需要手动执行refresh方法
