### ISSUE TITLE
版本号兼容问题

### ISSUE THREAD

**Issue by PL-FE** [xyxiao001/vue-cropper#702]
你好
0.5.10 版本去除了兼容性代码 this.$emit("imgLoad", "success");
导致vue2项目自动升级了0.5.10
建议非兼容性升级，可以+1大版本号。如：1.0.0

**Comment by xyxiao001** [comment]
ok，目前是统一了 emit 的方法，通过 emit('img-load')进行触发，你这边通过 imgLoad 应该也是可以监听到的

**Comment by PL-FE** [comment]
已经收到您的来信，我会尽快回复。

**Comment by xyxiao001** [comment]
ok  vue2的版本我修复下
