### ISSUE TITLE
vue3无法使用vue-cropper,一直报错

### ISSUE THREAD

**Issue by liujianya371** [xyxiao001/vue-cropper#706]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/4703288/228224128-59457fc0-c84e-4799-a9d2-4d7e50309526.png">

<img width="903" alt="image" src="https://user-images.githubusercontent.com/4703288/228223333-cbb90bec-6445-4fd0-8418-d5679d65f2e6.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/4703288/228223475-7c2c3879-3618-477a-9032-f61b07d9a053.png">

**Comment by xyxiao001** [comment]
我这边测试是可以的
https://codesandbox.io/s/vue-cropper-test-1-0-7-mm53jw
刚刚新建的例子

**Comment by liujianya371** [comment]
这个连接上确实可以 ，但我将demo下载下来，yarn install 安装，yarn serve运行，发现不行。
首先代码报定义却未引用，可是demo明明有引用。
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by liujianya371** [comment]
这个连接上确实可以 ，但我将demo下载下来，yarn install 安装，yarn serve运行，发现不行。本地运行看不到连接上的效果。
首先代码报定义却未引用，可是demo明明有引用。
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/4703288/228408856-6818e686-f09a-4410-9100-79199dd13edb.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4703288/228408911-b50e4854-c62d-41b3-8c3b-47bd26519df9.png">

**Comment by liujianya371** [comment]
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/4703288/228409069-6f9f4b5e-e74f-4623-bee0-a77a26ca4c07.png">
我是在这里下载的

**Comment by xyxiao001** [comment]
这个和组件没关系哈，是 setup 语法和 eslint 校验的关系

**Comment by liujianya371** [comment]
我从新用vite创建了哥vue3工程，按照demo引入，可以了,感谢
以下是非常简易的demo
有需要的同学可以下载
[vue3-copper-demo.zip](https://github.com/xyxiao001/vue-cropper/files/11107010/vue3-copper-demo.zip)
