### ISSUE TITLE
关于0.5.10不会自动升级0.6.1的问题

### ISSUE THREAD

**Issue by PL-FE** [xyxiao001/vue-cropper#708]
大佬你好，看到今天你发的新包了。但是我还有个问题。

项目中`vue-cropper@^0.5.5` 不能自动升级到 0.6.1.还是升级到 0.5.10。
大佬要不要补一个0.5.11😂,涉及项目比较多。

>^指明的版本范围，只要不修改 [major, minor, patch] 三元组中，最左侧的第一个**非0位**，都是可以的。也就是说，要确定 ^版本包含的范围，先要找到 最左侧的第一个非0位 ，只有在这一位右侧的变动，才被包含在这个 ^ 指定的范围内。举个 ：
^1.2.3版本包括：>= 1.2.3 并且 < 2.0.0
^0.2.3版本包括：>= 0.2.3 并且 < 0.3.0
^0.0.3版本包括：>= 0.0.3 并且 < 0.0.4

https://semver.npmjs.com/#syntax-examples

![image](https://user-images.githubusercontent.com/41770773/228465219-4e048526-44ac-471b-b252-c1f2fb41862a.png)

**Comment by xyxiao001** [comment]
可以的，我新发一个包

**Comment by xyxiao001** [comment]
已经更新了

**Comment by PL-FE** [comment]
感谢💖
