### ISSUE TITLE
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by wwq146213** [xyxiao001/vue-cropper#715]
通过扫描仪扫描到的图片 给img  src可以正常显示 点击编辑的时候报错
![image](https://user-images.githubusercontent.com/93062479/232452977-fefaa854-4fca-44f4-9a72-e1c19a6e3e6e.png)

**Comment by xyxiao001** [comment]
可以试一试转成 blob url 然后传递给组件

**Comment by wwq146213** [comment]
![image](https://user-images.githubusercontent.com/93062479/232453625-64d11495-468b-4c6f-8af7-5bc0f83977d2.png)
