### ISSUE TITLE
因插件源码中`t.preventDefault()`，而导致的控制台报错：`Unable to preventDefault inside passive event listener invocation.`

### ISSUE THREAD

**Issue by recreyed** [xyxiao001/vue-cropper#721]
![image](https://user-images.githubusercontent.com/83416709/233910253-2a690ebf-668e-437e-80f1-0b5e3d61413e.png)
vue-cropper版本：0.4.9（最新版0.5.11也测试过了，也是一样）  
使用环境：vue2，antdesign组件库，modal组件中。
![image](https://user-images.githubusercontent.com/83416709/233911403-0cf6cf48-634c-4312-a0c9-ff458cd0854d.png)

在去掉插件源码中所有的`t.preventDefault()`后，报错消失，我在网上查了相关原理  
https://www.cnblogs.com/L-xmin/p/12495065.html  
想问一下问什么源码中要加入`t.preventDefault()`，不可以去掉吗？  
虽然现在github的在线用例中，没有出现此问题，但是上述的开发环境中确实出现了，不知怎么修正，按照[上述链接](https://www.cnblogs.com/L-xmin/p/12495065.html )中的方法也没能解决，只有删除了源码中的`t.preventDefault()`才丑陋的修复了，望指点一二

**Comment by xyxiao001** [comment]
可以看看 最新的 chrome 有问题嘛，我测试看是没有报错的

**Comment by recreyed** [comment]
> 可以看看 最新的 chrome 有问题嘛，我测试看是没有报错的

个人觉得就是因为是最新的chrome版本，才会出现上述问题的。
![image](https://user-images.githubusercontent.com/83416709/233912442-2b23be6d-69f6-43bc-80e1-59224c61ee23.png)
另外，项目需求中需要把vue-cropper放到antdesign的modal弹窗中，实际单独使用我没有测试。

**Comment by xyxiao001** [comment]
https://github.xyxiao.cn/vue-cropper/docs/vue3.html  直接访问这个链接呢

**Comment by recreyed** [comment]
> https://github.xyxiao.cn/vue-cropper/docs/vue3.html 直接访问这个链接呢

我在上面提到了呀，访问插件的在线用例，没有出现控制台报错

**Comment by xyxiao001** [comment]
那有可能是 ant -design modal 的冲突吧

**Comment by recreyed** [comment]
测试新建的vue2项目中是正常的，有能是项目中webpack的问题，但依然不理解为什么要加`t.preventDefault()`，看来是无无法完美解决了，就这样吧，关闭issue了  :expressionless:
