### ISSUE TITLE
可以添加一个背景充颜色的参数吗

### ISSUE THREAD

**Issue by mjqbpais** [xyxiao001/vue-cropper#726]
可以添加一个背景充颜色的参数吗，如 fillColor:'#fff'
在getCropChecked 的setCanvasSize方法就可以配置，不晓得对不，大老
function setCanvasSize(width, height,ctx) {
        canvas.width = Math.round(width);
        canvas.height = Math.round(height);
        if(this.fillColor!=null){
             ctx.fillStyle =this.fillColor;
             ctx.fillRect(0, 0, width,height);
       }
}

**Comment by xyxiao001** [comment]
可以的，下个版本我加下，目前你可以获取 png 然后再去填色

**Comment by xyxiao001** [comment]
最新版本已经支持
