### ISSUE TITLE
getCropBlob()无法获取旋转的数据

### ISSUE THREAD

**Issue by AiYooooo** [xyxiao001/vue-cropper#729]
通过this.$refs.cropper.getCropBlob()方法获取到的data，在通过new File()和window.URL.createObjectURL()处理之后，图片始终是正的，没有旋转信息，请问如何拿到旋转的图片呢

**Comment by xyxiao001** [comment]
![image](https://github.com/xyxiao001/vue-cropper/assets/15681693/75ac3d04-af58-4ffd-9b85-82678159e723)
![image](https://github.com/xyxiao001/vue-cropper/assets/15681693/94b3bd9f-cd05-494a-afb9-f3a22c21a572)

测试发现是可以的
https://github.xyxiao.cn/vue-cropper/docs/vue3.html
