### ISSUE TITLE
截图框显示与照片一致的分辨率

### ISSUE THREAD

**Issue by iamchenjing** [xyxiao001/vue-cropper#732]
上传到组件里面的图片如何设置与原图一致的分辨率

**Comment by xyxiao001** [comment]
设置 original:true

**Comment by iamchenjing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
