### ISSUE TITLE
请教一下：jpg动图可以在裁剪时，让它动起来吗？或者可以禁用blob转换，直接使用url地址吗

### ISSUE THREAD

**Issue by yyfwyj** [xyxiao001/vue-cropper#733]
这是一张图片：https://bdn.135editor.com/files/images/editor_styles/e6606bcc2faacef37e52508ada4239fe.jpg。
我希望在截图的时候能够动起来，而不是直接显示第一帧，有没有办法解决一下呢？
![image](https://github.com/xyxiao001/vue-cropper/assets/102706925/1ea06eec-6aab-4361-b118-5a10cee110bf)

**Comment by xyxiao001** [comment]
目前暂不支持 动图的裁剪

**Comment by yyfwyj** [comment]
> 目前暂不支持 动图的裁剪
好的，谢谢解答
