### ISSUE TITLE
vite 4.4.4编译报错

### ISSUE THREAD

**Issue by DevHaoZi** [xyxiao001/vue-cropper#739]
```
vite v4.4.4 building for production...
transforming (3544) node_modules\.pnpm\vueuc@0.4.51_vue@3.3.4\node_modules\vueuc\es\resize-observer\src\VResizeObserver.jsnode_modules/.pnpm/vue-cropper@1.0.9/node_modules/vue-cropper/lib/index.ts:1:24 - error TS2307: Cannot find module './vue
-cropper.vue' or its corresponding type declarations.

1 import VueCropper from './vue-cropper.vue'
                         ~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/vue-cropper@1.0.9/node_modules/vue-cropper/lib/index.ts:1

 ELIFECYCLE  Command failed with exit code 2.
transforming (3744) node_modules\.pnpm\date-fns@2.30.0\node_modules\date-fns\esm\parse\_lib\parsers\ISOWeekParser.jsERROR: "type-check" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.
```

之前加allowJs和noImplicitAny到tsconfig的方案不好使了，怎么解决？

**Comment by xyxiao001** [comment]
再 import 上面加上  // @ts-ignore   这个
或者，再 .d.ts里面添加   
declare module "*.vue" {
  import Vue from "vue";
  export default Vue;
}

**Comment by DevHaoZi** [comment]
> declare module "*.vue" {
> import Vue from "vue";
> export default Vue;
> }

测试有一堆乱七八糟的报错，改成下面的以后可以正常通过编译了：
```
declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  import Vue from 'vue'

  const component: DefineComponent<{}, {}, any> | Vue

  export default component
}

```

**Comment by hx8321** [comment]
我的版本是1.0.9也遇到这个打包问题，无论怎么配置都没用，按照上面那个大佬配置就可以了

**Comment by Aaron-wupan** [comment]
> > 声明模块“*.vue”{
> > 从“vue”导入Vue; 
> > 导出默认Vue；
> > }
> 
> 测试有一堆乱七八糟的报错，改成下面的以后就可以正常通过编译了：
> 
> ```
> declare module '*.vue' {
>   import type { DefineComponent } from 'vue'
>   import Vue from 'vue'
> 
>   const component: DefineComponent<{}, {}, any> | Vue
> 
>   export default component
> }
> ```

感谢大佬，按照这个配置就可以了

**Comment by 13476911603** [comment]
我在vite-env.d.ts中加入你们提到的配置，也无法打包成功
