### ISSUE TITLE
截图之后要怎么传给后台

### ISSUE THREAD

**Issue by wsygdiv** [xyxiao001/vue-cropper#74]
@xyxiao001 
截图之后要上传给后台，传什么数据

**Comment by xyxiao001** [comment]
base64 blob都行 blob通过formdata传就行

**Comment by wsygdiv** [comment]
把`this.$refs.cropper.getCropBlob((data) => {
						console.log(data)
					})`中的data传出来就行了吗

**Comment by xyxiao001** [comment]
是的

**Comment by wsygdiv** [comment]
嗯，好的，谢谢，
