### ISSUE TITLE
vue3 + vite 裁剪报错'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by datamesh-yunqiangli** [xyxiao001/vue-cropper#746]
其它系统是好的，同样代码不知道为报这个
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
![Uploading image.png…]()

import { VueCropper } from "vue-cropper";
排查半天发现正常引入会报错
以下相对引入就没事
import { VueCropper } from "../../../node_modules/vue-cropper/dist/vue-cropper.es.js";
很奇葩，恳请大佬解答

**Comment by datamesh-yunqiangli** [comment]
![image](https://github.com/xyxiao001/vue-cropper/assets/141478014/0aab846d-13e1-484e-ae3a-289ff636bd40)

**Comment by xyxiao001** [comment]
这个应该不是引入的问题，我猜测可能是因为 dom 节点渲染延迟的问题，因为需要获取到外层节点宽高，可以等弹框出来后，再去渲染截图组件

**Comment by datamesh-yunqiangli** [comment]
试过了也不行，目前找到的区别就是跟引入方式有关，以下方式都可以
import { VueCropper } from "vue-cropper/lib/index";
import { VueCropper } from "../../../node_modules/vue-cropper/dist/vue-cropper.es.js";
唯独  import { VueCropper } from "vue-cropper"  不行

**Comment by datamesh-yunqiangli** [comment]
debugger查看截图组件内this.$refs.cropper是undefined
![image](https://github.com/xyxiao001/vue-cropper/assets/141478014/bbb0c2bf-3e8d-4f51-b449-07e4c571b03c)

**Comment by xyxiao001** [comment]
这个就是没有获取到对应的 cropper 节点了，这么奇怪，这个$refs, 是本身内部的节点

**Comment by datamesh-yunqiangli** [comment]
在组件内打印$refs是个空对象，加了延时也是，就是获取不到cropper dom
以下
![image](https://github.com/xyxiao001/vue-cropper/assets/141478014/62a68127-96f8-4230-a369-0db15ae5ae6e)

**Comment by datamesh-yunqiangli** [comment]
方便拉我进下 cropper 微信群。那个二维码过期了
微信号：LZ11170509

**Comment by xyxiao001** [comment]
![image](https://github.com/xyxiao001/vue-cropper/assets/15681693/e88f1fcc-7976-47e5-a384-bcc54558d0fb)

**Comment by Kanya19** [comment]
import { VueCropper } from "vue-cropper/lib/index"; 引用可以但是 import { VueCropper } from "vue-cropper" 不行
