### ISSUE TITLE
Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by DUMUUZEEJIA** [xyxiao001/vue-cropper#748]
vue-cropper.umd.js:2 Uncaught (in promise) RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)

**Comment by xyxiao001** [comment]
这个应该 exif 解析搞 dpi 图片出错了，我后续升级下版本处理下

**Comment by cplcurry3035** [comment]
> 这个应该 exif 解析搞 dpi 图片出错了，我后续升级下版本处理下

博主什么时候处理呀
