### ISSUE TITLE
上传时是否可拍照上传

### ISSUE THREAD

**Issue by wsygdiv** [xyxiao001/vue-cropper#75]
@xyxiao001  
问一下，上传时是否可以调用摄像头拍照

**Comment by xyxiao001** [comment]
可以

**Comment by wsygdiv** [comment]
怎么调用，有内置的方法吗，

**Comment by xyxiao001** [comment]
我这个插件不提供其他方法 只可以可以截图， 你可以看我的demo 去参考  
http://xyxiao.cn/vue-cropper/example/
