### ISSUE TITLE
vue3 启动运行  报错

### ISSUE THREAD

**Issue by cloudbam** [xyxiao001/vue-cropper#750]
vue-cropper doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix

**Comment by xyxiao001** [comment]
用 webpack 嘛，还是 vite

**Comment by cn1001wang** [comment]
![image](https://github.com/xyxiao001/vue-cropper/assets/34416681/2ffb7fb0-515f-4750-961d-659f2f63a773)
vue3启动报错，使用vite4.4.5+vue3.3.4+vue-cropper0.6.3

**Comment by soonwait** [comment]
这问题有解吗？我也遇到了相同的问题，vite-4.4.9 + vue-3.3.4 + vue-cropper-1.1.1
