### ISSUE TITLE
Black background of the crop picture

### ISSUE THREAD

**Issue by timofey3007** [xyxiao001/vue-cropper#77]
Hi, when I'm adding an image to cropper, trying to select crop area by the biggest side http://joxi.ru/52a1MNqF47YjG2 and saving this area, I'm receiving a black background border http://joxi.ru/eAOqK0pux5e3qm on one of the side. 

I think, it because the border crop. Thanks.

**Comment by xyxiao001** [comment]
you can set prop outputType -> png

**Comment by timofey3007** [comment]
In that case we'll get a transparent area instead black. Is there any way where resize area will not go beyond image size?) The property 'canScale' is set to false.

**Comment by xyxiao001** [comment]
Sorry  There is no such feature, and it will be added later.

**Comment by bodinsamuel** [comment]
This feature would be greatly appreciated :)
