### ISSUE TITLE
发现一个图片上传之后，出现黑色背景问题

### ISSUE THREAD

**Issue by ET-WY** [xyxiao001/vue-cropper#770]
<img width="723" alt="企业微信截图_a5fb0fd1-8669-447f-aaa8-7049d2e5c9cc" src="https://github.com/xyxiao001/vue-cropper/assets/149550114/66c07704-4799-49a5-94e9-7b8661793448">

**Comment by ET-WY** [comment]
<img width="433" alt="image" src="https://github.com/xyxiao001/vue-cropper/assets/149550114/2f47b406-9efc-4edd-9409-78e6aac8ac8f">
看你的源码 获取img数据 是通过canvas进行处理，不知道为什么有个图片会导致转换之后变黑

**Comment by xyxiao001** [comment]
是指输出黑色背景嘛，黑色的话，可以考虑输出 png，这样是透明背景

**Comment by ET-WY** [comment]
> 是指输出黑色背景嘛，黑色的话，可以考虑输出 png，这样是透明背景

<img width="407" alt="image" src="https://github.com/xyxiao001/vue-cropper/assets/149550114/8a83c9d1-007d-4f14-a23e-2a295c8e0554">
输出配置我设置了png

**Comment by yeyunwen** [comment]
有解决吗？
