### ISSUE TITLE
裁剪图片之后，设置了fillColor:'#fff'，outputType:'jpeg'，背景还是黑色，fillColor无效

### ISSUE THREAD

**Issue by n19ht** [xyxiao001/vue-cropper#771]
^0.5.10版本，vue2

**Comment by xyxiao001** [comment]
![image](https://github.com/xyxiao001/vue-cropper/assets/15681693/af49ad4a-3e68-4346-9be2-c42a95422017)
https://github.xyxiao.cn/vue-cropper/docs/vue2.html
例子上测试是可以的

**Comment by n19ht** [comment]
> ![image](https://user-images.githubusercontent.com/15681693/281344948-af49ad4a-3e68-4346-9be2-c42a95422017.png) https://github.xyxiao.cn/vue-cropper/docs/vue2.html 例子上测试是可以的

有测试例子的源代码吗，想对比一下哪位不同，我使用的是props传入fillColor，之后直接在this.$refs.cropper.getCropData()的回调函数中拿到的裁切图片，还有一个问题，这个cropper.startCrop方法的使用场景在哪呢

**Comment by xyxiao001** [comment]
这个是静态文件，直接点击右键查看源码就行了
startCrop 的场景是，开启后，可以直接通过鼠标滑动的形式，在截图框生成截图，类似 qq 截图那种

**Comment by n19ht** [comment]
> 这个是静态文件，直接点击右键查看源码就行了 startCrop 的场景是，开启后，可以直接通过鼠标滑动的形式，在截图框生成截图，类似 qq 截图那种

好的感谢 已经定位到问题了，就是使用的裁剪图片版本过低
