### ISSUE TITLE
最新的版本，为什么在git上没有发布对应的版本包呀

### ISSUE THREAD

**Issue by chenzio** [xyxiao001/vue-cropper#772]
![image](https://github.com/xyxiao001/vue-cropper/assets/24283515/a4cbdc23-614b-4f6c-83f5-3feeadfc1fec)
![image](https://github.com/xyxiao001/vue-cropper/assets/24283515/f461b05c-9b1e-4135-806f-6c3a294d33e4)

**Comment by xyxiao001** [comment]
https://github.com/xyxiao001/vue-cropper/releases/tag/1.0.7
已更新
