### ISSUE TITLE
real-time事件错误，不是实时的url

### ISSUE THREAD

**Issue by ashuicoder** [xyxiao001/vue-cropper#773]
代码复现请看，https://codesandbox.io/p/sandbox/vue-cropper-vcxpwr

**Comment by xyxiao001** [comment]
这里没有返回实时的 url 返回的是展示截图的信息

**Comment by ashuicoder** [comment]
> 这里没有返回实时的 url 返回的是展示截图的信息

那实时的地址我该怎么获取呢

**Comment by xyxiao001** [comment]
可以通过 
this.$refs.cropper.getCropData(data => {
  // do something
  console.log(data)  
})
实时获取截图
