### ISSUE TITLE
Vue  v2.4.4

### ISSUE THREAD

**Issue by gguney** [xyxiao001/vue-cropper#78]
Component is not working. I try to use it but nothing. When I try to upload an image it shows empty canvas and there is no error, cropper area shows 0x0 and I can not move it. 

Then I try to rotate and nothing again. No error nothing. 

Thanks in advance.

**Comment by xyxiao001** [comment]
You should set out div width and  height

**Comment by gguney** [comment]
Hello,

Can you be more specific? I've use it without a width or height specified. However, after updating it no luck it is not working. Even there is preloaded image it is not previewing anything

**Comment by xyxiao001** [comment]
Can you Show your code

**Comment by gguney** [comment]
My Component is quite long however this the part where I use cropper:

                <vueCropper
                        ref="cropper"
                        :img="option.img"
                        :outputSize="option.size"
                        :outputType="option.outputType"
                        :info="true"
                        :full="option.full"
                        :canMove="option.canMove"
                        :canMoveBox="option.canMoveBox"
                        :fixedBox="option.fixedBox"
                        :original="option.original"
                        :autoCrop="option.autoCrop"
                        :autoCropWidth="option.autoCropWidth"
                        :autoCropHeight="option.autoCropHeight"
                        @realTime="realTime"
                ></vueCropper>

and my data function in vue: 

        data: function () {
            return {
                crap: true,
                imageId: null,
                image: null,
                isLoading: false,
                isSaving: false,

                hasChange: false,
                previews: {},
                option: {
                    img: '',
                    size: 1,
                    full: true,
                    canScale: true,
                    outputType: 'jpeg',
                    canMove: false,
                    fixedBox: false,
                    original: false,
                    canMoveBox: true,
                    autoCrop: true,
                    autoCropHeight: 100,
                    autoCropWidth: 100,
                },
                downImg: '#'
            }
        },

**Comment by gguney** [comment]
This is the file

<template>
    <div class="crop-div has-border">

        <p v-if="isLoading && isSaving" class="save-warning saving">Kaydediliyor...<br>
            <i class="fa fa-arrow-down" aria-hidden="true"></i></p>
        <loading-progress
                v-if="isLoading"
                :indeterminate="true"
                :hide-background="false"
                shape="line"
                size="100"
                fillDuration="1"
        />
        <button for="uploads" @click.prevent="uploadButton()" class="choose-button is-info is-font-small"
                v-if="option.img == ''">
            Fotoğraf Seç
        </button>
        <button v-if="option.img != '' && hasChange" @click.prevent="finish()" hidden
                class="choose-button is-success is-font-small" ref="unSavedFinish" id="unsavedButton">
            Finish
        </button>
        <input type="file" id="uploads" ref="uploadInput" style="position:absolute; clip:rect(0 0 0 0);"
               accept="image/png, image/jpeg, image/gif, image/jpg" @change="uploadImg($event, 1)">

        <button v-if="!isLoading && option.img!=''"
                @click.prevent="makePrimary()" class="star-button is-font-small" :class="isPrimary"><i
                class="fa fa-star"></i></button>
        <button v-if="!isLoading && option.img!=''"
                @click.prevent="imageRemove()" class="remove-button is-font-small"><i
                class="fa fa-times"></i></button>
        <v-modal ref="modal" @onShow="modalOpened">
            <button slot="button" ref="cropButton" v-if="!isLoading && option.img!=''"
                    class="edit-button is-font-small"><i class="fa fa-crop"></i></button>
            <div class="container has-p-10">
                <vueCropper
                        ref="cropper"
                        :img="option.img"
                        :outputSize="option.size"
                        :outputType="option.outputType"
                        :info="true"
                        :full="option.full"
                        :canMove="option.canMove"
                        :canMoveBox="option.canMoveBox"
                        :fixedBox="option.fixedBox"
                        :original="option.original"
                        :autoCrop="option.autoCrop"
                        :autoCropWidth="option.autoCropWidth"
                        :autoCropHeight="option.autoCropHeight"
                        @realTime="realTime"
                ></vueCropper>
                
                <div class="cropper-buttons">
                    <button @click.prevent="rotateRight" class="btn" :disabled="isLoading">
                        <i class="fa fa-repeat" aria-hidden="true"></i>
                    </button>
                    <button @click.prevent="finish(true)" class="is-success" :disabled="isLoading">
                        <i class="fa fa-circle-o-notch fa-spin" v-if="isLoading"></i>
                        {{(!isLoading) ? 'Kaydet' : 'Kaydediliyor' }}
                    </button>
                    <button @click.prevent="rotateLeft" class="btn" :disabled="isLoading">
                        <i class="fa fa-undo" aria-hidden="true"></i>
                    </button>
                </div>


            </div>
        </v-modal>
        <div class="show-preview"
             :style="{'width': previews.w + 'px', 'height': previews.h + 'px',  'overflow': 'hidden', 'margin': '5px'}">
            <div class="show-preview-image-wrapper">
                <img :src="previews.url" ref="previewImage">
            </div>
            <div class="overlay-buttons">

            </div>

        </div>

    </div>
</template>
<script>
    import vueCropper from 'vue-cropper'
    import 'vue-progress-path/dist/vue-progress-path.css'
    import VueProgress from 'vue-progress-path'

    export default {
        props: ['name', 'imageData', 'index'],
        data: function () {
            return {
                crap: true,
                imageId: null,
                image: null,
                isLoading: false,
                isSaving: false,

                hasChange: false,
                previews: {},
                option: {
                    img: '',
                    size: 1,
                    full: true,
                    canScale: true,
                    outputType: 'jpeg',
                    canMove: false,
                    fixedBox: false,
                    original: false,
                    canMoveBox: true,
                    autoCrop: true,
                    autoCropHeight: 100,
                    autoCropWidth: 100,
                },
                downImg: '#'
            }
        },
        mounted() {
            this.setInitialImage();
            if (this.image) {
                this.$parent.setImageData(this.index, this.image);
                console.log();
                if (this.image.is_primary == 1) {
                    this.makePrimary();
                }
            } else {
                this.$parent.setImageData(this.index, {});
            }
        },
        methods: {
            imageRemove() {

                this.option.img = '';
                this.previews.url = '';
                this.hasChange = false;
                this.$parent.removeUnsavedImage(this.index);

                if (this.image != null) {
                    this.isLoading = false;

                    axios.delete('/my/image/' + this.image.id).then(response => {
                        // console.log(response);
                    });

                    this.image = null;

                }
            },
            modalOpened() {
                console.log("modal opened");

            },
            setInitialImage() {
                this.image = this.imageData;
                if (this.image) {
                    this.imageId = this.image.id;
                    this.option.img = this.getInitialImage();
                }
            },
            getInitialImage() {
                if (this.image) {
                    if (this.image.is_temp) {
                        return this.image.generated_url;
                    } else {
                        return this.image.original_url;
                    }
                } else {
                    return ''
                }
            },
            uploadButton() {
                this.$refs.uploadInput.click();
            },
            makePrimary() {
                this.$parent.makePrimary(this.index);
            },
            startCrop() {
                // start
                this.crap = true
                this.$refs.cropper.startCrop()
            },
            rotateLeft() {
                this.$refs.cropper.rotateLeft()
                this.hasChange = true;
            },

            rotateRight() {
                this.$refs.cropper.rotateRight()
                this.hasChange = true;

            },
            stopCrop() {
                //  stop
                this.crap = false
                this.$refs.cropper.stopCrop()
            },
            clearCrop() {
                // clear
                this.$refs.cropper.clearCrop()
            },
            // 实时预览函数
            realTime(data) {
                this.previews = data
            },
            finish(shouldCrop) {
                let vm = this;
                this.isLoading = true;
                this.isSaving = true;
                this.$refs.modal.hideModal();

                if (!shouldCrop) {
                    this.$refs.cropper.clearCrop();
                }

                /*
                this.$refs.cropper.getCropData((data) => {
                    this.option.img = data
                })
                */
                this.$refs.cropper.getCropBlob((data) => {
                    let fd = new FormData()
                    fd.append('image', data)
                    if (vm.$parent.getProduct()) {
                        let product = vm.$parent.getProduct();
                        fd.append('product_id', product.id);
                    }
                    let go = '';
                    if (vm.image && vm.imageId) {
                        go = '/' + vm.imageId;
                        if (vm.image.is_temp == true) {
                            fd.append('is_temp', true);
                        } else {
                            fd.append('is_temp', false);
                        }
                    }
                    axios.post('/my/image' + go, fd).then(response => {

                        vm.image = response.data.image;

                        vm.imageId = response.data.image.id;
                        vm.option.img = vm.getInitialImage();
                        vm.isSaving = false;
                        vm.hasChange = false;
                        vm.$parent.setImageData(vm.index, vm.image);

                        vm.$parent.removeUnsavedImage(vm.index);

                    }).catch(error => {
                        vm.error = true;
                        vm.errorMessage = "Bir Sorun Oluştu";
                        vm.isLoading = true;
                        vm.isSaving = false;
                        setTimeout(function () {
                            vm.error = false;
                            vm.isSaving = false;
                            vm.image = null;
                        }, 2000);

                    });
                    vm.$refs.previewImage.onload = function () {
                        vm.isLoading = false
                    };

                });
            },
            hasImageId() {
                if (this.image && this.image.id) {
                    return this.image.id;
                }
                return false;
            },

            down(type) {
                // event.preventDefault()
                var aLink = document.createElement('a')
                aLink.download = 'demo'
                // 输出
                if (type === 'blob') {
                    this.$refs.cropper.getCropBlob((data) => {
                        this.downImg = data
                        aLink.href = data
                        aLink.click()
                    })
                } else {
                    this.$refs.cropper.getCropData((data) => {
                        this.downImg = data
                        aLink.href = data
                        aLink.click()
                    })
                }
            },

            uploadImg(e, num) {
                //上传图片
                var file = e.target.files[0]
                if (!/\.(gif|jpg|jpeg|png|bmp|GIF|JPG|PNG)$/.test(e.target.value)) {
                    alert('Sadece .gif,jpeg,jpg,png,bmp uzantısı seçebilirsiniz.')
                    return false
                }
                this.isLoading = true;
                let vm = this;


                var reader = new FileReader()
                reader.onload = (e) => {
                    let data
                    if (typeof e.target.result === 'object') {
                        data = window.URL.createObjectURL(new Blob([e.target.result]))
                    } else {
                        data = e.target.result
                    }

                    this.option.img = data
                    this.hasChange = true;
                }
                reader.readAsArrayBuffer(file)
                vm.$refs.previewImage.onload = function () {
                    vm.isLoading = false
                };
                this.$parent.addUnsavedImage(this.index);
            },

        },
        computed: {
            isPrimary: function () {
                if (this.$parent.getPrimary() == this.index) {
                    return 'yellow';
                }
            }
        },
        components: {
            vueCropper
        },
    }
</script>
<style lang="scss">
   
</style>

**Comment by xyxiao001** [comment]
You can see
http://xyxiao.cn/vue-cropper/example/

**Comment by gguney** [comment]
I'm using component inside a modal. Actually preview is outside of a modal and real component is inside of a modal. It was working before however now it does not. I really like this component. Somewhat it is now broken because of new version of Vue I guess. Preview is not working and I can not event rotate the image. 

I started with your example but I go far far from it.

**Comment by xyxiao001** [comment]
Use v-if

**Comment by xyxiao001** [comment]
When your pop-up appears, rerender the screenshot plug-in.

**Comment by gguney** [comment]
Cropper preview area is not working propery, so the preview is not shown.

**Comment by gguney** [comment]
I changed cropW cropH from VueDev tool then preview showed. However, when I try to resize crop area it reset itself to 0x0 I guess there is a problem with it

**Comment by gguney** [comment]
I solved it. Actually problem is when you use the component inside of a modal. If the modal content is hidden then component wont initialize. However, If I only hide modal wrapper then there is no problem.

Thanks for your help.
