### ISSUE TITLE
拖动报错：vue-cropper.js?v=1c3e2802:648 Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by FastGUI** [xyxiao001/vue-cropper#785]
vue3 + vite 项目

![image](https://github.com/xyxiao001/vue-cropper/assets/35055114/243e38e9-dc46-4417-affa-8329018fb5ca)

**Comment by xyxiao001** [comment]
什么版本的chrome

**Comment by Keith0216** [comment]
> 用到是哪个版本的插件和什么版本的chrome

"vue-cropper": "^1.1.1",Chrome版本 121.0.6167.185（正式版本） （64 位）也有这个问题

**Comment by FastGUI** [comment]
> 用到是哪个版本的插件和什么版本的chrome

知道问题所在了，是我自己的原因，为了解决滚动流畅性问题安装了这个 default-passive-events  库，没想到和 vue-cropper 有冲突

**Comment by broccoliY** [comment]
请问后来怎么解决呢，注释defalut-passive-events这个库嘛
