### ISSUE TITLE
放大后无法缩小回初始大小

### ISSUE THREAD

**Issue by LAQKing** [xyxiao001/vue-cropper#792]
初始图片是这样的
![image](https://github.com/xyxiao001/vue-cropper/assets/53205480/cdcf8464-9b73-4c07-8d38-a30e6a914f1c)

但是放大后，就无法缩小回到最初的样子
![image](https://github.com/xyxiao001/vue-cropper/assets/53205480/8bd66999-9646-4606-875e-29f34f438f37)

这个需要怎么设置或修改？我是通过cropper.value.changeScale(1)放大，cropper.value.changeScale(-1)缩小的，鼠标滚轮也存在同样的问题。

**Comment by doubaodoubao** [comment]
卧槽我也是，怎么搞啊这个

**Comment by LAQKing** [comment]
> 卧槽我也是，怎么搞啊这个

我提交了pull-requests，等作者测试完成，合并后发布新版本应该可以解决了
