### ISSUE TITLE
查看演示demo报错

### ISSUE THREAD

**Issue by LAQKing** [xyxiao001/vue-cropper#802]
![image](https://github.com/xyxiao001/vue-cropper/assets/53205480/bb21bd55-6d15-4d1a-84c1-0717a86f693c)

**Comment by xyxiao001** [comment]
应该是vue cdn加载出错了, 可以刷新看看
![image](https://github.com/xyxiao001/vue-cropper/assets/15681693/6a600167-d33b-4391-bfbb-875f9d247a2b)

**Comment by LAQKing** [comment]
> 应该是vue cdn加载出错了, 可以刷新看看 ![image](https://private-user-images.githubusercontent.com/15681693/317578845-6a600167-d33b-4391-bfbb-875f9d247a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTYwNDAsIm5iZiI6MTcxMTU5NTc0MCwicGF0aCI6Ii8xNTY4MTY5My8zMTc1Nzg4NDUtNmE2MDAxNjctZDMzYi00MzkxLWJmYmItODc1ZjlkMjQ3YTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAzMTU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMGY3NzE4OWQ4ZjgyOGM4ZjA0YzJjNGJmMGFhMmU5OTMyZmNjYTc4OTc5ZDcwYTU0NGEyZDgyYWYyY2U0YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9geYtgGZ81vP6QeXsDyPcloJoWUQWToxJ79L0_35vgg)

不行，刷新了好多次，对了，放不放便加wx呀，有技术问题可以交流交流，或者拉我进群
![image](https://github.com/xyxiao001/vue-cropper/assets/53205480/c658354a-465c-4f77-a48f-1ead137a0f8c)

**Comment by xyxiao001** [comment]
![image](https://github.com/xyxiao001/vue-cropper/assets/15681693/f5eea591-3962-4448-ad5d-5798a3c2af6d)
