### ISSUE TITLE
时时预览怎么实现

### ISSUE THREAD

**Issue by daiyanxia** [xyxiao001/vue-cropper#808]
http://127.0.0.1:5500/vue-cropper/docs/vue3.html
这个链接里面有测试页面，但是没有实现时时功能：
<img width="281" alt="企业微信截图_1713266926205" src="https://github.com/xyxiao001/vue-cropper/assets/29750417/04e6f371-d18b-49ce-bd84-7bf2bf5f2fca">

**Comment by xyxiao001** [comment]
<div class="show-preview" :style="{'width': previews.w + 'px', 'height': previews.h + 'px',  'overflow': 'hidden',
    'margin': '5px'}">
  <div :style="previews.div">
    <img :src="option.img" :style="previews.img">
  </div>
</div>

把这段代码拷贝下展示就行，可以看看文档
