### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by zbwbowen** [xyxiao001/vue-cropper#81]
Can you help me to deal with the CORS policy error ?  I add a url to this component :img then log error

**Comment by xyxiao001** [comment]
This is a cross-domain picture problem If you use online pictures, you need to set the picture server to allow cross-domain

**Comment by styzy** [comment]
我查了一下资料，canva获取图片的确会涉及到跨域问题，我看了一下网络请求，发现这张图片的请求header里面没有定义cross-origin，我看了你的源代码，里面有定义corss-origin为*，但是好像不起作用，不知道是什么原因

**Comment by xyxiao001** [comment]
这个我当时也查了很久 好像有的图片就会出问题

**Comment by styzy** [comment]
问题解决了，我把tomcat配置跨域了，原来是和我的node服务器的cors冲突了，一开始以为是nginx的问题，后来找到是tomcat没有配置静态资源的cors

**Comment by xyxiao001** [comment]
好的

**Comment by 565784135** [comment]
https://yq.aliyun.com/ziliao/107930?spm=a2c4e.11155472.0.0.27587c40AIVNxh
