### ISSUE TITLE
dist目录下没有index.css

### ISSUE THREAD

**Issue by roffer-d** [xyxiao001/vue-cropper#812]

**Comment by xyxiao001** [comment]
vue3需要按照 1.x版本，才有css

**Comment by Steven-Zhl** [comment]
感谢，在这踩坑了，Vue 3需要安装`npm install vue-cropper@next`才是正确版本

**Comment by eefenaxce** [comment]
![Image](https://github.com/user-attachments/assets/20449311-f65b-4632-a5e4-ae388e40bb82) 

![Image](https://github.com/user-attachments/assets/23579f89-d4a1-46ec-95d5-f72841f9d958) 我用的是vue3.5.17, vue-cropper 1.1.4,报错显示不存在这个文件
