### ISSUE TITLE
预览图片偏移,无法正确预览

### ISSUE THREAD

**Issue by langshiyeye** [xyxiao001/vue-cropper#816]
为什么按照文档的代码复制下来,我预览图片显示一直不对,有些预览不了,有些预览偏移严重.
![image](https://github.com/xyxiao001/vue-cropper/assets/100590980/5b4005da-453b-4bf3-9ec3-dd878455dcdf)
![image](https://github.com/xyxiao001/vue-cropper/assets/100590980/6077e4da-ec7f-49fd-9fb4-36d1a0f79030)
预览效果如下图:
![image](https://github.com/xyxiao001/vue-cropper/assets/100590980/0a3fcf70-cb0c-4a30-abb5-71bbc5951eb7)

**Comment by xyxiao001** [comment]
kk 是不是img上面有默认的max-width影响到了，可以用开发者工具看看预览的图片css

**Comment by langshiyeye** [comment]
> kk 是不是img上面有默认的max-width影响到了，可以用开发者工具看看预览的图片css

对的,查看了下确实是,感谢感谢
![image](https://github.com/xyxiao001/vue-cropper/assets/100590980/a2c1e332-d59c-4d53-86c0-d5fd38c96f06)

**Comment by lmq2582609** [comment]
有帮助，谢谢
