### ISSUE TITLE
Vue3使用vue-cropper@next之后截图框只剩一个点可以移动

### ISSUE THREAD

**Issue by UTing1119** [xyxiao001/vue-cropper#823]
![image](https://github.com/xyxiao001/vue-cropper/assets/74576629/08a0276b-751e-4ec9-b8da-a5ba804242d7)

只剩左下角的点可以拖动截图框
是不是哪边没有设置好?

设置项:
```
outputSize: 1,
full: false,
outputType: 'png',
canMove: false,
fixedBox: false,
fixed: false,
fixedNumber: [16, 9],
original: false,
canMoveBox: true,
autoCrop: true,
centerBox: true,
high: true,
max: 99999,
```

**Comment by xyxiao001** [comment]
是不是css属性隐藏了呀，你用开发者工具聚焦看看

**Comment by UTing1119** [comment]
![image](https://github.com/xyxiao001/vue-cropper/assets/74576629/756210cb-3165-451f-b5b2-88ab10d7bb05)

结果是全挤一起了
这是我配置不好的问题吗

**Comment by xyxiao001** [comment]
可能是被你默认的css影响到了，看看是不是设置了什么属性影响的，看看工具栏应该可以看到影响的css

**Comment by UTing1119** [comment]
找到是因为before跟after都设成了`position: relative`
谢谢哈
