### ISSUE TITLE
Size and Quality

### ISSUE THREAD

**Issue by gguney** [xyxiao001/vue-cropper#83]
Hello,

I'm using your component edit images but it decreases the quality.  I'm using these options:

   option: {
                    img: '',
                    size: 1,
                    info:true,
                    full: false,
                    canScale: false,
                    outputType: 'png',
                    canMove: true,
                    fixedBox: false,
                    original: false,
                    canMoveBox: true,
                    autoCrop: true,
                },

I do not want to change the size of the image but when I crop the image with this component it decreases the quality makes it pixelated. 

I'm optimizing image on the backend. So do not want any special process. What should I do or change. Size: 1 does not work.

**Comment by xyxiao001** [comment]
you can set props => full : true

**Comment by xyxiao001** [comment]
autoCropWidth  only support px

**Comment by gguney** [comment]
Then can I make the crop area fit exactly the image width and height?

**Comment by gguney** [comment]
I have 2 scenarios: 1 User can crop the image this is working for now. Other one is the upload it without cropping; in this scenario I have to set crop area exactly the image preview width and height

**Comment by xyxiao001** [comment]
emm, Sorry for not having this kind of function at this moment, the later version, I will provide the detailed coordinate axis to set the position and the width and height

**Comment by gguney** [comment]
Ah that's bad news. Is there a way to upload the image exactly it is without cropping?

**Comment by gguney** [comment]
I implemented a function and created a pull request for it #84 . The function makes crop area to fit the image exactly. I did not test it inside of the component but I test it outside of the component and it works.
