### ISSUE TITLE
能否添加设置mode(图片默认渲染方式)方法？

### ISSUE THREAD

**Issue by zlecheng** [xyxiao001/vue-cropper#830]
我的业务需要在清空框选的时候把图片的渲染方式再改回到 cover 的模式

**Comment by xyxiao001** [comment]
可以直接通过props 修改mode就行了

**Comment by zlecheng** [comment]
> 可以直接通过props 修改mode就行了

直接改可以生效吗？

**Comment by xyxiao001** [comment]
直接改 就会自动重新渲染了

**Comment by zlecheng** [comment]
> 直接改 就会自动重新渲染了

![image](https://github.com/xyxiao001/vue-cropper/assets/42574059/ebc7ec50-9dd7-4b28-aaf7-39f58e35a7f6)
![image](https://github.com/xyxiao001/vue-cropper/assets/42574059/5638cf2e-31d8-4195-b58e-aa5eebdcfc13)

似乎没有生效

**Comment by zlecheng** [comment]
> 直接改 就会自动重新渲染了

![image](https://github.com/xyxiao001/vue-cropper/assets/42574059/f06423f8-43ff-4567-bfce-deab023b2775)

**Comment by zlecheng** [comment]
> https://github.xyxiao.cn/vue-cropper/docs/vue3.html 可以看看例子，就是直接通过prop更改mode的

![image](https://github.com/xyxiao001/vue-cropper/assets/42574059/7642c862-6674-43a5-86d0-9296bb031174)

你用的是刷新的方法

**Comment by xyxiao001** [comment]
这是刷新截图框 ，mode是改变传入就会渲染的

**Comment by zlecheng** [comment]
但是我的没变



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月05日 21:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xyxiao001/vue-cropper] 能否添加设置mode(图片默认渲染方式)方法？ (Issue #830) |

这是刷新截图框 ，mode是改变传入就会渲染的

**Comment by xyxiao001** [comment]
https://jsbin.com/jivoyewaco/edit?html,css,output  看看这个例子，什么都没改变，只改了传入的props mode的值

**Comment by xyxiao001** [comment]
![20240605212531_rec_](https://github.com/xyxiao001/vue-cropper/assets/15681693/913ddf3f-c744-455d-95cf-fd4edbd25d79)

**Comment by xyxiao001** [comment]
watch是要mode值发生改变才会重新渲染

**Comment by xyxiao001** [comment]
你如果只想重新渲染可以执行reload方法

**Comment by zlecheng** [comment]
> 你如果只想重新渲染可以执行reload方法

![image](https://github.com/xyxiao001/vue-cropper/assets/42574059/ea4b22e2-5d17-4c36-ae83-8c9bcda2ae4b)
用按钮点击改变mode就不行了

**Comment by zlecheng** [comment]
> 你如果只想重新渲染可以执行reload方法

用reload方法没办法把选区清空，只会把图片还原成初始的尺寸

**Comment by xyxiao001** [comment]
https://jsbin.com/moluquvizi/edit?html,css,js,console,output  怎么可能出现按钮点击就不行呢，这是watch监听的，除非mode没变
![20240606093001_rec_](https://github.com/xyxiao001/vue-cropper/assets/15681693/e2cf63cf-c869-4cfc-b6e1-dc71f457bff3)

**Comment by xyxiao001** [comment]
reload没办法清空截图框，是因为你设置了自动生成截图看，可以吧autoCrop那几个值设置为false，然后reload截图框就没了

**Comment by zlecheng** [comment]
> https://jsbin.com/moluquvizi/edit?html,css,js,console,output 怎么可能出现按钮点击就不行呢，这是watch监听的，除非mode没变 ![20240606093001_rec_](https://private-user-images.githubusercontent.com/15681693/337068878-e2cf63cf-c869-4cfc-b6e1-dc71f457bff3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mzc5MTksIm5iZiI6MTcxNzYzNzYxOSwicGF0aCI6Ii8xNTY4MTY5My8zMzcwNjg4NzgtZTJjZjYzY2YtYzg2OS00Y2ZjLWI2ZTEtZGM3MWY0NTdiZmYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxMzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTdhZjljZDliMmU0MDdiZDJiZDdlNGNjNTYzMmFmYTYzZDkzMTc3MjRkNzg3NjE1Yjk2ZmFiMGZmYjk4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJJWnpjXi3Q1H6U5VntW7q5AMyUxZ6g41WL5n2y30iA) [ ![20240606093001_rec_](https://private-user-images.githubusercontent.com/15681693/337068878-e2cf63cf-c869-4cfc-b6e1-dc71f457bff3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mzc5MTksIm5iZiI6MTcxNzYzNzYxOSwicGF0aCI6Ii8xNTY4MTY5My8zMzcwNjg4NzgtZTJjZjYzY2YtYzg2OS00Y2ZjLWI2ZTEtZGM3MWY0NTdiZmYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxMzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTdhZjljZDliMmU0MDdiZDJiZDdlNGNjNTYzMmFmYTYzZDkzMTc3MjRkNzg3NjE1Yjk2ZmFiMGZmYjk4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJJWnpjXi3Q1H6U5VntW7q5AMyUxZ6g41WL5n2y30iA) ](https://private-user-images.githubusercontent.com/15681693/337068878-e2cf63cf-c869-4cfc-b6e1-dc71f457bff3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mzc5MTksIm5iZiI6MTcxNzYzNzYxOSwicGF0aCI6Ii8xNTY4MTY5My8zMzcwNjg4NzgtZTJjZjYzY2YtYzg2OS00Y2ZjLWI2ZTEtZGM3MWY0NTdiZmYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxMzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTdhZjljZDliMmU0MDdiZDJiZDdlNGNjNTYzMmFmYTYzZDkzMTc3MjRkNzg3NjE1Yjk2ZmFiMGZmYjk4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJJWnpjXi3Q1H6U5VntW7q5AMyUxZ6g41WL5n2y30iA) [ ](https://private-user-images.githubusercontent.com/15681693/337068878-e2cf63cf-c869-4cfc-b6e1-dc71f457bff3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2Mzc5MTksIm5iZiI6MTcxNzYzNzYxOSwicGF0aCI6Ii8xNTY4MTY5My8zMzcwNjg4NzgtZTJjZjYzY2YtYzg2OS00Y2ZjLWI2ZTEtZGM3MWY0NTdiZmYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxMzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTdhZjljZDliMmU0MDdiZDJiZDdlNGNjNTYzMmFmYTYzZDkzMTc3MjRkNzg3NjE1Yjk2ZmFiMGZmYjk4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJJWnpjXi3Q1H6U5VntW7q5AMyUxZ6g41WL5n2y30iA)

**Comment by zlecheng** [comment]
> https://jsbin.com/moluquvizi/edit?html,css,js,console,output 怎么可能出现按钮点击就不行呢，这是watch监听的，除非mode没变 ![20240606093001_rec_](https://private-user-images.githubusercontent.com/15681693/337068878-e2cf63cf-c869-4cfc-b6e1-dc71f457bff3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzgwODMsIm5iZiI6MTcxNzYzNzc4MywicGF0aCI6Ii8xNTY4MTY5My8zMzcwNjg4NzgtZTJjZjYzY2YtYzg2OS00Y2ZjLWI2ZTEtZGM3MWY0NTdiZmYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxMzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NWJjNGM3OWU1MWM1NjNkY2ZmN2UzMDU0YTc2NDlhZmE4MzY3ZTVhZTAzZjJhMzE5MDU4YWYxYzMzNTQ1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gG3PQurwOcb0EoVN0zF7CagoItQdM3W8L5RhzN89HNM) [ ![20240606093001_rec_](https://private-user-images.githubusercontent.com/15681693/337068878-e2cf63cf-c869-4cfc-b6e1-dc71f457bff3.gif

为啥我的vue3就不行呢，打印的mode值已经变了
![image](https://github.com/xyxiao001/vue-cropper/assets/42574059/75fab70c-a429-456b-b87e-4846f4e4f8f0)
![image](https://github.com/xyxiao001/vue-cropper/assets/42574059/c225cc69-92ad-47ab-856e-1cecdfb2ab6e)
