### ISSUE TITLE
特殊图片宽高不正确问题

### ISSUE THREAD

**Issue by luoyulingi** [xyxiao001/vue-cropper#847]
大佬，遇到个特殊图片的宽高获取到的时候为实际宽高的一半，然后缩放比又是按照这一半的宽高去缩放，就导致最终坐标除缩放比为原来图的一半。图为3000*4000的，在实时预览中获取到的为1500*4000，麻烦大佬看看是什么情况。

**Comment by luoyulingi** [comment]
![Uploading Snipaste_2024-09-26_10-50-48.jpg…]()

**Comment by xyxiao001** [comment]
图裂了

**Comment by luoyulingi** [comment]
> 图裂了

大佬有别的途径我发您图片看看吗   这里不让我上传图片 不知道怎么回事

**Comment by luoyulingi** [comment]
大佬就是这个情况，图片为3000*4000的，但是实时原理参数缩小了一半，自己看不出问题特来求助，还有我这缩放比获取的方式正确吗哈哈




衷心未改i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xyxiao001/vue-cropper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月26日(星期四) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xyxiao001/vue-cropper] 特殊图片宽高不正确问题 (Issue #847)






图裂了

**Comment by xyxiao001** [comment]
![image](https://github.com/user-attachments/assets/551ca924-2f5a-4eec-8467-12ab9de6ee6e)

**Comment by luoyulingi** [comment]
后续加上了大佬群，大佬指出了问题。原因是我配置没加maxImgSize，大于等于3000的会压缩，我设置了 9999可以获取正确的大小。再次感谢大佬。
