### ISSUE TITLE
enlarge = 1  正常 enlarge= 2 会有透明边

### ISSUE THREAD

**Issue by ValueLan** [xyxiao001/vue-cropper#850]
enlarge = 1  正常 enlarge= 2 会有透明边
其他参数都一样

**Comment by ValueLan** [comment]
<vueCropper ref="cropper" enlarge="2" @real-time="realTime" autoCropWidth="320" mode="cover" :autoCrop="true"
          autoCropHeight="240" :fixedBox="true" style="width: 400px;height: 310px;" :centerBox="true" :img="localUrl"
          outputType="png">

**Comment by xyxiao001** [comment]
enlarge 应该是正常的放大，可以提供下出错的图片嘛
