### ISSUE TITLE
怎么让裁剪框 铺满图片， 图片大小不固定， 翻了一下issue 很多人都有这样的问题 但是解决方案好像没有下一步了都~~

### ISSUE THREAD

**Issue by Ya-hui** [xyxiao001/vue-cropper#854]
怎么让裁剪框 铺满图片， 图片大小不固定， 翻了一下issue 很多人都有这样的问题 但是解决方案好像没有下一步了都~~
我尝试 给裁剪框 设置图片的宽高 但是超出边界了

**Comment by xyxiao001** [comment]
设置mode:cover呢

**Comment by Ya-hui** [comment]
autoCropWidth="3000"
autoCropHeight="3000"

目前是这样处理的
