### ISSUE TITLE
fixedNumber动态宽高比调整裁剪框

### ISSUE THREAD

**Issue by chaoyue0** [xyxiao001/vue-cropper#859]
使用fixed固定裁剪框，配置fixedNumber设置动态变量，改变裁剪宽高比，调整fixedNumber变量后需要手动拖拽一下裁剪框才能出现对应得宽高比的裁剪框，如何一检测到fixedNumber的值发现变化就默认调整裁剪框的比例？

Use fixed to fix the cropping box, configure fixedNumber to set dynamic variables, and change the cropping aspect ratio. After adjusting the fixedNumber variable, you need to manually drag the cropping box to display the cropping box corresponding to the aspect ratio. How to detect the change as soon as the value of fixedNumber is detected? Adjust the cropping frame proportions by default?

**Comment by xyxiao001** [comment]
目前美哦与检测，可以考虑在变更后手动执行下 goAutoCrop 这个方法

**Comment by chaoyue0** [comment]
好的，上述问题已解决，还有一个问题：goAutoCrop方法中，截图框默认大小可以设置成100%嘛？现在截图框实际显示的大小和实例中cropH、cropW属性值的尺寸对不上

**Comment by xyxiao001** [comment]
这个方法接收两个参数，截图看宽度和高度，可以传进去

**Comment by chaoyue0** [comment]
目前只有裁剪框移动的事件，可以增加一个裁剪框尺寸调整的事件嘛？
