### ISSUE TITLE
iphoneX手机 微信端中点击拍照上传失败

### ISSUE THREAD

**Issue by xiajunqcy** [xyxiao001/vue-cropper#86]
iPhoneX手机，在微信端中点击拍照上传，正常拍照点击完成之后，页面中无图片，会自动刷新一次页面，刷新完成之后同样无图片。其他安卓以及苹果手机都可正常拍照显示

**Comment by xyxiao001** [comment]
没道理啊 我也是iphonex 没问题

**Comment by xyxiao001** [comment]
safari里面呢

**Comment by xiajunqcy** [comment]
使用demo在微信端以及safari里都测试了，用iPhoneX手机拍照之后显示正常。不知道用在项目里为什么就不行，我再排查看看吧。
