### ISSUE TITLE
在低版本iOS中（如iOS8.1），safari运行会报错

### ISSUE THREAD

**Issue by pylee** [xyxiao001/vue-cropper#87]
本地上传图片，选择图片或拍照过后，会报
`Cross-origin image load denied by Cross-Origin Resource Sharing policy.
setAttr — vue.esm.js:6295`
然后界面起来，但是没有图片加载，请问怎么解决呢？

**Comment by xyxiao001** [comment]
低版本浏览器的问题 我还在研究中 目前 ios8还不能用

**Comment by xyxiao001** [comment]
0.33版本已经解决
