### ISSUE TITLE
图片加载到编辑框时，出现延迟。

### ISSUE THREAD

**Issue by 2015-lizaiyang** [xyxiao001/vue-cropper#89]
在Android手机上，选择大的图片时，给您这个插件传入图片数据时，会出现延迟，能不能暴露出一个判断图片是否加载完毕，这样我们就可以在加载图片时给用户一个提示loading。

**Comment by xyxiao001** [comment]
v0.29

新增图片加载的回调 imgLoad 返回结果success, error
