### ISSUE TITLE
裁剪框移动时，预览图像不变化

### ISSUE THREAD

**Issue by pikadun** [xyxiao001/vue-cropper#97]
如何监听裁剪框的移动？

**Comment by xyxiao001** [comment]
realTime (data) {
  this.previews = data
}
<div class="show-preview" :style="{'width': previews.w + 'px', 'height': previews.h + 'px',  'overflow': 'hidden',
    'margin': '5px'}">
  <div :style="previews.div">
    <img :src="previews.url" :style="previews.img">
  </div>
</div>

**Comment by pikadun** [comment]
谢谢，需要严格按照这个格式去写对嘛

**Comment by xyxiao001** [comment]
这个是个回调函数， 当截图框发生变化 会触发改变

**Comment by xyxiao001** [comment]
可以看例子1

**Comment by pikadun** [comment]
谢谢，回掉函数确实被触发了，但是每次触发之后，生成的base64，打印出来都是完全一样的，所以导致了预览图片不变化，请问大佬遇到过这种情况嘛

**Comment by xyxiao001** [comment]
预览不需要重新生成图片  直接用坐标就可以

**Comment by xyxiao001** [comment]
可以看在线例子1  有代码的  点击展开看就行

**Comment by pikadun** [comment]
明白了，谢谢！
