### ISSUE TITLE
父元素的text-align非left时， 被裁剪图片定位错误

### ISSUE THREAD

**Issue by 272092461** [xyxiao001/vue-cropper#99]
当.cropper-view-box元素继承到的text-align为center合作left，且图片尺寸小于该容器时，被裁剪图片的定位会发生明显偏移，此时能够看到两张图片

**Comment by xyxiao001** [comment]
是不是设置了图片的最大宽度

**Comment by 272092461** [comment]
@xyxiao001 
用的基本例子二的代码
`
<v-cropper
                                ref="cropper"
                                :img="cropper.img"
                                :auto-crop="cropper.autoCrop"
                                :output-size="cropper.size"
                                :output-type="cropper.outputType"
                                :full="true"
                                :info="cropper.info"
                                :can-scale="cropper.canScale"
                                :auto-crop-width="cropper.autoCropWidth"
                                :auto-crop-height="cropper.autoCropHeight"
                                :fixed="cropper.fixed"
                                :fixed-number="cropper.fixedNumber"
                            >
                            </v-cropper>
`
错误原因是组件的父元素text-align: center 被.cropper-view-box（裁剪框）这个子元素继承， 影响了裁剪框的img图片行内的初始定位位置是裁剪框的中心附近， 而不是裁剪框的左侧

**Comment by xyxiao001** [comment]
修改之后可以吗

**Comment by 272092461** [comment]
可以了

**Comment by xyxiao001** [comment]
好 那我去修改下 避免因为父组件影响
